### ISSUE TITLE
In user profile, show the total count of videos submitted by user

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1001]
On http://www.amara.org/en/profiles/videos/username, please add the total count of the videos submitted by the user.
(The list is paginated with 30 videos/page and 30 thumbnails are not very easy to count manually, so having the total number displayed when it is already known would be super helpful.)

If possible, it would also be really nice to have the option to see the full list of videos without thumbnails.

**Comment by kslottow** [comment]
will be handled in pculture/amara-enterprise/issues/2124
