### ISSUE TITLE
Enable users with SocialAuth accounts to use automatic password reset

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1006]
At this time, users signed up with Google, FB, Twitter, OpenID accounts receive the following message when trying to reset their password through the web UI:
“The user account associated with this e-mail address cannot reset the password.”

Instead of this vague message the email from Amara should: 
- Inform user how she was expected to sign in (by clicking Google/FB/OpenID button and entering the credentials for that account; the account on Amara does not have a password)
- Let the user override SocialAuth authentication and set the password as usual, with a warning that the change is permanent and irreversible.

**Comment by deanjansen** [comment]
Helpful explanation via Maggie:

1. User creates a basic password-based account, indicating Google email address at registration, does stuff.
2. User clicks Google button, expecting to sign in to the existing account. Another, Google-authenticated, user account is created instead.
3. User is unhappy with the result of p.2 and wishes to restore access to the original basic account. She itries to recover the password for it. The recovery procedure looks up the Google email address in the database, finds the Google-authenticated accounts, chokes and reports to the user that this type of account cannot have a password reset. The user is blocked until receiving help from Amara personnel who have full access to the production database.

**Comment by bendk** [comment]
I think this was fixed and deployed right?  If not, can we remove the milestone?  Then we can do one of the following:
  - Add to a different milestone if we know when we want to fix it
  - Add the important label if we think it's higher priority, but don't know when we will get to it
  - Just leave it alone and hope it gets fixed sometime.

**Comment by PCF-Testing** [comment]
This one was deployed. Marking as closed.
