### ISSUE TITLE
Allow splitting the current subtitle cell in the editor with a keyboard shortcut

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1008]
When a subtitle line has focus, a special key combination should split the line into two. 

Ideas:
CTRL+SHIFT+| (vertical line)
Shift + C (suggested by client)
Cmd + T (GarageBand)
Cmd + B (Final Cut "blade")
ctrl+shift+v (Subtitle Workshop)

Text:
- Lines should be split by the current position of the text cursor
- If the text cursor is at the beginning of the line, all the text goes into the second new line
- If the text cursor is at the end of the line, all the text goes into the first new line

Timing:
- If the split line is untimed, both new lines should be untimed
- If the split line is timed AND time cursor is at the start/end of the line or outside of it, the line should be split into two equal halves
- If the line is timed AND time cursor is at the middle of the line, the line should be split by the current timestamp. Both new lines should have no less than 0.7 s.
- If the line is open-ended (has the start time but not the end time) AND time cursor is outside of it, the first of the new lines should last 2 seconds, and the second one be open-ended.

Example: 

```
<p begin="00:01:08.910000" end="00:01:12.600000" xml:id="subtitle42"> I would like to stick my nose in and get involved but that's that's just me,</p>
<p begin="00:01:12.600000" end="00:01:13.440000" xml:id="subtitle43"> or maybe that's daughters</p>
<p begin="00:01:14.130000" end="00:01:14.710000" xml:id="subtitle44"> talked and therefore</p>
```

Typing the `split shortcut`  when the cursor is placed between `in and` would produce:

```
<p begin="00:01:08.910000" end="some time" xml:id="subtitle42"> I would like to stick my nose in</p>
<p begin="some time" end="00:01:12.600000" xml:id="subtitle43"> and get involved but that's that's just me,</p>
<p begin="00:01:12.600000" end="00:01:13.440000" xml:id="subtitle44"> or maybe that's daughters</p>
<p begin="00:01:14.130000" end="00:01:14.710000" xml:id="subtitle45"> talked and therefore</p>
```

We would not change the start time of the original line, and the added line would have the end time of the original line.  The middle times would be calculated based on some logic."

**Comment by kslottow** [comment]
Current process:

Currently, a translator or transcriber can: 
Pause-->put the cursor where you want to split the line-->hit shift+enter

However, if it's the second line in the subtitle that needs to split, you also have to:
Select and copy the extra words--> paste in next line or subtitle-->skip back 4/8 sec to replay-->adjust subtitle timing by dragging.  

OR

Cmd-Shift-arrow down (to select remaining text), 
Cmd-X (to cut), add … at the end of the line, 
Cmd-Shift-I (to insert a new row below), 
Enter (to move to the next line) 
Cmd-V (to paste)

More context on these forum topics: 
https://support.amara.org/support/discussions/topics/313472; https://support.amara.org/support/discussions/topics/28857/page/7?url_locale=; 
https://support.amara.org/support/solutions/articles/192394-how-do-i-split-a-subtitle-into; https://support.amara.org/support/discussions/topics/28857/page/8?url_locale=

**Comment by kslottow** [comment]
- video editing tools have several ways of splitting for different use cases. You split while playing the video by using a keyboard shortcut, or split while paused by holding down a key to select a "blade" or "razor" tool (B in Final Cut and C in Premiere) and then clicking at a point in the middle of a video clip. This is different from what we want to do because the Amara knows where they want to split based on the text; not based on the timing. We should find out if this is true all the time.
- Garageband uses cmd+t for splitting

**Comment by bendk** [comment]
I'm pretty sure the main use case is a subtitle that's too many chars, so it's going to be based on splitting the text.  Seems like there should be quick ways to do the following:

 - Take a single subtitle, and split it into two subtitles, based on the position if the cursor inside a textbox.
   - I'm not sure how we should split the time out.  Maybe just 50/50
- Adjust the timings for both subtitles at once.  There should be a way to adjust the end time of subtitle 1 and the start time of subtitle 2 without it being two different actions
   - Alternatively, maybe some sort of close the gap action, so I would adjust the end time of subtitle 1, then click somewhere, and subtitle 2's start time would be set to the end time of subtitle 1.

**Comment by PCF-Testing** [comment]
Splitting works well for me. However, the shortcut has not been added to the list of available shortcuts in the editor (Keyboard controls -> more commands>>>).

One potential problem with the new feature I see is that SHIFT+ENTER (new line) and CTRL+ENTER (split subtitle) are on most keyboards very close to each other, so users are bound to make mistakes often, splitting subtitles instead of just inserting a line break. Splitting a subtitle is pretty hard to correct if you don't have the merge command, which is a natural undo for splitting. So I think it would be best to implement both splitting and merging on the same branch and release both together.

**Comment by bendk** [comment]
I disagree that users are particularly likely to make a mistake.  I don't think that happens with other ctrl combinations that often, like typing "Shift-C" instead of Ctrl-C.  Still, I agree that it would make sense to deploy merging and splitting together in one release.

One thing we could do is just comment out the code for now so the functionality is there, but it's just not enabled.  I guess it depends on how urgent this is for on-demand and our partners.

@kslottow tell me what you think

**Comment by bendk** [comment]
Talked with kenzie and she says we should try to get this one out quickly.  So I'm going to make a PR for it.

**Comment by PCF-Testing** [comment]
Deployed.
