### ISSUE TITLE
Enable users to choose the language of Amara UI

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1053]
At this time, the language used for Amara UI depends on the browser settings. If altered manually through the address bar, it switches back to the original selection on a number of links. This is inconvenient, since some UI languages are poorly translated or incomplete.

Expected: add "Site Language" option to user Account page where a user can select the desired UI language at will. Make English the default selection.

**Comment by bendk** [comment]
Does changing the first language on the user profile change this?

**Comment by PCF-Testing** [comment]
No, the choice of the UI language is determined by the browser's language settings.

**Comment by deanjansen** [comment]
The user profile setting might be a good place to start, and in some future version of the website chrome we could add a language selector.

**Comment by bendk** [comment]
Yeah, I'm pretty sure we use that in the logic right now.  Probably what happens is the browser settings overrides that.  What about this priority order?

* First language in the profile
* Browser settings
* Next languages in the profile

**Comment by deanjansen** [comment]
That definitely makes sense.

**Comment by bendk** [comment]
One issue with "First language in the profile" is that languages aren't ordered.

Also, if we make this change, I would also love to change they way the language is encoded into the URL.  I don't like the practice for several reasons:
 * You have 1 resource mapped to multiple URLs.
 * It messes with copy+paste if the users use different languages
 * It adds complexity to the redirection code and also the urlresolver code

I'd rather we just set a cookie and use that.

**Comment by PCF-Testing** [comment]
@syl22-00 is working now on ordering users' preferred languages in #2030. For the feature to work, we need to make sure that users can modify and save the order of language preference.

**Comment by PCF-Testing** [comment]
Deployed.
