### ISSUE TITLE
Modify signup procedure to avoid creating multiple SocialAuth accounts by the same user

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1057]
Having Google, FB, and other SocialAuth buttons on Sign Up page causes users to create multiple accounts without knowing what they are doing. This causes a lot of confusion and is hard to revert, since we cannot merge existing accounts gracefully (preserving the history, associated videos etc.).

The new procedure should warn if the Google email already has other accounts in the system, and prompt users to tie FB/Twitter accounts to their existing account, if one exists.

The button click should be processed as follows:

- If user clicks Google button and the system cannot find a matching record in CustomUsers:
    * Check if there are other user accounts associated with this email address.
    * If any existing active accounts are found, tell the user "There is no Amara user account for this Gmail address yet, but we found other account(s) associated with this address. What would you like to do now? [Go Back and Sign In with Another Account]  |  [Create New Account]"
    * If no accounts were found or they are all inactive, tell the user: "There is no Amara user account for this Gmail address yet. A new account will be created. Do you wish to continue?  [Yes, Create New Account]  |  [No, Cancel]"

- If user clicks FB or Twitter button and the system cannot find a matching record in Facebook or Twitter tables:
   * Tell the user "This Facebook|Twitter account does not look familiar to us. You can either create a new user account or sign in with another Amara account and add your Facebook|Twitter login to it (link to how-to page on helpdesk site) What would you like to do now?   [Go Back and Sign In with Another Account]  |  [Create New Account]"

Related tickets in FD:
http://ted-support.amara.org/helpdesk/tickets/70499
http://ted-support.amara.org/helpdesk/tickets/70574

**Comment by syl22-00** [comment]
Issue replaced and fixed in branch gh-enterprise-511

**Comment by PCF-Testing** [comment]
Deployed.
