### ISSUE TITLE
Keyboard shortcuts should work regardless of keyboard configuration

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1069]
There's a lot of different keyboard / language settings.  We should test these an choose shortcuts that work on the various possible combinations.

Re: The new editor seems easier to use now, though navigation commands still don't work for me (Mac OS X, Firefox 30.0 and Swiss French keyboard) except tab for play/pause that does work.

**Comment by bendk** [comment]
I'm not sure exactly what needs to be done here.  I think #3239 should handle it though.
