### ISSUE TITLE
Handle videos moving teams with collaborations.

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#1086]
We need to handle a video moving from team to team when collaborations are enabled.  I think it should be done this way:
- For in progress collaborations there are two cases:
  - Moving to a collab team: collabs are not changed.  The video will belong to the new team, but the collaboration will still belong to the old team.
  - Moving to a non-collab team: not sure about this one, there are a couple ways to implement it:
    - Prevent the move altogether
    - Delete the collab
    - Implement something similar to pro-requests where even if a video belongs to another team, if there's a collaboration for a language then the collab workflow applies to that language.
- Any collaborations that have not been started will be deleted.
- If the new team is a collaboration-based team, then we will auto-create new collaborations based on their language settings.

**Comment by kslottow** [comment]
this is done, right @bendk ?

**Comment by bendk** [comment]
We implemented it by deleting the collaboration in the case of moving to a non-collab team.
