### ISSUE TITLE
Editor display on tablets and other mobile devices

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1104]
Currently the new editor does not display well on smaller screen.  

Ex: Chrome when zoomed in on content, or tables.

We should make sure the editor display is responsive to various screensizes and displays all content.

Screenshot is an example of the new editor on an ipad.  

Not the progression text is out of view (shoved down the page) and the subtitles are not displayed.

![photo](https://f.cloud.github.com/assets/299270/1703652/57f271f4-60b9-11e3-99ee-2064c2652da9.PNG)

**Comment by PCF-Testing** [comment]
On tablets (iPads), a tutorial set to ON cannot be hidden and does not allow to access any controls in the editor.

**Comment by PCF-Testing** [comment]
The editor's layout has changed since this ticket was made, the screen no longer looks like the screenshot above. Marking as closed.
