### ISSUE TITLE
New editor: do not display languages with 0 lines in the drop-down on the reference panel

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1109]
The drop-down selector above the reference panel currently includes abandoned languages (which were started but no version was saved). This clutters the list and hampers choosing a valid language as a source.

Example: Bulgarian in http://www.amara.org/en/subtitles/editor/wlISF54mlV2J/fr/

Expected: do not include empty languages into the list.

**Comment by bendk** [comment]
This one is fixed.  Just tested with that example.
