### ISSUE TITLE
re-org video language tab to more closely resemble videos tab layout.

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1120]
Currenlty our video language tab looks like this: 

![current-video-lang](https://f.cloud.github.com/assets/299270/1754281/56c5a6ae-664d-11e3-8643-412dd69b4d03.png)

I'm suggesting that we take out the embedded widget, and move the editing tools over to the side bar in it's place, which would
-  make it easier for users to find the editing buttons they need
- be more consistent with the video page layout
- take out the duplicate description text (once on the side under the video and again in the subtitles tab view)
- remove that extra line of buttons under the subtitles tab.
- for a moderated team, add a direct link to the tasks filtered to that language assigned to anyone.

Here's a visual of my suggestions:
- if you are a site admin of a non-team video

![admin-non-team-video](https://f.cloud.github.com/assets/299270/1754293/960f5be8-664d-11e3-8e65-788d90baae69.png)
- if it is a moderated team video, and you are a non-admin

![non-admin-tasks-team](https://f.cloud.github.com/assets/299270/1754305/bcfad3f4-664d-11e3-8c54-e80125953075.png)

**Comment by bendk** [comment]
This happened with the futureui rework of the page.
