### ISSUE TITLE
When filtering team videos by language, respect IsComplete flag regardless of syncing

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1137]
Existing, marked as complete, languages get ignored by team videos filter if the last line is missing the end time.

Example: http://www.amara.org/en/teams/udacity/videos/?q=&project=any&lang-mode=-&lang=zh-cn&sort=-time
The first video returned by the filter does have Chinese, Simplified subtitles: http://www.amara.org/en/videos/GVa9EAqjrNZF/zh-cn/305978/

Expected: the filter results respect is_complete flag and ignore the end time for the last line.

**Comment by bendk** [comment]
We're not working on this page anymore.  Let's focus on the futureui version.
