### ISSUE TITLE
Pre-DMR comments on languages are not displayed

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1140]
Comments added to languages before Jun 29, 2013, are not displayed on language pages.

Example: http://www.amara.org/en/profiles/profile/steloim/?page=83
Comment added to http://www.amara.org/en/videos/eGZ0uCS5E3fd/ko/257173/?tab=comments is missing.

**Comment by bendk** [comment]
Not sure if this was fixed or not, but it's so old I don't think we need to take action anymore.
