### ISSUE TITLE
New editor: subtitles freezing in Safari on Mac OS X

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1141]
Steps to reproduce:
1. Open subtitles for an MP4 video in the new editor (example: http://www.amara.org/en/subtitles/editor/GaSlfkb6w8c5/en/) in Safari on Mac OS X (10.6.8).
2. Start playing the video. Subtitles would freeze and stop updating.

Not reproducible with a different browser or video format, but behaves similarly with another MP4 video.

**Comment by kslottow** [comment]
@PCF-Testing can this one be closed?

**Comment by PCF-Testing** [comment]
Not a problem anymore on Mac OS X 10.13 and Safari 11. Marking as Closed.
