### ISSUE TITLE
tool to bulk add member to a team via api

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1156]
create tool that will bulk add users to a team. 

I think the ideal tool for the on-demand managers would be something where they can upload a csv file that contains the

team slug | amara username | role

Then we'd user the safe-member resource via the api http://amara.readthedocs.org/en/latest/api.html#safe-team-member-resource

Which will send an invitation to the user inviting them to the team.

**Comment by bendk** [comment]
We now have this in the UI.
