### ISSUE TITLE
Uploading subtitles for videos that are part of collab teams

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1162]
Currently the only place to upload subtitles for a video is via the Video's home page.  

One issue with this currently is that uploaded subtitles don't get listed on the collab tab.

We can:

- [x] do #993, allowing users to upload directly to the new editor, and make we do a permission check and associate the upload with a collab

or 

- [ ] implement upload button in the new editor, and uploading from with-in the editor should be the only way to perform uploads for collab-team videos

of 

- [ ] something else.

**Comment by bendk** [comment]
#993 was implemented.
