### ISSUE TITLE
New Editor: Switch to typing mode just with click at "1. Type what you hear"

### ISSUE THREAD

**Issue by muescha** [pculture/unisubs#1178]
New Editor:

Switch to typing mode just with click at "1. Type what you hear"

now its just a hidden feature:

```
It's not so obvious in the UI yet.  
But if you hide the timeline - you are effectively back into Typing mode
```

**Comment by bendk** [comment]
Great idea moving to the backlog.

Sorry for taking so long to go through these.  It's taking a while for us to get our dev process in a state where we're finally going through all our old issues.

**Comment by bendk** [comment]
This is implemented in the experimental-editor branch.  We're going to be testing out a lot of changes there, then they will get merged to the main editor.  Look for an announcement soon.
