### ISSUE TITLE
Video actions log in the admin interface has no search or filter function

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#1183]
I need to check the log of revision deletions for a video, but the videos/action admin page has no filtering options. The deletions happened around a week ago and it would be impractical to try to locate them manually, as there's by now lots of pages to go through.

**Comment by bendk** [comment]
Yeah, I think the API usage is probably good enough for this one.  @franontanaya if you still need something though, please re-open and we can implement it pretty easily.
