### ISSUE TITLE
optimize the team dash page

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1192]
Queries to generate the list of videos that need your help on the team dashboard page need to be optimized.

Things that slow the queries and therefore site down are the membership narrowing: checking to display the approve tasks specific the the user's project or language manager roles.  Additionally we filter out the review tasks if the user was the subtitler.

We can either:
1. Optimize the existing queries to try to make them run faster
2. Simplify what's displayed on the tab, limiting it to the Subtitle / Translate tasks, which is what most volunteers need to see and allow team admins / managers to find their work to do on the Tasks tab.

cc @reville @bendk for opinions.

**Comment by bendk** [comment]
We've done some optimization along these lines, plus we've introduced a new dashboard.  Let's close it.
