### ISSUE TITLE
Add "Project" column in billing reports

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#1216]
If a video is in a project when the billing report is pulled on a team, it should display the project it is in. This will help larger orgs who perhaps have several different departments (such as a University) that need to be billed individually, yet wish to use one singular team on Amara.

**Comment by jdragojevic** [comment]
So it looks like langauges that were completed prior to this change show in the billing reports with the project name as an object.    However anything new displayes correctly.

![image](https://cloud.githubusercontent.com/assets/299270/6109828/fefa7fc2-b07d-11e4-96d4-c07992427680.png)

I don't think this is too big a deal, it will just be something to mention to Terri.

**Comment by jdragojevic** [comment]
ok - so what's happening is that the subtitles that created on amara are displayed as expected, however the extra entries we generate for language that were imported from youtube (for example) have the object for the project name.

![image](https://cloud.githubusercontent.com/assets/299270/6146273/5489bdf4-b1eb-11e4-80c5-7fbf26dd6f72.png)

**Comment by syl22-00** [comment]
argh, sorry, that one was hiding. It should be fixed now.

**Comment by jdragojevic** [comment]
this was fixed and deployed.
