### ISSUE TITLE
Remove "beta" from YouTube account linking controls

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1237]
The feature has been around for more than a year and does not cause any significant problems.

Two places where edits are needed:

1. http://www.amara.org/en/profiles/account/
"Enable Amara crowd subtitles on your personal YouTube channel (beta)"

2. Pop-up "Enable Crowd Subtitles on your Personal YouTube Channel (beta)"

**Comment by PCF-Testing** [comment]
"Beta" is still present in the pop-up. Reopening.

**Comment by bendk** [comment]
Fixed in the gh-2447 branch.

**Comment by PCF-Testing** [comment]
Cannot start gh-2447 - master branch is ahead of gh-2447 on unisubs:

Attaching to unisubs_worker_1, unisubs_app_1
worker_1 | INFO 2016-02-05 05:00:53,266 base 1 140529373677376 Raven is not configured (logging is disabled). Please see the documentation for more information.
worker_1 | Traceback (most recent call last):
worker_1 |   File "manage.py", line 37, in <module>
worker_1 |     startup.startup()
worker_1 |   File "/opt/apps/unisubs/startup.py", line 68, in startup
worker_1 |     run_startup_modules()
worker_1 |   File "/opt/apps/unisubs/startup.py", line 59, in run_startup_modules
worker_1 |     __import__('%s.startup' % app)
worker_1 |   File "/opt/apps/unisubs/apps/teams/startup.py", line 21, in <module>
worker_1 |     import teams.workflows.startup
worker_1 |   File "/opt/apps/unisubs/apps/teams/workflows/startup.py", line 27, in <module>
worker_1 |     from teams.workflows.old import OldTeamWorkflow
worker_1 |   File "/opt/apps/unisubs/apps/teams/workflows/old/__init__.py", line 3, in <module>
worker_1 |     from .workflow import OldTeamWorkflow
worker_1 |   File "/opt/apps/unisubs/apps/teams/workflows/old/workflow.py", line 26, in <module>
worker_1 |     from teams import views
worker_1 |   File "/opt/apps/unisubs/apps/teams/views.py", line 50, in <module>
worker_1 |     from teams.forms import (
worker_1 |   File "/opt/apps/unisubs/apps/teams/forms.py", line 133, in <module>
worker_1 |     class MoveTeamVideoForm(forms.Form):
worker_1 |   File "/opt/apps/unisubs/apps/teams/forms.py", line 136, in MoveTeamVideoForm
worker_1 |     team = forms.ModelChoiceField(queryset=Team.objects.all(),
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 116, in all
worker_1 |     return self.get_query_set()
worker_1 |   File "/opt/apps/unisubs/apps/teams/models.py", line 129, in get_query_set
worker_1 |     return TeamQuerySet(Team).filter(deleted=False)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 624, in filter
worker_1 |     return self._filter_or_exclude(False, *args, **kwargs)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 642, in _filter_or_exclude
worker_1 |     clone.query.add_q(Q(*args, **kwargs))
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1250, in add_q
worker_1 |     can_reuse=used_aliases, force_having=force_having)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1122, in add_filter
worker_1 |     process_extras=process_extras)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1304, in setup_joins
worker_1 |     field, model, direct, m2m = opts.get_field_by_name(name)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 311, in get_field_by_name
worker_1 |     cache = self.init_name_map()
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 341, in init_name_map
worker_1 |     for f, model in self.get_all_related_m2m_objects_with_model():
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 429, in get_all_related_m2m_objects_with_model
worker_1 |     cache = self._fill_related_many_to_many_cache()
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 443, in _fill_related_many_to_many_cache
worker_1 |     for klass in get_models(only_installed=False):
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 181, in get_models
worker_1 |     self._populate()
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 64, in _populate
worker_1 |     self.load_app(app_name, True)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 86, in load_app
worker_1 |     app_module = import_module(app_name)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
worker_1 |     __import__(name)
worker_1 |   File "/opt/apps/unisubs/amara-enterprise/ted/__init__.py", line 8, in <module>
worker_1 |     from thirdpartyaccounts import register_thirdpartyaccount_type
worker_1 | ImportError: cannot import name register_thirdpartyaccount_type
app_1    | INFO 2016-02-05 05:00:53,913 base 1 139808643172160 Raven is not configured (logging is disabled). Please see the documentation for more information.
app_1    | Traceback (most recent call last):
app_1    |   File "manage.py", line 37, in <module>
app_1    |     startup.startup()
app_1    |   File "/opt/apps/unisubs/startup.py", line 68, in startup
app_1    |     run_startup_modules()
app_1    |   File "/opt/apps/unisubs/startup.py", line 59, in run_startup_modules
app_1    |     __import__('%s.startup' % app)
app_1    |   File "/opt/apps/unisubs/apps/teams/startup.py", line 21, in <module>
app_1    |     import teams.workflows.startup
app_1    |   File "/opt/apps/unisubs/apps/teams/workflows/startup.py", line 27, in <module>
app_1    |     from teams.workflows.old import OldTeamWorkflow
app_1    |   File "/opt/apps/unisubs/apps/teams/workflows/old/__init__.py", line 3, in <module>
app_1    |     from .workflow import OldTeamWorkflow
app_1    |   File "/opt/apps/unisubs/apps/teams/workflows/old/workflow.py", line 26, in <module>
app_1    |     from teams import views
app_1    |   File "/opt/apps/unisubs/apps/teams/views.py", line 50, in <module>
app_1    |     from teams.forms import (
app_1    |   File "/opt/apps/unisubs/apps/teams/forms.py", line 133, in <module>
app_1    |     class MoveTeamVideoForm(forms.Form):
app_1    |   File "/opt/apps/unisubs/apps/teams/forms.py", line 136, in MoveTeamVideoForm
app_1    |     team = forms.ModelChoiceField(queryset=Team.objects.all(),
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 116, in all
app_1    |     return self.get_query_set()
app_1    |   File "/opt/apps/unisubs/apps/teams/models.py", line 129, in get_query_set
app_1    |     return TeamQuerySet(Team).filter(deleted=False)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 624, in filter
app_1    |     return self._filter_or_exclude(False, *args, **kwargs)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 642, in _filter_or_exclude
app_1    |     clone.query.add_q(Q(*args, **kwargs))
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1250, in add_q
app_1    |     can_reuse=used_aliases, force_having=force_having)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1122, in add_filter
app_1    |     process_extras=process_extras)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1304, in setup_joins
app_1    |     field, model, direct, m2m = opts.get_field_by_name(name)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 311, in get_field_by_name
app_1    |     cache = self.init_name_map()
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 341, in init_name_map
app_1    |     for f, model in self.get_all_related_m2m_objects_with_model():
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 429, in get_all_related_m2m_objects_with_model
app_1    |     cache = self._fill_related_many_to_many_cache()
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 443, in _fill_related_many_to_many_cache
app_1    |     for klass in get_models(only_installed=False):
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 181, in get_models
app_1    |     self._populate()
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 64, in _populate
app_1    |     self.load_app(app_name, True)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 86, in load_app
app_1    |     app_module = import_module(app_name)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
app_1    |     __import__(name)
app_1    |   File "/opt/apps/unisubs/amara-enterprise/ted/__init__.py", line 8, in <module>
app_1    |     from thirdpartyaccounts import register_thirdpartyaccount_type
app_1    | ImportError: cannot import name register_thirdpartyaccount_type
unisubs_worker_1 exited with code 1
unisubs_app_1 exited with code 1

**Comment by bendk** [comment]
Just merged and pushed an update.

**Comment by PCF-Testing** [comment]
After pulling in the updates and rebuilding, getting the following:

worker_1 | [2016-02-06 06:07:17,746: ERROR/Beat] Celerybeat: Connection error: timed out. Trying again in 4.0 seconds...
worker_1 | [2016-02-06 06:07:17,749: ERROR/MainProcess] consumer: Cannot connect to amqplib://guest@172.17.0.2:5672//: timed out.
worker_1 | Trying again in 4.00 seconds...
worker_1 | 
worker_1 | [2016-02-06 06:07:24,746: ERROR/Beat] Celerybeat: Connection error: [Errno 113] No route to host. Trying again in 6.0 seconds...
worker_1 | [2016-02-06 06:07:24,746: ERROR/MainProcess] consumer: Cannot connect to amqplib://guest@172.17.0.2:5672//: [Errno 113] No route to host.
worker_1 | Trying again in 6.00 seconds...

etc.

**Comment by bendk** [comment]
I think this must be because of the infrastructure changes that got merged it.  I would recommend doing `docker-compose rm` and trying again.

**Comment by PCF-Testing** [comment]
Verified the fix.

**Comment by PCF-Testing** [comment]
Deployed.
