### ISSUE TITLE
add social sharing to the subtitles saved dialog when subtitles are completed

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1252]
related to #1239 - making the dialogs consistent. 

Currently when a user completes subtitling, 'endorsed' or completed a version, we currently show a Subtitles saved dialog - that is generally pointless.

We should socialize that dialog to the user can fb or tweet that they've just completed a revision.

Something like this, and if we can do the twitter cards here too, #1238, even better.

![image](https://f.cloud.github.com/assets/299270/2230069/4f5ac9d0-9afa-11e3-9bdf-6d5d6055364c.png)

ps - pretend there isn't a white background around the share images.

Also - we probably should only do this for published versions from public teams - since moderated subs aren't visible yet and videos on private teams would produce 404s.

**Comment by bendk** [comment]
This seems like a cool idea, but we're not sure this is how we want to implement it.  For example, in collab teams, only the approver would see the link, but ideally we want to allow all assignees an opportunity to share.  Maybe connecting it to the request complete email would be better.  In any case, let's close this one and we can rethink it later.
