### ISSUE TITLE
server 502 when using post instead of put for team video move

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1290]
zombieF - was doing some testing with api integration against staging and

used POST instead of PUT when moving a video from 1 team to another.  The result was he got a 502 error.

Looking in sentry, I see this error:

https://sentry.amara.org/amara/amarastaging/group/12288/

Exception
Types:  
MultipleObjectsReturned
Value:  
get() returned more than one Project -- it returned 2! Lookup parameters were {'slug': u'cinemagraph'}
Location:   django/db/models/query.py in get , line 368

In this case there are two teams with same project names, but that should be OK as many teams do it.

**Comment by bendk** [comment]
Two projects with the same slug shouldn't be allowed, even though it is technically possible now.  Let's close this one.
