### ISSUE TITLE
Makeover Upload Subtitles dialog

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1326]
With the new editor made primary, modify Upload Subtitles dialog:
1. Remove obsolete options - "Translate from" is no longer needed, all the files will be uploaded as they are, without tampering with timing or the number of lines. I would also remove "Is Complete?" flag, marking all uploaded versions as incomplete - this should encourage users to review and edit uploaded versions in the editor.
2. Make the style of the editor match the style of other dialogs on Amara.

Setting the milestone to "Make New Editor Primary", but as a nice-to-have, rather than must-have, addition. Please feel free to postpone a bit, if it is not an easy fix.

**Comment by bendk** [comment]
We're using the editor upload dialog now.  Let's just close this one.
