### ISSUE TITLE
video sent back by reviewer cannot be re-submitted for review if unedited.

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1339]
Steps to reproduce:
1. Pick a transcription task.
2. Make a subtitle version and submit for review.
3. As a reviewer, send back.
4. As the transcriber, resume the task and click Complete in the editor. The subtitles will not be sent for review.

**Comment by kslottow** [comment]
we won't fix this because it's a problem specific to the task model and should not occur with subtitle requests in the collab model
