### ISSUE TITLE
New editor: cannot set beginning-of-paragraph on line 1 after clearing it

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1354]
Observed on staging with http://staging.amara.org/en/subtitles/editor/NmkV5cbiCqUU/en/

Line 1 has beginning-of-paragraph mark set by default. After clearing it with a mouse click, it cannot be restored by clicking again - the shaded mark is there, but does not respond to mouse clicks.

**Comment by bendk** [comment]
I'm pretty sure this got fixed.

**Comment by PCF-Testing** [comment]
At this time, it behaves slightly different, but still buggy:

In the editor, the paragraph mark for line 1 can be toggled off and on again, but regardless of the toggle value, the subtitle version is always saved with paragraph on in the first line - probably this comes from the dfxp format we use.

How about keeping line 1 always with paragraph mark on and forbidding to turn it off in the editor for consistency?

**Comment by bendk** [comment]
Fixed in the experimental-editor branch.

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed (experimental editor).
