### ISSUE TITLE
Make sure notifications on subtitles reviewed include the link to the subtitle set

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1415]
When subtitles have been reviewed or approved, always send the link to the subtitles in the body of the message to the transcriber / translator (both in onsite messages and in emails).

Current behaviour: only the title of the video, without the link, is listed. The translator needs to search for the video and the language.

**Comment by kslottow** [comment]
I added the appropriate linked text to the template on our [New style teams system messages doc](https://docs.google.com/document/d/1Jjd0dNArA24ahs4b1ZFQDR53Z9bbXtbduLDp7PMa-_c/edit ). 

We'll adjust the copy for all in a single issue.
