### ISSUE TITLE
Keyboard shortcuts broken in longer vimeo videos

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#1424]
For videos that are ~90min long, all keyboard shortcuts (Tab, Shift+Tab, Shift+Control+, and Shift+Control+.) are unresponsive on the video.

The keyboard controls are broken as soon as you load the editor. Has been observed in Firefox but works fine in Chrome in OSX.

Steps to reproduce are:
1) Find a long video on Vimeo
2) Add it to Amara
3) Enter editor via "Add a new language" on the video page
4) Video cannot be played by the tab button, only through the Vimeo player within the editor. Keyboard controls are completely unresponsive.

**Comment by bendk** [comment]
Not sure if this is still an issue.  @pcf-testing have you heard anyone complain about it lately?  If so, let's re-open and move to the backlog.
