### ISSUE TITLE
For YouTube videos, indicate whether they sync subtitles to YouTube

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1425]
A number of users invest time and effort into transcribing or translating other people's YouTube videos in hope that the results of their work will be exported to YouTube and visible to public. If the video turns out to be not syncing subtitles to YouTube, disappointment ensues.

Could we label in some manner YouTube videos that currently sync subtitles to YouTube? A caption under the video player should be ok - just something that would enable users to tell linked videos from unlinked.

**Comment by bendk** [comment]
Implemented this in the gh-1425 branch.  You can see it by clicking on the URLs tab.  Video URLs that are synced have a "Synced" emlem, in the same section as primary/original.

It's pretty subtle, but it should work okay.  I would be happy to move them to a more prominent place.
