### ISSUE TITLE
Errors when a video is has "is_original: true" and "is_translation: true"?

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#1450]
In one video at On Demand 047 a subtitle file had been uploaded to the wrong language, and in an attempt to fix it the Edit subtitle language admin page had been used to switch it from English to German (German is the original language of the video).

After doing so, the metadata for the only language in the video looked like this:

![is_complete_error_meta](https://cloud.githubusercontent.com/assets/2067592/2844919/7c0b2c88-d090-11e3-90c1-8e1a5782fe11.png)

And the following actions returned an error:
- Trying to access the video.
- Trying to view the activity stream for the team.
- Trying to delete the video via API.

Downloading the subtitles via API and reading the video's metadata via API still worked.

Upon posting via API a new EN language with the "is_original" attribute set as true, the video was restored to working order again. 

This video has since been deleted to recreate it and resume the work with German set as the original language.

I haven't been able to reproduce this myself on a test team, but I've seen similar symptoms several times before.

**Comment by bendk** [comment]
This is an old bug that's hard to reproduce.  Let's just close.
