### ISSUE TITLE
New editor: Skipping back with SHIFT+TAB does not work for MP4 in Firefox

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1465]
Instead of 2 sec, SHIFT+TAB skips back an arbitrary number of seconds.

**Comment by kslottow** [comment]
Tested this and it looks fixed.  Is that correct/can this issue be closed?

**Comment by PCF-Testing** [comment]
It is an old issue and it seems to be gone now. Marking as closed.
