### ISSUE TITLE
Make task assignees follow the language they are assigned to

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1471]
This change is part of the feature requested by TED that would enable them to broadcast messages to all the collaborators working on a video.

Expected:
- When a user is assigned a task or picks a task, make her a follower of the language, even if she has not saved any revision yet.
- If a user declines a task or leaves it to expire without saving anything, she should stop following this language.

The current ticket is accompanying #1470.

The change request is at http://ted-support.amara.org/helpdesk/tickets/73008.

**Comment by bendk** [comment]
Seems like like this is maybe taken care of.  I'm going to close, but please reopen if there's still an issue.
