### ISSUE TITLE
Wrong user role displayed on team members page

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1474]
http://www.amara.org/en/teams/ted/members/

"Your role: Owner (or Admin) for Bulgarian language"

Expected: "for Bulgarian language" is not needed here.

To reproduce, impersonate ted_symbolt and open the page.

![bulgarian](https://cloud.githubusercontent.com/assets/288455/2926879/a2f33ed4-d762-11e3-8be4-4ca4a37a2122.png)

**Comment by bendk** [comment]
I think this is fixed in futureui.
