### ISSUE TITLE
get  / store video duration for use in billing / payment processing

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1480]
Currently for our billing reports / payment processing - we are using the time of the last synced subtitle when the video was marked as complete.  This can result in us using inaccurate data for billing.

For youtube we stored the video duration. We should also get the video's duration and store it when we are adding videos from vimeo, brightcove, kaltura, wistia, and any feeds that are used to import videos.

For html5 video, we should try do a lookup on the video's duration using something like gstreamer (python-gst) that has the Discoverer (gst.pbutils.Discoverer.get_duration()) 

if we really can't get the video's duration, then we should fall be to the time of the last synced sub.

**Comment by PCF-Testing** [comment]
@bendk: since this ticket was created, we have made changes to automatically retrieve video duration for billing purposes. Is it OK to close this one?

**Comment by bendk** [comment]
I think so.
