### ISSUE TITLE
Editor: do not allow SHIFT+SPACE play and pause the video

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1481]
This key combination occurs in the normal typing process, so playing and pausing the video every time these keys are hit is very annoying for the typists. Please suppress the video player actions.

Request: http://ted-support.amara.org/helpdesk/tickets/73354

**Comment by PCF-Testing** [comment]
This issue is of particular importance to Persian translators, who use SHIFT+Space to enter Zero-Width-Non-Joiner (aka &zwnj; or Nim-Faseleh), a character that is essential for correct display of Persian texts. The request to stop using SHIFT+Space for playing/pausing the video was reiterated at TED Translators Workshop 2015.

**Comment by bendk** [comment]
The above change makes it so space toggles playback, but only if you are not editing a subtitle.  I think that's a nice UI to have, but I'm not sure.  What do others think?

**Comment by deanjansen** [comment]
I had originally thought it was a bug and kept accidentally play/pausing while I was typing.
