### ISSUE TITLE
Excessive api load can cause outages

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1541]
This morning we had a confluences of requests from 3 major amara users which resulted in some site down time.

![image](https://cloud.githubusercontent.com/assets/299270/3246321/5a0f5ee6-f17a-11e3-9d6c-ad53fbc23692.png)

Here's some requests while it was problematic
![screenshot 2014-06-11 02 09 52](https://cloud.githubusercontent.com/assets/299270/3246331/7494c35a-f17a-11e3-8aac-41f885f28424.png)

And once it got back to normal
![screenshot 2014-06-11 02 14 26](https://cloud.githubusercontent.com/assets/299270/3246330/748ac42c-f17a-11e3-84c7-d1ccc6f0361f.png)

**Comment by bendk** [comment]
API performance has been improved across the board.  I'm closing this one.
