### ISSUE TITLE
embedder code doc

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#1558]

**Comment by PCF-Testing** [comment]
@bendk: what do we do with this one? It is dated by 2014, the change is at https://github.com/pculture/unisubs/blob/gh-1558/docs/embedder.rst.

**Comment by bendk** [comment]
I think we should update these a bit, then merge to dev.

**Comment by bendk** [comment]
Docs updated: http://amara.readthedocs.io/en/latest/embedder.html
