### ISSUE TITLE
Allow users to enter password, for pw protected videos

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1569]
In the case of password protected videos (ex vimeo)

We should allow users to input the passwords and play the videos in amara / embedder.

**Comment by kslottow** [comment]
@syl22-00 @PCF-Testing @bendk is this old/can it be closed? If not let's put it in the backlog

**Comment by syl22-00** [comment]
password-protected vimeo videos actually work, but their is a small quirck with the player where it needs be be refreshed before being used. There is another ticket for that.
