### ISSUE TITLE
Take unnecessary js out of pages

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1577]
- [ ] Optimizely - loads on every single page and takes about 1/2 second. It's for A/B testing which we haven't done for a few years.  And if we want to use it in the future, we should add it only to the specific pages we want to test.
- [ ] embedder-offsite page loads from snipt.net.  Takes about 1 sec to load and isn't required to show the embedder text.
- [ ] ... anthing else?

**Comment by bendk** [comment]
We've updated our JS a lot since this one.  I don't think it's needed anymore.
