### ISSUE TITLE
update display on personal info page

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1583]
We should make the 'personal info' page more clear about what it is: ie the information that will be displayed as the users Public profile.

![image](https://cloud.githubusercontent.com/assets/299270/3509569/b34dde4c-069c-11e4-9cd5-ba45a01da8c6.png)

We should probalby change the name to Public Profile, so it's clear that it's the information that the user is sharing.

And change the field heading for homepage to External profile, and let users know they can add a link to any public page of theirs that they want.  (ex fb, gh, transifex... )

**Comment by bendk** [comment]
We're going to be working on this and have a different issue for it.  Let's use that one.
