### ISSUE TITLE
Move away from sites app

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#1619]
We currently use the sites app to determine the URL for our server.  The sites app was designed to have multiple sites running from the same database, which we don't need currently or in the foreseeable future.

I think we can switch from using sites to simply having a SITE_URL in the settings files.

Some things to test after this test:

- [ ] brightcove syncing works for preview branches
- [ ] URLs in emails have the correct domain name 

Once we deploy we should double check:
- [ ] staging, but not production, should have this in the `<head>` element: `<meta name="robots" content="noindex, nofollow"/>`

**Comment by bendk** [comment]
This is causing issues with dev.amara.org, let's fix this one soon.

**Comment by bendk** [comment]
Gonna do this one earlier, because it makes the django upgrade much easier.

**Comment by bendk** [comment]
There's a few small issues we need to follow up on once this is deployed:

- [ ] staging, but not production should have this in the `<head>` element: `<meta name="robots" content="noindex, nofollow"/>`

**Comment by bendk** [comment]
Merged this one to dev since that's the best way to test it.

**Comment by PCF-Testing** [comment]
@bendk: tried OAuth signup on dev.amara.org:

- [ ] Google signup redirects to staging instead of dev
- FB, Twitter, and TED seem to work OK
- OpenID and Udacity do not work on production either

**Comment by PCF-Testing** [comment]
With Brightcove integration, something does not look quite right - on dev, subtitles are labeled as synced, but no subtitles are present on the Brightcove side:
https://dev.amara.org/en/videos/tySsMITyAyUn/en/2/?team=brightcove-test-collab#subtitles_sync_history
https://dev.amara.org/en/videos/tySsMITyAyUn/es/3/?team=brightcove-test-collab#subtitles_sync_history
https://studio.brightcove.com/products/videocloud/media/videos/5734492854001

**Comment by bendk** [comment]
I think this should be fixed now, can you try again?

**Comment by PCF-Testing** [comment]
Sorry, still doesn't seem to work...

**Comment by bendk** [comment]
Hmm, I'm not sure what's happening there, but the one_time_url code is fixed and I thought that was the issue with this.  I think we should close this one since that was the main point.

Can you check if brightcove is working with production?

**Comment by bendk** [comment]
Made #3133 for the remaining work.

**Comment by PCF-Testing** [comment]
> Can you check if brightcove is working with production?

It is.
