### ISSUE TITLE
update the video page upload subtitles dialog

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1627]
The upload subtitles dialog on the videos page still has pre-dmr fields and restrictions. We can remove the Translated from field and the check on the number of lines.

Ideally we'd update the styling to match the dialog we use in the editor, or remove it completely and just have users upload via the editor, however @PCF-Testing mentions a concern that: 

_...users who, because of hardware, software, or ISP limitations, cannot open the subtitle editor and have to do all the translation work offline, just uploading the resulting file to the server. I agree that the Tools menu inside the editor is the right place for Upload command - but could we leave a back door somewhere for those users who cannot handle the editor, so that they still could upload without having to use API or send subtitles to tech support?_

**Comment by bendk** [comment]
This has been done.

**Comment by PCF-Testing** [comment]
This has not been done:

![screenshot from 2018-07-04 07 48 49](https://user-images.githubusercontent.com/288455/42283628-e407c5ae-7f5e-11e8-884e-b452d0f845d6.png)

But hopefully we won't need to fix it if subtitles only will be uploaded through the editor and there will be no separate upload dialog on the new video page.
