### ISSUE TITLE
issues when video URL are redirects to files

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#1641]
This URL pointing to an mp4 file:
https://median.emerson.edu/amara_dl/36375.mp4
redirects to this one
https://median.emerson.edu/html5/159a6b0823/36375_696kbps.mp4

Some in-consistent issues have been reported with these videos, on Safari and Firefox, but at least on Chrome, there is a consistent problem: since we alter the URL because of a Chrome bug where one file can not be loaded in several tabs (issue #1208) , the altered URL is not understood by the application server that does the redirect. So these videos just can not be loaded by the embedder or the editor on Chrome.

Hopefully we can find a solution, and we can investigate if the Chrome issue has been fixed.

**Comment by bendk** [comment]
Pretty sure that chrome bug has been fixed, so let's close this.
