### ISSUE TITLE
Task completion leaves language not marked as complete

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1655]
This has been reported by a few TED users but seems to be hard, if possible, to reproduce at will.

The task (translation or approval) is completed and submitted, but the language remains stuck in incomplete state.

Examples:
http://amara.org/en/videos/QsFNyf8yudNH/en/675027/
http://www.amara.org/en/videos/tbJUgoY7Jf17/zh-tw/726057

In most cases, however, task completion marks the language as complete.

**Comment by bendk** [comment]
I think this either fixed, or it happens intermittently.  Either way I think we should close and try to switch teams to collab.
