### ISSUE TITLE
Adjust DFXP upload to fit Brightcove/3Play formatted subtitles

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#1661]
3Play exports DFXP subtitles to Brightcove formatted in this way:

`<tt xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling">
 <head>`

 `<styling>
      <style xml:id="1" tts:textAlign="center" tts:color="white" tts:textOutline="black 2px 0px" >tts:fontSize="0.90c" tts:fontFamily="Arial, Helvetica, sans-serif" tts:padding="2px"/>
    </styling>`

`</head>`
 `<body>`
    `<div xml:lang="en">`
     `<p begin="00:00:00.00" end="00:00:04.59" style="1"><![CDATA[ ]]></p>`
     `<p begin="00:00:04.59" end="00:00:07.94" style="1"><![CDATA[For nearly 25 years, I wandered. ]]></p>`

Uploading DFXP files formatted this way doesn't work in Amara, unless the 1 in `<style xml:id="1"` is changed to a numerical value.

Is it possible to loosen our parser to allow DFXP files to be uploaded with a number in the xml:id?

**Comment by bendk** [comment]
I think this isn't an issue anymore.
