### ISSUE TITLE
With a YouTube channel linked to multiple teams, only one team lists it on Integration tabs

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1662]
Suppose a YouTube account is linked to several teams with checkboxes on Integration tab.

The channel and the list of linked (checked) teams are shown only on the Integrations tab of the team where the channel was linked from (example: http://staging.amara.org/en/teams/maggietest/settings/accounts/).

Integrations tabs for the other linked teams (http://staging.amara.org/en/teams/testm/settings/accounts/, http://staging.amara.org/en/teams/unisubs-internal/settings/accounts/) display "No youtube accounts linked yet." On attempt to link the same channel to these teams, error message "That youtube account has already been linked to the MaggieTest team"  is displayed.

EXPECTED:
1. If a channel is linked to multiple teams, show it for all the teams.
2. On attempt to re-link the channel to an already linked team, either silently ignore it or say "That YouTube channel has already been linked to the selected team".

**Comment by bendk** [comment]
We're working on updating the settings design.  Let's work on this one there.
