### ISSUE TITLE
Outdated text in video submission banner

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1682]
The banner displayed upon video submission still refers to the obsolete SubtitleMe widget button:

"To add or improve subtitles, click the button below the video."

Actually, there is no more such button. This sentence should be removed from the banner.

**Comment by bendk** [comment]
I believe this has been fixed.  Re-open if I'm mistaken.

**Comment by PCF-Testing** [comment]
Confirming it has been fixed. The banner says, "To start new subtitles, click "Add a new language!" in the sidebar."
