### ISSUE TITLE
VTT files mix \r\n and \n line breaks

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#1733]
The VTT files downloaded from Amara use DOS line breaks on all lines except the format header and the caption text itself, where they use a UNIX line break. E.g.:

```
WEBVTT{\n}
{\r\n}
00:00:03.895 --> 00:00:06.250{\r\n}
<i>(narrator) Like the proverbial pebble{\n}
dropped in a pond,</i>{\r\n}
{\r\n}
00:00:06.250 --> 00:00:10.040{\r\n}
<i>some surfers have an influence{\n}
so profound it ripples across oceans</i>{\r\n}
 ```

Apple's player seems to tolerate both, but Chromecast wants UNIX line breaks only. All three styles of line break are in spec ( http://dev.w3.org/html5/webvtt/#dfn-webvtt-line-terminator ), but mixing them seems to be causing trouble for some.

**Comment by franontanaya** [comment]
This issue is affecting Kickstarter users. The VTT files fail to upload until they replace all line breaks to UNIX.

**Comment by bendk** [comment]
Seems like what we're doing is valid, but I agree that mixing line breaks is confusing.  I just changed it to all unix-style in babelsubs.

Janet, can you update your babelsubs and test that nothing breaks?  I think it should be very safe, but we should test it before the next deploy.

**Comment by jdragojevic** [comment]
check that we can upload vtt with both types (what amara currently downloads) and new downloads have only unix-style line breaks.

**Comment by jdragojevic** [comment]
fixed and deployed ages ago.
