### ISSUE TITLE
Integrate help links better in editor

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#1742]
Help links should be better integrated into editor. Color is #44a76e

![screen shot 2014-09-25 at 11 41 16 pm](https://cloud.githubusercontent.com/assets/216145/4415608/0a6e30b6-452f-11e4-8bd1-631844ab0031.png)

**Comment by bendk** [comment]
Not sure what this one is, but the links now look blue.  Also, we're going to revamp the help in general.  Let's close this one.
