### ISSUE TITLE
Give error message when "start syncing" is unavailable

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#1743]
When an user clicks "Start syncing" and it's unavailable, it's totally impossible to tell why, and very frustrating. I could not find a blank line on this video, in english: http://amara.org/en/subtitles/editor/5Mo4oAj1bxOb/en/#

Before we get fancy with a fix, when the user tries to click the button, can we pop up a super simple javascript alert that explains the issue? It could just add the opening timestamp for the earliest blank line remaining:

![screen shot 2014-09-25 at 11 11 53 pm](https://cloud.githubusercontent.com/assets/216145/4415425/f10f2322-452a-11e4-9594-a00f81f0d91d.png)

**Comment by syl22-00** [comment]
This was done in a similar way as for issue #1866 :
* Show warning if typing phase can not be completed
* Warning links to first incorrect subtitle

**Comment by jdragojevic** [comment]
![image](https://cloud.githubusercontent.com/assets/299270/7250676/a8f315d8-e824-11e4-878e-fd6a4c2bef93.png)

Can we make the error text a little smaller (10px vs 12px) and change it to read: 'Subtitles can not be blank'

**Comment by syl22-00** [comment]
Wording and layout adjustments done in gh-1743

**Comment by jdragojevic** [comment]
since we now have the time warning, maybe we should switch the 'Not all lines are complete' to the same logic as the 'Subtitles can not be blank' error.

Otherwise, we could end up with double warnings link this: 

![image](https://cloud.githubusercontent.com/assets/299270/7302161/af9bb222-e9e7-11e4-9a5f-5f47bcff4dc4.png)

**Comment by syl22-00** [comment]
Done in branch gh-1743

**Comment by jdragojevic** [comment]
@syl22-00 there's a dash in front of the 'Timing error text' when it's the only warning.

![image](https://cloud.githubusercontent.com/assets/299270/7385553/a910a5ba-ee48-11e4-87e8-0472baf742d2.png)

Also - can you please make it so we only show 1 error message at a time vs both.  So if we are already showning the warning about blank lines, no need to show the timing warning too.

![image](https://cloud.githubusercontent.com/assets/299270/7385562/d550df3c-ee48-11e4-839e-46d8e0c35f46.png)

**Comment by syl22-00** [comment]
@jdragojevic that should be the case now

**Comment by jdragojevic** [comment]
@syl22-00 - one more request.  When a user first starts subtitling, of course there is always going to be blank lines.  Would it be possible during the typing step to not start showing the warnings until they've tried to Click on the 'Start syncing' button for the first time?

**Comment by syl22-00** [comment]
OK, so, as we discussed, those warnings are not shown while no subtitle is being edited.

**Comment by jdragojevic** [comment]
this stuff looks good.  Filed https://github.com/pculture/unisubs/issues/2193 minor errors related to the review stage warnings.

**Comment by jdragojevic** [comment]
deployed.
