### ISSUE TITLE
YT quota limit prevents subs from being sent to YouTube

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#1858]
If subtitle attempt to publish to YouTube is interrupted by the YT Quota limit, we don't try to re-publish them at a later time. This results in subtitles not showing up on YouTube, with the only workaround being to manually edit the subtitles and republish them, or for an Amara admin to force them to sync by hitting the "resync" button in the "sync history" tab on the language. 

Below are a few recent examples for context:
http://www.amara.org/en/videos/j0mRRF34HioK/it/847149/?tab=sync-history
http://www.amara.org/en/videos/sFdcbLuq05GG/es-mx/812251/?tab=sync-history
http://www.universalsubtitles.org/en/videos/0pAln1asqBuB/ko/846525/?tab=sync-history
http://www.universalsubtitles.org/en/videos/Dlp2INAqtEHP/ko/846534/?tab=sync-history

**Comment by bendk** [comment]
The gh-1858 branch should do this.  It uses a different scheme than the above system:

* Entries in the SyncHistory table have a retry flag.  If True, we should try to resync the subtitles for that entry.
* Every 5 minutes, we try to pick out one SyncHistory entry and re-sync it.
* Migrated entries start with retry=False.  We'll have to manually re-sync those.

This is semi-testable from a dev system.  I don't know a reliable way to cause the quota error to happen, so there's no way to test that code.  But you can go into the SyncHistory admin section and manually set the retry flag for any entry.  After you do that, you should look at the worker logs.  Within 5 minutes, we should try to re-sync those subtitles.

**Comment by jdragojevic** [comment]
@bendk 

I've gotten to a state where I get a multiple objects returned error.

I had my account configured for team syncing.  Then I deleted my account and then resynced the language.

It's on the Dutch version, not the English.

![image](https://cloud.githubusercontent.com/assets/299270/5645787/41881512-9674-11e4-9c06-a78c8b041d08.png)

![image](https://cloud.githubusercontent.com/assets/299270/5645793/563a255e-9674-11e4-9b88-313f1b19c933.png)


```
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/unisubs/apps/videos/decorators.py" in wrapper
  21.         return func(request, video, *args, **kwargs)
File "/opt/apps/unisubs/apps/videos/views.py" in language_subtitles
  676.     context = ContextClass(request, video, lang, lang_id, version_id)
File "/opt/apps/unisubs/apps/videos/views.py" in __init__
  522.         self.setup_tab(request, video, language, version)
File "/opt/apps/unisubs/apps/videos/views.py" in setup_tab
  650.                            get(video_url=video_url)).version
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in get
  368.                 % (self.model._meta.object_name, num, kwargs))

Exception Type: MultipleObjectsReturned at /videos/d8bfF0HDpu9k/nl/16/
Exception Value: get() returned more than one SyncedSubtitleVersion -- it returned 2! Lookup parameters were {'video_url': <VideoUrl: http://www.youtube.com/watch?v=rIE6Mk0VRg0>}
```

**Comment by jdragojevic** [comment]
After I hit resycn on the English version - I got the same error.

**Comment by bendk** [comment]
0a77a19 should fix the MultipleObjectsReturned errors.
