### ISSUE TITLE
Handle private YouTube videos gracefully

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1863]
A private video from YouTube can be submitted into the system if its URL on YouTube is known. However, the video does not load into the embedder and subtitle editor, no matter whether by the video's owner or by somebody else. Embedder endlessly shows the "loading" animation.

Suggested solutions:
- Suppress uploading private videos
- Display an appropriate message if the YouTube video is private and cannot be loaded

**Comment by kslottow** [comment]
we will accept these pculture/amara-enterprise/issues/1129
