### ISSUE TITLE
Editor: Don't allow saving if timestamps are invalid

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#1866]
We should prevent saving and display a dialog box if the subtitles have invalid timestamps.  I don't think these can be created in the editor, but they can be uploaded.  Invalid timestamps include:

* Any time < 0
* start_time >= end_time (or should equal be considered valid?)
* start time > video duration (?)

We need to decide a few things about the UI for this:

* How should the errors be displayed?
* Should save draft be allowed?

**Comment by syl22-00** [comment]
This should be done in branch gh-1866:
* warning if:
    * Any time < 0
    * start_time >= end_time
* Subtitle can't be publish if such warning present
* Warning is a link to first invalid subtitle

**Comment by jdragojevic** [comment]
@syl22-00 

Another case for this is where the user managed to somehow copy/paste a block of subtitles so they have cases where the start-time is the same in the following subtitle.

Please look at: http://www.amara.org/en/videos/QoE9qzu3qdFq/es/298369/#revisions @ time 17:59

In the editor the times are displayed by timestamp, and you can see two with identical start times:

![image](https://cloud.githubusercontent.com/assets/299270/7135009/d5427c64-e2a2-11e4-8830-84e26ee968a1.png)

In the actual subtitle file - there's actually a whole block of subs that was pasted in somehow and the time jumps from 22:17 to 17:59.  

```
00:22:03,787 --> 00:22:06,417^M
las señoras del almuerzo le miran y dicen:^M
^M
290^M
00:22:06,417 --> 00:22:08,556^M
nunca olvidaré la primera vez que vi esto,^M
^M
291^M
00:22:08,556 --> 00:22:11,368^M
la señora de almuerzo dice:
"¿Quieres vegetales hoy?"^M
^M
292^M
00:22:11,368 --> 00:22:13,698^M
[Johnny:] "No".^M
^M
293^M
00:17:59,229 --> 00:18:01,399^M
[Señoras de almuerzo:] "¿Quieres fruta hoy?"^M
^M
294^M
00:18:01,419 --> 00:18:02,795^M
[Johnny:] "No".^M
^M
295^M
00:18:02,800 --> 00:18:06,160^M
Pues Johnny recibe un pedacito
de pizza y una leche chocolatada^M
^M
296^M
00:18:06,160 --> 00:18:08,974^M
porque muchas escuelas dan
a nuestros hijos la opción^M
^M
297^M
00:18:08,974 --> 00:18:12,227^M
de si quieren vegetales
o fruta en el plato o no.^M

```

I belive this is the primary reason that TED was requesting this fix.

**Comment by jdragojevic** [comment]
more information on this case is in #794 translations with invalid timings.

**Comment by jdragojevic** [comment]
@syl22-00 - also I don't see any way to get negative start or end times into the editor.

**Comment by syl22-00** [comment]
The case of 2 subs with same start time was added. UI was slightly improved in case of multiple warnings in workflow

**Comment by jdragojevic** [comment]
Errors look like this and prevent publish or approval.  Clicking the link will bring the user to the subtitle line that is in error.

![image](https://cloud.githubusercontent.com/assets/299270/7158272/9baa036a-e378-11e4-8bc4-b36b9c95e0df.png)

Added testcases for checking the various error conditions.

**Comment by jdragojevic** [comment]
deployed.
