### ISSUE TITLE
Add some more options per subtitle line in the editor

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1873]
Add some controls at the subtitle line to allow users to:
- [x] Insert a new line above or below ( and remove the + that interferes will adding line breaks sometimes.)
- [x] Add a note that includes the start time of the current sub
- [x] jump the video to the start time of the current subtitle

**Comment by jdragojevic** [comment]
@syl22-00  - can you just capitalize the start of 'seek to subtitle' so it is 'Seek to subtitle' and matches the rest of the hover help hints.

**Comment by jdragojevic** [comment]
@syl22-00 the sync helpers are not displaying during sync after the first subtitle.

**Comment by syl22-00** [comment]
@jdragojevic May it just be because the screen is too narrow (we had this issues a few times before)? Tray does display fine for me.

**Comment by jdragojevic** [comment]
@syl22-00 the disappearing helpers I can reproduce on ff and chrome they show only for the first subtitle and then they don't show for the rest. Same sized browser and they do display on staging branch

**Comment by jdragojevic** [comment]
if it helps track this down - for me it actually starts with the first commit of this branch:

6cb0bfb751be81f40e36daf2d40df1e7e1d9
