### ISSUE TITLE
Make the soft limits on subtitle line length and CPS customizable per subtitle request via API

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1874]
Some users need that warnings in the subtitle editor be triggered by different values of line length and cps. These limits need to be made customizable.

First, we'll allow setting different subtitle line lengths and CPS via the teams API.

Later, we can:
- include it in the UI
- make it customizable per language
- make it customizable per batch (group of subtitle requests with due date that can be linked to client billing)

Request: 
http://ted-support.amara.org/helpdesk/tickets/76382

**Comment by PCF-Testing** [comment]
Requested in https://pculture.freshdesk.com/helpdesk/tickets/100936.

**Comment by kslottow** [comment]
Issue moved to [pculture/amara-enterprise #2137](https://github.com/pculture/amara-enterprise/issues/2137) via [**ZenHub**](https://www.zenhub.com/)
