### ISSUE TITLE
show failed sync list to team admins

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1881]
We should have a page visible to team admins that any sync errors for the latest revision of videos on that team and allow the admin to initialize a resync

**Comment by syl22-00** [comment]
OK, so that should finally be here and working:
* Only the last sync error is displayed for a given subtitle language
* Items marked as "retry" are not in the list as they are scheduled to be resynced
* Once an item is selected to be resynced, it is marked as "retry", meaning that it will take a few instants to retry, during which it is not part of the list anymore. So if an item is selected, once submitted, it will be out of the list, and if sync still fails, it will be added again to the list (it will LOOK the same, but will actually be a new sync history item to resync).

**Comment by syl22-00** [comment]
List is also available for users, from the account page.

**Comment by jdragojevic** [comment]
UI:

table headings v content:

![image](https://cloud.githubusercontent.com/assets/299270/7677735/ef1913b6-fd4e-11e4-918f-e9faa98093d9.png)

![image](https://cloud.githubusercontent.com/assets/299270/7677725/dca4c694-fd4e-11e4-959a-adb52f240fdc.png)


What if we:

- [ ] 1. Put the checkbox first, and included a select all option
- [ ] 2. Instead of showing video title or url, just link to the url / amara video page, so
- [ ] 3. Shorten the headings we just show 'Language' instead of Subtitle Language and 'Error' vs Error Details
- [ ] 4. Use the light-blue table border color like we do for the simple-list  that we make for the bulk-approve tasks table vs the black outline.


![image](https://cloud.githubusercontent.com/assets/299270/7677930/6d289942-fd50-11e4-87df-5c0b3a2bf7d3.png)

On the new-style teams - maybe just left-align the headers and use the blue button style.

**Comment by syl22-00** [comment]
@jdragojevic those changes should be done now

**Comment by jdragojevic** [comment]
Bit of an alignment issue for the new style teams:

![image](https://cloud.githubusercontent.com/assets/299270/7698187/79e883cc-fe0e-11e4-9dfb-d6afd4ef2fe9.png)

**Comment by jdragojevic** [comment]
How it looks on User account page:

![image](https://cloud.githubusercontent.com/assets/299270/7699835/0549a2c8-fe1b-11e4-816e-0de1ed9746ba.png)

![image](https://cloud.githubusercontent.com/assets/299270/7699859/1d1f7990-fe1b-11e4-9338-81018129311d.png)

**Comment by syl22-00** [comment]
Latest screenshot, for knowledge base
![sync_issues_table](https://cloud.githubusercontent.com/assets/875066/7700674/a1c8e01e-fe20-11e4-97b7-0bb19d3d159f.png)

**Comment by PCF-Testing** [comment]
If the Video column lists the video ID, could it be the video title instead? Would be more user-friendly, especially with lots of videos on a single account.

**Comment by jdragojevic** [comment]
We had a long chat about that and there are a few drawbacks:

1. if there is no title it defaults to the video url which is long and ugly.
2. if there is a really long title - we'd need to truncate it, since there
isn't a lot of space in the table.

Using the video id has a fixed length and makes it easy to scan if there
are a bunch of errors for 1 video and also since there's a link to the
video lang page, it's easy to get there and see what the video is.

**Comment by jdragojevic** [comment]
if I have a database with about 100000 versions I get this error opening the sync page

```
139783185430272 Internal Server Error: /en/teams/team-1/settings/sync/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/apps/unisubs/apps/teams/views.py", line 138, in wrapper
    return view_func(request, team, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/apps/unisubs/apps/externalsites/views.py", line 107, in team_settings_sync_errors_tab
    sh = SyncHistory.objects.get_attempts_to_resync(team=team)
  File "/opt/apps/unisubs/apps/externalsites/models.py", line 686, in get_attempts_to_resync
    video_id = item.video_url.video.video_id
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 350, in __get__
    rel_obj = qs.get(**params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 361, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 85, in __len__
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 838, in execute_sql
    return list(result)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 832, in <lambda>
    result = iter((lambda: cursor.fetchmany(GET_ITERATOR_CHUNK_SIZE)),
InterfaceError: Cursor needed to be reset because of commit/rollback and can no longer be fetched from.

```

**Comment by jdragojevic** [comment]
this was deployed.  closing.
