### ISSUE TITLE
Add lists of My Subtitles and Videos I Follow to user profile

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1882]
A lot of incoming user requests are related to their need of a better way of tracking videos and subtitles.

At this time, users only have their personal activity log (which lists every edit they make and sometimes duplicate or triplicate entries of the same event - hence, it is very long and unwieldy) and the list of videos they submitted to Amara (except anonymous submissions). There have been even conflicts between users regarding who should have the video listed in their profile - the copyright owner whose YouTube channel hosts the video, or the actual contributor of the video.

To ease this tension and provide users with better tools for tracking their past work and the videos they are interested in, we need more lists, which can be added as new tabs in the profile:
- [ ] - _My Subtitles_: the list (with clickable URLs) of the languages the user has ever worked on, sorted in reverse chronological order
- [ ] - _Videos I Follow_: the list of videos where the user follows the whole video or some language(s)

When the user retires the account, both these lists and My Videos tab should display "Profile deleted by user." instead of actual data.

**Comment by andreamussap** [comment]
Hello,
I think when you say "My Subtitles: the list (with clickable URLs) of the **languages** the user has ever worked on", you mean "the list (with clickable URLs) of the **subtitles** the user..", isn't it?

At least, what I'd like to see is the list of the subtitles that I've worked on.

**Comment by bendk** [comment]
When we talk about subtitles, "Language" usually means the set of subtitles in a language for a video.  Meaning you would see a list like:

 * English subtitles for Video A
 * French subtitles for Video A
 * English subtitles for Video B
...

So 1 item for each video/language pair even if you saved multiple revisions for that language.  Would that work for you?

The terminology isn't great, but we haven't found something better to replace it with.

**Comment by andreamussap** [comment]
Ok, thanks.

**Comment by kslottow** [comment]
now included in #2124
