### ISSUE TITLE
Add some more help for new users of the Editor

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1883]
We've heard from a few different sources that using the Amara editor for the first time can be a bit confusing. 

We should add in some context-sensitive help so that users in the Editor have access to some additional resources.  We do have our short-clear translated help videos that we should use.

My suggestion is that we add a link in each of the progression steps, for help.

![image](https://cloud.githubusercontent.com/assets/299270/5200468/878a7674-7566-11e4-916f-54e27f75bcf3.png)

Clicking the link would open a page in a new tab that has the relevant embedded help video, and maybe some additional text and links to the support pages with related content.

Also Margarita has suggested we use video urls in the embedded videos that we host on our own S3 server to avoid the issue of hosting services banned in some countries.

For example the Typing Step would go to a page with the http://amara.org/en/videos/JPKkPWXIDG7x/info/typing-step/ video, whereas if it was a translation, we'd have a page with translation specific help http://amara.org/en/videos/mBUYmL6sROYS/info/translating-subtitles-with-amara/ and some advanced hints about switching reference languages and using copy timings.

Once we have better more detailed help in place, we can remove the help overlayed on the videos.

**Comment by syl22-00** [comment]
Branch gh-1883 has the overlay, it includes a migration to keep user's preference (ie still wants to see the overlay next time)

**Comment by jdragojevic** [comment]
Few comments on the styling: 

1.  I think reddish-pink it too jarring / rough on the eyes, what about teal or blue, for me, blue is most readable.
2. We should hide/remove the video overlay help when we have this new overlay
3.  Need some more space between the heading and the text of the bubbles
4. I think we should point out the play / pause helper, not the video play button because 1 common issue users have reported,  is not knowing that they can easily pause the video.
5. The banner should go from the edge of the left panel to the edge of the right panel and not stretch into the dark border (if possible)
6. Made some tweeks to the wording
7. On the banner wording, I think the don't show again, should be centered and not off to the right so it's immediately obvious that they can put it away forever.
8. Hide forever checkbox should be centered with that line of text, not top-aligned.


### Current branch

![image](https://cloud.githubusercontent.com/assets/299270/6247035/ef5e32ae-b76f-11e4-82f2-a6a62e9c7ac5.png)


### Recommended Changes
![image](https://cloud.githubusercontent.com/assets/299270/6246952/b7c63054-b76e-11e4-8f8b-5362e2948742.png)

### Or maybe in blue
![image](https://cloud.githubusercontent.com/assets/299270/6247063/5e35f2e8-b770-11e4-97c2-476f2a01fb10.png)

**Comment by jdragojevic** [comment]
Some functional comments:

- [ ] This overlay is specific to the transcribing step.  It should not be displayed for review / approve steps.  We should also make a seperate one for a 1st time translator, which is more common on teams like TED.

- [ ] The checkbox should reflect the stored state in the db and not display unchecked by default.  So if you hide it forever, and then display via the tools menu option, it should show that it is checked.  I can't image a user would want to uncheck it, however if we allow that, then it should work.

**Comment by syl22-00** [comment]
At commit 95ac5b363f2acd6845cb0f1baa3e644ab765bb67 we now have:
* Color of bubbles is teal
* Old overlay on video is out
* Welcome banner is only displayed to new users, not when tutorial is open through menu item
* Tutorial content depends on workflow stage
* Content for sync and review stages was added
* Styling improvements
* Existing users do not see tutorial by default (added data migration)

**Comment by jdragojevic** [comment]
- [ ] make the boxes a bit wider and try to center more around the section where they are pointing.

Some wording tweaks:

- [ ] Banner line 2: Click anywhere to hide me. Find me again in the tools menu for help with any step.
![image](https://cloud.githubusercontent.com/assets/299270/6265499/47f00356-b82f-11e4-87f6-2cabbf29c269.png)

- [ ] Typing step 2: Once you fill a line, hit enter. Don't worry about timing. 
- [ ] Typing step 3: Click to start syncing your subtitles.

- [ ] Syncing step 1: Keeps the same as Typing step 1.
- [ ] Syncing step 2: Position bubble below the first line of text with the arrow pointing upwards.  Text should read:
  - [Line 1] 2. Press the Down Arrow to start each subtitle.
  - [Line 2] Don't worry about small mistakes, we can adjust them later.
  -  Line 3] If you need start over, use clear timing from the tools menu.
- [ ] Syncing step 3: (pointing at the review button)
  - [Line 1] 3. Are all lines completed and timed?
  - [Line 2] Click to review and make corrections.

- [ ] Review step 1: (points at the Guidelines link)
 - [Line 1] 1. Checkout the guidelines for tips on making quality subtitles
- [ ] Review step 2: (points at the timeline bubbles)
 -  [Line 1] 2. Adjust the subtitle times
 - [Line 2] Click on a bubble to drag the whole thing or just grab move the edges for fine-tuning.
- [ ] Rebiew step 3 (points at the Complete / Publish button)
 - [Line 1] 3. Click when you are done subtitling.
 - [Line 2] Or click Save Draft to come back and finish later.

**Comment by jdragojevic** [comment]
Starting a new translation step.  

- [ ] Translation step 1 (Below the reference language pulldown menu pointing upwards)
 - [Line 1] 1. Select the language you want to use as a reference
 - [Line 2] Here's a quick video with more info about reference languages. (Link to http://www.amara.org/en/videos/j0mRRF34HioK/info/switching-reference-languages/)

- [ ] Translation step 2 (Points to the Blank space in the working lang)
 - [Line 1 ] 2. Fill in all the blank lines with your translated text
 - [Line 2] Use the tools menu copy timings if you have changed the reference language.

- [ ] Translation step 3 (points to the syncing button)
 - [ Line 1] 3. Done translating?
 - [Line 2] Click to adjust the timing.

- [ ]  Translation Syncing help
 - [Step 1] Same a Typing 1.
 - [Step 2] Same as Review step 2.
 - [Step 3] Same as Typing step 3.

**Comment by syl22-00** [comment]
All above items should now be completed. There should also be a wrench icon in the banner to indicate more clearly where to find the tutorial later.

**Comment by jdragojevic** [comment]
@syl22-00  - just a few minor wording tweaks from jenny @ ted.

1. edit text in bottom banner:
"Click to hide. Reopen anytime from the tools menu ( Tools > Show tutorial).

2. first time translator (translate step) — edit helper text for #1:
“If you change the reference language, use Tools > Copy Timings to update the translation timing.”

3. first time translator Review step + Peer Review step — edit helper text for #1:
“They include tips for improving subtitles.”

Check the screenshot shot as it uses the image not the word tools.

![image](https://cloud.githubusercontent.com/assets/299270/6380346/3eeb3564-bd39-11e4-9da8-ab66dec89a61.png)

**Comment by jdragojevic** [comment]
fixed and deployed.
