### ISSUE TITLE
Improve type readability for Amara.org homepage + nav

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#1890]
Some reports of poor type legibility, esp on windows w/ certain versions of chrome.

![screen shot 2014-12-02 at 1 30 28 pm](https://cloud.githubusercontent.com/assets/216145/5268440/78a7d7a8-7a27-11e4-9239-c8bea2910fdb.png)

**Comment by jdragojevic** [comment]
Here's the demo of the latest changes: http://gh-1890.amara.org/en/

If you both can give your opinions, we can get this merged in.

**Comment by deanjansen** [comment]
Looks good to me. Still pretty thin in windows, but it is more legible.

**Comment by franontanaya** [comment]
Just saying -- the fad now is Roboto, because it's the font used in Google's "Material" recommendations.

http://www.google.com/fonts/specimen/Roboto

The font declarations at http://gh-1890.amara.org/en/ are using `"Helvetica Neue", Helvetica, sans-serif` as the base, but Helveticas are Mac fonts and the design will default to whatever is set as "sans-serif" for Windows and Linux. `"Helvetica Neue", Helvetica, Arial, "Liberation Sans", sans-serif` would be more multiplatform.

**Comment by jdragojevic** [comment]
@deanjansen  - I closed the pull request for now in case you'd like to take Fran's comments into consideration.

I personally don't like the way it looks on my machine (chrome, ubuntu), but was deferring to your opinion hoping it was looking better on windows and osx.

![image](https://cloud.githubusercontent.com/assets/299270/5737977/5706ac28-9be7-11e4-9ea3-9278bdb41a12.png)

![image](https://cloud.githubusercontent.com/assets/299270/5737982/64fa260c-9be7-11e4-87a5-55647a5b347a.png)

**Comment by deanjansen** [comment]
Thanks for the advice, @franontanaya – I'll try some add'l experiments.

**Comment by deanjansen** [comment]
Just pushed again – still need to check it out in windows/linux, but it seems to look pretty decent in OSX.

**Comment by jdragojevic** [comment]
I think this looks significantly better.  

Here's a screenshot from a saucelabs run on windows 8.1 and ie 11
https://assets.saucelabs.com/jobs/524b7ff896d54f0390639f51b8f55b33/0001screenshot.png

Here's what is looks like for me on linux:
![image](https://cloud.githubusercontent.com/assets/299270/5797386/38ebdb20-9fb9-11e4-8591-3877d6cdac1a.png)

![image](https://cloud.githubusercontent.com/assets/299270/5797389/48381aa8-9fb9-11e4-9ba0-575e4a8278d8.png)

**Comment by jdragojevic** [comment]
this was deployed to production.
