### ISSUE TITLE
Add Tunisian Arabic

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1896]
ISO 639-3 code: aeb (http://en.wikipedia.org/wiki/Tunisian_Arabic)
Direction: RTL

Reason: http://ted-support.amara.org/helpdesk/tickets/76765
Tunisian Arabic is the language of ~11 M people, with the scientific terminology significantly different from the Standard Arabic.

**Comment by jdragojevic** [comment]
this was deployed.
