### ISSUE TITLE
Team activity filtering works incorrectly for comments

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1930]
When activity type is set to "comment" and a particular language is selected, comments on all the languages are returned:

http://www.amara.org/en/teams/ted/activity/?q=&action_type=3&subtitles_language=en&video_language=any&sort=-created

Reported in: http://ted-support.amara.org/helpdesk/tickets/77053

**Comment by bendk** [comment]
See #826 for the history of this one.

**Comment by jdragojevic** [comment]
@bendk - testing on the new-teams-ui branch.  Old-style teams are missing the filters.

No filters and no toggle

![image](https://cloud.githubusercontent.com/assets/299270/8357054/1c60e3ee-1b59-11e5-8cb2-ee94c17f8b87.png)

**Comment by jdragojevic** [comment]
this was fixed and deployed.
