### ISSUE TITLE
Compute team activity statistics as task

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#1935]
We should:
. Compute statistics for all teams at regular intervals and keep the result
. When statistics are displayed, we should show when they were computed

**Comment by syl22-00** [comment]
This was done in brancg gh-1935, but instead of computing them in tasks, it uses a per-view caching, which does what we want. For testing, cache is set to expire in one minute, will be changed to one day (or any other value) once tested.

**Comment by jdragojevic** [comment]
![image](https://cloud.githubusercontent.com/assets/299270/5723993/a901a1da-9b48-11e4-8a15-d67d9dbca585.png)
