### ISSUE TITLE
As an Amara user, I want to be redirected to a single domain whether I log into www.amara.org or amara.org

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#1943]
Currently if you log in on www.amara.org, you get cookies for www.amara.org and are logged for that subdomain, but not for amara.org, and vice-versa.

- [x] With Darren, compile list of partners that have API integrations
- [ ] notify partners with API clients that they need to update their code to make calls to amara.org (not www.amara.org)
- [ ] redeploy this fix

Problem A: 
1. Log in to www.amara.org with your amara username.
2. Open a new tab and log into amara.org with the same username.  You are now logged in separately to the two subdomains.

This leads to situations in which you think you are logged in/out of your account while you aren't on one of the domain versions.  It would also be bad on shared computers, where logging out of both domains would be necessary.

**Expected:**
All amara.org URLs redirect on the server either to the domain with www, or the one without.  When I log into www.amara.org, I am automatically also logged into amara.org.

Problem B: 
1. Log into amara.org with one username.
2. Log into www.amara.org with another username on your account.
3. In some cases, Amara switches that person back-and-forth between the two usernames.  
    - Darren thinks this is causing linguists to be switched
back-and-forth between their old deleted VT accounts and their newly
created VT Sesame accounts.

We put a band-aid on this issue by instructing VT and Google teams (the ones experiencing the most problems due to this bug) to always add "www" to Amara URL's, but it has come to the attention of both important clients so we should fix as soon as possible.

**Comment by deanjansen** [comment]
Longer term, is it worth redirecting all traffic from www.amara.org to the equivalent amara.org page (i.e. no longer use 'www')? 

That's beyond the scope of this ticket and I don't know about feasibility or side-effects, but maybe this could be a dev-ops project?

**Comment by bendk** [comment]
This is trivial to do and I believe it's been suggested before.  My understanding is that some people liked the non-redirect, but I could be wrong about that.

It's also possible to share the cookie across www.amara.org and amara.org.

Which behavior is the best?

**Comment by bendk** [comment]
I just implemented the redirect.  Looks like it's working to me.

**Comment by kslottow** [comment]
@bendk confirming that this was the solution:

All logins/links to www.amara.org are now redirected to amara.org.

- It is no longer possible for a user to be signed in to www.amara.org and amara.org separately, which should eliminate the problems.
- if a user is was logged into a combination of the two domains before this fix, they are now logged in only to amara.org and should not experience problems related to dual login.

**Comment by bendk** [comment]
Pretty much.  The one issue remaining is if a user was only logged into www.amara.org.  In that case, they will be redirected, but not logged in.  They'll need to re-login.  However this shouldn't be an issue going forward since the redirect code will make it so you always login to amara.org.

**Comment by bendk** [comment]
I guess another issue would be if they were logged into www.amara.org and amara.org with different accounts.  Again, they'll need to re-login to the correct account.

**Comment by kslottow** [comment]
Got it - we'll make sure they know to do that.  Thanks!

**Comment by kslottow** [comment]
@bendk please roll back this change for now, we can re-deploy (is that the right word?) after giving partners a few days to update their code so that they don't run into issues.

**Comment by deanjansen** [comment]
Add'l background: One partner integration is repeatedly triggering requests

**Comment by kslottow** [comment]
@bendk please confirm: it is not possible on our end to redirect all API calls to amara.org; each partner with an API client needs to update their own code.

**Comment by bendk** [comment]
It's possible to redirect the calls and that's what we were doing.  However that often doesn't work with API clients, because a) they often don't follow redirects b) the HTML spec says not to send POST data to the redirected URL (I think).
