### ISSUE TITLE
redesign login page to use newer page layout

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1944]
With gh-1902 we are requiring users to be logged in to submit a video.  Since the homepage links to the submit page - and a new user will have a stop a the login page in the middle - we should keep the styles consistent.

@deanjansen  - do you want to work up something for this?

**Comment by deanjansen** [comment]
@jdragojevic yes, will aim to have some mockups by next week, if that sounds good.

**Comment by jdragojevic** [comment]
@bendk @syl22-00 

Dean made some styling changes to the login form page 1e64946d0b6c94cfdc796d5f682a6e99c049b039.  

When you have a chance can one of you please review the changes.

**Comment by bendk** [comment]
Looks fine from a code perspective.

**Comment by deanjansen** [comment]
Could someone let me know when this goes live – I'll make a note in analytics and then we can see if there's any obvious change in the bounce/exit rates for new folks coming to the create subtitles page.

Thanks in advance.

**Comment by jdragojevic** [comment]
@deanjansen this was deployed.

**Comment by deanjansen** [comment]
Annotation added to analytics. Thanks.
