### ISSUE TITLE
Do not show line breaks in the transcript viewer

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1950]
Currently the transcript viewer breaks lines where a subtitle has a line break (Shift+Enter) in it. This does not look nice, and the text is uncomfortable to read. Line breaks should be ignored in the viewer.

![linebreaksintranscriptviewer](https://cloud.githubusercontent.com/assets/288455/5690192/2ea24ec4-982f-11e4-99ef-73ae08fbbd50.png)

**Comment by syl22-00** [comment]
In branch gh-1950, we now have, in the transcript viewer:
* new lines in subtitles are ignored,
* new subtitle does not trigger a new line,
* `new_paragraph` mark does trigger a new paragraph (it was not working properly).

**Comment by andreamussap** [comment]
Hi.
I've tested this ticket here: http://gh-1950.amara.org/en/videos/Fknr4iEi16ar/info/open-source-philosophy/

I tested line breaks with markup (bold and italics) and it worked fine.
