### ISSUE TITLE
Restyle Guidelines link in the subtitle editor

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1951]
Restyle TED Guidelines link in the subtitle editor to make it stand out.

Request: http://ted-support.amara.org/helpdesk/tickets/77370

**Comment by kslottow** [comment]
Issue moved to [pculture/amara-enterprise #1186](https://github.com/pculture/amara-enterprise/issues/1186) via [**ZenHub**](https://www.zenhub.com/)
