### ISSUE TITLE
staging:  error accessing paginated pages

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1960]
http://staging.amara.org/en/profiles/profile/janetPCF/ for example.

http://logman.amara.org:9000/pcf/amara-staging/group/585/

```
KeyError: 'page'

File "profiles/view.html", line 24

<div class="highlight"><pre>                    &lt;li&gt;{{ item.render }}&lt;/li&gt;
</pre></div>
<div class="highlight"><pre>                {% endfor %}
</pre></div>
<div class="highlight"><pre>            &lt;/ul&gt;
</pre></div>
<div class="highlight"><pre>            {% if is_paginated %}{% paginator %}{% endif %}
</pre></div>
<div class="highlight"><pre>        {% else %}
</pre></div>
<div class="highlight"><pre>            &lt;p class=&quot;empty&quot;&gt;{{ user_info }} {% trans &quot;doesn&#39;t have any activity yet.&quot; %}&lt;/p&gt;
</pre></div>
<div class="highlight"><pre>        {% endif %}
</pre></div>
```

**Comment by bendk** [comment]
This seems like a general bug with the views that used object_list() and pagination.  Can you try testing that view with a ton of activity and make sure the pagination works well.  Also, can you test the team dashboard/videos page, which use a slightly different pagination code path?

**Comment by jdragojevic** [comment]
Also on the user messages page: http://staging.amara.org/en/messages/

Team pages pagination is fine.

**Comment by bendk** [comment]
let me deploy staging, then can you test again?

**Comment by jdragojevic** [comment]
@bendk I am still seeing this on staging

**Comment by bendk** [comment]
Oops, the code hasn't been merged yet.  It's still in the gh-1960 branch.

**Comment by jdragojevic** [comment]
this was deployed to production.
