### ISSUE TITLE
sync-history: multiple objects returned

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1961]
It's possible to get this error such that the sync history page won't open:

http://logman.amara.org:9000/pcf/amara-staging/group/612/

If the version was previously synced
Delete the youtube account associated to the team
Re-add the account
Attempt to re-sycn the video.

The actual syncing reports success (can see in the history table), but further attempts to access the sync-history tab result in an error page.

```
Exception (most recent call last)
MultipleObjectsReturned Root Cause
get() returned more than one SyncedSubtitleVersion -- it returned 2! Lookup parameters were {'video_url': <VideoUrl: http://www.youtube.com/watch?v=kZfDoRpQDnw>}
```

Deleting the entry for the video/language in the http://staging.amara.org/en/admin/externalsites/syncedsubtitleversion/ page, where the version is shown as associated with (deleted account) will resolve the errors.

**Comment by bendk** [comment]
The gh-1961 branch should fix the main issue here which is that we weren't deleting the SyncedSubtitleVersion and SyncHistory objects when we deleted an account.

A side issue is that page can't handle multiple accounts per video URL.  If there's ever a case where we sync a single video URL to multiple sites, then this error will happen again.  I don't think there's any plans as of now though, so I didn't fix that part.

**Comment by bendk** [comment]
I just saw the notes in #1972...  Is it an issue that we delete the sync history when we delete the account? There are other ways we could deal with this ticket.  We could also try to re-use the same account model object when you unlink, then re-link you're account.

**Comment by jdragojevic** [comment]
so #1972 could come from deleting, but it could also be from a late decision to sync.  I thought of it today when testing this branch - but thought to keep it seperate.

**Comment by bendk** [comment]
I don't mean issue #1972 specifically, just the issue of unlinking an account and relinking it.  Is it bad UI if that causes the sync history to be lost?

**Comment by jdragojevic** [comment]
I guess in the case where the user linked / unlinked because they had syncing issues, losing the history wouldn't be great because there would not be a good way to tell which videos had never been synced - so all videos would need a retry.

**Comment by bendk** [comment]
I think what we should do is when a user/team unlinks the account, we keep the object in the DB but flag it inactive or something like that.

When a user/team re-links an account:
* If there is a inactive account with the same channel id, we re-use that object and update the auth info
* If there is an inactive account with a different channel id, we delete it (at this point we would lose the history).

**Comment by bendk** [comment]
Alternatively, we could make it so we don't ever delete accounts and we support multiple accounts per video URL on the history page.

**Comment by jdragojevic** [comment]
@bendk - perhaps supporting multiple would be best, as I do believe we have some customers they use both youtube and vimeo, or other combinations of video hosts.

**Comment by bendk** [comment]
So for this issue, I think we should just commit the current code and call it finished.

Supporting multiple accounts could be nice for some edge cases, but note that the only issue is having multiple accounts per video URL.  So teams/users could have both vimeo and youtube accounts linked without issue.

Keeping the youtube account info around after you unlink the account is also nice, but we would have to deal with a couple tricky things:
  * Deleting the video feed.
  * Re-using the account if you re-link it.

I think both of these things should be separate ticket and I'm hoping they can be low priority.

**Comment by jdragojevic** [comment]
this was checked and deployed.
