### ISSUE TITLE
staging: autocreate missing collaborations

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1964]
Moved some videos into a collab team on staging.
Set autocreate translation for a lang
Clicked the autocreate_missing_collaborations button.

Result error:

```
DatabaseError: (1267, "Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='")
```

**Comment by bendk** [comment]
So this is related to the mysql collation settings.  I have to admit that I have little clue what's going on.  I ran this statement to on staging to make the values match production:

set collation_database=utf8_unicode_ci;

Can you test it out after that change?  If that doesn't work I'll need to make it so we change collation settings for the tables/ columns.

**Comment by jdragojevic** [comment]
I still got the error page

**Comment by bendk** [comment]
Janet says this one got fixed on staging after I messed with the collate settings enough.
