### ISSUE TITLE
Add Gothic language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1967]
Gothic language, http://en.wikipedia.org/wiki/Gothic_language

ISO 639 code 'got'

Request: http://ted-support.amara.org/helpdesk/tickets/77491

**Comment by PCF-Testing** [comment]
Can this one get squeezed into the development schedule any time soon?

Thanks!

**Comment by bendk** [comment]
I just merged the branch, it should be available after the next deploy.
