### ISSUE TITLE
Place complete, working embed code into Embed Video dialog

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#1968]
At this time, Embed Video dialog offers a placeholder for embed code that must be filled out by users, e.g.
<div class="amara-embed" data-height="px" data-width="px" data-url="">
</div>

Expected: include the full list of available parameters and set them to the default values, so that users could paste the script into HTML code and get a working offsite embedder.

Reason:  some users are struggling with filling out the placeholders, making plenty of mistakes that render the player non-functional or make it work incorrectly.

**Comment by PCF-Testing** [comment]
The need for complete script reiterated at support.amara.org/helpdesk/tickets/78039.

**Comment by PCF-Testing** [comment]
Actually, users are trying to insert the URL of Amara page instead of the video URL into embed script template: http://ted-support.amara.org/helpdesk/tickets/78247

**Comment by syl22-00** [comment]
Done in branch gh-1968
