### ISSUE TITLE
Add A/B test to Amara.org homepage

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#1969]
Try a split test on amara.org...

**Comment by deanjansen** [comment]
Just pushed code that should render a split test for navigation site-wide on amara.org. 

Will test these changes in nav: 

![screen shot 2015-01-18 at 7 52 10 pm](https://cloud.githubusercontent.com/assets/216145/5794805/724e6198-9f4c-11e4-99c5-6a04131313fa.png)

**Comment by bendk** [comment]
Added a couple comments to that PR.  I don't think it's quite so simple.  Did you write the code for the PR?  Are there docs on how to do it?  I'd much rather a dev worked on it.

**Comment by deanjansen** [comment]
@bendk Here's the code I used for the experiment: https://developers.google.com/analytics/solutions/experiments-client-side I was also following guidelines for event tracking: https://developers.google.com/analytics/devguides/collection/analyticsjs/events and https://support.google.com/analytics/answer/1136920?hl=en

I'd love to figure out a way where Janet and/or I could relatively easily slot these A/B tests in and run them, without too much hassle from an engineer. For this first test, I vote we do whatever's simplest/safest from your POV, and if it seems like a valuable tool, we can think about how to make it more streamlined down the road.

**Comment by syl22-00** [comment]
This has been refactored in branch gh-1969-refactor. To add experiments:
* `EXPERIMENTS_CODE` must be set to whatever it is in `settings.py`. Will be used this way:
```html
<script src="//www.google-analytics.com/cx/api.js?experiment={{ EXPERIMENTS_CODE }}"></script>
```
* `RUN_LOCALLY` should be `False` (in which case we turn analytics off anyways)
* Experiment JavaScript code is set in `media/src/js/unisubs.variations.js`

**Comment by jdragojevic** [comment]
this was deployed.
