### ISSUE TITLE
Collab workflow for private videos

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#1976]
We should support a tasks-like workflow for collaboration teams where all versions get flagged private until the collaboration is completed.  Once the collaboration is complete, we should flag the last version public.

**Comment by bendk** [comment]
The gh-1976 branch on amara-enterprise should implement this one.

One thing to definitely check is how it affects vimeo's videos, both pro-requests and user ones.  I think everything should work the same as before, but it needs to be tested.

**Comment by jdragojevic** [comment]
@bendk 

Here are my team settings:

![image](https://cloud.githubusercontent.com/assets/299270/5863207/f1f7fcb4-a277-11e4-9e26-83faf3554c3e.png)


Here is my collaboration, that needs review:
![image](https://cloud.githubusercontent.com/assets/299270/5863159/ba242952-a277-11e4-8175-ab469af1ff81.png)


Here's what I'm getting back from the api:
```
{
  "created": "2015-01-22T13:42:36",
  "description": "",
  "id": "10",
  "is_original": true,
  "is_rtl": false,
  "is_translation": false,
  "language_code": "hr",
  "metadata": {
    
  },
  "name": "Croatian",
  "num_versions": 2,
  "original_language_code": "",
  "resource_uri": "\/api2\/partners\/videos\/6Bsd2QFMJwGA\/languages\/hr\/",
  "site_url": "http:\/\/unisubs.example.com:8000\/videos\/6Bsd2QFMJwGA\/hr\/10\/",
  "subtitle_count": 6,
  "subtitles_complete": true,
  "title": "m101 2 simple example",
  "versions": [
    {
      "author": "janet",
      "published": true,
      "version_no": 2
    },
    {
      "author": "janet",
      "published": true,
      "version_no": 1
    }
  ]
}
```

**Comment by jdragojevic** [comment]
@bendk - I see what's happening.

When I hit 'Complete' in the editor, then the versions are all getting marked published.  It's ignoring the existance of existing steps in the collab.

**Comment by jdragojevic** [comment]
Uploading subtitles through the editor will also set the version to published.

**Comment by bendk** [comment]
d940f04 on amara-enterprise fixes that issue.

**Comment by jdragojevic** [comment]
this was checked and deployed.
