### ISSUE TITLE
Test the new video resource

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#1985]
I finished the initial work on the video resource in the in the api-refactory branch.  The next step is testing it.  The video resource is pretty complex, so there are a bunch of things to test:
- [ ] Documentation is correct
- [ ] We return the correct data for videos
- [ ] We filter the video list by permissions checks.  I believe this means returning _only_
  - Non-team videos
  - Videos on public teams
  - Videos on teams that the user is a member of
- [ ] We filter out the detail page by permissions checks.  This should be the same check as viewing the normal video page in a browser.
- [ ] We filter the list by the various query params:
  - [ ] team
  - [ ] video_url
  - [ ] project (only valid together with team)
- [ ] We create/update videos correctly.  There are several tricky fields here:
  - [ ] metadata
  - [ ] team
  - [ ] project
- [ ] We do proper permissions checks for updating videos. 
  - [ ] If changing a team we should make sure the user has permission to add videos to the destination team and remove videos from the source team
  - [ ] If changing a project within a team we should make sure the use has permission to add videos to that team

**Comment by bendk** [comment]
Sorry that there's a ton of stuff here.  Maybe this should just be a testing checklist.  If there are issues, let's open individual tickets for them.

Speaking of issues, should we simply return all videos for staff users?

**Comment by franontanaya** [comment]
On the On Demand side, GET-only full access to metadata would save us from having to add a member to each team we need to monitor through the API.

**Comment by bendk** [comment]
This code was merged long ago.  I don't think we need to keep an issue open for testing it at this point.  If we find an problem, we should open a new issue.
