### ISSUE TITLE
Use "X-api-key" instead of "X-apikey"

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#1988]
This matches our other header param "X-api-username"

**Comment by PCF-Testing** [comment]
This one will require changing all the partners' and in-house API-based software. Do we really need to change this?

**Comment by jdragojevic** [comment]
there's some in-progress docs here, http://amara.readthedocs.org/en/api-refactor/new-api.html as well as a blog post here that explains the changes.  http://about.amara.org/2015/01/20/api-changes/.

In short - this change will make specifying the new headers more consistent, but won't break the old way of doing it either.

**Comment by bendk** [comment]
I actually want to eventually remove the old way.  It just seems so weird to me to require 2 header strings and use a totally different naming scheme for both.

That said, there's no urgency to this one, and if we do it I think there should be a very long period of deprecation where we encourage people to move to the new one.

**Comment by PCF-Testing** [comment]
@bendk: X-api-key has been in use for quite a while. Can we close this ticket?
