### ISSUE TITLE
Filter-and-sort by length of the video.

### ISSUE THREAD

**Issue by andreamussap** [pculture/unisubs#1991]
Is it possible to implement a filter by the length of the video?
When I look for tasks, there are some filters: all projects, idioms, date, etc; but when you are newbie in a project, it's good to start with short videos. So, is it possible to implement this feature?

Suggestion:
**Lengh video:**
< 8 min
8-15 min

> 15 min

![video length](https://cloud.githubusercontent.com/assets/10401080/5961106/6295ab6c-a7c1-11e4-9f3b-5d1e6e31606f.jpg)

**Comment by bendk** [comment]
I like this feature, but I'm not sure if we will implement it with the tasks system.  We are working on a replacement for it called the collaboration model, which should be nicer in many regards.  Let's try to implement it there.

**Comment by andreamussap** [comment]
Hi @bendk 
ok, it's nothing urgent.

But just out of curiosity, can you tell the number of this (collaboration model)'s ticket?

**Comment by bendk** [comment]
Collaborations model is being implemented step by step.  Right now there is some functional code, but only a few teams are using it.  We can use this ticket to track implementing your suggested feature with the collab model.

**Comment by PCF-Testing** [comment]
The need for this filter was reiterated at TED Translators Workshop @ TED Active 2015. Fitting it into the collab-based workflow should be fine, I think.

**Comment by bendk** [comment]
We're not actively working on the code for tasks-based teams anymore, but this is implemented for collab-based teams.  Once we move TED over they will get this functionality.
