### ISSUE TITLE
staging branch: error on videos page rollback

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#1992]
Clicking Rollback on the video versions page.

AttributeError at /videos/rollback/23/
type object 'Video' has no attribute 'get'
Request Method:	GET
Request URL:	http://li732-11.members.linode.com:8000/en/videos/rollback/23/
Django Version:	1.4.13
Exception Type:	AttributeError
Exception Value:	
type object 'Video' has no attribute 'get'
Exception Location:	/opt/apps/unisubs/apps/videos/decorators.py in get_object_or_403, line 20
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/opt/apps/unisubs/libs',
 '/opt/apps/unisubs/apps',
 '/opt/apps/unisubs',
 '/usr/local/lib/python2.7/dist-packages/pip-6.0.6-py2.7.egg',
 '/opt/src/unisubs/unilangs',
 '/opt/src/unisubs/babelsubs',
 '/opt/src/unisubs/bleach',
 '/opt/src/unisubs/python-memcached',
 '/opt/src/unisubs/django-sslserver',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/opt/apps/unisubs/amara-enterprise']
Server time:	Fri, 30 Jan 2015 14:14:36 -0600

**Comment by bendk** [comment]
That should be easy to fix.  Do you recognize the hostname in the request URL?  I'm wondering if something went wrong with one of my staging deploy tests.

**Comment by jdragojevic** [comment]
yes that's a linode instance I have set up to run tests off my local machine.

**Comment by jdragojevic** [comment]
@bendk there are two unittests that fail as well.
ERROR: test_model_rollback (videos.tests.test_views.TestViews)
ERROR: test_model_rollback (videos.tests.test_views.TestViews)

**Comment by jdragojevic** [comment]
this was checked and deployed.
