### ISSUE TITLE
403 downloading completed subs from collab team

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2006]
On some videos in a collab team - once the Collab is completed, getting 403 errors trying to download the subtitles from the Video Language page.

Able to download subs for incomplete videos.

**Comment by jdragojevic** [comment]
Update - this isn't d/t just completed videos as I can download some.

**Comment by bendk** [comment]
I think this is fixed now.

The issue was the language codes for the SubtitleLanguages got changed from "pt-br" to "pt", but the language code for the collaborations and versions wasn't.  This is a very tricky operation and probably shouldn't be done if we can avoid it.
