### ISSUE TITLE
Bug - duplicate comments

### ISSUE THREAD

**Issue by andreamussap** [pculture/unisubs#2014]
Always when I include a comment in the (comment tab), Amara duplicate comments. Please see the attach: in this case there were two comments - from *TED Open Translation* and  *Samantha Lipton*. 

I included one comment, and after that, Amara duplicated *Samantha Lipton's* comment **under mine**.

![duplicate comments](https://cloud.githubusercontent.com/assets/10401080/6078798/216a94d0-ade4-11e4-942d-a4e7f452da7f.jpg)

**Comment by PCF-Testing** [comment]
This only happens until the Comments page gets refreshed. Looks fine at this time: http://www.amara.org/en/videos/IyxwGa6uGkRR/info/my-mothers-strange-definition-of-empowerment/?tab=comments

The 'duplication' glitch has always been there, it is not a regression issue. We also have a general ticket for improving the styling of Comments page (https://github.com/pculture/unisubs/issues/4).

**Comment by andreamussap** [comment]
Well,
so if it's a question of time to refresh, I'll close this issue. 
Thanks.

**Comment by andreamussap** [comment]
Hi everyone,can you help me?
I discovered that I have two usernames, I don't know why.

Here ( http://gh-882.amara.org/en/profiles/account/ ) my usarname is andreamussap

Here ( http://amara.org/pt/profiles/account/) my usarname is andrea_mussap

I've tried to change (andrea_mussap) to (andreamussap) but I couldn't. See:



I'd like to have an unique username = andreamussap.
Can you change it for me?

Thanks.

**Comment by bendk** [comment]
The gh-882 site is just used for testing.  Your "official" username is your one on amara.org.  I wouldn't worry about others.

Ben
