### ISSUE TITLE
youtube quota error retry duplicates

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2020]
Checking out the status of youtube syncing in the admin ui - I see some requests are being flagged for retry - but some are not.  It appears that we have duplicate entries for the same video language with different retry states.

![image](https://cloud.githubusercontent.com/assets/299270/6104456/e85a9340-b04d-11e4-9fa7-56ad41683d6b.png)

![image](https://cloud.githubusercontent.com/assets/299270/6104491/2773b584-b04e-11e4-8c5b-3b5d5e222313.png)

![image](https://cloud.githubusercontent.com/assets/299270/6104477/08b304b0-b04e-11e4-98b6-acdc27cc4c77.png)

**Comment by bendk** [comment]
We log a history for every sync attempt.  So this isn't necessarily an error since you could have 2 in a row for the same video.  If there are lots for a single version (like 5 or more), then I think it would be looking into.

**Comment by jdragojevic** [comment]
That makes sense.  I'll keep an eye on it.  Possible a future feature would be to clean up errors for a video / language once there's been a successful retry.  However, I don't think that's a high priority.
