### ISSUE TITLE
return userid in tasks resource if available for the team

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2027]
TED team users have the TED userid associated with their accounts.

When using the tasks endpoint, if there is a partner userid associated with the account, return it with the tasks information.

For example:

/api2/partners/teams/<slug>/tasks/?video_id=&type=translate&order_by=created

return something like

```
    {
      "author": "tomoyuki_suzuki",
      "author_id": "2223799",
      "published": false,
      "reviewer": "tomoyuki_suzuki",
      "reviewer_id": "2223799",
      "version_no": 66
    }
```

**Comment by bendk** [comment]
This leads into the general question of how to extend the API behavior for our partners.  I think that in general, we've gone down the path of making it overly general for a single partner and it gets hard to maintain.

For this one, I think we can make accomplish it by:
* Adding a hook for the tasks resource for other apps to change the behavior.
   * I think the behaviors module would work well for this
   * I think the hook function would be passed the data from to_representation() and also the request.  Then it could modify the data based on stuff in the request.
* Have the ted app implement the hook.
  * Check for request.username == 'ted'
  * If so, add the extra fields.  I kind of like ted_author_id for the field name, to make it clear that it's a TED-specific field.

What's the timeframe for this one?  Could we implement it alongside the new API?  This would mean that we would deliver the feature in probably 2-4 weeks.

**Comment by bendk** [comment]
This was implemented a while back.

**Comment by bendk** [comment]
Or was it?  I actually think we implemented something related, but not exactly this one.

**Comment by bendk** [comment]
We now return TED user ids, so I think we can close.
