### ISSUE TITLE
Link to existing team if duplicate

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2028]
If a user is trying to add a video via the teams form, and it is already on another team, link to the team in the error message.

update:

![image](https://cloud.githubusercontent.com/assets/299270/6211939/d834d484-b5df-11e4-92f3-03bd18391e9b.png)

to read: 

![image](https://cloud.githubusercontent.com/assets/299270/6211968/2a28d98e-b5e0-11e4-8bc5-87cbbd0a2a5a.png)

If the user doesn't have permission to access the team where the video is located (a private team), we should just say, 

You do not have permission to add this video to your team.

**Comment by bendk** [comment]
What If the team is private?  Just use the original text?

**Comment by jdragojevic** [comment]
original text is also fine.

**Comment by jdragojevic** [comment]
@syl22-00 @bendk 

The last formatting changes leave us with a '.' after the team slug.

![image](https://cloud.githubusercontent.com/assets/299270/6578106/6cd1e4e2-c742-11e4-8f50-41451d676718.png)

Also - I think it would be nice if we displayed the team name as the link text.
