### ISSUE TITLE
Do not log task send back actions as approvals

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2029]
When a user performs a send-back action on a task, we are currently logging two entries:
 an "approved" entry and a "rejected" entry.

Only the rejected entry should be logged.  Otherwise api queries for approved subtitles return incorrect results.

**Comment by bendk** [comment]
I'm just seeing a declined action when I try it for a review task in the new editor.

This is probably specific to a certain workflow.  Can you give steps to reproduce?

**Comment by PCF-Testing** [comment]
@bendk: This happens for approval tasks.

**Comment by jdragojevic** [comment]
@bendk Testing on the preview build of this branch.  When I do a sendback in the approve step, the rejection is not being logged in the activity for the team or for the video.

**Comment by bendk** [comment]
@jdragojevic this is working for me locally.  Maybe it's an issue with the preview branch, since the logging happens in a worker script and that works a bit weird on preview branches.

**Comment by jdragojevic** [comment]
my issue on this was in fact related to the worker.

**Comment by jdragojevic** [comment]
this was fixed and deployed
