### ISSUE TITLE
Language specific welcome messages for new users

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2030]
Allow team admins to configure language-specific welcome messges for new users.

When a user joins a team, they should receive the original English welcome message and their first non-English language, if there is a localized message for that language.

This will require switching the current user language into an ordered list, so we know which is the user's 1st preferred non-English language.

**Comment by deanjansen** [comment]
Additional notes:
* Create UI for admins to add + edit custom welcome message text for any language
* Automatically send welcome message when new member joins with a language that matches 
  * send message in English and 1st non-English language (if a custom message exists for that language)

**Comment by bendk** [comment]
Part of this is to make the language list into an ordered list.  I guess this is just adding an ordering field to it, but then the question is how to order the existing languages?

I'm thinking that we should always put english first, then the rest of them in any order.

**Comment by deanjansen** [comment]
What if we did something like this:

![proficency](https://cloud.githubusercontent.com/assets/216145/10254564/92848b6e-6912-11e5-989e-0f9c6722b599.png)

People could add them in whatever order (english could be 2 or 3 or not on the list). The welcome message they get would be in english plus the highest proficiency non-english language. We'd only send non-english if a custom message exists for that highest proficency non-english language.

**Comment by syl22-00** [comment]
How about just putting in the messages all available languages the user speaks:
* Because existing users were no instructed that languages have to be put in proficiency order.
* Because ordering languages by proficiency might not always make sense, you might know several languages well, without really knowing which one is best.
* There might be no downside in receiving a long email in several languages a user speaks.

**Comment by PCF-Testing** [comment]
Was Waiting for Deploy status assigned by error? Changing back to in-progress.

**Comment by syl22-00** [comment]
This is now implemented. Note that:
* There are migrations to run.
* The UI to enter the localized messages is available from the message page where admins enter non-localized messages.
* It is available on old and new teams pages.
* New localized messages can be entered, and users can modify existing localized messages.
* If an existing localized message is modified to be empty, it is actually deleted.
* If a user joins a team before he has set any language, he is reminded he can enter them. However, the reminder comes after the welcome message is sent, so he won't get a localized message after he sets them.

**Comment by PCF-Testing** [comment]
Regarding ordering users' languages:

1) The language selection dialog looks broken in Chrome:
![languageselectiondialogbrokenchrome](https://cloud.githubusercontent.com/assets/288455/10362112/58006f5a-6d61-11e5-94f5-fb78a691aec3.png)

2) Team application form (/team/team-slug/join) does not have drop-downs numbered:
![teamapplicationformlanguagesunordered](https://cloud.githubusercontent.com/assets/288455/10362129/833c4e00-6d61-11e5-8b75-b1e8c46aa4a1.png)

**Comment by PCF-Testing** [comment]
Instead of "Define localized messages>>>", the link should read "Add messages in users' preferred languages>>>". It should be placed on the page under "Custom messages" header, after "Customize the messages sent to your users. The text you enter will accompany the default system message."

**Comment by syl22-00** [comment]
These should now be done, still in branch gh-2030

**Comment by PCF-Testing** [comment]
Pp. I,II are fixed.

P.III still does not seem to work - once the order of languages has been set, it is immutable.

IV. Do we need to display empty numbers for non-entered languages?
![languagepreferencesorderedlist](https://cloud.githubusercontent.com/assets/288455/10363904/432b266e-6d6c-11e5-9ab2-745f717dbe35.png)

V. The message that actually gets sent is in the first translation that was added by team admin, rather than in the user's top choice language.

VI. Together with the customized message, user joining the team receives the standard message:
"Hi username,

Congratulations! You are now a member of the TED Collab team.

[customized message]
[translated customized message]

Check out the team dashboard at http://unisubs.example.com:8000/en/teams/team-slug/

Happy subtitling!"

Thus, the translated text is fully placed inside the standard English text. Is that OK? Or would it better to have the message laid out as standard English message with the custom English addition inside -> visual divider -> translated custom message if available?

**Comment by PCF-Testing** [comment]
VI. For old-style teams, the page /teams/team-slug/settings/lang-messages/ errors out:

NameError at /teams/welcome-team/settings/lang-messages/
global name 'forms' is not defined
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/teams/welcome-team/settings/lang-messages/
Django Version:	1.4.21
Exception Type:	NameError
Exception Value:	
global name 'forms' is not defined
Exception Location:	/opt/apps/unisubs/apps/teams/views.py in settings_lang_messages, line 334

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  20.                 return view_func(request, *args, **kwargs)
File "/opt/apps/unisubs/apps/teams/new_views.py" in wrapper
  112.         return view_func(request, team, *args, **kwargs)
File "/opt/apps/unisubs/apps/teams/new_views.py" in settings_lang_messages
  718.         return old_views.settings_lang_messages(request, team)
File "/opt/apps/unisubs/utils/__init__.py" in wrapper
  55.             output = func(request, *args, **kw)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  20.                 return view_func(request, *args, **kwargs)
File "/opt/apps/unisubs/apps/teams/views.py" in wrapper
  137.         return view_func(request, team, *args, **kwargs)
File "/opt/apps/unisubs/apps/teams/views.py" in settings_lang_messages
  334.         form = forms.GuidelinesLangMessagesForm(languages=languages)

Exception Type: NameError at /teams/welcome-team/settings/lang-messages/
Exception Value: global name 'forms' is not defined

**Comment by PCF-Testing** [comment]
VII. On /land-messages/ page, sort localized messages by the language name to ease finding the desired language.

**Comment by syl22-00** [comment]
@PCF-Testing all those issues have been fixed, except V.

Is V important?

**Comment by PCF-Testing** [comment]
VIII. Language numbers in old-style team application forma are off:

![languagenumbersoffapplicationformoldteam](https://cloud.githubusercontent.com/assets/288455/10389281/ff84abd8-6e24-11e5-9781-e964b65697cc.png)

**Comment by PCF-Testing** [comment]
It is possible to add to /lang-messages/ a message in English. In this case, if a user has English as the top choice, she will receive two copies of the message - from the main page and from /lang-messages/. We probably should not try to fix this - just a point worth noting and explaining to partners.

Finally, for usability purpose it might be better to visually separate the drop-down and the top entry field, on one side, and the remaining entry fields, on the other hand. The first group could have the header "Add message in a new language". The second group should go under the header "Edit messages". There should be some space separating both groups.

**Comment by PCF-Testing** [comment]
Deployed.
