### ISSUE TITLE
Messages: Differentiate between email messages and system notifications

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2033]
User -> User messages or Team -> User messages should be displayed in the UI separately from systems notification messages.

**Comment by franontanaya** [comment]
With more folks working on On Demand, being able to get notifications only for user messages may be important. I'm a member of dozens of teams for support, etc. so turning on notifications is quite spammy and the new messages alert on the header becomes meaningless. If I turn them off though I don't get email alerts for messages sent by users that need help and didn't reach out via email or IM.

**Comment by PCF-Testing** [comment]
@syl22-00: How about making the labels read "Personal Messages" and "System Notifications", respectively?

**Comment by PCF-Testing** [comment]
Deployed to production.
