### ISSUE TITLE
Messages: user lookup for should match real name too

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2036]
In the messages/new view.  Searching on the user's real name (first or last name) does not return based on the user's first or last name, only username.

![image](https://cloud.githubusercontent.com/assets/299270/6227829/c8254cde-b6a4-11e4-8990-509b0290ab28.png)

searching in that field should lookup based on the username, or first or last name.

**Comment by PCF-Testing** [comment]
Deployed to production.
