### ISSUE TITLE
email notifications of messages should link to the message in the amara inbox

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2037]
When amara sends an email to a user regarding a message, it should link to the exact message in the user's inbox.  

(This assumes the user has the amara inbox setting turned on)

![image](https://cloud.githubusercontent.com/assets/299270/6228046/4587abc0-b6a7-11e4-802f-b7d2afb9669e.png)

I think it may be ideal if when splitting up the messages / notification (#2033) we use the settings pictured above to control system notifications, and always send user -> user messages and team -> user message to both the amara  inbox and user's configured email.

**Comment by syl22-00** [comment]
We made email threads instead of individual message age. @PCF-Testing do you think we should do something for that?

**Comment by PCF-Testing** [comment]
I think placing a link to onsite thread into email could be useful. I am not really sure about the second part of the ticket though (overriding user profile settings for personal and team broadcasting messages), that seems a bit weird and illogical and may annoy some users who are sensitive about email notifications they are getting.

Maybe add the following to the email templates:

{ { View the message in Amara Message Inbox } }
Cannot view the message at the above link?  { { Enable Notifications by message here } }

Ticker https://github.com/pculture/unisubs/issues/2447 is pretty much related here.

**Comment by syl22-00** [comment]
This should happen when we do the new message center

**Comment by kslottow** [comment]
moving to #2037
