### ISSUE TITLE
document data/activity collection needed

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2040]
Document the user activity / data that needs to be collected in order to provide a more customized team user dashboard.

**Comment by jdragojevic** [comment]
- [ ] How to differentiate between a new vs experienced user?

- [ ] How to tell is a translator is struggling
 - abandon jobs
 - take a long time to complete translations
 - have many revisions returned for more edits.

- [ ] How to tell if a translator is doing a great job
 - high volume of completed translations 
 - gives good encouraging feedback on reviews
 - low sendback rate

**Comment by bendk** [comment]
The new user issue is pculture/amara-enterprise#232.  Let's figure the other issues later.
