### ISSUE TITLE
collab model dashboard ui/ux work

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2041]
Meta ticket to capture team dash ui improvements for the collab model

- [ ] Create a plan for implementing some of those needs as uncovered by the use cases (#2039)
- [ ] Team UI navigation improvements
 - video search from the user dash
 - presentation of tasks by type (translate v review...)
 - provide details about the video (description, languages available as ref languages)
 - allow users to claim a collab without having to open it in the editor first
- [ ] Remove functional duplication
 - content in sidebar + content in tabs
- [ ] Customize Dashboard for the user based on Role / Languages spoken
- [ ] Dashboard ui for new users
 - #2040 determine criteria for what is a new translator
 - New users shouldn’t be shown review tasks
 - New users should be presented with shorter videos first
- [ ] Allow users some customization of displays (languages, collab types, layout? list vs thumb TBD)
 - ex: Some people mainly work on transcriptions, or say, exclusively TED-Ed videos. Would be great if users can customize what they see on their dashboard (video types (project?), collab type, language) to conform to their work habits.
- [ ] Simplify finding work - and provide more details about videos, duration, languages, state and previous translator / reviewers
- [ ] enable filtering videos / assignments by original video language
- [ ] Bulk management actions for admins

**Comment by bendk** [comment]
Some of this is implemented and the rest is captured in the amara-enterprise collab UI milestone .
