### ISSUE TITLE
collab model mentoring ui/ux

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2042]
Meta ticket for collab model ui improvements for team mentoring.

- [ ] Allow users to see the LCs (language manager) for their languages
 - [ ] filtered by those who have been active in the last x months.
 - [ ]   Provide a means for team members to communicate with LCs via dash.
 - [ ]  Show if they are currently available on amara for chat or just send message.

- [ ] Give LCs a way to view user activity in the languages for which they are responsible
 - [ ] #2040 determine active vs struggling translators
 - [ ] Add in a view notes functionality - where the LC can see a list of the notes from translator reviewers from the past month in the languages they manage.

**Comment by bendk** [comment]
Captured this in pculture/amara-enterprise#235 and  pculture/amara-enterprise#239
