### ISSUE TITLE
enable communication between collaborators in the editor

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2044]
depends on #2043 (show collaborators in the editor) enable users to communicate with eachother from within the editor so they do not have to either finish the editing session or or open a new tab and perform complex navigation.

**Comment by bendk** [comment]
This is implemented in the gh-2044 branches on unisubs/amara-enterprise.

I created a page specific to a collaboration.  On that page it lists the collaborators and notes for the collaboration and also lets you post a new note.

**Comment by bendk** [comment]
I think the styling could be improved, but it looks okay to me for now.

**Comment by jdragojevic** [comment]
Few suggestions if they are quick-n-easy, or I can just put in new tickets.

- [ ] 1. include the video embed in the page.  It would allow user to quickly preview the video or existing subs before joining.
- [ ] 2. include the videos full description
- [ ] 3. include a join / edit link - so if you get to that page, you want to work on the collab you can start from there. 
- [ ] 4. have a join link that doesn't actually open into the editor - so a user can pick something to work on, but not necessarily have to immediately enter the editor to do so.

I'm happy to open new tickets for any of these if you think they are outside the scope (like item 4).  These suggestions come from earlier discussions with TED where users would like to be able to see more information about the video without having to naviagate all over the site and back,  and also ti be able to choose something to work out with out starting it right away.

**Comment by bendk** [comment]
Implemented all of these.  I'm not totally sure about including the description, it pushes down the rest of the content quite far.  What do you think janet?

The styling is really not great, but I don't want to change it so much right now.  It's a bit weird because all our CSS is in the main repository.  I think that when we rework our CSS we should make it so that we can have SCSS files in amara-enterprise that get combined into the main CSS.

**Comment by jdragojevic** [comment]
@bendk: what do you think of something like this where we use a smaller video and put it at the top with the title.  And then have below the Collab info, including the current status of the collab.

![image](https://cloud.githubusercontent.com/assets/299270/6572179/79cf9478-c710-11e4-90e1-b41ac6c2c2f2.png)

The other thing we'd want to do is use similar params from the video  lang page embed, so the extra menus don't get chopped off on the smaller embed size

```
<div class="amara-embed" data-show-subtitles-default="false" data-initial-language="{{ COLLAB LANG CODE }} data-hide-subtitle-me="true" data-hide-logo="true" data-hide-order="true" data-hide-improve="true" data-hide-download="true" data-hide-embed="true" data-noanalytics="true" data-height="{{ height }}px" data-width="{{ width }}px" data-url="{{ collaboration.video.get_video_url }}" data-noanalytics="true"></div>
```

Other thing I noticed is we don't have any logic in there for when we are showing the Editor button.  We are currently not allowing post-edits of collabs, but are showing the button as active anyway.  We also show it for the reviewer for example when it's being approved.

**Comment by bendk** [comment]
Good idea with the video embed.  I think all this should be fixed in the gh-2044 branch now.

**Comment by jdragojevic** [comment]
- [ ] I like the endorse field.  However when it's blank then the table borders don't extend the whole length.

![image](https://cloud.githubusercontent.com/assets/299270/6578190/f63c8ebc-c742-11e4-9721-a5255a74cb01.png)


- [ ] pesky line breaks are not preserved when they are displayed in the collab details page.

**Comment by jdragojevic** [comment]
post new note form doesn't display unless there is at least 1 note.

**Comment by bendk** [comment]
Last two comments should be fixed with the latest gh-2044 commits.

**Comment by jdragojevic** [comment]
@bendk those are good. But the post new note form needs a submit button now, because hitting enter, creates a line break.

**Comment by bendk** [comment]
You can use shift-enter to add a line break, like an IM client.  I could add a submit button, but I figured line breaks would be uncommon.

**Comment by jdragojevic** [comment]
It was like that - but after the last changes, when I type Enter i get a new line (on collab details page).

**Comment by bendk** [comment]
I think it should sill be working, are you using gh-2044 on the unisubs repo as well?

**Comment by jdragojevic** [comment]
@bendk  - not seeing the endorsements (from #2043) in the editor, they are showing on the details page notes:

![image](https://cloud.githubusercontent.com/assets/299270/6638286/ce56ee58-c984-11e4-9bad-7e1e6f55c329.png)

**Comment by bendk** [comment]
This is working for me, can you double check that you are on gh-2044 in the unisubs repo?

**Comment by bendk** [comment]
I needed to push the changes to gh-2044
