### ISSUE TITLE
api-refactor: version query on subtitles is not supported.

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2049]
From the docs, and works in api2/partners 
- *version – version number to fetch. Versions are listed in the VideoLanguageResouce request. If none is specified, the latest public version will be returned.*

Querying on version using new api returns the latest version.
```
GET /api/videos/fRie2N4V3gwd/languages/es-mx/subtitles/?version=2
HTTP 200 OK
Content-Type: application/json
Vary: Accept
Allow: GET, POST, HEAD, OPTIONS

{
    "version_number": 3, 
    "sub_format": "json", 
    "subtitles": [
...
```

**Comment by bendk** [comment]
I was trying to switch to using "version_number" since that's the name we use elsewhere.  Still the old name should continue to work.
