### ISSUE TITLE
Malformed HTML in email_base

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2051]
An Outlook 2007 user reported Outlook was very unresponsive/crashing when viewing or forwarding the New team videos email. I checked the source and found an empty table with an unpaired closing anchor in email_base:

https://github.com/pculture/unisubs/blob/69b453fba36a9edd76f1dc20a774dd9c119bba6a/templates/videos/email_base.html#L125

Outlook 2007 isn't very good at handling HTML emails so this could be a (the) source of issues.

**Comment by franontanaya** [comment]
I've placed an edit on branch gh-2051 for this.

**Comment by bendk** [comment]
Looks good to me, do you want to open a pull request for it?

**Comment by franontanaya** [comment]
Closing -- https://github.com/pculture/unisubs/pull/2052
