### ISSUE TITLE
TED authentication broken on www.amara.org

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2058]
http://www.amara.org/en/auth/login/ted_auth.url returns a 404.

However,  http://www.universalsubtitles.org/en/unisubservicesauth/ted_login/  works.

Related ticket: http://ted-support.amara.org/helpdesk/tickets/78162

**Comment by jdragojevic** [comment]
Looks related to login form changes, 

before:  <li><a class="provider" id="ted" href="{{ ted_auth.url }}">ted</a></li>

after:     <li><a class="provider" id="ted" href="{{ "ted_auth.url" }}">ted</a></li>

Got some extra quotes in there.

**Comment by jdragojevic** [comment]
this was fixed and deployed on friday.
