### ISSUE TITLE
Detect whitespace-only search strings

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2062]
If you search for whitespace (" ") on the page, it causes an error.

In apps/search.forms.py we have a check for blank queries.  I think we should extend that to also check for whitespace only queries.

**Comment by bendk** [comment]
This should be fixed.  Now if you search for whitespace:
  * There's no error in the server log
  * The search results aren't filtered by the query (i.e. they are filtered by the languages, or we just return all videos like when you first go to the search page).

**Comment by jdragojevic** [comment]
this was fixed and deployed.
