### ISSUE TITLE
Switch to OpenID Connect for google

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2064]
Google has deprecated OpenID 2.0 and will stop supporting it soon.  We need to switch to using OpenID Connect.  One tricky thing here is we need to make sure that users who already have logged in via OpenID 2.0 will still get their same user accounts when using OpenID Connect.

**Comment by bendk** [comment]
This is implemented on the google-open-id-connect branch.  We should test the following things there:

  * Login works for new users
  * Login works for users who have already used openid connect 2.0 and we re-use the same amara account
  * The youtube sync still works (I reworked this code since it was doing basically the same thing).

**Comment by bendk** [comment]
While I was at it, I also implemented a side feature.  When we create a new user account, we copy the first, last, and full names from the open ID profile to the amara account.  I think full_name is only used in the api, but it should be getting set still.

* If you login via openid connect, change your user info, then login again, we shouldn't overrite the changes
* If you had an account created with openid 2.0, and the field is blank, then we should overwrite the blank value.

**Comment by bendk** [comment]
This is going to require a change to our google developer account settings.  I made the change for the dev instances.  Once it's ready to merge to staging, I'll make the changes for staging and production.

**Comment by PCF-Testing** [comment]
Got a few reports from people who were unable to sign in with their Google accounts on or after Wednesday - new accounts were created instead of getting users signed in with the old ones. Possibly, related to this change?

Tickets: 
http://ted-support.amara.org/helpdesk/tickets/78397
http://ted-support.amara.org/helpdesk/tickets/78380

**Comment by bendk** [comment]
I think this is working for most users.  Let's keep this ticket closed and work on the issue in #2110.
