### ISSUE TITLE
Reviewers can approve tasks by re-opening the editor

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2067]
From TED:

As a contributor, I picked up a Review task.  I hit 'approve' on the review task, waited about 2 seconds, while the 'approving...' message was on the screen then hit the back button.  I then used the browser forward button to reenter into the editor.

It still showed me that I was on a Review step, and I hit 'approve' again.  

In the activity log you can see the task was both accepted and approved by @PCFQA a team contributor.

I reproduced this a few times.  Seems the trick is using the back button to go out of the editor while it's processing, and then entering back in.

**Comment by bendk** [comment]
This can be tricky to reproduce, but the easiest way is with the API directly.

* go to/api/videos/<video-id>/languages/<language-code>/subtitles/actions/
* submit the "approve" action
* submit the "approve" action again

This will approve both the review and approval, even for users who shouldn't have the ability to approve tasks.

**Comment by bendk** [comment]
So the case in question is what to do if we get an approval action for a task that's not assigned.
  * Before we would assign it to the user and complete the task
  * After the fix we check if the user has permission to assign the task first
  * Maybe we should not allow this in any case.  I think that all normal user workflows should make the task assigned, but I'm not really sure.

Also, the action will probably result in a 500 error, rather than a nicer error code like 403 or 400.  But I don't think it matters so much and would like to avoid writing code for the tasks system if we don't have to.

**Comment by jdragojevic** [comment]
OK - so on branch 2067 if I go  back in to try to do the approve, I end up seeing the Save error message:

![image](https://cloud.githubusercontent.com/assets/299270/6505283/ad574864-c340-11e4-9526-0b01ed43978e.png)


If I wait long enough ( I think for the lock to expire) then I get the expected subs moderarted message

![image](https://cloud.githubusercontent.com/assets/299270/6505298/d585137a-c340-11e4-9c37-61a923950585.png)


This seems good enough for me to prevent publishing by users w/o sufficient permissions.

Lastly - if I try to double-submit via the api - i get an error page and the sentry error is 'Task not assigned to user' - which seems fine for me.

**Comment by jdragojevic** [comment]
this was fixed and deployed.
