### ISSUE TITLE
404 looking up accounts via api that contain a '.' in the username

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2076]
If I use the api (old or new) to lookup a user account contains a '.' in the name, like janet.finn, or dragojevic.j - I get a 404 error returned.

ex: 
```
GET /api/users/janet.finn/ HTTP/1.1" 404 14095
```

**Comment by bendk** [comment]
I also snuck in a small fix for creating subtitles via the API.  Before we weren't running video_changed_tasks, which may have messed with the indexing (or maybe not, it's hard to know).
