### ISSUE TITLE
new api: user resource password field is not required

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2078]
In the old users api (api2/partners/users/) the password field is a required field, in the new api (api/users/) , it is not.

**Comment by bendk** [comment]
I don't think it should be.  We allow the creator to make the auto-login URL, in which case they won't need the password.  Maybe one of the two fields should be required, but I could still see a use case for a partner creating a user then telling them to use the password recovery to login.

**Comment by jdragojevic** [comment]
that works for me.  Just pointing out the difference.  Closing.
