### ISSUE TITLE
new api: exception with non-ascii chars in username

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2079]
If a username is created via the api with non ascii chars:  ex: 

{
    "username": "čevapčići",
    "email": "monkey@monkey.com",
    "password": "password"
}

```
Exception (most recent call last)
UnicodeEncodeError Root Cause
'ascii' codec can't encode character u'\u010d' in position 0: ordinal not in range(128)
```

Old api would return an error message.

```
{
    "username": ["This value may contain only letters, numbers and @/./+/-/_ characters."]
}
```

**Comment by bendk** [comment]
I made a fix for this one.

Note that there is another error with decoding form data that contains non-ascii chars.  I don't think this one is easily fixable.  However, things should work with JSON data.
