### ISSUE TITLE
Show user who submitted video on the page somewher

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2100]
We should put this somewhere on the video page.  It's useful information because it controls how we sync subtitles back to youtube and other video hosts.  It probably doesn't need to be very prominent but it should be there.

**Comment by jdragojevic** [comment]
Isn't it the owner account the controls the syncing?  If we were to open up the sync-tab view - we could indicate whether or not a video is being synced by showing submitter + owner account.

**Comment by bendk** [comment]
See #2101 for the issue about syncing.  I still think this is useful information for the general public to see.

**Comment by bendk** [comment]
I'm not sure how important this one is to implement though.  I'm going to leave it alone for now.  If someone things it's high priority, please speak up.

**Comment by PCF-Testing** [comment]
Related ticket: https://github.com/pculture/unisubs/issues/1425

**Comment by jdragojevic** [comment]
We actually are showing who submitted the url on the URL page.  So I think we can close this one.

![image](https://cloud.githubusercontent.com/assets/299270/6748928/88237b60-ceeb-11e4-8d81-eaed8cc4e350.png)
