### ISSUE TITLE
Make Embed Responsive

### ISSUE THREAD

**Issue by jeremyclarke** [pculture/unisubs#2102]
Sorry if this is a duplicate but I can't find anything when searching the repo for "responsive" and I can't find a way to make the player behave responsively. 

Currently it seems that loading a YouTube video through Amara breaks it's responsiveness. Amara forces the API user to declare a width and height, which are then used absolutely regardless of viewport. This means that our responsive site is broken whenever we use Amara, and certainly devalues Amara for our purposes (we'll still use it when we know the subtitles are necessary for comprehension, but can't justify using Amara just in case someone would prefer another language). 

Is there a specific reason why the embeds aren't responsive, or is it a matter of limited resources?

IMHO there should be no requirement for a width/height to be set, and in that case a responsive player should be output. Beyond that, even players with width/height should always behave as "max-width:100%" within their container, and shrink in size (keeping their aspect ratio) to fit perfectly. I doubt anyone is depending on Amara embeds overflowing their containers, and if they are they'd probably rather Amara be responsive instead ;)

A good starting point would be to make this page responsive and ensure that the Amara embeds inside are as well:

http://amara.org/en/embedder-offsite/

Also updating this page to express how users can make sure their embeds are responsive:

https://github.com/pculture/unisubs/wiki/Embed-Code-Usage-Guide

**Comment by bendk** [comment]
+1 on making width/height optional

However, I don't think that we can set max-width with the embedder since it uses an iframe (and even if we didn't the youtube player would).  The best way that I know how is this one:

https://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php

**Comment by syl22-00** [comment]
In addition, the width and height set as data attribute are the video's width and height (as given to popcorn which then applies it to the underlying player, such as youtube iframe, flash player, html5 tag). The height of the iframe we embed is actually longer as it adds our controls, and gets even longer when transcript viewer is expanded.

So the way to be more responsive/fluid is probably to build on our JavaScript embedder code that deals with the dimensions.

**Comment by netAction** [comment]
Is it possible to force a redraw of the player on resize/orientationchange/zoom/whatever? Then we had a JavaScript workaround for this issue.

**Comment by jeremyclarke** [comment]
Redrawing based on JS can be a big performance drain and IME comes with a lot of bugs. I'm sure it's possible but I doubt it's the most effective way to solve this problem compared to just not passing width/height to YouTube.

**Comment by NicolaiKilian** [comment]
So, is there any workaround?

**Comment by bendk** [comment]
There is no workaround at this point, we are currently working on other things.  Our code is open source and if anyone wanted to try to hack it, I would love to help you out.  You can usually find me as bendk on #amara on freenode.

**Comment by syl22-00** [comment]
We have a few constrains that make things a little complex, such as:
* We do not know the video dimensions as, depending on the player, some videos might be available indifferent dimensions.
* height is dynamic, depending on user's actions (like expanding the transcript viewer).

So I just pushed something we could take as basis:

*  Width and height are still necessarily given in embed code, they are now equivalent to a max-width and max-height, and also indicate the aspect ratio.
* If embedder overflows its parent in width, then it is resized to its parent's width.

For now, there are a few quirks that could be fixed if we agree on the approach:

* Resizing is done once, at init time. So it won't resize if browser window size is reduced after the embedder is initialized.
* It is first displayed in full width, then reduced during initialization, which does not look great.

This is done in branch gh-2102.

**Comment by netAction** [comment]
Seams that the real issue is the existance of the iframe. At least since you need dynamic height some inline HTML like Disqus does could be the solution.

**Comment by syl22-00** [comment]
So back to this issue, in the branch (gh-2102), we have a new embedder parameter. If `data-resizable="true"`, then the embedder will scale down to fill in its container. It does not scale up if container is wider than width.

**Comment by jeremyclarke** [comment]
That sounds good enough for me! Let me know how and when I can test it out :)

**Comment by syl22-00** [comment]
Thanks for offering your help. I setup a preview instance with those changes. To try it out, you can:
* go to `http://gh-2102.amara.org`, create an account, a video and subtitles,
* make an embedder for that video (beware the embed code should point to `http://gh-2102.amara.org/embedder-iframe`)
* In the div, you should add `data-resizable="true"`.
* You should see the embedder scale down to its container or browser window, if it is smaller than the specified video size.

**Comment by PCF-Testing** [comment]
data-show-transcript-default="true" does not work in data-resizable mode - the transcript icon is on, but the transcript is not displayed.

**Comment by syl22-00** [comment]
Right, the transcript viewer was just broken (no matter it was on by default or not). It is now fixed.

**Comment by jeremyclarke** [comment]
Hi Sylvain, thanks so much for writing this up. I got around to testing it
but it looks like the test server isn't running anymore:

503 Service Unavailable
> No server is available to handle this request.


Is that expected? Are the changes going to be on the live site soon?

On Mon, Sep 21, 2015 at 3:58 PM, Sylvain Chevalier <notifications@github.com
> wrote:

> Thanks for offering your help. I setup a preview instance with those
> changes. To try it out, you can:
>
>    - go to http://gh-2102.amara.org, create an account, a video and
>    subtitles,
>    - make an embedder for that video (beware the embed code should point
>    to http://gh-2102.amara.org/embedder-iframe)
>    - In the div, you should add data-resizable="true".
>    - You should see the embedder scale down to its container or browser
>    window, if it is smaller than the specified video size.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pculture/unisubs/issues/2102#issuecomment-142092688>.
>



-- 
Jeremy Clarke
Code and Design • globalvoicesonline.org

**Comment by syl22-00** [comment]
Sorry @jeremyclarke we cleaned up our preview instances since I posted. It should be back one by now. Thanks a lot for testing out.

**Comment by jeremyclarke** [comment]
Thank you!

Got it working on my local site (tip for anyone else: You have to add "s" to make it HTTPS if your test/live environment is SSL).

Definitely a huge improvement! Here's what I see:

* Starts off at full width+height, under/over elements outside it's parent.
* Jumps down to fit in it's container later (presumably when page finishes downloading and JS triggers). 
* Doesn't resize when window is resized (i.e. fits container's original size, but doesn't grow/shrink if window size changes). 
* Even after resizing the original height is still taken up, leaving an empty space if the final size is smaller than `data-height`. 

Personal reactions:

* I can live with the "jump" between full size and fitting in container, but it's really ugly and distracting. Any "containment" before this point would significantly increase the elegance of user experience. 
* I can live with the lack of resizing when the window resizes (many embeds have this problem) but it's also not very elegant, and many iframe embeds have solved this problem and are truly "resizeable" rather than "resize-on-load". 
* The un-collapsed `data-height` is a bit of a dealbreaker to me. It looks deeply wrong in the midst of a post and could seriously confuse a visitor into thinking the story is over because of all the whitespace. Notably the effect is prominent even on my laptop, but would be exacerbated to the point of silliness on a smartphone where the original hight might put content entirely off the screen. 

**It seems like the height problem is being caused by the `style` property of the main `div` having hardcoded width+height. This seems like something that could be solved by just resetting those properties during the resize routine? Maybe that would also help with the initial size breaking out of the box?**

Screenshots (apologies if any of these problems are specific to my site):

<img width="903" alt="amara-dev-loading" src="https://cloud.githubusercontent.com/assets/139995/10179194/7272bc84-66d2-11e5-9909-196d18518a16.png">
<img width="878" alt="amara-dev-loaded" src="https://cloud.githubusercontent.com/assets/139995/10179198/78a315fe-66d2-11e5-8474-ac1ad0f3d4ef.png">

**Comment by syl22-00** [comment]
In branch gh-2102, embedder now scales up and down, even after initialization. `embedder-offsite` demo page has the option set for the 3 embedders (`data-resizable="true"`).

**Comment by PCF-Testing** [comment]
The new version looks beautiful - the subtitles get resized, too, to match the smaller video player size, I love that.
However, when the transcript viewer button is toggled on (from the default off position), the video player and the whole page go totally crazy. This issue must be taken care of before the change may be rolled out.

**Comment by PCF-Testing** [comment]
Looks great locally, marking as Waiting for Deploy.
