### ISSUE TITLE
Google button creates new account instead of signing in to the existing one

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2110]
Reported by users. Related FD tickets:

http://ted-support.amara.org/helpdesk/tickets/78397
http://ted-support.amara.org/helpdesk/tickets/78380

Two similar reports filed over the last day. Possibly, related to https://github.com/pculture/unisubs/issues/2064?

**Comment by bendk** [comment]
Looks like this only happened to 2 users and I'm not sure why them.  There's a lot of things that could have gone wrong with the google open id change, I think at this point we should just fix things on a case-by-case basis.

To do that, I added some functionality to the admin site.  Site admins should be able to fix linking issues with the following steps:

  * go to https://amara.org/en/admin/externalsites/openidconnectlink/
  * Search for the username of the user that was created, or incorrectly linked
  * Click on the OpenIDConnectLink link
  * Change the user to the correct user and save the data

Hopefully this works well enough to transition us.  If we get lots of errors, then maybe we'll need to do something more drastic.
