### ISSUE TITLE
TED profile links automatically added to Amara profiles are broken

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2121]
Example:
http://www.amara.org/en/profiles/profile/guzel_bagmanova/
http://www.ted.com/users/4115364/profile - returns 404
http://www.ted.com/profiles/4115364 works, but obviously points to a different user, because the method used by automatic URL insertion into Amara profiles utilizes TED ID instead of TED profile IDs. (These 2 IDs are different; TED profile links should include TED profile IDs.)
Compare: http://www.amara.org/en/admin/ted/tedaccount/52019/ (which includes TED ID).

**Comment by jdragojevic** [comment]
@PCF-Testing - when we implemented the feature, TED setup a redirect so we can use https://www.ted.com/users/:user_id/profile - which should then resolve to the user's actual profile.

I'll email Alex @ TED regarding the link redirects.

**Comment by PCF-Testing** [comment]
@jdragojevic: awesome, thanks a lot for the quick response!

**Comment by jdragojevic** [comment]
This was resolved on the TED side.
