### ISSUE TITLE
Use symbolic names for activity API

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2133]
Right now we use integers to specify video activity types.  We should use machine names instead, for example ``add-video`` instead of ``1``

**Comment by bendk** [comment]
This is implemented in the activity2 branch for the new activity URLs. For the legacy URL I just kept things the same.

**Comment by PCF-Testing** [comment]
Works as expected on the branch.

**Comment by PCF-Testing** [comment]
Deployed.
