### ISSUE TITLE
api-last-bits branch - can not delete application via api

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2139]
@bendk - this is a departure from apiv2 where deleting an application was allowed via the API.  However I'm not sure that this change will affect any current users, so we could leave it the behavior as-is and it would be a matter of updating the documentation.

**Comment by bendk** [comment]
Can you delete an application via the team admin page?  If so I can implement it in the API.  it's not that hard to do.

**Comment by jdragojevic** [comment]
You can not delete an application via tha team application page.  Only can approve or deny.

**Comment by bendk** [comment]
ok, so then I don't think it makes sense to allow deletion via the API.  We should just fix the docs.

**Comment by jdragojevic** [comment]
fixed in branch
