### ISSUE TITLE
Font weight fixup

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2142]
We should clean up our font weight usage on the homepage.  Right now we are only pulling in weights 200 and 300 from google for the body text, but we use weight 500 in several places for bold and also 400 (normal) for the user menu links.

This makes it so the browser creates the bold using an automatic algorithm.  This means inconsistency between different browsers and also probably less readable fonts.

I think we should pick 1 weight for normal, 1 for bold and stick to that.  Seems like 300 is what we use most for normal weight.  To my eyes, weight 600 matches the auto-generated 500 weight the closest.

**Comment by deanjansen** [comment]
These inconsistencies are my fault – partly due to switching things up so that the fonts looked decent on Windows. Maybe we could run instances with 1 or 2 different approaches and compare how they render on each platform?

**Comment by bendk** [comment]
Okay, here's a demo instance to try out

URL|normal weight|bold weight
---|---|---
http://font-weights.amara.org/en/|300|500
http://font-weights.amara.org/en/?base_css=hands_home_25.css|200|500
http://font-weights.amara.org/en/?base_css=hands_home_34.css|300|400
http://font-weights.amara.org/en/?base_css=hands_home_36.css|300|600

**Comment by bendk** [comment]
I only changed the weights for the body text.  Header text is 200,300 weight.  (maybe we should pick one or the other for that as well?)

**Comment by deanjansen** [comment]
I'm having trouble seeing any differences – would it only show in the footer?

**Comment by bendk** [comment]
Yeah, the footer is the main place that I know of.  I think it's a couple other places too, but I'm not sure.

**Comment by bendk** [comment]
I also just noticed that roboto doesn't come in 200 weight, so the first two are identical.
