### ISSUE TITLE
Languages section in user profile is shown empty when it has data

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2146]
Languages section in the left panel on the user's profile does not show the list of the user's preferred languages:

![languagessectionprofileempty](https://cloud.githubusercontent.com/assets/288455/6936448/3553d478-d807-11e4-8bc0-6962a020cfa5.png)

Reported in http://ted-support.amara.org/helpdesk/tickets/78646

**Comment by bendk** [comment]
Fixed in the gh-2146 branch.
