### ISSUE TITLE
Post-publish metadata edits for TEDTalks do not send callbacks to TED

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2150]
A few user reports indicate that post-publish edits made to TEDTalks do not get synced to TED.com - apparently, callbacks do not get sent when a new complete, public subtitle version is created. The only way to sync the changes is by creating a new approval task for the subtitles and going through approval again.

**Comment by jdragojevic** [comment]
So far we have two reports in freshdesk.  Looks like in both cases it's the title and description that's not getting synced back to TED.com not edits to the subtitles themselves.

* user report 1
*I have been trying to revise the Japanese title and description of the below video by using post editorial tool, but it somehow doesn't reflect on TED page. And I am wondering if you could kindly look at it when you have a chance. (I have also revised the subtitles in the video, but it does reflect on the TED page properly. It's just title and description that are not updated.)*

* user report 2
*After publication of these Romanian subtitles, the video title and description were updated. However, the information on TED.com wasn't updated, and it looks like a case similar to #78582.
Additionally, even though edits are clearly visible when the original and edited description is compared (e.g. the missing "--"), the description field is not highlighted in red in the diffing view.*

**Comment by PCF-Testing** [comment]
Report #3 (FD ticket 78582) - similar issue with the title and description not updating:

*After publication of these Spanish subtitles, the video title and description were updated. However, we didn't receive a ping from Amara when this post-edit happened, so we couldn't update the info on TED.com.*

**Comment by bendk** [comment]
So I believe we send the "subs-new" event instead of "subs-approved" when a post-publish edit happens.  Are you getting that event?

**Comment by jzurawell** [comment]
Looks like we aren't getting any pings when metadata post-edits happen.

Two latest examples:
http://amara.org/en/videos/26NjkgOEYcOb/pt-br/928172/
http://amara.org/en/videos/FEuPcijJaVCX/pt-br/958738/

Thanks,
Jenny

**Comment by bendk** [comment]
So does this accurately describe what's happening:

* Before the task is approved you get the `subs-approved` ping
* After the task is approved, if there are changes to the subtitles you get the `subs-new` ping
* After the task is approved, if only the metadata changes then you don't get any ping

Once I have a clear idea what's happening it should be easy to fix.

**Comment by jzurawell** [comment]
Yes, that is accurate @bendk.

**Comment by bendk** [comment]
I'm pretty sure this is related to the new API code.  I made branch gh-2150 and gh-unisubs-2150 in amara-enterprise to handle this.

These branches do a couple things:
* Adds logging when we would send out team notifications.  This will appear in the logs regardless of the team notification settings.
* Add code to send the subs-new notification whenever a new version is added
* Removed code in the old API that sent out the subs-new notification to prevent a double notification from being sent.

To check:
* Make sure that we log a line like this for a post-publish edit:
  signals 56 139972509955840 notification: subs-new (version: SubtitleVersion 158 / xGa2dIIRcjn8 / English v8)
* It should also log when changes are made in the legacy editor
* We should only log things once when using the old API (not sure what a good way to test this is, probably manually with curl or a similar tool).

**Comment by jdragojevic** [comment]
@bendk Testing branch gh-2150 

-  [ ] 1. When editing and approving subs at the same time, the subs-new notification is sent, however I believe in this case is should be a subs-approved notification

- [ ] 2. Seeing 2 subs-new notifications sent for edits via the legacy editor

Otherwise I can confirm that:
 -  subs-new is sent for post-publish edits of either subs or description via editor
 - subs-new is sent for PPEs sent via new api
 - subs-new is sent for PPEs sent via old api (and only 1 time)

**Comment by bendk** [comment]
I think the behavior for 1 is correct, the user is creating a new version and also approving the task.  I also think it matches the the behavior with the old editor, but can you check on that?

For 2, are you on gh-unisubs-2150 in amara-enterprise?

**Comment by jdragojevic** [comment]
@bendk I think the subs-approved would need to be sent when the final Approval happened, otherwise TED wouldn't know that the tasks are done for that language.  

for 2 - def on the gh-unisubs-2150 branch.

If I edit and approve subs I get three notifications:
```
app_1 | INFO 2015-04-20 11:39:00,615 signals 3971 139636777780992 notification: subs-new (version: SubtitleVersion 409 / em3t03H8btSy / Norwegian Bokmal v2)

app_1 | INFO 2015-04-20 11:39:00,884 signals 3971 139636777780992 notification: subs-new (version: SubtitleVersion 409 / em3t03H8btSy / Norwegian Bokmal v2)

app_1 | INFO 2015-04-20 11:39:02,224 signals 3971 139636777780992 notification: subs-approved (version: SubtitleVersion 409 / em3t03H8btSy / Norwegian Bokmal v2)

```

for a post-publish I get 2.

```
app_1 | INFO 2015-04-20 11:40:55,549 signals 3971 139636777780992 notification: subs-new (version: SubtitleVersion 410 / em3t03H8btSy / Norwegian Bokmal v3)

app_1 | INFO 2015-04-20 11:40:55,759 signals 3971 139636777780992 notification: subs-new (version: SubtitleVersion 410 / em3t03H8btSy / Norwegian Bokmal v3)

app_1 | [20/Apr/2015 11:40:55] "POST /widget/rpc/xhr/finished_subtitles HTTP/1.1" 200 118

```

**Comment by bendk** [comment]
Just pushed some fixes to gh-2150 and gh-unisubs-2150.  We should now emit subs-approved and subs-rejected.  Note that we will only do this for the approval task, not the review task -- even if the team has review-only.  I'm pretty sure this matches the behavior for the old API, and I don't want to change things too much for TED.
