### ISSUE TITLE
Editor shortcuts

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2153]
Implement editor shortcuts, in particular the ones suggested in editor help section and shortcuts related to new subtitle menu.
- [x] Alt+i to insert subtitle above
- [x] Alt+Shift+i to insert subtitle below
- [x] Alt + Del (or backslash) to delete current subtitle
- [x] Alt + UP arrow to navigate to previous subtitle
- [x] Alt + DOWN arrow to navigate to next subtitle

**Comment by PCF-Testing** [comment]
Will up/down navigation shortcuts work if the user has not yet entered the typing mode (i.e. if the focus is outside any text entry field)? I had a specific request from a TED coordinator to ease navigation with keyboard alone, without mouse scrolling, so perhaps these shortcuts should always do the scroll.

**Comment by jdragojevic** [comment]
Right now the shortcuts are only for when the subtitle line in active.   We don't have navigation through the ui via shortcut, and I think we'd need to implement that in a different ticket.

**Comment by jdragojevic** [comment]
deployed.
