### ISSUE TITLE
YouTube syncing error: local variable 'language_code' referenced before assignment

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2154]
http://www.amara.org/en/videos/R6ZcrfqbUjQS/cnh/943987/?tab=sync-history

Error reported in http://ted-support.amara.org/helpdesk/tickets/78741

**Comment by jdragojevic** [comment]
This should be fixed in the gh-452 branch: https://github.com/pculture/unisubs/issues/452#issuecomment-87649152

**Comment by PCF-Testing** [comment]
This one was fixed.
