### ISSUE TITLE
Brightcove videos don't load over HTTPS

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2158]
This was the source of issue 115 on amara-enterprise and that Janet and I looked at on IRC some time ago.

It was affecting only specific users (including myself), on all platforms/browsers, while the rest of the on demand subtitlers were being able to complete their tasks successfully.

The trigger is that some of us have either Amara bookmarked as https:// or use HTTPS Everywhere, and then the editor is opened as https://, but the brighcove player fails to load in that case. Most users seem to use Amara over http:// so they never see this issue.

Changing the URL manually makes the player work.

**Comment by jdragojevic** [comment]
This isn't an amara issue, it's a brightcove issue in that they don't serve over ssl. 

For example try opening this url in your browser vs this one
https://bcove.me/services/player/bcpid3179719187001?bckey=AQ~~,AAAApHEZDkE~,jZWJYMC1C8ThBTGv1iNvfNI_nYoYiHXD&bctid=1189002034001

http://bcove.me/services/player/bcpid3179719187001?bckey=AQ~~,AAAApHEZDkE~,jZWJYMC1C8ThBTGv1iNvfNI_nYoYiHXD&bctid=1189002034001

**Comment by syl22-00** [comment]
We need to find a way to get brightcove videos work on https if we want to turn amara into https-only.

**Comment by kslottow** [comment]
@syl22-00 is there anything more to do here?
