### ISSUE TITLE
Some users cannot access their Messages | Sent Messages pages

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2162]
1. http://ted-support.amara.org/helpdesk/tickets/78861
Username: petra_submarine
http://www.amara.org/en/messages/ 500s.

2. http://ted-support.amara.org/helpdesk/tickets/78854
Username: harasta
http://www.amara.org/cs/messages/sent/ 500s.
The problems started 3-4 days ago (around April 9-10).

**Comment by jdragojevic** [comment]
Checking for errors in new relic I see:

https://rpm.newrelic.com/accounts/207361/applications/3323332/traced_errors/2657656332

Error message
exceptions:ValueError: Invalid IPv6 URL

![image](https://cloud.githubusercontent.com/assets/299270/7134320/191a6c96-e29c-11e4-83f0-2aa2b3c8e9cc.png)

Can also see the error in sentry:

http://logman.amara.org:9000/pcf/amara/group/2003/

**Comment by bendk** [comment]
Looks like this is an issue with our version of django's urlize() function.  See https://code.djangoproject.com/ticket/19070

I think the main way to fix this would be to upgrade django, but we need to do a few things before that.  In the meantime, I'll make it so if urlize() throws an exception we'll just ignore it and not urlize the message.

**Comment by bendk** [comment]
Pretty sure you can reproduce with a message line like this:
```
http://prirucka.ujc.cas.cz]
```
