### ISSUE TITLE
Password reset form is gone from Django CustomUser form

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2168]
This blocks Amara staff from resetting users' passwords when they fail to get reset in other ways. Please do restore this feature.

**Comment by jdragojevic** [comment]
@PCF-Testing  As a workaround - you can go to /api/users/USERNAME and via the api update the password for that user.

**Comment by bendk** [comment]
The above commit should fix this.  I just made it so you could edit the password directly from the user form.

**Comment by PCF-Testing** [comment]
The password change form is now present, but it is always shown blanc and does not indicate whether the account previously had a user-specified password, a Google login, or a different SocialAuth authentication token. This was previously shown on Django admin page; is this functionality permanently lost, or it could be restored? Thanks!

**Comment by bendk** [comment]
I just snuck a fix in for this in staging.  I called the field "Raw password" and made it readonly so it doesn't conflict with the other password fields.  Tell me if any more changes need to be made.
