### ISSUE TITLE
Syncing to YouTube overwrites ASR subtitles instead of creating a new track

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2181]
Example:
https://www.youtube.com/watch?v=LmErkHysOdA
Subtitles from
http://www.amara.org/id/videos/B9x0kfPRwxdL/ru/874179/
have overwritten the Russian ASR track and remain labeled as Russian ASR.
Expected: Russian ASR track remains intact, a new Russian track gets created.

**Comment by bendk** [comment]
ASR = Automatic speach recognition?

I'm not sure there is a way to differentiate subtitle tracks based on if they are ASR or not.  I would need to look into this more.

If there's not, then what is the correct behavior in general:
  * Amara subtitles always overwrite subtitles with the same language code
  * We only overwrite other amara subtiltes (this may or may not be possible to do).

**Comment by bendk** [comment]
Looks like there is a way to determine if tracks are ASR, so I think we can just simply go back to the previous behavior and create a new track in this case.

**Comment by PCF-Testing** [comment]
Can we get this one fixed soon? It seems to affect many videos and cause a lot of confusion:

http://ted-support.amara.org/helpdesk/tickets/79054

**Comment by PCF-Testing** [comment]
http://ted-support.amara.org/helpdesk/tickets/79079
http://ted-support.amara.org/helpdesk/tickets/79081

**Comment by bendk** [comment]
Just pushed a fix for this one.  I actually don't have an ASR track to test with, but I'm pretty sure the fix should work.  Can you check it out in the real-world janet?
