### ISSUE TITLE
ASR subtitles get automatically imported from YouTube

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2182]
Reported in http://ted-support.amara.org/helpdesk/tickets/78970

Examples:
http://www.amara.org/en/videos/EaQxBdpOinsh/en/975310/
http://www.amara.org/en/videos/U24oOtwvvhtB/en/975309/
http://www.amara.org/en/videos/WiPe69fhLy6S/fr/975312/
http://www.amara.org/en/videos/Er3mjG7KvMmh/ja/975308/

Expected: ASR subtitles by default should not be imported.

This seems to be related to #2181, having to do with the way ASR subtitles are treated.

**Comment by jdragojevic** [comment]
As a workaround, can ASR subtitles be turned off by default on the channel?
