### ISSUE TITLE
New API returns null language in team video activity

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2189]
API v2:
GET /api2/partners/activity/?before=1429884000&limit=20&offset=0&team=ted&format=json&type=4
returns:
{"comment": null, "created": "2015-04-24T08:59:08", "id": "4578778", **"language": "en"**, "language_url": "/en/videos/mwEex69OTj6l/en/977456/", "new_video_title": "", "resource_uri": "/api2/partners/activity/4578778/", "type": 4, "user": "naoko_fujii", "video": "mwEex69OTj6l"}

New API:
GET /api/activity/?before=1429884000&limit=20&offset=0&team=ted&format=json&type=4
returns:
{"id":4578778,"type":4,"created":"2015-04-24T08:59:08","video":"mwEex69OTj6l","video_uri":"https://www.amara.org/api/videos/mwEex69OTj6l/",**"language":null**,"language_uri":null,"user":"naoko_fujii","comment":null,"new_video_title":"","resource_uri":"https://www.amara.org/api/activity/4578778/"}
i.e. "language":null, instead of English.

**Comment by bendk** [comment]
The gh-2189 branch fixes this one.

One other issue is that `language_url` was renamed to `language_uri` when the API changed happened.  This wasn't intentional and I changed it back.  I don't think any client was relying on the new name, since the data was clearly not correct.
