### ISSUE TITLE
get request on subtitles with accept in header

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2209]
This did work with api2/partners, however when used with new api it produces an error

```
curl -H 'X-api-username: janetPCF' -H 'X-apikey: MYAPIKEY' \
     -H 'Accept: application/json' -H 'Content-Type: application/json' \
     http://staging.amara.org/api/videos/yKsUAgChJlGA/languages/en/subtitles/?format=srt 
```

```
{"detail":"Could not satisfy the request Accept header"}
```

**Comment by bendk** [comment]
I don't think that request is valid.  The Accept header is asking for the subtitles in JSON format, but the format param is specifying SRT.  If you remove the format param, or change it to sub_format the request works.
