### ISSUE TITLE
All YouTube videos only play till 3:56 in the editor, regardless of the actual length

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2210]
Example: http://amara.org/en/subtitles/editor/5Mo4oAj1bxOb/en/

**Comment by syl22-00** [comment]
It seems to come from the fact that popcorn gets the youtube video duration from an API call to the data API, on its version 2. That version is deprecated. The call does return, but always giving the same duration value (236 seconds).
Calling the data API is actually not needed to get the video duration as the player API does provide it. It is known a little bit later that way though, as the player must be loaded. First quick fix is available in branch gh-2210. Proper fix is to remove any dependency on data API in popcorn.

**Comment by jdragojevic** [comment]
0cff092bdb5f6c4 has been merged to production directly and deployed. Leaving this ticket open for the the proper fix, dropping the priority to important.

**Comment by syl22-00** [comment]
Just pushed a better fix in branch gh-2210. This was done on the latest popcorn version, and was submitted upstream. As there has been some recent changes in popcorn, in different players, so we should make sure they do not introduce regressions to us.
