### ISSUE TITLE
Editor has performance issues when playing videos with long (near 3K) subtitles

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2212]
Reported in http://ted-support.amara.org/helpdesk/tickets/79171 and confirmed.

Problem: while playing long subtitles (such as http://www.amara.org/en/videos/dBizWtr5EVMA/en/928883/), the video player and timeline jerk at the start and end of each subtitle. The situation gets worse after a number of edits/time adjustments and/or skipping forward and back.

Users also report seeing a similar behaviour with much shorter videos and subtitles (such as https://www.amara.org/en/videos/9JBwbulYgMOi/info/you-be-the-one-that-wins-your-self-back/), but this is harder to see - perhaps, only happens on slower machines.

Expected: the editor should be able to play and sync subtitles with ~3K lines.

**Comment by syl22-00** [comment]
I pushed some optimizations in the editor, related to recent changes. According to the profiler, it removed a lot of unnecessary computations (like 40-60%).
However, timeline still does not seems super smooth, it seems to be related to having the subtitle list having to keep focus in sync with timeline. This should not be new, checking if this can be improved.

**Comment by syl22-00** [comment]
Digged out that the delay when going from one sub to another is due to `getSubtitleTop`, probably because it selects all subs from the DOM then extract the needed one by index. This can be optimized.

**Comment by syl22-00** [comment]
OK, so the timeline is really smooth now, the small pause when jumping from subtitle to subtitle is gone.

**Comment by jdragojevic** [comment]
Definately noticeably better on this branch!
