### ISSUE TITLE
error adding project - project is actually created.

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2225]
NoReverseMatch at /teams/old-style-open/settings/projects/add/
Reverse for 'settings_projects' with arguments '()' and keyword arguments '{'slug': <Team: old style open>}' not found.
Request Method:	POST
Request URL:	http://unisubs.example.com:8000/en/teams/old-style-open/settings/projects/add/
Django Version:	1.4.13
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'settings_projects' with arguments '()' and keyword arguments '{'slug': <Team: old style open>}' not found.
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 420
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/opt/apps/unisubs/libs',
 '/opt/apps/unisubs/apps',
 '/opt/apps/unisubs',
 '/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg',
 '/opt/src/unisubs/unilangs',
 '/opt/src/unisubs/babelsubs',
 '/opt/src/unisubs/bleach',
 '/opt/src/unisubs/python-memcached',
 '/opt/src/unisubs/django-sslserver',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/opt/apps/unisubs/amara-enterprise']
Server time:	Tue, 19 May 2015 14:29:26 -0500

**Comment by bendk** [comment]
This was a pretty simple issue.  I pushed the fix directly to staging.
