### ISSUE TITLE
Several languages consistently fail to sync to YouTube

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2233]
http://www.amara.org/en/teams/ted/settings/sync/

Montenegrin (srp)
Hakha Chin (cnh)
Punjabi (pan)
Chinese Yue (zh)

Error: local variable 'language_code' referenced before assignment

**Comment by bendk** [comment]
Can you add some more details about this one, like the entire traceback for the error?

**Comment by jdragojevic** [comment]
@bendk - I'm pretty sure this ticket is actually a dup of https://github.com/pculture/unisubs/issues/2154 which should be resolved by #452

**Comment by bendk** [comment]
Makes sense to me, let's close this one.
