### ISSUE TITLE
slow queries on accessing activity data

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#2235]
https://rpm.newrelic.com/accounts/207361/applications/3323332/datastores#/overview/MySQL/trace/?id=2921096234&metric=Datastore%252Fstatement%252FMySQL%252Fvideos_action%252Fselect

and 

https://rpm.newrelic.com/accounts/207361/applications/3323332/datastores#/overview/MySQL/trace/?id=2921080778&metric=Datastore%252Fstatement%252FMySQL%252Fvideos_action%252Fselect

show the details.

**Comment by bendk** [comment]
I think the slow queries had this form:
http://staging.amara.org/api/activity/?team=ted&language=en

The gh-2235 branch should fix this one. 

We can test the speed difference on staging after it's merged, but first please test that we return the correct results when you have `language` in the query param (with and without `team`)

**Comment by jdragojevic** [comment]
Added a webdriver test for the team and language query and grabbed some times on staging for the ted team + lang queries:

ted + fr = 26s
ted + de = 3.8s
ted + es = 44.4s

**Comment by jdragojevic** [comment]
Retest on staging with changes merged in:

ted + fr = 4.5 s
ted +de = 4.2 s
ted + es = 5.1 s
ted + en = 4.9 (**Note:** before changes ted + en would not return results it was so slow)

**Comment by bendk** [comment]
Pretty sure this can be considered fixed (although another round of speedups would be nice).
