### ISSUE TITLE
Use different URLs for activity types

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2239]
Right now we use the same URL all video activity queries (/api/activity) with a query param to switch modes.  For example normally we return activity on the users videos, but if the team GET param is present, then we return activity on that team.  There are a couple things that are confusing about this:

 * Normally query params filter results, but in this case they switch the result set so you get a totally different set of items.
 * Related to that, if you specify both the video and team params, then we filter by team and ignore the video param.
 * We had to implement the team-activity query param, which changes the meaning of the team query param in a weird way.

I think we should switch it so that we have different URLs for the different cases instead of trying to have one URL handle everything.  Something like this:

Activity type | Current GET param | New URL
------------------| --------------------------| ---------------
User activity | `?user=<username>` | `/api/users/<username>/activity/`
Video activity | `?video=<video-id>` | `/api/videos/<video-id>/activity/`
Team video activity | `?team=<slug>` | `/api/teams/<slug>/activity/`
Team activity | `?team=<slug>&team-activity=1` | `/api/teams/<slug>/activity/`

**Comment by bendk** [comment]
Also right now we have a specialized activity URL for TED.  I think that we should have an extension system where we can change the response data of the team endpoints based on the team.

**Comment by bendk** [comment]
Note that if we implement #2349, then we wouldn't need the "team video activity" endpoint.  We would just have 1 endpoint for team activity.

**Comment by bendk** [comment]
This is implemented in the activity2 branch.  The docs are here: http://amara.readthedocs.io/en/activity2/api.html#activity

**Comment by PCF-Testing** [comment]
Works as expected.

**Comment by PCF-Testing** [comment]
Deployed.
