### ISSUE TITLE
Standardize mysql collation settings

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2242]
Right now we have a weird situation in our mysql databases where we have a bunch of different collations settings:
- I've noticed they're different on staging and production 
- I've noticed that some tables have different settings than the default setting

This creates weirdness, especially because the collation settings affect how keys work.  It also is potentially dangerous since we could test a migration on staging and have it work, but fail on production.

We should standardize things so that each table has the same collation setting on staging and production.  That setting should match the default unless there's a good reason not to -- which I don't think exists for any of our tables.

We should also consider changing the default collation setting to utf8_general_bin, which will make string comparisons and key checks case-sensitive rather than case-sensitive like we currently have.

**Comment by bendk** [comment]
I tired to do this today, but ran into issues with the subtitles_subtitleversion table.  Trying to convert that one took over 10 minutes and slowed down the entire site.  I'm pretty sure this is because the table is just so huge.  Maybe we need to do #727 before we can do this one.

**Comment by bendk** [comment]
With a bit of monkeying around, I was able to do this for all tables except the following:

```
    'subtitles_subtitleversion',
    'videos_action',
    'videos_subtitle',
    'videos_subtitlelanguage',
    'videos_subtitlelanguage_followers',
    'videos_subtitlemetadata',
    'videos_subtitleversion',
    'videos_subtitleversionmetadata',
    'videos_video',
```

I think we can ignore the `videos_subtitle*` tables.  Those are pre-dmr and probably should just be deleted.  That leaves subtitles_subtitleversion, videos_action, and videos_video.  All of those are really large tables that make the conversion process take too long (since it locks the tables while doing it).

**Comment by asabine** [comment]
not including any of the columns or tables that only exist on staging,
differences between staging and production column collations:
```
staging:
< teams_task,language,utf8_bin
< teams_task,body,utf8_bin
---
production:
> teams_task,language,utf8_unicode_ci
> teams_task,body,utf8_unicode_ci
```
differences between staging and production table collations:
```
staging:
< teams_task,utf8_bin
---
production:
> teams_task,utf8_unicode_ci
```

the differences between column and table collations are the same on both production and staging and are as follows:
table `auth_user` has `utf8_bin` but the columns `first_name` and `last_name` have `utf8_general_ci`
table `videos_videoindex` has `utf8_bin` but the `text` column is `utf8_general_ci` as well
