### ISSUE TITLE
Add Swiss German language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2247]
ISO 639 code: gsw
http://en.wikipedia.org/wiki/Swiss_German

Reason: we currently have subtitles requested in this language and have to use "de" instead, although Swiss German is significantly different from High German.

**Comment by jdragojevic** [comment]
I think we should use de-ch - since it's already defined in unilangs and is also used by vimeo. 

```
        'de': gettext_noop(u'German'),
        'de-at': gettext_noop(u'German (Austria)'),
        'de-ch': gettext_noop(u'German (Switzerland)'),
```

Pretty sure it just needs to be added to the _add_unisubs list to show up as a valid option.

**Comment by bendk** [comment]
Fixed in unilangs

**Comment by PCF-Testing** [comment]
@bendk: I am afraid de-ch is a different thing from what was requested in the ticket. de-ch (German, Switzerland, ) is the Swiss variation of Standard German language. gsw (Swiss German, or Schwizerdütsch) is quite a different language that significantly varies from Swiss Standard German.

Suppose we just keep de-ch that has been already added, and insert gsw as a separate entity?

Reference: https://en.wikipedia.org/wiki/Swiss_Standard_German
"Swiss Standard German is not a German dialect, but a variety of standard German. It must not be confused with Swiss German, an umbrella term for the various Alemannic German dialects (in the sense of ‘traditional regional varieties’) that are the default everyday languages in German-speaking Switzerland."

**Comment by bendk** [comment]
Sounds good, it should be fixed now in unilangs and will be fixed on production with the next deploy.

**Comment by PCF-Testing** [comment]
Sorry, the language as I am seeing it on http://gh-amara-enterprise-353.amara.org/ is not named correctly - 'gsw' should be called 'Swiss German' (without "Standard").

**Comment by bendk** [comment]
Fixed that now.

**Comment by PCF-Testing** [comment]
Verified on staging.

**Comment by PCF-Testing** [comment]
Deployed.
