### ISSUE TITLE
<br> tags in JSON format

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2249]
There's no JSON standard for subtitles, but I'm pretty sure we shouldn't include `<br>` tags in it.  Check out this link for an example.

`http://www.amara.org/api2/ted/videos/2024/languages/ar/subtitles/?format=json`

**Comment by franontanaya** [comment]
I would assume too that anything able to parse the escaped unicodes would parse a \n as per the JSON specs. I think a literal line break is not allowed though.

**Comment by bendk** [comment]
Hmm, I'm not sure about this one, since we still are going to have <i>, <b>, and <u> tags.  Considering that, <br>, doesn't seem too weird.  I don't think anyone is actively complaining, so I would lean torwards no changes.

**Comment by jdragojevic** [comment]
I agree with no changes as well.  I'm pretty certain that only TED uses
this format and there's a good chances they are using the <br> tags as is.
For any changes to this format, we should check with them first.
