### ISSUE TITLE
API response codes for invalid values

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2251]
I think we are sometimes returning 500 codes when we get invalid values.  We should detect input errors and return the correct codes.  Some examples that I see are:

* 500 when the subtitles data is invalid (for example the javascrript value false)
* 500 when get_video false (`"/opt/apps/unisubs/apps/api/views/subtitles.py", line 623, in get_video`)

**Comment by jdragojevic** [comment]
this was fixed and deployed last week or before
