### ISSUE TITLE
Filter by subtitle language on team videos page does not search for exact match

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2252]
The result set returned by Languages - has - <language_code> does not exactly match <language_code> selected by user. Instead of videos selected by exact match, it returns all videos that have subtitles in languages whose codes start with the value of the filter.

Example:
http://amara.org/en/teams/ted/videos/?q=&project=ted-ed&lang-mode=%2B&lang=zh&sort=-time
instead of just videos with subtitles in zh (chinese, Yue), it also returns videos with subtitles in zh-cn and zh-tw.

Expected:
The filter should yield results that exactly match the value of the filter.

Related ticket:
http://ted-support.amara.org/helpdesk/tickets/79723

**Comment by syl22-00** [comment]
As we discussed, until we update the search index (right now, the language code is treated as text, meaning that punctuation is ignored), this is fixed by going through query search result and parsing the values of languages one by one. In branch gh-2252.

**Comment by jdragojevic** [comment]
I can't actually see the complete error message on sentry: however I did get an error when trying to do a negative (doesn't have) search:

http://gh-2252.amara.org/en/teams/ted/videos/?q=&project=ted-ed&lang-mode=-&lang=zh&sort=-time

```
teams.models in get_videos_for_languages_haystack
TypeError: argument of type 'NoneType' is not iterable
users 143 minutes ago Amara (staging)root
```

**Comment by jdragojevic** [comment]
@PCF-Testing - can you please take a look at this one?  There's a preview build: http://gh-2252.amara.org/en/

**Comment by bendk** [comment]
I think this is fixed. @PCF-Testing: can you double check it?

**Comment by PCF-Testing** [comment]
Works well both in positive and negative filtering.

**Comment by syl22-00** [comment]
Once we revamp search, we hopefully can remove this workaround.

**Comment by PCF-Testing** [comment]
Negative filtering 500s on staging:
http://staging.amara.org/en/teams/ted/videos/?q=&project=tedtalks&lang-mode=-&lang=ar&sort=-time

This definitely did not happen on the local dev instance for the branch - perhaps it only breaks on TED team data set?

**Comment by bendk** [comment]
We ended up reverting the change for this.  This should be fixed as part of #838.

**Comment by PCF-Testing** [comment]
#838 has been deployed, but the issue is still present.

**Comment by bendk** [comment]
#838 isn't fully deployed yet, I expect this will be fixed once it is.

**Comment by syl22-00** [comment]
This indeed seems to be fixed

**Comment by PCF-Testing** [comment]
Works for both positive and negative filtering. Marking as closed.
