### ISSUE TITLE
Syncing to YouTube reported successful, but actually failed

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2266]
Observed on the following videos/subtitles:
1. https://www.youtube.com/watch?v=5weJ4b2Pu5M
http://www.amara.org/en/videos/uj4y9HTI4OwH/ko/117534/
1. http://www.youtube.com/watch?v=JezIHeM1NtQ
   http://www.amara.org/en/videos/0LtviaCyAez6/ko/428498/

The system reported success on both counts, but the videos on YouTube side do not have Korean (non-ASR) subtitles.
The channel is configured OK - consider, for example, http://www.amara.org/en/videos/5fhCESHhJlrz/es/514344/?tab=sync-history, which successfully synced subtitles.
The subtitles also seem to be OK - got synced well on a test video. However, for the original videos syncing seems to be a problem.

**Comment by jdragojevic** [comment]
I saw this on one of my own videos.  It seems like there's something happening on the youtube side as when I looked in the CC tab on youtube for that language, youtube indicated that it was still processing the subtitles.  May want to have the video owner check in youtube and report what they are seeing.

**Comment by bendk** [comment]
Too old to be useful at this point.
