### ISSUE TITLE
API datetimes should use UTC timezone

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2267]
Right now when we return dates/times in the API, it's using the Chicago time and does not include the timezone.  We should switch that to returning UTC time and specify that it's UTC with the "Z" as the time zone designator.

**Comment by bendk** [comment]
I changed the format for the following fields:
  * activity (created)
  * video (created)
  * video_url (created)
  * subtitle note (created)
  * subtitle language (created)
  * project (created/modified)
  * task (completed)
  * team application (created/modified)

This gives us a chance to test the API deprecation/switchover code that we talked about with the new API.  I made the switchover date 2015/07/16 which is 3 weeks from today, but we can change that when we are ready to deploy.  For each of the API endpoints you should:

  * Get the old format by default (the response should include an X-API-DEPRECATED header)
  * Get the new format if you send the X-API-FUTURE header with a value >= 20150716
  * Get the new format if you add the api-future GET param with a value >= 20150716 
  * Get the new format if you change your system clock to after 7/16

**Comment by bendk** [comment]
Oh yeah, the old format should be the for Chicago (I think thats UTC +5 hours).

The new format should be UTC time and also should include a "Z" at the end, which signifies that it's UTC.

**Comment by jdragojevic** [comment]
getting 403 errors when running webdriver tests that use the old api endpoints: api2/partners:

```
<body>
<div id="summary">
  <h1>Forbidden <span>(403)</span></h1>
  <p>CSRF verification failed. Request aborted.</p>

</div>
```

ex: `dev test webdriver_enterprise_tests.check_api_v2.test_team_project_resource:TestCaseTeamProjectResource.test_projects_delete`

**Comment by bendk** [comment]
The new and old endpoints are actually the same nowadays.

**Comment by bendk** [comment]
0c7a24e should fix the last issue.

**Comment by jdragojevic** [comment]
@bendk - I believe the before and after queries are broken.  Had a previously passing test case:

`dev test webdriver_testing.check_api.test_activity:TestCaseActivity.test_time_query` which is now failing and returning too many results.

ex: this query:  `/api/activity/?team=team-1&after=1436792249` , where the after time in seconds converts to `Mon, 13 Jul 2015 12:57:29 GMT` is returning results with a creation time ranging from 12:57:27 to 12:57:31

**Comment by bendk** [comment]
I think this is just the effect of changing the before queries to UTC.  time.time() returns a time based on the timezone of your computer, but the before/after filters use UTC time.  So I think the following is happening:

 - You create activity A
 - You record the time T
  - You sleep a few seconds
 - You create activity B
 - You use time T for the before/after param.

Since we convert T to UTC, unless you live in GMT, then T will either be before activity A, or after activity B.

Ben
