### ISSUE TITLE
HTML5 player adds arbitrary query params

### ISSUE THREAD

**Issue by warrenseymour** [pculture/unisubs#2277]
The fix for issue #1208 (https://github.com/pculture/unisubs/commit/78bd65ef351880124fa1508dd73fc7e611a6d559) is to add an arbitrary query string to the video URL.

For our integration using signed CloudFront URLs, this is not acceptable. CloudFront does not accept custom query parameters in a signed URL, and will throw a 403 if it finds any parameters aside from `Expires`, `Signature` or `Key-Pair-Id`.

Is this still an issue in recent versions of Chrome? If not, can this code be reverted?

**Comment by syl22-00** [comment]
So this Chrome issue does seem to be resolved, at least I can not reproduce it with my previous test case on Chrome 43. Making the change in branch gh-2277, but we probably want to test it more widely.

**Comment by jdragojevic** [comment]
Branch is working for me with Chrome Version 42.0.2311.90 (64-bit)

**Comment by bendk** [comment]
Pretty sure this is fixed.
