### ISSUE TITLE
Allow HTTP Callbacks without amara-enterprise

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2280]
We have more-or-less enough code to handle http callbacks in this repository, but trying to use it will fail unless the amara enterpise repository is installed (specifically the ted app).

With a bit of code shuffle, we should be able to remove the dependency and allow users to use the BaseNotification class.

I think the starting point to implement this one is TeamNotificationSetting.notify() in teams/models.py around line 2900.

While we're doing it, we may want to change BaseNotification to return URLs to the new API.

**Comment by bendk** [comment]
This is impemented in the gh-2280 and gh-unisubs-2280 branch.

I added a logging statement so you should be able to test this from a dev environment pretty easily:

  - Create a team notification setting object for your team, choose either 1 for normal notifications or 2 for TED notifications.  Choose a URL in example.com.  Any team can have TED notifications, they don't need to be named TED.
  - Add a video to the team (or any other action that creates a notification)
  - You should see a line like this in the logs: `Sending TEDNotification video-new (team: Collab) (partner: None) (data: {'video_id': 'I1r6Upb9o35x'})` (Although it could be somewhat hard to find in all the chatter)

**Comment by PCF-Testing** [comment]
@bendk: tested this one locally POSTing callbacks to requestb.in (online http listener).

1) Callbacks of class 1 and class 2 did not reach requestb.in (while callbacks from my test team on production server did).
2) In the worker logs, found the following:
[36mworker_1 | [0m[2015-07-17 20:27:51,696: INFO/MainProcess] Sending BaseNotification video-new (team: Test Team) (partner: None) (data: {'video_id': 'rir2YxLY7YY6'})
[36mworker_1 | [0m[2015-07-17 20:27:51,701: ERROR/MainProcess] Task teams.tasks.api_notify_on_video_activity[44fb320f-0842-4b1c-a823-a77f6b03618c] raised exception: ImportError('No module named apiv2.api',)
[36mworker_1 | [0mTraceback (most recent call last):
[36mworker_1 | [0m  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
[36mworker_1 | [0m    R = retval = fun(*args, **kwargs)
[36mworker_1 | [0m  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 403, in __protected_call__
[36mworker_1 | [0m    return self.run(*args, **kwargs)
[36mworker_1 | [0m  File "/opt/apps/unisubs/apps/teams/tasks.py", line 175, in api_notify_on_video_activity
[36mworker_1 | [0m    TeamNotificationSetting.objects.notify_team(team_pk, event_name, video_id=video_id)
[36mworker_1 | [0m  File "/opt/apps/unisubs/apps/teams/models.py", line 2826, in notify_team
[36mworker_1 | [0m    notification_settings.notify(event_name, **kwargs)
[36mworker_1 | [0m  File "/opt/apps/unisubs/apps/teams/models.py", line 2903, in notify
[36mworker_1 | [0m    event_name,  **kwargs)
[36mworker_1 | [0m  File "/opt/apps/unisubs/apps/teams/notifications.py", line 107, in __init__
[36mworker_1 | [0m    self.api_url = self.get_api_url()
[36mworker_1 | [0m  File "/opt/apps/unisubs/apps/teams/notifications.py", line 115, in get_api_url
[36mworker_1 | [0m    from apiv2.api import (
[36mworker_1 | [0mImportError: No module named apiv2.api

...

[36mworker_1 | [0m[2015-07-17 20:40:02,170: ERROR/MainProcess] Could not find notification class 2

**Comment by PCF-Testing** [comment]
Also failed the following test:
ERROR: test_notify_lookup (teams.tests.test_teams.TestNotification)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/unisubs/apps/teams/tests/test_teams.py", line 148, in test_notify_lookup
    TeamNotificationSetting.objects.notify_team(t1.pk, 'x')
  File "/opt/apps/unisubs/apps/teams/models.py", line 2826, in notify_team
    notification_settings.notify(event_name, **kwargs)
  File "/opt/apps/unisubs/apps/teams/models.py", line 2903, in notify
    event_name,  **kwargs)
  File "/opt/apps/unisubs/apps/teams/notifications.py", line 107, in __init__
    self.api_url = self.get_api_url()
  File "/opt/apps/unisubs/apps/teams/notifications.py", line 115, in get_api_url
    from apiv2.api import (
ImportError: No module named apiv2.api

**Comment by bendk** [comment]
I think this should be fixed now.  That reqestb.in site is awesome.

You can test things as follows:

* Add a video to a team -- this should result in a `video-new` event.  `api_url` should be for the video.
* Add subtitles to the video -- this should result in the `subs-new` event.  `api_url` should be for the subtitles (with version_no specified)
* Apply to the team -- this should result in an `application-new` event.  `api_url` should be for the application.

There are probably other events that result in a notification, but those generate the 3 different types of api_urls.  Note that there is code to handle generating an api_url without version_no, for example for the `language-new` event, but I can't see any way to trigger it.  I think this is fine for now.

Also, I changed the api_url to use the new API urls (/api/) instead of the old ones (/api2/partners/).

**Comment by bendk** [comment]
Also, you can test using notificaction_class=2.  That should implement the TED logic.  In this case, we should return api_urls using the old API.  This is only going to work if amara-enterprise is present.  The thing to test is that nothing is changing in this case.

**Comment by PCF-Testing** [comment]
All three test cases for class 1 passed on local instance.

With class 2, after adding /amara-enterprise from master branch to unisubs folder and recreating/restarting the worker, I cannot get any notifications to be sent. The logs say:

[36mworker_1 | [0m[2015-07-22 03:37:19,184: DEBUG/MainProcess] Task accepted: teams.tasks.api_notify_on_application_activity[1b12c042-3c9f-4da7-85f5-f16ec1fbaca0] pid:16
[36mworker_1 | [0m[2015-07-22 03:37:19,184: DEBUG/MainProcess] Task accepted: messages.tasks.application_sent[2c7e0c40-045e-429e-9828-1cd63ebdec25] pid:18
[36mworker_1 | [0m[2015-07-22 03:37:19,188: ERROR/MainProcess] Could not find notification class 2
[36mworker_1 | [0m[2015-07-22 03:37:19,189: INFO/MainProcess] Task teams.tasks.api_notify_on_application_activity[1b12c042-3c9f-4da7-85f5-f16ec1fbaca0] succeeded in 0.00689792633057s: None

Could there be anything missing in the setup? Does it require dbreset for the change to take effect?

**Comment by bendk** [comment]
You need the gh-unisubs-2280 branch on amara-enterprise.

**Comment by PCF-Testing** [comment]
gh-unisubs-2280 enabled me to send class 2 notifications for new applications and new TEDx (YouTube) videos and subtitles. For TEDTalks, sending class 2 notifications will fail with the following error if talk_id for the new video is not set:

worker_1 | [2015-07-23 03:33:39,456: DEBUG/MainProcess] Task accepted: teams.tasks.api_notify_on_video_activity[a2c5d12e-7092-47d2-b2b6-67ac4b9b64bf] pid:14
worker_1 | [2015-07-23 03:33:39,459: INFO/MainProcess] Sending TEDNotification video-new (team: TED) (partner: None) (data: {'video_id': 'FG4U6u0KxeNg'})
worker_1 | [2015-07-23 03:33:39,465: ERROR/MainProcess] Task teams.tasks.api_notify_on_video_activity[a2c5d12e-7092-47d2-b2b6-67ac4b9b64bf] raised exception: ValueError('Unknown video id',)
worker_1 | Traceback (most recent call last):
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
worker_1 |     R = retval = fun(*args, **kwargs)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 403, in __protected_call__
worker_1 |     return self.run(*args, **kwargs)
worker_1 |   File "/opt/apps/unisubs/apps/teams/tasks.py", line 171, in api_notify_on_video_activity
worker_1 |     TeamNotificationSetting.objects.notify_team(team_pk, event_name, video_id=video_id)
worker_1 |   File "/opt/apps/unisubs/apps/teams/models.py", line 2826, in notify_team
worker_1 |     notification_settings.notify(event_name, **kwargs)
worker_1 |   File "/opt/apps/unisubs/apps/teams/models.py", line 2903, in notify
worker_1 |     event_name,  **kwargs)
worker_1 |   File "/opt/apps/unisubs/apps/teams/notifications.py", line 107, in __init__
worker_1 |     self.api_url = self.get_api_url()
worker_1 |   File "/opt/apps/unisubs/amara-enterprise/ted/notifications.py", line 28, in get_api_url
worker_1 |     return video_klass(self.api_name).get_resource_uri(self.video)
worker_1 |   File "/opt/apps/unisubs/amara-enterprise/apiv2/api.py", line 326, in get_resource_uri
worker_1 |     "pk": self.from_internal_video_id(source.video_id),
worker_1 |   File "/opt/apps/unisubs/amara-enterprise/ted/api.py", line 123, in from_internal_video_id
worker_1 |     return  YoutubeVideoType._get_video_id(video_url)
worker_1 |   File "/opt/apps/unisubs/apps/videos/types/youtube.py", line 105, in _get_video_id
worker_1 |     raise ValueError("Unknown video id")
worker_1 | ValueError: Unknown video id

It is my understanding that talks without IDs should not get added in the real world use, if TEDTalks get submitted from a feed that already includes and imports talk IDs.

**Comment by bendk** [comment]
Also, this is the same code as before, so if it fails it's not a regression at least.
