### ISSUE TITLE
Brightcove accounts using Custom Domain creates unrecognized video URL

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#2285]
If a client decides to use Brightcove's Custom Domain, the video URL's created for their RSS feeds aren't recognized as compatible videos, and thus aren't imported to a team.

<strong>Documentation for how Brightcove Custom Domain</strong>: https://support.brightcove.com/en/video-cloud/docs/using-custom-domain-name-links-and-feeds

<strong>Example of a RSS feed created using Custom Domain</strong>: http://link.brightcove.com/services/mrss/player4333002481001/1399189305/tags/Amara

<strong>Example of video URL from Custom Domain RSS</strong>: http://video.scientificamerican.com/services/link/bcpid4333002481001/bctid4316617720001?src=mrss

<strong>Example of RSS feed for non-custom domain</strong>: http://link.brightcove.com/services/mrss/player3404083053001/2385340575001/tags/9amara

<strong>Example of video URL from non-custom domain</strong>: http://link.brightcove.com/services/link/bcpid3404083053001/bctid4339963904001?src=mrss

The current workaround is to manually adjust the URL's for custom domain's. For example, by changing "http://video.scientificamerican.com/services/link/bcpid4333002481001/bctid4316617720001?src=mrss" to "http://link.brightcove.com/services/link/bcpid4333002481001/bctid4316617720001?src=mrss"
Then the videos can be added by copy/pasting the adjusted URL into the Video's tab --> "Add Video" dialogue.

**Comment by bendk** [comment]
Do these videos need to be recognized as brightcove videos?  If we just treated them as generic HTML5 videos would that be okay?

**Comment by jdragojevic** [comment]
They have to be recognized as brightcove videos.

**Comment by bendk** [comment]
So there's 2 options:
  * Try to match brightcove URLs more aggresively.  We assume videos are from brightcove if we see "bcpid" followed by the a string of numbers (maybe we can match the length too).  Don't worry about the domain name
 * Add a list of extra domains that we know are brightcove ones.

Option 1 would require less changing if more clients do this.  Option 2 seems slightly safer to me.

**Comment by darren-bridenbeck** [comment]
Either approach sounds good to me - how difficult would it be to add a new
domain when we sign a new BC client that has a custom domain? Currently we
have five BC clients, and only one (AFAIK thus far) has a custom domain -
at that rate we wouldn't need to add new ones that often, however if we
begin scaling fast with BC clients that could change.

**Comment by jdragojevic** [comment]
This is another example of a brightcove url that we currently don't support.

**Comment by bendk** [comment]
After thinking about it more, we could have a setting for extra brightcove domains.  This means that we could change things pretty fast by just adding an entry in the settings file and redeploying.  I think that's the best way to handle this.

@jdragojevic what's the other example?

**Comment by jdragojevic** [comment]
@bendk this url http://players.brightcove.net/753071706001/default_default/index.html?videoId=4078241835001 doesn't play when added to amara.  Not recognized as a brightcove url + there is no player id.  I think it's just a completely different brigthcove url player.

**Comment by franontanaya** [comment]
Brightcove videos themselves are streamed from .TS containers, rather than MP4.

The net log looks a bit different for http://players.brightcove.net/ than described here (https://github.com/pculture/amara-enterprise/issues/115), but it's still based around returning a m3u8 playlist with .TS assets:

http://c.brightcove.com/services/mobile/streaming/index/master.m3u8?videoId=4078241835001&pubId=753071706001

**Comment by darren-bridenbeck** [comment]
@syl22-00 the editor / player issues you reported in the weekly staff call the other week seem to be a non-issue. I've changed the video URL to reference a different player correctly configured for Amara, and it seems to work in the editor as expected.

To confirm this, I took the following link: http://video.scientificamerican.com/services/link/bcpid4333002481001/bctid4316617720001?src=mrss

Pasted it into my browser to get this elongated URL: http://video.scientificamerican.com/services/player/bcpid4333002481001?bckey=AQ~~,AAAAAFNl7zk~,OmXvgxJOvrHfFCskybwLj2AmSNWmgKoD&bctid=4316617720001

I then swapped out "video.scientific" to "link.brightcove" and updated the BCPID to 3617301057001 (which is an updated player, which is properly configured in Brightcove.)

http://link.brightcove.com/services/player/bcpid3617301057001?bckey=AQ~~,AAAAAFNl7zk~,OmXvgxJOvrHfFCskybwLj2AmSNWmgKoD&bctid=4316617720001

**Comment by syl22-00** [comment]
OK, so that should now be done. Here is how to use it:
* One must add patterns for the type, in the admin page (video type url pattern). For example pattern: http://video.scientificamerican.com/, type: brightcove
Then videos starting with that pattern will be recognized as that type.

Not that for now the player would only be set up correctly following the type in the case of brightcove, just for safety reason. We can easily make this behaviour span all types though.

@PCF-Testing Would you mind giving it a try? It is a quite invasive change.

**Comment by darren-bridenbeck** [comment]
I can confirm that the editor works as expected with this in place. Hotkeys and syncing all seem to work fine.

It doesn't look like our embedder works with these URL's though. Example here: http://gh-2285.amara.org/en/videos/7SSsPthZ9jBD/info/is-fire-saving-or-destroying-the-italian-olive-industry/

**Comment by syl22-00** [comment]
This was an issue with the preview deployment scripts, it was fixed in that branch

**Comment by syl22-00** [comment]
@PCF-Testing this seems to have been fixed a while ago

**Comment by PCF-Testing** [comment]
Yes, this has been fixed. Marking as closed.
