### ISSUE TITLE
Make lists of languages sorted alphabetically in not case-sensitive way

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2288]
Currently language lists are sorted in case-sensitive way (A-Za-z). This causes a mess in partially translated Amara UI, where less popular languages are listed in English at the top of the list, staring with uppercase chars, and the most popular languages, that are localized and start with a lowercase char, sit at the bottom of the list.

Make the lists sorted in case-insensitive way (Aa-Zz).

The language lists include:
- User languages
- Video language
- Subtitle language (add, upload, create task)
- Preferred and blacklisted languages for teams
- Language filters on team videos and tasks pages

**Comment by bendk** [comment]
Seems like the best thing would be to have the localizations use upper case, but that's not really an option right now because our transifex process is not working.

What language can I localize the interface in to see this issue?

**Comment by jdragojevic** [comment]
You can see this if you localize to spanish.

**Comment by PCF-Testing** [comment]
Language list are ordered by code now. Marking closed.
