### ISSUE TITLE
Home page is messed up for user without email address

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2291]
Observed on staging.

Username - testuser2015
Password - testpassword2015
Email address - none (Django admin allows leaving this field blank when creating a new user)

Home page displayed to such user after sign in looks as follows:
![staginguserwithoutemailaddress](https://cloud.githubusercontent.com/assets/288455/8719542/5e121da4-2b61-11e5-937d-6121fda40471.png)

**Comment by bendk** [comment]
I kind of think the whole concept is wrong.  There's no normal way outside of testing to create a user without an email.  Also, it's not really that big of a deal if the user doesn't have their email set.  For example, all facebook logins don't have a valid email.

I think we should just not show the prompt on the new homepage.  We also don't show it on the pages that use the new styles (right now just the new teams pages).

I think we can leave the old pages like they are and pop up the dialog for now.  As we move over to the new styles, then these pages will stop popping up the dialog.
