### ISSUE TITLE
YouTube videos in Amara editor and embedder not playable in Google Chrome

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2296]

**Comment by syl22-00** [comment]
Seems like a Chrome and Youtube issue, we have a hack now. See
https://github.com/mozilla/popcorn-js/issues/458

**Comment by PCF-Testing** [comment]
Deployed to production.

**Comment by syl22-00** [comment]
Made the fix better, better use this one as this does not seem to get fixed on Youtube side. Still in branch gh-2296.
