### ISSUE TITLE
Not possible to submit a vimeo video using https

### ISSUE THREAD

**Issue by bradmsmith** [pculture/unisubs#2303]
A user who submits a video like https://vimeo.com/[video_id] will have it convert to http://video.com/[video_id] which results in a warning message on the video page that says, "You have submitted a video that is served over http."

This is because the code in `app/videos/type/vimeo.py` is hard-coded to use http://vimeo.com instead of the https in the original submission.

**Comment by kslottow** [comment]
pculture/amara-enterprise/issues/486

**Comment by kslottow** [comment]
check warning message - then close

**Comment by syl22-00** [comment]
It is just an internal normalisation of the url to avoid having multiple versions of one video.
