### ISSUE TITLE
Update popcorn, remove workaround for fixed youtube issue

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2308]
* We miss a few commits from upstream popcorn,
* Workaround for issue #2296 is no longer necessary

**Comment by syl22-00** [comment]
This is done, in branch gh-2308.

**Comment by PCF-Testing** [comment]
Tested locally, looks good.

**Comment by bendk** [comment]
I think this one is fixed.

**Comment by PCF-Testing** [comment]
@bendk: seems this one is not on production yet - maybe close tickets when the changes go live?

**Comment by syl22-00** [comment]
This has been on production for a while now
