### ISSUE TITLE
Implement dashboard for new-style simple teams

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2311]
New sections:
- the top section is for finding new work.  It has latest videos with CTAs to click.  There are a couple cases here:
  - Videos that need caption in a language you speak -- CTA labeled `Transcribe [language]`
  - Videos that need 1 translation in a language you speak -- CTA labeled `Translate [language]`
  - Videos that need multiple translations in languages you speak -- Split button CTA:
     - The main button says `Translate [language]` where language is the top language in your profile
     - The dropdown lists other languages that you can translate to
  - Videos that don't have primary audio language set -- Don't show these
  - Videos that don't need subtitles for the languages you speak -- Don't show these
 - Under that is the section for your recent history.  It uses the "assignment history" style, with the following columns:
   - Video title
   - Subtitle language
   - The date you subtitled
   - Video duration
   - Some of these might be hidden on smaller screens

Same as collaboration teams futureui dashboard:
- new videos
- new members
- top languages

**Comment by kslottow** [comment]
@juditpinol has ideas about what else would be helpful for simple teams here - she will add some drawings and reasoning!

**Comment by Juditpinol** [comment]
As we are looking to create more self-sufficiency for clients, it would be ideal to incorporate some kind of helptext/guidelines so brand new users can learn how the team functions by themselves.

Some ideas for this are to incorporate help text similar to the one on the Editor, or to have a pop up with animations or screenshots (see files attached for examples)
![ux-rollout-3-2](https://user-images.githubusercontent.com/32497005/40555415-55fed6f0-6049-11e8-9ae5-d1c5ba474b0e.gif)

![ux-rollout-3](https://user-images.githubusercontent.com/32497005/40555417-57db912a-6049-11e8-9aa8-a6f89e9b5d20.png)

What are your thoughts?

**Comment by kslottow** [comment]
Issue moved to [pculture/amara-enterprise #2014](https://github.com/pculture/amara-enterprise/issues/2014) via [**ZenHub**](https://www.zenhub.com/)
