### ISSUE TITLE
Simple teams: Add a new language dialog warns about primary language after it is set

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2314]
Add a new language dialog displays "Please double check the primary spoken language. This step cannot be undone" warning even for a video that already has the primary language set:

![simpleteamaddnewlanguagedialog](https://cloud.githubusercontent.com/assets/288455/9246140/5c2a080e-415e-11e5-8d6e-93ee65c30c34.png)

Expected: after the primary language is set, the warning should no longer appear.

**Comment by bendk** [comment]
This only happens on the team dashboard, not the video page.  It will be fixed once we implement #2311.
