### ISSUE TITLE
"Learn more" link on team dashboard points to an outdated URL

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2315]
On the team dashboard, "Learn more" link references http://support.universalsubtitles.org/solution/categories/13504, which does not resolve correctly. Should be http://support.amara.org/support/home instead.

![teamdashboardlearnmoreaboutsubtitlingamara](https://cloud.githubusercontent.com/assets/288455/9246565/516fa4a2-4161-11e5-8cf8-4df39c7efed0.png)

**Comment by bendk** [comment]
This is another dashboard one, but I think it also affects old-style private teams so I went ahead and fixed it.

**Comment by PCF-Testing** [comment]
Looks good on simple-workflows branch.

**Comment by PCF-Testing** [comment]
Has been deployed.
