### ISSUE TITLE
Simple teams: With the primary language set for video, cannot add this language from dashboard

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2317]
Steps to reproduce:
1. Add a video to a simple team.
2. Set the original language for the video. Do not add any subtitles for the primary language.
3. As a user without any language preferences set, open the team dashboard and click Create Subtitles button under the video. In the invoked dialog, the primary language will be grayed out and unavailable for selection.

**Comment by bendk** [comment]
The dashdboard is pretty non-functional at the moment.  Let's fix this as part of #2311.
