### ISSUE TITLE
Key Error on Video Statistics page

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2318]
KeyError at /teams/private-simple-team/activity/videosstatistics/
u'es-es'
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/teams/private-simple-team/activity/videosstatistics/
Django Version:	1.4.21
Exception Type:	KeyError
Exception Value:	
u'es-es'
Exception Location:	/opt/apps/unisubs/apps/teams/statistics.py in compute_statistics, line 40

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/unisubs/apps/teams/new_views.py" in wrapper
  61.         return view_func(request, team, *args, **kwargs)
File "/opt/apps/unisubs/apps/teams/new_views.py" in statistics
  168.         context = compute_statistics(team, stats_type=tab)
File "/opt/apps/unisubs/apps/teams/statistics.py" in compute_statistics
  40.             numbers.append((strip_strings_chrome(ALL_LANGUAGES_DICT[l]), count_complete + count_incomplete, "%s - Published: %s" % (ALL_LANGUAGES_DICT[l], count_complete)))

Exception Type: KeyError at /teams/private-simple-team/activity/videosstatistics/
Exception Value: u'es-es'

**Comment by bendk** [comment]
This is a generic error, it should happen on all teams.

Not sure how you got "es-es" as a language code, we normally just use "es" for Spanish spoken in Spain.

@syl22-00 can you check this one out?.

**Comment by PCF-Testing** [comment]
@bendk: "es-es" was imported to the team from YouTube with this video: http://www.youtube.com/watch?v=WVz5CGnWwkE. Could it be fallout from #452?

**Comment by syl22-00** [comment]
This issue does not happen anymore because `es-es` was added to the list of languages in `unilangs`. Same error would happen in case of subtitles with invalid or unknown or incorrect language code.

**Comment by PCF-Testing** [comment]
This seems to be the issue fixed in https://github.com/pculture/amara-enterprise/issues/703. Marking as closed.
