### ISSUE TITLE
"French Canadian" displays as "?" on team dashboard 

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#2320]
If I select "French Canadian" as one of my languages in my profile: 
![screen shot 2015-08-13 at 6 08 00 pm](https://cloud.githubusercontent.com/assets/5092242/9262883/77538d20-41e6-11e5-82a7-7ef7cd052d33.png)

It shows as "?" instead of "French Canadian" when viewing the team dashboard:
![screen shot 2015-08-13 at 6 08 34 pm](https://cloud.githubusercontent.com/assets/5092242/9262881/752fc392-41e6-11e5-9eb4-f2cbba1ae7d2.png)

**Comment by bendk** [comment]
Can you post the URL to the page?

**Comment by darren-bridenbeck** [comment]
@bendk here's the url, sorry for not including in the original ticket!: http://amara.org/en/teams/autodesk-open-translation-project/

**Comment by bendk** [comment]
I can reproduce this one when I use a old-style team without tasks.  It also happens on the new-style "Simple" teams.

**Comment by PCF-Testing** [comment]
@bendk : Still seeing the issue for Fr-Ca on simple-workflow branch after pulling the recent changes and running migrations - is there anything I might be missing on my side?

**Comment by bendk** [comment]
It's the gh-2320 branch.

**Comment by PCF-Testing** [comment]
On gh-2320, languages with locales (pt-PT, pt-BR) fail to import from YT - I believe this has been fixed on production?
Video for testing: http://www.youtube.com/watch?v=3_petnJUYqk. Please ping me for the account credentials.

**Comment by unisubs-transifex** [comment]
There's no way that this change affected YouTube import.  Maybe it's a
staging issue.  It shouldn't block merging this branch though.

**Comment by bendk** [comment]
The last comment was from me.

**Comment by PCF-Testing** [comment]
OK, if merging this branch is not going to introduce YT issue as a regression bug, I am going to create a PR for this one.

**Comment by PCF-Testing** [comment]
Has been deployed.
