### ISSUE TITLE
Team Statistic pages gives error

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#2321]
"We're sorry - you've encountered an error." displays when attempting to view team statistic pages. 

![screen shot 2015-08-13 at 11 33 19 pm 1](https://cloud.githubusercontent.com/assets/5092242/9266786/b477bb4a-4213-11e5-84a2-03826c064b12.png)

Below are some example links that I can't get to load:
http://amara.org/en/teams/adventist/activity/videosstatistics/
http://amara.org/en/teams/adventist/activity/teamstatistics/
http://amara.org/en/teams/udacity/activity/videosstatistics/
http://amara.org/en/teams/udacity/activity/teamstatistics/

This doesn't seem to be affecting all pages/teams the same, as I was able to successfully load TED's "Team Statistics" page earlier, although it now seems to throwing the error again: http://amara.org/en/teams/ted/activity/teamstatistics/

**Comment by darren-bridenbeck** [comment]
^^ Updated w/ screenshot of error

**Comment by deanjansen** [comment]
Confirmed – I'm seeing the error as well for the TED link at the bottom.

**Comment by bendk** [comment]
Here's the sentry error:

http://logman.amara.org:9000/pcf/amara/group/2648/

**Comment by darren-bridenbeck** [comment]
@PCF-Testing recommended I add some additional issues happening on stats pages here. Let me know if any of these should be it's own ticket:
**Issue 1:** Y axis units seem out of order: http://amara.org/en/teams/calacademy/activity/videosstatistics/
![screen shot 2015-08-28 at 2 06 55 pm](https://cloud.githubusercontent.com/assets/5092242/9553623/469fc17c-4d8e-11e5-9ec3-ef738cc83096.png)

Another example here: http://amara.org/en/teams/calacademy/activity/videosstatistics/
![screen shot 2015-08-28 at 2 08 58 pm](https://cloud.githubusercontent.com/assets/5092242/9553636/5f2e7008-4d8e-11e5-99ec-854cf61eb3fd.png)

![screen shot 2015-08-28 at 2 09 32 pm](https://cloud.githubusercontent.com/assets/5092242/9553644/6c64698a-4d8e-11e5-9d0a-4be31f22dc03.png)

**Issue 2:** When hovering over bars in graphs, help text used to populate over your cursor to reveal the actual number value of the bar graph. Currently it's pretty difficult to see exactly what the values are.

**Comment by olexiy-logvinov** [comment]
I get "504 Time-out" error when trying to load /teamstatistics/
![selection_001](https://cloud.githubusercontent.com/assets/3581695/12608124/9870ddf8-c4e2-11e5-825c-7f80d28e9e70.jpg)
