### ISSUE TITLE
Problems with charts on Team Statistics page

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2328]
https://amara.org/en/teams/ted/activity/teamstatistics/

In Chrome, ellipsis is displayed as weird characters. In Safari on Mac OS X, the legend is blank until hovered over. In Firefox, the legend is displayed correctly.

![teamstatschrome](https://cloud.githubusercontent.com/assets/288455/9423735/65b7981c-4886-11e5-9a03-cb2df943f45a.png)
![teamstatssafari](https://cloud.githubusercontent.com/assets/288455/9423736/68db0c68-4886-11e5-8a5a-1e3dee3ba0f4.png)

Also, truncated bar names are non-informative when the language locale or the family name of the user are left out - there is no easy way to discriminate between Chinese Simplified and Chinese Traditional, etc. Could we display non-truncated version of the label on mouseover? (At this time, the truncated one is displayed.)

Related FD ticket: http://support.amara.org/helpdesk/tickets/80684

**Comment by PCF-Testing** [comment]
Another related problem report from @darren-bridenbeck:

**Issue 1:** Y axis units seem out of order: http://amara.org/en/teams/calacademy/activity/videosstatistics/
![screen shot 2015-08-28 at 2 06 55 pm](https://cloud.githubusercontent.com/assets/5092242/9553623/469fc17c-4d8e-11e5-9ec3-ef738cc83096.png)

Another example here: http://amara.org/en/teams/calacademy/activity/videosstatistics/
![screen shot 2015-08-28 at 2 08 58 pm](https://cloud.githubusercontent.com/assets/5092242/9553636/5f2e7008-4d8e-11e5-99ec-854cf61eb3fd.png)

![screen shot 2015-08-28 at 2 09 32 pm](https://cloud.githubusercontent.com/assets/5092242/9553644/6c64698a-4d8e-11e5-9d0a-4be31f22dc03.png)

**Issue 2:** When hovering over bars in graphs, help text used to populate over your cursor to reveal the actual number value of the bar graph. Currently it's pretty difficult to see exactly what the values are.

**Comment by PCF-Testing** [comment]
This issue was reiterated again by TED staff in http://support.amara.org/helpdesk/tickets/81280.

**Comment by syl22-00** [comment]
Hopefully these have been fixed and improved in branch gh-2328

**Comment by PCF-Testing** [comment]
Testing locally on gh-2328.

1. In Chrome, chart labels & column values are not displayed in the tooltip at all.

2. In Firefox, the data does show up in the tooltip for a second or two, then disappears. The black text is hard to see against the dark background. Then the data disappears too quickly, but well-visible "Pygal" text remains. In some cases "Pygal" alt text overlaps the meaningful chart column data - can it please be removed?

![teamstatisticschart](https://cloud.githubusercontent.com/assets/288455/10633787/098c1c8e-77a2-11e5-8031-2b739a3f4486.png)


3. It might be a good idea to show y guides, as currently in the production version.

**Comment by PCF-Testing** [comment]
The recent updates to production have solved most of the issues from this ticket.

A. However, on http://www.amara.org/en/teams/ted/activity/teamstatistics/ the two bottom graphs for top contributors are missing - just the headers are present.

B. For non-members, the video statistics and team statistics pages 404 - is that intentional? If we absolutely do not want to allow non-members see these stats pages, maybe display a 403 page instead?

C. Firefox still displays the black ugly Pygal hint on mouseover on the chart - is it removable?

D. If possible, the context bar legend would be better if displayed on the top of everything else, including the chart legend under the bars - if the bar-specific legend overlaps the legend under the chart, the link in the bar legend (Link >>) for the members by languages chart may be non-clickable.

**Comment by darren-bridenbeck** [comment]
It's looking like the top contributors (all time) and top contributors (30 days) also broke recently. Seeing this on several teams. Example: http://amara.org/en/teams/newshour/activity/teamstatistics/

![screen shot 2015-11-24 at 3 28 33 pm](https://cloud.githubusercontent.com/assets/5092242/11379789/4f15b402-92c0-11e5-8b11-9b31e0492885.png)

**Comment by syl22-00** [comment]
Closing because charts will be revamped.
