### ISSUE TITLE
Simple teams: private videos, subtitles visible to non-members

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2338]
Observed on staging.

Videos/subtitles from private simple team (http://staging.amara.org/en/teams/simple-team-test/) are visible to non-members:
http://staging.amara.org/en/videos/v7rUuzcEpJHI/fr
Videos added to the private team through a video feed appear in the Recent Videos list (http://staging.amara.org/en/videos/watch/latest/).

**Comment by bendk** [comment]
What user we're you using?

**Comment by PCF-Testing** [comment]
http://staging.amara.org/en/profiles/profile/%40PCFQA/

**Comment by bendk** [comment]
Deployed directly to staging.

**Comment by bendk** [comment]
I just tested this one.  That video is not visible to non-members and it doesn't show up in the search.

**Comment by PCF-Testing** [comment]
Fixed.

**Comment by PCF-Testing** [comment]
Has been deployed.
