### ISSUE TITLE
Add Mizo language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2342]
Mizo language, ISO 639 code 'lus' (https://en.wikipedia.org/wiki/Mizo_language).
Directionality - LTR.
Reason: request by TED staff (http://support.amara.org/helpdesk/tickets/80919).

**Comment by bendk** [comment]
Fixed in unilangs.

**Comment by PCF-Testing** [comment]
Looks good on staging.

**Comment by PCF-Testing** [comment]
Deployed to production.
