### ISSUE TITLE
Restore individual check-boxes for "move videos" link on teams

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#2347]
Issue: The individual check-box in the "move videos" link for a team, no longer exists.
Expected: Users should be able to select individual videos to be moved.

Link: http://amara.org/en/teams/darrentest/move-videos/ (note, impersonate darren.bridenbeck if you can't view this page)

Screenshot:
![screen shot 2015-09-16 at 11 37 02 am](https://cloud.githubusercontent.com/assets/5092242/9909779/ab282b92-5c67-11e5-8f26-b367b2befd71.png)

**Comment by bendk** [comment]
Fixed in the gh-2347 branch, but I'm not sure on where the checkbox should be placed.  Tell me if I got that wrong.

**Comment by PCF-Testing** [comment]
@bendk: not exactly where they are now - the checkbox for a video used to be placed above and left-aligned with the video thumbnail, not overlapping the thumb.

**Comment by bendk** [comment]
I just pushed a change that aligns them better.  Does it look okay now?

**Comment by PCF-Testing** [comment]
Yes, looks better on bulk videos move page, but on Applications page check-boxes are now off and overlap with the thumbnails, which are smaller than they should be: 

![applicationsbulk](https://cloud.githubusercontent.com/assets/288455/9973958/cf86a79e-5e32-11e5-82b4-7bcdcada3d56.png)

Also, on Messages Inbox page the position of the checkboxes has changed. Probably we can live with it - just FYI that they are affected by the change, too.

Other pages that use bulk actions, but seem to be unaffected so far:
- Bulk task approval
- Syncing issues

**Comment by deanjansen** [comment]
Is this ready for deployment? We've been getting more questions from teams (including On Demand) about it recently.

**Comment by bendk** [comment]
Not yet, I hope to get it deployed with the other stuff on monday though.

**Comment by bendk** [comment]
I went through the changes and think I have a nice better fix.  The following pages use the "bulkable" checkboxes:
  * Team videos
  * Applications
  * Messages

I believe all should be working correctly now.

**Comment by PCF-Testing** [comment]
Looks good to me now. Maybe on the Messages page the checkboxes are too close to the upper edge of the message, but afaik messages are going to be restyled soon anyway.

**Comment by PCF-Testing** [comment]
Deployed.
