### ISSUE TITLE
Enable users to track their past collab activity

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2348]
From PCF-Testing:

Personal activity tab in the user's profile only lists edits (new subtitle versions) made to subtitles. It does list approvals and rejections made for task-based teams, but does not include endorsements, sendbacks, or posting notes to collabs. Therefore, if a user, say, reviews and endorses subtitles without making edits, the only way to track these actions is to filter collaborations list by assignee. This needs to be done for each team where the user is a member.

We need to provide users with a better way to track their collab-related activities, ideally - in a single feed including all the teams where the user is a member.

**Comment by bendk** [comment]
I think this might be working on the collab-activity branch, although I wasn't really paying attention to it when I did the coding.  Is it working?  Are there any issues?

**Comment by PCF-Testing** [comment]
Yes, this seems to work on the branch, and the feed obeys the general privacy rules: the user can see all their activity, while other viewers can only see the entries that are related to their own teams.

I am going to close this ticket for now; in case of any specific issues in the future, they will be placed into new bite-sized tickets.
