### ISSUE TITLE
Activity model index refactor

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2349]
Right now there are a ton of places where activity queries are slow.  I think we should refactor our model to make things fast.

I think the simplest way is to make it so the user, team, and video columns are used to specify which activity listing things get place in.  So when I go to my user activity, then the where clause is `WHERE user_id=<my user-id>`.  Similarly for teams and videos.  Then we can just add a few indexes and make the queries really fast (the indexes should be also include creation date since that's the ordering we always use).

There's a couple differences that I can see between this and our current system:
  * For user activity, I think we also try to include activity from teams that the user is a part of.  I personally think we can just leave this out.
  * For team activity, we include activity from videos that are part of the team.  This has a subtle difference when a video gets moved from one team to another.  With our current system, this means the activity entries get moved from the old team's activity page to the new team's activity page.  I think it would be fine to not do this.

**Comment by bendk** [comment]
A nice side effect of this would be that there could be just 1 type of team activity again.  Not this weird split between "team activity" and "team video activity".

**Comment by deanjansen** [comment]
Here's an example of an activity page that won't load at all: http://amara.org/en/teams/captions-requested/activity/

**Comment by bendk** [comment]
This is implemented in the activity branch.  It requires a migration.  A couple notes about this one:

 - You need to run migrate to pull in the DB changes
 - The old activity won't yet show up.  I need to write a script to migrate that stuff
 - The main thing to test is that all of the activity shows up in the correct places
 - The things I implemented was:
    - activity API
    - Team activity page
    - User profile page
    - User dashboard page
    - Video activity tab
    - Video activity page ("all activity" link from the tab)
 - I believe a few activity types haven't been working and don't need to be tested.  Correct me if I'm wrong about this one:
      - title changed
      - translation added
      - subtitle request
      - version reviewed
 - Member join/leave has some quirks:
   - There's a bug with the current code around the member join action.  If you join a team, then leave, the TeamMember object gets removed, so the activity record goes to.  This is fixed with the new code
   - The member leave action only happens if you leave the team using the member tools.  If an admin removes you, we don't create an activity record for it.  I kept this behavior for the new code, I think we should add a member removed action to capture that case.

**Comment by PCF-Testing** [comment]
Hmm, both /api/activity/ and team activity pages show no entries (while Django admin list has plenty). The migrations ran with some errors; was it migrate activity that really matters for this ticket?

**Comment by bendk** [comment]
Did you do actions to create new activity?  The old activity won't show up.  I'm in the process of writing a script to convert from the old model to the new.

**Comment by bendk** [comment]
I just pushed a new version of this with the ability to migrate old activity records.  Some notes:

- I made a slight change to the database, to be safe I would recommend doing `dev migrate activity zero` then `dev migrate activity`
- To migrate the old actions, use `dev migrateactivity` (no space).
- migrateactivity should work for multiple runs.  One way to test that is:
  - switch to the activity branch, run migrateactivity
  - switch back to staging, generate some more activity
  - switch back to activity, run migrateactivity again

**Comment by PCF-Testing** [comment]
Seeing a few quirks with activity:

- [ ] API /activity/ endpoint and Django admin actions/activity lists show different activity counts - API returns total_count 424, while Dango says the activity records list has 592 entries

- [ ] User profile (/profiles/profile/username) has totally irrelevant entries, e.g. member left for a different user. The list looks very similar to the one on the dashboard (Activity in your teams). Also, IMO the user's activity looks worse without the username, since most action records start with a lowercase character and look like an incomplete sentence - not very neat. The old way (which is currently on production) looks nicer.

**Comment by bendk** [comment]
I don't think the first issue is a problem.  The activity API listing doesn't list all activity, it lists activity "for the user", which is a pretty weird result set (see #2557).  I also get different numbers on production.

The second one should be fixed with my latest commit.  I got confused trying to implement that one.

**Comment by PCF-Testing** [comment]
Checked the fix for user profile activity log locally on the branch - looks ok now.

**Comment by PCF-Testing** [comment]
Deployed.
