### ISSUE TITLE
Problem with moderation status for Ted Talk 1449 David Kelley

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#235]
Alex just reached out to us telling that English transcripts for http://www.universalsubtitles.org/videos/FQSfRWRaLwz2/ are all 'not_under_moderation' . This is what their data looks like right now (see attached)

Apparently this got into this state because the English transcript was reverted.

There is a review tasks for revision #1 that approved it, see (task.png)

I reset the moderation status to approved, but we should figure out what went wrong with this.

**Comment by PCF-Testing** [comment]
This issue seems out of date. Closing.
