### ISSUE TITLE
Get duration for vimeo videos

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2358]

**Comment by syl22-00** [comment]
Done in gh-1553

**Comment by PCF-Testing** [comment]
Should this include fetching the duration for password-protected videos? They are often used by AOD, but on gh-1553 the duration for such videos cannot be retrieved.

**Comment by PCF-Testing** [comment]
Marking this one as Waiting for deploy.

**Comment by PCF-Testing** [comment]
Deployed.
