### ISSUE TITLE
Error uploading DFXP from API that has an encoding specified

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2367]
An attempt to upload DFXP with an encoding specified results in a 500 error.

You can test this by taking any DFXP file and replicing the first line with one that has an encoding specifed like this:
```
<?xml version="1.0" encoding="UTF-8"?>
```

**Comment by PCF-Testing** [comment]
Tested locally on gh-2367.

Actually, to generate a sample file it was necessary to insert - not replace - the encoding line at the beginning of the dfxp file.

Tested with: 
- DFXP from Amara modified as described above
- XML file exported from SubtitleEdit (thanks to Fran for a sample)
- DFXP file with encoding produced by Amara OnDemand on a special order (thanks to Fran)

Upload worked nicely from the video page, from the subtitle editor, through API.

**Comment by PCF-Testing** [comment]
Deployed.

**Comment by bendk** [comment]
Looks like that fix caused issues saving subtitles.  I'm going to revert and work on a different fix.

**Comment by bendk** [comment]
When we re-test, please make sure to test non-ascii text as subtitles.

**Comment by bendk** [comment]
The gh-2367-try2 should fix both issues:

  * POSTing DFXP via the API with an XML encoding.
  * Saving subtitles in the editor with non-ascii characters.

**Comment by PCF-Testing** [comment]
Looks good with different DFXP input with and without the encoding line. Tested with emergency DFXP backup from Amara, regular DFXP downloads, DFXP with non-ascii text (Chinese, Russian, Arabic, English text with music symbols), uploading subtitles through the upload dialog, subtitle editor, and API.

**Comment by PCF-Testing** [comment]
Deployed.
