### ISSUE TITLE
SRT files mix \r\n and \n line breaks

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2370]
Same bug as #1733, which was fixed. The SRT generator in babelsubs is almost a copy of the VTT one and didn't get the fix.

This causes troubles in some text editors like TextWrangler, which we had been recommending to people that needed to perform subtitle surgery. See this thread:

https://pculture.freshdesk.com/discussions/topics/309667

With SRT being more of a legacy format I would switch it to \r\n rather than using UNIX style like on VTT.

**Comment by bendk** [comment]
Fixed in babelsubs.  This should go out with the next deploy.

**Comment by PCF-Testing** [comment]
Looks good on staging - all lines in SRT are separated with \r\n, while all lines in VTT with \n. Both formats get parsed correctly when being uploaded.

**Comment by PCF-Testing** [comment]
Deployed.
