### ISSUE TITLE
Collab teams: error when trying to edit subtitles from an unauthenticated user

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2374]
To reproduce:
  * Create a collab team, add a video, and create subtitles for that video
  * Go to the language page
  * In another window, logout
  * Refresh the language page

Here's the sentry issue:

http://logman.amara.org:9000/pcf/amara/group/2761/

**Comment by PCF-Testing** [comment]
Looks OK.

**Comment by PCF-Testing** [comment]
Deployed.
