### ISSUE TITLE
Team Videos page 404s for non-member

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2376]
Steps to reproduce:
- Open http://amara.org/en/teams/captions-requested/videos/ impersonating user maggie_s

Expected:
Allow non-members to view video lists in publicly visible old-style teams (preferred), or display a styled 403 page.

**Comment by PCF-Testing** [comment]
Confirming videos are now visible to non-members.

The two other tabs in the old-style team menu (Members and Activity) still keep 404-ing. Not too nice to users; just wondering whether it is worth the effort fixing, or it would be better to switch our existing non-task teams to Simple Team setup.

**Comment by bendk** [comment]
Okay, I made it so those tabs are visible to non-members as well now.

**Comment by PCF-Testing** [comment]
Works well for me, except that one test is broken on the branch:

ERROR: test_get_video_info_exception (videos.tests.test_video_types.YoutubeVideoTypeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/unisubs/utils/test_utils/monkeypatch.py", line 182, in wrapper
    return func(self, mock_obj, *args, **kwargs)
  File "/opt/apps/unisubs/apps/videos/tests/test_video_types.py", line 87, in test_get_video_info_exception
    'http://www.youtube.com/watch?v=_ShmidkrcY0')
  File "/opt/apps/unisubs/apps/videos/models.py", line 567, in get_or_create_for_url
    vt.set_values(obj, **kwargs)
  File "/opt/apps/unisubs/apps/videos/types/youtube.py", line 79, in set_values
    video_info = self.get_video_info()
  File "/opt/apps/unisubs/apps/videos/types/youtube.py", line 75, in get_video_info
    self._video_info = google.get_video_info(self.video_id)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1010, in _mock_call
    raise effect
APIError

**Comment by bendk** [comment]
This was a broken test in staging.  I pulled the fix from the gh-1553 branch to staging and then merged it into staging.

**Comment by PCF-Testing** [comment]
The tests now pass for me as well.

However, when I create new teams on an empty gh-2376 database after dbreset, I get 404s on Videos and Members pages for Collab and Simple teams when viewing them as the team owner (Ensemble team is OK). This is definitely a bug.

**Comment by bendk** [comment]
I think that might be a caching issue.  Try running `dev manage clear_cache`

**Comment by PCF-Testing** [comment]
Tried that - still happens, even on a just created from scratch team :(

**Comment by bendk** [comment]
Okay, this is finally fixed now.

**Comment by PCF-Testing** [comment]
Looks good now.

**Comment by PCF-Testing** [comment]
Deployed.
