### ISSUE TITLE
Do not send email notifications to owners of retired accounts

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2386]
If a user has deactivated their user account on Amara, the system would still keep sending out email notifications. Owners of deactivated accounts have should not receive notifications by email, even if they have this setting checked in their profile.

**Comment by syl22-00** [comment]
Should be done in branch gh-2386 and gh-unisubs-2386 in enterprise

**Comment by PCF-Testing** [comment]
I do not see a way to test this change properly, since at this time I cannot produce email notifications at will on production even for an active user, except for team-specific messages (which are irrelevant for a retired account - when deactivated, all team memberships get revoked).

**Comment by PCF-Testing** [comment]
This branch breaks the following test: 

======================================================================
ERROR: test_block_settings_for_team (messages.tests.TeamBlockSettingsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/unisubs/apps/messages/tests.py", line 474, in test_block_settings_for_team
    function.run(*args)
  File "/opt/apps/unisubs/apps/messages/tasks.py", line 543, in reviewed_and_published
    return _reviewed_notification(task_pk, REVIEWED_AND_PUBLISHED)
  File "/opt/apps/unisubs/apps/messages/tasks.py", line 469, in _reviewed_notification
    user = version.author
UnboundLocalError: local variable 'version' referenced before assignment

----------------------------------------------------------------------

Otherwise, the branch seems to behave in the same way as production, which does not send out email notifications to inactive users, unless it might be some very specific type of notification.

**Comment by syl22-00** [comment]
That should be fixed in the branch

**Comment by PCF-Testing** [comment]
Marking as Waiting for deploy.

**Comment by PCF-Testing** [comment]
Deployed.
