### ISSUE TITLE
Increase maximum URL length for videos on Amara

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#2394]
If there is no penalty for accepting long URL's let's use what search engines generally top out at: 2048 characters (according to this thread: http://stackoverflow.com/a/417184 ).

If the database would grow (for instance, if we would need to reserved lots of extra space for every URL that is shorter than the max), we could probably get away with 768 characters for all current users/needs.

**Comment by bendk** [comment]
Implemented in the gh-amara-enterprise-1139 branch.

**Comment by PCF-Testing** [comment]
Made PRs for both 1139 branches.

**Comment by PCF-Testing** [comment]
Deployed.
