### ISSUE TITLE
Display total duration for teams

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2398]
We should display the total duration of all videos in a team and as well as per-project.

**Comment by deanjansen** [comment]
Would be ideal if we could implement this for both old-style teams and collab teams.

**Comment by bendk** [comment]
This is mainly for amara staff and I wasn't sure how to integrate this with the current UI and also didn't want to think about old-style teams so much, so I made this an admin-only page.

You can find it by going to any team page as a staff user and looking at the links at the bottom of the page.  There's one called "Video durations" and it will take you to a page that lists all projects and the total duration for videos in that project.  The link is present for both old and new-style teams, although it looks a bit different.

**Comment by PCF-Testing** [comment]
This branch breaks one test:

======================================================================
ERROR: test_get_video_info_exception (videos.tests.test_video_types.YoutubeVideoTypeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/unisubs/utils/test_utils/monkeypatch.py", line 182, in wrapper
    return func(self, mock_obj, *args, **kwargs)
  File "/opt/apps/unisubs/apps/videos/tests/test_video_types.py", line 87, in test_get_video_info_exception
    'http://www.youtube.com/watch?v=_ShmidkrcY0')
  File "/opt/apps/unisubs/apps/videos/models.py", line 567, in get_or_create_for_url
    vt.set_values(obj, **kwargs)
  File "/opt/apps/unisubs/apps/videos/types/youtube.py", line 79, in set_values
    video_info = self.get_video_info()
  File "/opt/apps/unisubs/apps/videos/types/youtube.py", line 75, in get_video_info
    self._video_info = google.get_video_info(self.video_id)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1010, in _mock_call
    raise effect
APIError


Also, two minor UI nitpicks:
- [ ] "XX with unknown duration" IMHO sounds better than "XX without duration"
- [ ] Is it possible to force HH:MM:SS format for aggregates with HH==0 to keep the values in Total Duration column aligned (please see the screenshot below)?
![videodurationspage](https://cloud.githubusercontent.com/assets/288455/10997838/59e5a3d0-8445-11e5-8835-e224367b8fd8.png)

**Comment by syl22-00** [comment]
The broken test comes from the changes in gh-1553, I'll fix them

**Comment by syl22-00** [comment]
So the issue leading to test fail was fixed in gh-1553 and merged back into gh-2398

**Comment by bendk** [comment]
Updated that text string and right-aligned the column.  I think that should solve the issue with comparing the numbers.

**Comment by PCF-Testing** [comment]
Fixed on both counts. The duration numbers are shifted way too far to the right from the column header, but I suppose we'll just have to live with it.

However, when the number of HH exceeds 24, the hours should keep adding up, so that the total remains in HH:MM:SS format, rather than DD:HH:MM:SS.

**Comment by bendk** [comment]
I right-aligned the header as well and removed the days section.  I'm just going to directly merge this because it seems like the only issues are display issues and it's really needed for the OD team.

**Comment by PCF-Testing** [comment]
Deployed to production.
