### ISSUE TITLE
Bulk actions for videos not functioning on filtered lists

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#2405]
On a collaboration team, bulk actions to videos aren't working when there's a filter in place. They work OK when there's no filter. Tried in multiple browsers and confirmed by other users.

**Comment by PCF-Testing** [comment]
Is there a specific scenario / setup where this breaks? Filtering by title keyword + bulk edit (or removal) works for me on staging and production.

**Comment by deanjansen** [comment]
Nice catch, Maggie – I see what what you mean... I don't know how exactly the videos got into that state though.

**Comment by bendk** [comment]
Pretty sure the reason for the mismatch is the search index.  We use the solr index to select videos when you add a filter.  That index can be out of date compared to the database, especially when manual admin actions are taken on the video.
