### ISSUE TITLE
Username search should match full names

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2409]
When we search for uses, we should match against their username and also their fullnames.

I think the main things to fix are the new-style inputs, for example invite members for a new-style team or assign a user to a collab team.

Note that "full name" means a couple things:
  - Normally it means the combination of first_name/last_name fields
  - Some 3rd-party logins give us profile information, but only have a full name.  In that case it's in the full_name field.

See #2305

**Comment by PCF-Testing** [comment]
Checked on the local dev instance of the branch for the following new teams dialogs: 
- Invite new member
- Assign collab
- Appoint language coordinator
- Appoint project coordinator
Works well on all of the above.

Does not work as search input though (filter by Assigned Users on Collaborations page, search on Members page). Is this beyond the scope of the current ticket?

Also, one nitpick - while the user is typing input, the dialog is displaying both username and full name for the found matches (which is good). However, once the selection is made, only the username remains shown, so the user cannot check if the correct entry had been clicked. Can the selected value also display username (full name) pair?

**Comment by bendk** [comment]
Yeah the scope of the change is only the new-style inputs.  The old ones use a totally different system and I think it's okay to let that be for now.

I agree about the input issue, but it's not a trivial fix.  Right now the input is a simple textbox, we would have to change it to a hidden input + a DIV that gets filled in with javascript.  It's not so difficult, but I think that should be a separate ticket.

**Comment by bendk** [comment]
Oops, I just read that comment again.  I think it would be good to fix the member search and assignment search alongside this fix.

**Comment by bendk** [comment]
I just pushed a fix for the assignment filter to the amara-enterprise repo.

I believe that member search should be working for new-style teams at least.  It also matches against bio and homepage.  I thought about making the other searches match against that as well, but I didn't make the changes.  I think it makes sense for the member search to match against a wider set of criteria.  I'm not 100% sure on this one though.

**Comment by PCF-Testing** [comment]
Assignment filter seems to work fine.

Member search does not return the expected results when searching by full name (field from auth_customuser table).

**Comment by bendk** [comment]
are you using a new-style team?  I don't think it's implemented on the old ones, and I'm okay with just letting that sit like that for a while.

**Comment by PCF-Testing** [comment]
Yes, it is new style. Probably not too much of a deal as long as only AOD use the new design, but we definitely need to roll the fix out before having TED use it. Should I make a new ticket for full names in member search?

**Comment by bendk** [comment]
I keep reading your comments wrong, sorry about that!  It should be fixed in the branch now.

**Comment by PCF-Testing** [comment]
Looks good to me now.

**Comment by PCF-Testing** [comment]
Deployed.
