### ISSUE TITLE
Make the tip version on the revisions page unchecked by default

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2414]
so that users have no trouble selecting two arbitrary subtitle versions to compare (since no more than two versions can be checked at any moment of time, you cannot select and check a second version while the tip version is checked).

Request: http://support.amara.org/helpdesk/tickets/81950

**Comment by bendk** [comment]
Fixed in the revisions-page branch.

**Comment by PCF-Testing** [comment]
Confirming this is fixed.

**Comment by PCF-Testing** [comment]
Deployed.
