### ISSUE TITLE
Use full usernames for editor notes

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2419]
Right now we just use the usernames.

**Comment by PCF-Testing** [comment]
During the current editing session, the author of the recently posted note is displayed by the username. Once the editor has been closed and re-opened, during the following sessions the author is displayed by full name, as expected.

Also, cannot open the list of team collaborations on the branch:

DatabaseError at /teams/collab-test/collaborations/
(1146, "Table 'amara.collab_collaboration' doesn't exist")
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/teams/collab-test/collaborations/
Django Version:	1.4.21
Exception Type:	DatabaseError
Exception Value:	
(1146, "Table 'amara.collab_collaboration' doesn't exist")
Exception Location:	/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py in defaulterrorhandler, line 36

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/unisubs/apps/teams/new_views.py" in wrapper
  88.         return view_func(request, team, *args, **kwargs)
File "/opt/apps/unisubs/amara-enterprise/collab/views.py" in collaborations
  345.                         .select_related('video', 'subtitle_provider')
File "/opt/apps/unisubs/amara-enterprise/collab/models.py" in prefetch_assignments
  326.         for assignment in all_assignments:
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in _result_iter
  118.                 self._fill_cache()
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in _fill_cache
  892.                     self._result_cache.append(self._iter.next())
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in iterator
  291.         for row in compiler.results_iter():
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in results_iter
  763.         for rows in self.execute_sql(MULTI):
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in execute_sql
  818.         cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
  40.             return self.cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py" in execute
  114.             return self.cursor.execute(query, args)
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py" in execute
  205.             self.errorhandler(self, exc, value)
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py" in defaulterrorhandler
  36.     raise errorclass, errorvalue

Exception Type: DatabaseError at /teams/collab-test/collaborations/
Exception Value: (1146, "Table 'amara.collab_collaboration' doesn't exist")

**Comment by bendk** [comment]
@PCF-Testing Can you test this one again?  I just merged staging into it.  I don't think that this branch should cause that database issue to happen.  It looks to me like an issue caused by some of the db changes and switching between branches.

**Comment by PCF-Testing** [comment]
@bendk: yields the following error on bin/dev up:

Attaching to unisubs_worker_1, unisubs_app_1
worker_1 | INFO 2016-02-11 05:47:43,922 base 1 140565740357440 Raven is not configured (logging is disabled). Please see the documentation for more information.
worker_1 | Traceback (most recent call last):
worker_1 |   File "manage.py", line 37, in <module>
worker_1 |     startup.startup()
worker_1 |   File "/opt/apps/unisubs/startup.py", line 68, in startup
worker_1 |     run_startup_modules()
worker_1 |   File "/opt/apps/unisubs/startup.py", line 59, in run_startup_modules
worker_1 |     __import__('%s.startup' % app)
worker_1 |   File "/opt/apps/unisubs/apps/teams/startup.py", line 21, in <module>
worker_1 |     import teams.workflows.startup
worker_1 |   File "/opt/apps/unisubs/apps/teams/workflows/startup.py", line 27, in <module>
worker_1 |     from teams.workflows.old import OldTeamWorkflow
worker_1 |   File "/opt/apps/unisubs/apps/teams/workflows/old/__init__.py", line 3, in <module>
worker_1 |     from .workflow import OldTeamWorkflow
worker_1 |   File "/opt/apps/unisubs/apps/teams/workflows/old/workflow.py", line 26, in <module>
worker_1 |     from teams import views
worker_1 |   File "/opt/apps/unisubs/apps/teams/views.py", line 50, in <module>
worker_1 |     from teams.forms import (
worker_1 |   File "/opt/apps/unisubs/apps/teams/forms.py", line 133, in <module>
worker_1 |     class MoveTeamVideoForm(forms.Form):
worker_1 |   File "/opt/apps/unisubs/apps/teams/forms.py", line 136, in MoveTeamVideoForm
worker_1 |     team = forms.ModelChoiceField(queryset=Team.objects.all(),
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 116, in all
worker_1 |     return self.get_query_set()
worker_1 |   File "/opt/apps/unisubs/apps/teams/models.py", line 129, in get_query_set
worker_1 |     return TeamQuerySet(Team).filter(deleted=False)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 624, in filter
worker_1 |     return self._filter_or_exclude(False, *args, **kwargs)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 642, in _filter_or_exclude
worker_1 |     clone.query.add_q(Q(*args, **kwargs))
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1250, in add_q
worker_1 |     can_reuse=used_aliases, force_having=force_having)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1122, in add_filter
worker_1 |     process_extras=process_extras)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1304, in setup_joins
worker_1 |     field, model, direct, m2m = opts.get_field_by_name(name)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 311, in get_field_by_name
worker_1 |     cache = self.init_name_map()
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 341, in init_name_map
worker_1 |     for f, model in self.get_all_related_m2m_objects_with_model():
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 429, in get_all_related_m2m_objects_with_model
worker_1 |     cache = self._fill_related_many_to_many_cache()
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 443, in _fill_related_many_to_many_cache
worker_1 |     for klass in get_models(only_installed=False):
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 181, in get_models
worker_1 |     self._populate()
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 64, in _populate
worker_1 |     self.load_app(app_name, True)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 86, in load_app
worker_1 |     app_module = import_module(app_name)
worker_1 |   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
worker_1 |     __import__(name)
worker_1 |   File "/opt/apps/unisubs/amara-enterprise/ted/__init__.py", line 8, in <module>
worker_1 |     from thirdpartyaccounts import register_thirdpartyaccount_type
worker_1 | ImportError: cannot import name register_thirdpartyaccount_type
app_1    | INFO 2016-02-11 05:47:44,427 base 1 140014458173248 Raven is not configured (logging is disabled). Please see the documentation for more information.
app_1    | Traceback (most recent call last):
app_1    |   File "manage.py", line 37, in <module>
app_1    |     startup.startup()
app_1    |   File "/opt/apps/unisubs/startup.py", line 68, in startup
app_1    |     run_startup_modules()
app_1    |   File "/opt/apps/unisubs/startup.py", line 59, in run_startup_modules
app_1    |     __import__('%s.startup' % app)
app_1    |   File "/opt/apps/unisubs/apps/teams/startup.py", line 21, in <module>
app_1    |     import teams.workflows.startup
app_1    |   File "/opt/apps/unisubs/apps/teams/workflows/startup.py", line 27, in <module>
app_1    |     from teams.workflows.old import OldTeamWorkflow
app_1    |   File "/opt/apps/unisubs/apps/teams/workflows/old/__init__.py", line 3, in <module>
app_1    |     from .workflow import OldTeamWorkflow
app_1    |   File "/opt/apps/unisubs/apps/teams/workflows/old/workflow.py", line 26, in <module>
app_1    |     from teams import views
app_1    |   File "/opt/apps/unisubs/apps/teams/views.py", line 50, in <module>
app_1    |     from teams.forms import (
app_1    |   File "/opt/apps/unisubs/apps/teams/forms.py", line 133, in <module>
app_1    |     class MoveTeamVideoForm(forms.Form):
app_1    |   File "/opt/apps/unisubs/apps/teams/forms.py", line 136, in MoveTeamVideoForm
app_1    |     team = forms.ModelChoiceField(queryset=Team.objects.all(),
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 116, in all
app_1    |     return self.get_query_set()
app_1    |   File "/opt/apps/unisubs/apps/teams/models.py", line 129, in get_query_set
app_1    |     return TeamQuerySet(Team).filter(deleted=False)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 624, in filter
app_1    |     return self._filter_or_exclude(False, *args, **kwargs)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 642, in _filter_or_exclude
app_1    |     clone.query.add_q(Q(*args, **kwargs))
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1250, in add_q
app_1    |     can_reuse=used_aliases, force_having=force_having)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1122, in add_filter
app_1    |     process_extras=process_extras)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1304, in setup_joins
app_1    |     field, model, direct, m2m = opts.get_field_by_name(name)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 311, in get_field_by_name
app_1    |     cache = self.init_name_map()
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 341, in init_name_map
app_1    |     for f, model in self.get_all_related_m2m_objects_with_model():
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 429, in get_all_related_m2m_objects_with_model
app_1    |     cache = self._fill_related_many_to_many_cache()
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 443, in _fill_related_many_to_many_cache
app_1    |     for klass in get_models(only_installed=False):
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 181, in get_models
app_1    |     self._populate()
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 64, in _populate
app_1    |     self.load_app(app_name, True)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 86, in load_app
app_1    |     app_module = import_module(app_name)
app_1    |   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
app_1    |     __import__(name)
app_1    |   File "/opt/apps/unisubs/amara-enterprise/ted/__init__.py", line 8, in <module>
app_1    |     from thirdpartyaccounts import register_thirdpartyaccount_type
app_1    | ImportError: cannot import name register_thirdpartyaccount_type
unisubs_worker_1 exited with code 1
unisubs_app_1 exited with code 1

**Comment by bendk** [comment]
I think the merge should fix that issue.

**Comment by PCF-Testing** [comment]
This one works well for displaying older notes made during previous editor session, but breaks for the current editing session - notes made during the current session are signed by username.

Consider the case where a user (username subtitle_maker, name John Doe) creates subtitles in several editing sessions, making notes all down the road. He will see some of his notes signed as John Doe, while the latest notes will be signed as subtitle_maker. Maybe not a super biggie, but doesn't look nice; is it hard to fix?

Otherwise, the branch looks good.

**Comment by bendk** [comment]
Good catch.  I think that should work now as well.

**Comment by PCF-Testing** [comment]
Great, looks good now.

**Comment by PCF-Testing** [comment]
Deployed.
