### ISSUE TITLE
Submission of YouTube videos fails with a 500 error

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2421]
Happens on production, staging.

None of YouTube videos can be submitted to the system - an attempt to do so fails with a 500 error. The problem started after the deploy on Wed Nov 25.

On local instance of production, submission works.

**Comment by syl22-00** [comment]
It seems like the request package refuses the https requests to google:
```
./bin/dev manage shell
> import requests
> r = requests.get("https://google.com")
...
SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
> r = requests.get("https://google.com", verify=False)
... SUCCESS
> r = requests.get("http://google.com")
... SUCCESS
> r = requests.get("https://github.com")
... SUCCESS
```

On my own python environment (Python 2.7.10/requests 2.6.0), all requests succeed.

**Comment by syl22-00** [comment]
Two ways to get around the issue:

* Changing requests to google to `verify=False`
* Manually adding recent certificates from another machine running a recent up-to-date distribution
  * `scp user@machine.com:/usr/i686-pc-linux-gnu/usr/share/ca-certificates/mozilla/GeoTrust_*.crt /usr/local/share/ca-certificates/`
  * Add the certificates: `dpkg-reconfigure ca-certificates`
  * Secure requests to google can now succeed.

**Comment by PCF-Testing** [comment]
This has not been an issue for quite a while, so closing the ticket.
