### ISSUE TITLE
Disable video API listing without filters

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2426]
The video API view is slow, mostly because it needs to calculate the entire list of videos that a user can see.  This is:
  - non-team videos
  - team videos on public teams
  - team videos on teams the user is a member of

This creates a pretty nasty SQL query.  We should try to optimize it.  What about this system:

 - Add a team_id index on the video table.  Make it match the value on TeamVideo (or NULL if there is no team video).
- Create an index on (videos_video.team_id, created)
- Sort by videos (team_id, created).  This makes allows us to use the index.  It means that videos will be grouped by team in that list for amara users.  That seems okay to me though.

**Comment by bendk** [comment]
We would also probably need to remove the order_by parameter and force this order.

**Comment by bendk** [comment]
Another option is to simple not allow browsing the video API index without any filters (AKA by team, video_url).  I don't really know if there's a use case for this.

**Comment by bendk** [comment]
Fixed in the gh-2426 branch, I decided not to return an error result but instead return 0 videos.

**Comment by PCF-Testing** [comment]
Tested on a local instance. A user can view a particular public video by video_url, the list of videos in a public team, the list of videos in their own private team.

The following call:

GET http://unisubs.example.com:8000/api2/ted/videos/?format=json
returns
{"error_message": "Unknown video id", "traceback": "Traceback (most recent call last):\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 192, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 397, in dispatch_list\n    return self.dispatch('list', request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 427, in dispatch\n    response = method(request, **kwargs)\n\n  File \"/opt/apps/unisubs/amara-enterprise/apiv2/api.py\", line 289, in get_list\n    to_be_serialized['objects'] = [self.full_dehydrate(bundle) for bundle in bundles]\n\n  File \"/opt/apps/unisubs/amara-enterprise/apiv2/api.py\", line 606, in full_dehydrate\n    bundle = super(VideoResource, self).full_dehydrate(bundle)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 660, in full_dehydrate\n    bundle.data[field_name] = method(bundle)\n\n  File \"/opt/apps/unisubs/amara-enterprise/apiv2/api.py\", line 570, in dehydrate_id\n    value = bundle.obj and self.from_internal_video_id(None, video=bundle.obj)\n\n  File \"/opt/apps/unisubs/amara-enterprise/ted/api.py\", line 123, in from_internal_video_id\n    return  YoutubeVideoType._get_video_id(video_url)\n\n  File \"/opt/apps/unisubs/apps/videos/types/youtube.py\", line 105, in _get_video_id\n    raise ValueError(\"Unknown video id\")\n\nValueError: Unknown video id\n"}
while on production a similar call returns a valid list of videos.

**Comment by bendk** [comment]
I didn't touch the code for the TED API.  I think this is just some weirdness with the dev environment and that code.  If that's the only problem, I would consider this fixed.

**Comment by bendk** [comment]
Didn't hear any concerns on the dev call, just opened a PR for this one.

**Comment by PCF-Testing** [comment]
Deployed.
