### ISSUE TITLE
Don't allow public access to the team activity tab

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2427]
This can be slow for some teams and I don't think there's a big use case for people to view it.  Most of the recent activity has been web crawlers.

**Comment by PCF-Testing** [comment]
One test is broken on this branch:

======================================================================
FAIL: test_all_views (teams.tests.test_teams.TeamsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/unisubs/apps/teams/tests/test_teams.py", line 802, in test_all_views
    self.assertTrue(team.is_member(self.user))
AssertionError: False is not True
-------------------- >> begin captured stdout << ---------------------
Indexing 0 team videos.
Indexing 0 videos.

Other than that, the fix seems to be OK.

**Comment by bendk** [comment]
I "fixed" the test by simply removing it.  No concerns with this one on the dev call, so I'm opening a PR.

**Comment by PCF-Testing** [comment]
Deployed.
