### ISSUE TITLE
Handle collaborations when videos get moved

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2428]
Right now we handle it like this:
- If they're moved to another collab team, then we set the work team to that team
- If they're moved to a non-collab team then we delete them

I have no idea why we choose that logic, both parts seem wrong to me.  I think instead we should just not touch the collaborations.  If an admin wants to move them they can, if not then it's just normal business for a video to be in one team but the collaborations are being worked on by another.

Note that if you move the videos to an old-style team, then the collaborations will still be present in the DB, but the workflow will follow the old-style rules like tasks or whatever.  If you move the videos to a simple team though, then the collaborations will still be active.  In any case, we will still have the data in the DB which is very useful.

**Comment by PCF-Testing** [comment]
The idea behind killing the collaborations was the same as behind deleting all tasks and publishing all subtitles when moving videos between teams - to avoid potential conflicts. Suppose we move a video from a collab to a no-collab (or old style) team, and both the collaborators from the old team and the team members (or task assignees) from the new team will attempt to simultaneously work on these subtitles, are we going to allow this? If yes, how will the permission to edit and subtitle lock be handled? This needs careful thinking before implementation. As for the collaboration history, it should be preserved in the collab activity feed.

**Comment by bendk** [comment]
The new workflow system handles this pretty well.  The team type determines what we use to check permissions, so if you move the collabs to an old-style or simple team, then the collaborations won't affect things anymore.  If you moved it back to a collab team, then they would again, but I don't think that's the worst behavior.

I forgot about the collab history and I'm also now remembering that survives the collaboration being deleted.  Still, I think it's always nice to keep as much data around as possible.

**Comment by bendk** [comment]
Thinking about this one now I'm not really sure what the correct behavior is.  I just posted this ticket to the on-demand channel asking them what they would like it to be.  I think we should go with whatever they want.

**Comment by kslottow** [comment]
this seems old but @bendk please reopen if it's still needed
