### ISSUE TITLE
Tasks: users must not be able to review their own subtitles

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2429]
No user except team owner should be able to review their own subtitles. This currently breaks on production.

Steps to reproduce:
1. Sign in as a TED user.
2. Pick a translation task, fill out the subtitle cells, submit task.
3. In the browser, go back (ALT+Left Arrow) to the editor. If you do not see the subtitles and Approve | Send Back  buttons, refresh the page.
4. Click Approve button. This will submit the review task and create the approval task.

Expected: when trying to go back after submitting the transcription or translation task, user (except team owner) should see the error message saying they have no permission to work on the subtitles.

Issue reported: http://support.amara.org/helpdesk/tickets/82177

**Comment by PCF-Testing** [comment]
Pretty sure we have had a similar issue in the past, and this is a regression.

**Comment by PCF-Testing** [comment]
Bouncing up - yet another report including several incidents.

**Comment by bendk** [comment]
I think this should be fixed in the branch.  Note: I think we want to allow team admins/owners to review their own work.

**Comment by PCF-Testing** [comment]
On the branch, I get a 403 Forbidden or 400 Bad Request when trying to submit own subtitles for review. UI-wise, the user attempting to go back sees a translation-stage subtitle editor and gets a styled saving error when trying to complete the task.

It is not very nice that users are allowed to go back to the editor after completion the task at all - would be better if the permission check happened on navigating back in the browser - but if this is not technically possible, we'll probably have to live with it until the tasks are gone.

**Comment by bendk** [comment]
Good point about that one.  I think it could be an issue with collab teams as well, depending on how the UI works.  In general, I think we should force a reload and I made #2530 for that.

**Comment by PCF-Testing** [comment]
Deployed.
