### ISSUE TITLE
Remove email friend link

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2433]
We removed the page since it allowed anyone to send an email anywhere.  We should also remove the icon link to it from the videos page.

**Comment by bendk** [comment]
I just pushed this one straight to staging as well.

**Comment by PCF-Testing** [comment]
The icon is still on staging, but clicking it invokes a 404 page.

**Comment by bendk** [comment]
Looks like the deploy was earlier than the commit.  I'm re-deploying now.

**Comment by PCF-Testing** [comment]
The icon is gone now, too.

**Comment by PCF-Testing** [comment]
Deployed to production.
