### ISSUE TITLE
Allow "Origin Team Project" filter for collaborations

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#2440]
Enable user to filter on "Originating Team Project" – text field for project slug. This would allow an user to see collaborations on a team sorted by the project they are in on the originating (aka client) team. 

Might look something like this:

![screen shot 2015-12-17 at 3 45 45 pm](https://cloud.githubusercontent.com/assets/216145/11881546/831f0d94-a4d5-11e5-99e9-bf752a0f589f.png)

**Comment by bendk** [comment]
Fixed in the gh-unisubs-2440 branch in amara-enterprise

**Comment by PCF-Testing** [comment]
This works as an exact match (entering part of the slug won't produce any valid search results), and the unit tests all pass, so making a PR for this one.

**Comment by PCF-Testing** [comment]
Deployed.
