### ISSUE TITLE
Add Mauritian Creole language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2442]
Mauritian Creole: https://en.wikipedia.org/wiki/Mauritian_Creole
ISO 639 code: mfe
Directionality: LTR

Reason: request by TED staff (http://support.amara.org/helpdesk/tickets/82438)

**Comment by bendk** [comment]
I updated unilangs and deployed staging.amara.org.  I think it's all ready to go, but could you double check it @PCF-Testing?

**Comment by PCF-Testing** [comment]
Deployed.
