### ISSUE TITLE
Cannot change reference language in Chromium on Ubuntu

### ISSUE THREAD

**Issue by olexiy-logvinov** [pculture/unisubs#2443]
**Summary**: Reference language does not change when I choose different languages in drop-down menu.
**Subtitle editor**: NEW
**Steps to reproduce**:  Click the drop-down menu and then click on a language.
**Expected result**: subtitles change to chosen reference language
**Actual result**: I still see original language.
**OS**: Ubuntu 14.04
**Browser**: Chromium - Version 47.0.2526.73
**Browser extensions**: Adblock Plus.

![amara_reference_language_selection](https://cloud.githubusercontent.com/assets/3581695/12033583/2abddc6e-ae2d-11e5-98c2-4b3895460b98.png)

**Comment by PCF-Testing** [comment]
Confirming that the reference language would not change.

System:
Ubuntu 14.04
Chromium 47
Flash Player - adobe-flashplugin (https://wiki.ubuntu.com/Chromium/Getting-Partner-Flash)
JS console:
![referencelanguageerrorchromiumjsconsole](https://cloud.githubusercontent.com/assets/288455/12411337/a5ecaa04-be32-11e5-8a17-a44f765b35d3.png)

**Comment by bendk** [comment]
It's working for me on ubuntu 14.04 with chromium 48.  Is it still happening for you?

**Comment by olexiy-logvinov** [comment]
yes, it works now.

**Comment by PCF-Testing** [comment]
Seems to be a problem with Chromium 47. Updating to version 48 solved it for me, too.
