### ISSUE TITLE
Allow getting latest private subtitles from the endpoint

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2448]
Right now the subtitles endpoints has 2 options:
  - By default we return the latest public version
  - You can specify `version=[number]` to get a specific version

I think you should also be able to specify `version=last` to get the latest private version (of course we should still do the access checks on this).

**Comment by PCF-Testing** [comment]
@bendk: is the fix on branch 2448? (Does not work on staging as described in the ticket ) If yes, could the latest changes please be merged into the branch? Thanks!

**Comment by bendk** [comment]
Just merged staging

**Comment by PCF-Testing** [comment]
Looks good.

**Comment by PCF-Testing** [comment]
This will probably also need to get documented in API guide.

**Comment by bendk** [comment]
I just added the note the the docstrings in staging.  I think it should automatically get updated on readthedocs soon.

**Comment by PCF-Testing** [comment]
Deployed.
