### ISSUE TITLE
Make notifications about new videos added to teams more frequent

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#245]
Paid captioning services (in particular, PoP) will need to be notified more often about new videos added to their team.

Ideally, the frequency should be configurable for each team (not necessarily via the UI--admin pages should suffice), with the default option still set to once a day, but changeable to some reasonable maximum (say, 12 or 24 times a day).

**Comment by PCF-Testing** [comment]
We now have daily/hourly notification interval configurable for teams. Closing.
