### ISSUE TITLE
Account deletion does not remove all external login methods

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2450]
Account deletion marks users and inactive, takes them out of teams and removes openid links but does not delete third party accounts.

**Comment by syl22-00** [comment]
Done in branch gh-enterprise-511

**Comment by PCF-Testing** [comment]
Actually what we do when an account is deactivated is releasing the third-party authentication token, so that it can be used to create another user account on Amara.

**Comment by PCF-Testing** [comment]
New user account policy changes have been deployed. Marking as closed.
