### ISSUE TITLE
/usr/bin/python: can't open file 'manage.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by tuanbs** [pculture/unisubs#2453]
Hi, I'm at step 4: "bin/dev up" but got the following issue:
"
Creating unisubs20160121_cache_1
Creating unisubs20160121_queue_1
Creating unisubs20160121_db_1
Creating unisubs20160121_worker_1
Creating unisubs20160121_app_1
Attaching to unisubs20160121_worker_1, unisubs20160121_app_1
worker_1 | /usr/bin/python: can't open file 'manage.py': [Errno 2] No such file or directory
unisubs20160121_worker_1 exited with code 2
app_1    | /usr/bin/python: can't open file 'manage.py': [Errno 2] No such file or directory
unisubs20160121_app_1 exited with code 2
"

I guest the command: "bin/dev up" wants to execute file manage.py which does not exist in folder bin/dev. Another weird thing I notice is that after running step 3: "bin/dev build" successfully, there's no new files generated in folder bin/dev. By the way, at step 3 I faced the issue of "Setting up ca-certificates-java" hanging which I solved it using "overlay" machine thanks to this topic: "https://github.com/docker/docker/issues/18180". Could anyone please help me to fix this issue? Thank you.

**Comment by bendk** [comment]
That command runs `docker-compose up`, which in turn runs a bunch of docker containers.  Those containers expect manage.py to be in /opt/apps/unisubs/ and it should get put there with the bind-mound specified in the docker-compose file.

I'm not sure why it's not working for you.  The overlay driver could be an issue, although I'm not sure why it would be.

Can you try running `bin/dev bash`?  Does that command work?  What happens if you then run `ls /opt/apps/unisubs/`

**Comment by tuanbs** [comment]
Hi, I downgraded the docker version from 1.9.1 to 1.9.0 which fixed the issue of "Setting up ca-certificates-java", so I don't need to use the "overlay" driver anymore. But still cannot run through step 4.
I followed your instruction: the command "bin/dev bash" works fine and the "ls /opt/apps/unisubs/" returns "docker-dev".

**Comment by bendk** [comment]
There should be a lot more files there, in fact the entire repository should be there.  I think we've identified the issue, but I'm no sure what's causing it.

**Comment by tuanbs** [comment]
Is there a workaround for this issue? Like how to copy the entire repository there manually?

**Comment by bendk** [comment]
That's what the volumes part of the docker-compose file should do.  You'd need to figure out why that isn't working.  You can also try using docker run with bind-mounting a volume (e.g -v /path/to/unisubs:/opt/apps/unisubs) and see if that works.

**Comment by tuanbs** [comment]
Ok. I'll try to figure it out. Thanks for your time.

**Comment by NamPNQ** [comment]
What is result of command
`docker-compose exec app ls /opt/apps/unisubs/`
Try run with latest docker and docker-compose version

**Comment by tuanbs** [comment]
Sorry but I switched to using Subtitle Edit tool instead of UniSub. Please close this issue. Thanks.
