### ISSUE TITLE
Wrong help link in Connect to YouTube popup

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2454]
In "Enable Crowd Subtitles on your Personal YouTube Channel" popup: 

- [x] Learn More link points to http://support.universalsubtitles.org/solution/articles/40227-syncing-to-youtube, which 404s. Should be https://support.amara.org/support/solutions/articles/40227-syncing-to-youtube instead.

- [x] "We automatically add your YouTube videos to Amara (and import their
subtitles)." should read "We automatically add your public and unlisted YouTube videos to Amara
(and import their subtitles)."

**Comment by PCF-Testing** [comment]
Could be fixed together with https://github.com/pculture/unisubs/issues/1237.

**Comment by bendk** [comment]
I updated that HTML.  Should we actually be importing unlisted videos to amara?  Seems like this isn't good behavior to me.  We should probably use a different issue to track that though.

**Comment by PCF-Testing** [comment]
I don't see any problem with importing unlisted videos so far as: A. Users know about this, and B. A privacy option exists that prevents videos from being automatically imported - private YouTube videos are skipped during import.

If you wish, we could make importing unlisted videos optional, adding "Import unlisted videos" checkbox to the pop-up. If it is left blank by default, pulling in unlisted videos won't happen accidentally, but can be easily done on purpose by disconnecting the channel, marking the checkbox and reconnecting the channel. If you like this idea, we could add it to https://github.com/pculture/unisubs/issues/2456 or place it into a separate ticket.

**Comment by bendk** [comment]
Ahh, I didn't realize that youtube offered both private and unlisted.  I think a checkbox would be ideal, but I'm think the current situation is fine.

**Comment by PCF-Testing** [comment]
Deployed.
