### ISSUE TITLE
Don't show private teams on a user's profile page

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2461]
We should only show public teams on a user's profile page.

Couple UI questions:
  - I think we should show all teams if the user themselves are viewing
  - If another user is viewing:
     - Should we show private teams that that user is a member of?
     - Should we have a note saying the user may be a part of more teams?

**Comment by deanjansen** [comment]
If I'm looking at my own profile, it'd be nice to see something like:

- Team name 1 (private)
- Team name 2
- Team name 3 (private)

Note: If we can make the (private) tag a bit lighter text, that'd make it clear it's not part of the team name.

If it doesn't add much time or complexity (I suspect it might?), if I'm looking at a fellow team member's profile and we can show private teams where we are both members, that'd be nice too.

Probably OK if we do not note that an user may be part of more teams.

**Comment by bendk** [comment]
I just made (private) be regular text instead of part of the link.  I think that distinguishes it enough without having to mess with the CSS.

**Comment by bendk** [comment]
Merged.

**Comment by PCF-Testing** [comment]
Looks good.

**Comment by PCF-Testing** [comment]
Deployed.
