### ISSUE TITLE
Exception when importing subtitles for a collab team

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2462]
I saw the following exception.  Pretty sure it's because we're trying to access self.collaboration.settings, sub self.collaboration is None.  I think we should get the settings from the team that owns the video in this case.

```
Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "/opt/apps/unisubs/apps/externalsites/subfetch.py", line 44, in fetch_subs
    fetch_subs_youtube(video_url)
  File "/opt/apps/unisubs/apps/externalsites/subfetch.py", line 73, in fetch_subs_youtube
    origin=ORIGIN_IMPORTED)
  File "/opt/apps/unisubs/apps/subtitles/pipeline.py", line 533, in add_subtitles
    complete, action)
  File "/opt/apps/unisubs/apps/subtitles/pipeline.py", line 564, in _calc_action_for_add_subtitles
    complete)
  File "/opt/apps/unisubs/apps/subtitles/workflows.py", line 368, in action_for_add_subtitles
    .action_for_add_subtitles(user, complete))
  File "/opt/apps/unisubs/amara-enterprise/collab/subtitle_workflow.py", line 382, in action_for_add_subtitles
    return NonCollabSaveDraft(language, self.collaboration.settings)
AttributeError: 'NoneType' object has no attribute 'settings'
```

**Comment by bendk** [comment]
When we fix this, we should fix a related issue which is what to do if there is a collab for that language.  I think in that case, we shouldn't import the subtitles.  Right now I think we sort-of do that, but that's because we throw an exception.

**Comment by bendk** [comment]
I think there was a race condition here.  It would often work because the code to import the subtitles was running before the video was added to the team.  The easiest way to force it to happen is to run the app separately with `docker-compose up app`, then add the video to the collab team, then start the worker with `docker-compose up worker`

**Comment by bendk** [comment]
I pushed the fix directly to master since it was a very small change to the code.  I made #2469 to cover the issue if there is a collaboration in a general way.

**Comment by PCF-Testing** [comment]
@bendk: what do you mean by "importing subtitles for a collab team" - could you please describe the scenario where that exception happened?

**Comment by bendk** [comment]
It happens when there's a team video on a collab team and we import subtitles into it.  The tricky thing is there's a race condition between us adding the video to the team and the import process.

The easiest way to reproduce the bug is to run the app separately with docker-compose up app, add the video to the collab team, then start the worker with docker-compose up worker

**Comment by PCF-Testing** [comment]
OK, here's what I did (locally on the latest staging+master):
- Ran docker-compose up app
- Linked a YouTube channel to a collaboration team
- Added a subtitled video from the channel to the team (subtitles were not imported from the channel)
- Ran docker-compose up worker. Both subtitle languages were imported from YT at this point and marked as incomplete, drafts. No exception appeared in the logs (except from unrelated ones, regarding a denied permission to access video thumbnail images in the media folders).
Is that the correct scenario? Does it verify the ticket?

**Comment by bendk** [comment]
Seems good to me.

**Comment by PCF-Testing** [comment]
Marking as Waiting for Deploy.

**Comment by PCF-Testing** [comment]
Deployed.
