### ISSUE TITLE
Typos in Your videos were imported! email

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2463]
Email message sent after videos from a feed have been successfully added to the team contains typos:

> Hi, 3 your videos were successfull imported!
> Too see them, you can go to your user page
> 
> If you believe you've received this message in error, we apologize—feel free to ignore it. If you have any concerns, please contact us at feedback@universalsubtitles.org.
> 
> Thanks, 
> The Amara team

Should read:

> Hi, your 3 videos were successfully imported!
> To see them, you can go to the Videos tab in your user profile.
> 
> If you believe you've received this message in error, we apologize—feel free to ignore it. If you have any concerns, please contact us at feedback@amara.org.
> 
> Thanks, 
> The Amara team

**Comment by bendk** [comment]
Just pushed a fix to staging for these issues:
  - "Successfull" -> "Successfully"
  - "Too" -> "To"
  - "feedback@universalsubtitles.org" -> "feedback@amara.org"

Did I miss any?

**Comment by PCF-Testing** [comment]
Does "22 your videos were successfully imported" sound good? I thought it ought to be "Your 22 videos... (etc.)", but if this sounds fine as is, we can close this ticket.

**Comment by bendk** [comment]
I fixed the template for that.  It should also handle pluralization correctly now.

How is this template getting used anymore?  I don't think we send it for team feeds, only user feeds.  As far as I know there's no UI to create user feeds anymore.  I needed to use the django admin to create it.

**Comment by PCF-Testing** [comment]
@bendk: Video feeds feature in new teams UI, on /settings/feeds/.

The fix is verified.

**Comment by bendk** [comment]
Hmm, I think that may actually be a bug.  That form sets both the team and user field which I think is incorrect.  It leads to videos being added to the team, but the email being sent to the user.  Is that what happens with old-style teams?  If not, I think we should open a new issue to fix that behavior.

**Comment by PCF-Testing** [comment]
In tests, it sends a notification to the admin who added the feed and requested the import, which IMO makes sense. It behaves in a similar way in old style teams.

**Comment by bendk** [comment]
Ahh okay, fair enough.  I just deployed the fix this morning.
