### ISSUE TITLE
Downloading subtitles broken for videos with non-ascii titles

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2473]
Example: 
http://www.amara.org/en/videos/lqfPykxqZMw2/ru/205240/
http://www.amara.org/en/subtitles/lqfPykxqZMw2/ru/1/download/%D0%9E%D0%B1%D1%8A%D1%8F%D1%81%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BD%D0%B5%D1%80%D0%B0%D0%B2%D0%B5%D0%BD%D1%81%D1%82%D0%B2%20%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B0%201.ru.srt
Possibly caused by the infrastructure changes.

**Comment by bendk** [comment]
Looks like it was an issue with us trying to log the request.  Deploying a fix right now.

**Comment by PCF-Testing** [comment]
Fixed. Closing the issue.
