### ISSUE TITLE
404 errors when building image

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2482]
Not very sure why but it seems like we need to adjust the URLs in `/etc/apt/sources.list`.

**Comment by PCF-Testing** [comment]
This change solved the issue for me on two Ubuntu Trusty machines. Marking as Waiting for Deploy.

**Comment by bendk** [comment]
Sylvain says that this got fixed on its own without the change.  I think it was a temorary internet issue (DNS?).
