### ISSUE TITLE
Saving subtitles in Microsoft Edge errors out

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2484]
When a user attempts to save subtitles in MS Edge (the new Web browser in Windows 10), a standard subtitle saving error is displayed:

![erroronsavingsubtitlesmsedge](https://cloud.githubusercontent.com/assets/288455/13212780/ac9993c2-d8f8-11e5-9204-bbf534d64711.PNG)

The downloaded DFXP subtitles have the head section Amara cannot parse, so uploading subtitles from a backup results in an error - please see https://gist.github.com/PCF-Testing/596fff14f3ab366e36db for a sample DFXP backup.

**Comment by syl22-00** [comment]
There seem to be other issues with Edge:

* MP4 videos do not play
* Embedder menu does not load

**Comment by syl22-00** [comment]
This should be fixed now. Also in the same branch, there is a fix for an issue where exiting editor did not work.

**Comment by PCF-Testing** [comment]
Looks good, including playing MP4 from S3.

**Comment by PCF-Testing** [comment]
Deployed.
