### ISSUE TITLE
Have oauth logins for partners go to the partner team page

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#249]
When someone logs in via TED or Coursera oauth, it currently lands the person on amara.org front page. Coursera has requested that the login link land the person on their team page, since it's tough to find Coursera's team page, otherwise. 

I'm pretty sure TED would also appreciate this.

Note: I don't think we should do it with Google.

**Comment by PCF-Testing** [comment]
Works as described for TED. Coursera oauth is no longer in use. Closing.
