### ISSUE TITLE
Add Lushotseed language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2492]
ISO 639 code "lut"
https://en.wikipedia.org/wiki/Lushootseed_language
Reason: https://pculture.freshdesk.com/helpdesk/tickets/83581

**Comment by bendk** [comment]
I'm going to deploy staging now.  It should pick up the new language.

**Comment by PCF-Testing** [comment]
Not seeing it on staging - was it deployed?

**Comment by PCF-Testing** [comment]
Works now.

**Comment by PCF-Testing** [comment]
Deployed.
