### ISSUE TITLE
Allow users to tie notes to a particular line.

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2494]
I think it would work nicely if we added a link to the subtitle helper overlay to add a note.

![add-note](https://f.cloud.github.com/assets/299270/1919899/67ae36aa-7ddd-11e3-9995-a8d85e303e81.png)

Clicking that would grab the sub lines start time and bring the Notes to the forefront and allow the user to add the note text.  

The note would be added referencing the subtitles start time.

[janet]() Wed Jan 15 2014 06:01am
[00:01.00]() This line is wrong, please correct it.

Then clicking on the time in notes sidebar would take you to the sub line with the nearest start time. (And I'm saying nearest here because obviously subs can be resync and the exact start time may no longer be there, but if we can get the user close, hopefully they'll know what the problem is.

**Comment by deanjansen** [comment]
Don't we already enable this via the little icon menu for each subtitle line? Or is this just another way to accomplish it?

**Comment by PCF-Testing** [comment]
Yes, we already have this option implemented as_ Start note for current time _item in the cell menu (https://support.amara.org/support/solutions/articles/210102-subtitle-cell).
