### ISSUE TITLE
Add inline documentation to browsable API endpoints

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2497]
We should document our API inside the webpages that we serve when they're viewed in the browser.  Currently the only example is from amara-enterprise (http://amara.org/api/providers/queue/).  We should extend this to all API endpoitns.

**Comment by bendk** [comment]
This is implemented in the api-work branch.  You should be able to see the documentation by simply going to any public API endpoint.  I also update the readthedocs documentation, by removing documentation for specific endpoints and linking to the api urls.  readthedocs still has general documentation, like what auth headers to send, etc.  I also fixed the readthedocs build in that branch.  You can see it here: http://amara.readthedocs.org/en/api-work/

**Comment by PCF-Testing** [comment]
This looks very nice and handy in general, but leaves me wondering how will other endpoints - such as Team Members, Applications, Messages, etc. - be documented.

One more thing that can raise questions is visibility of teams lists with some team configuration details (including those for private teams) to general users - is that OK? Also, API Teams page has a form for POSTing a new team - it returns a 403, as expected, but should it be there at all in first place?

**Comment by bendk** [comment]
I think all of those team-related endpoints are documented, you should be able to follow the link from a team endpoint to view them.

I'm not sure about the visibility of team fields, that's a good point.  I think it's out of the scope of this issue though, can you make a separate ticket for it?

Users with is_partner set can POST to create teams, I think that's there for udacity and other partners that want to be able to create subteams.

**Comment by PCF-Testing** [comment]
- [ ] /api/message/ is not documented and not cross-linked anywhere in new API browser

- [ ] The way parameters for /api/activity/ are documented seems confusing:

Current documentation in api-work branch:
**video-id video**: Show only items related to a given video
**integer type**: Show only items with a given activity type (see below for values)
**language-code language**: Show only items with a given language
**integer before**: A unix timestamp in seconds

should become:

**video**: Show only items related to the video with the specified video ID
**type** (integer): Show only items with a given activity type (see the list of available values below)
**language**: Show only items with a given language code
**before** (integer): A unix timestamp in seconds

etc.

**Comment by bendk** [comment]
The top 2 should be fixed in the api-work branch.

For the 3rd, I just added the team member documentation to the safe team member reasource.  I would have liked to cross-link, but that's tricky because the team member resource depends on the team slug, so you would have to make some sort of dynamic documentation.

**Comment by PCF-Testing** [comment]
Deployed.
