### ISSUE TITLE
More links between API endpoints

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2498]
We should add more links between our API endpoints to allow users to easily navigate between them (AKA HATEOAS).  Some ones I think would be nice:

- from the video resource link to the languages list and the urls list (not just individual languages/urls)
- from video-language resource, link to the subtitles resource
- when we list versions on the video-language page, link to the user resource for the author
- Backlinks:
  - video-language -> video
  - subtitles -> video-language

**Comment by bendk** [comment]
This is implemented in the api-work branch.  In addition to the links above, I also added a bunch of links from the team endpoint to the various sub-resources (members, applications, tasks, etc).

I didn't implement the backlinks.  I'm not sure if they're really needed.

**Comment by PCF-Testing** [comment]
This one looks good. However, /api/message/ does not seem to be linked anywhere.

**Comment by bendk** [comment]
Just pushed a fix for that.

**Comment by PCF-Testing** [comment]
Deployed.
