### ISSUE TITLE
Move Videos page does not display video titles

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2511]
Observed on production - please see the attached screenshot. Regression.

![movevideospagehasnotitles](https://cloud.githubusercontent.com/assets/288455/14106341/4694da62-f565-11e5-890f-8ba2e03b0fcc.png)

**Comment by PCF-Testing** [comment]
Just a reminder that this one needs to be fixed.

**Comment by syl22-00** [comment]
Fixed in branch gh-2511

**Comment by PCF-Testing** [comment]
Looks fine.

**Comment by PCF-Testing** [comment]
Deployed.
