### ISSUE TITLE
Language bar caching issues

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2518]
Seems like there's a couple of issues here:

- Deleting a language doesn't result in the language being removed from the list
- We don't separated cached versions by user language, so you sometimes see the list in the wrong language

**Comment by bendk** [comment]
I couldn't reproduce the issue with deleting a language, but the other issue is fixed in the branch.

**Comment by PCF-Testing** [comment]
1. I've been able to reproduce the language deletion issue locally on the branch as follows:
- Submitted a standalone (non-team) video and added subtitles in a bunch of languages (about 7-9).
- In a different Web browser viewed that video as a different user
- Opened one of the languages (Italian) in Django admin and deleted it
- From the Italian language page, clicked the title of the video and got to the main video page which still had Italian in the languages panel. Clicking the link produced the following exception:
AttributeError at /videos/in0xF5X8IXEH/it/50/
'NoneType' object has no attribute 'language_code'
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/videos/in0xF5X8IXEH/it/50/
Django Version:	1.4.21
Exception Type:	AttributeError
Exception Value:	
'NoneType' object has no attribute 'language_code'
Exception Location:	/opt/apps/amara/apps/videos/views.py in _get_language, line 483
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/apps/videos/decorators.py" in wrapper
  42.         return func(request, video, *args, **kwargs)
File "/opt/apps/amara/apps/videos/views.py" in language_subtitles
  626.     context = ContextClass(request, video, lang, lang_id, version_id)
File "/opt/apps/amara/apps/videos/views.py" in __init__
  458.         language = self._get_language(video, lang_code, lang_id)
File "/opt/apps/amara/apps/videos/views.py" in _get_language
  483.         if language.language_code != lang_code:

Exception Type: AttributeError at /videos/in0xF5X8IXEH/it/50/
Exception Value: 'NoneType' object has no attribute 'language_code'

2. On the branch, I see that all languages are listed in English, regardless of the selected UI language - is it the intended change?

3. Spotted language mixup when switching between UI languages. Example: viewed a video page in EN, then switched to TH, then to ZH-CN. While opening the user menu, noticed Thai text in it:
![cachinglanguagemix](https://cloud.githubusercontent.com/assets/288455/14982764/77023f48-10ed-11e6-943a-f44904ac8f48.png)

**Comment by bendk** [comment]
- Fixed the language list after deleting a language
- Made it so the language list names get translated
- Fixed the user menu when switching languages

**Comment by bendk** [comment]
I think that covers everything, tell me if there's more to do.

**Comment by PCF-Testing** [comment]
Verified locally.

**Comment by PCF-Testing** [comment]
Deployed.
