### ISSUE TITLE
User-defined messages are not always correctly displayed in emails

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2520]
New lines entered in text boxes do not translate in new lines in HTML

**Comment by syl22-00** [comment]
In branch gh-2520, each line in from inputs in text box becomes a paragraph in HTML

**Comment by PCF-Testing** [comment]
Making a PR for this fix.

**Comment by PCF-Testing** [comment]
Deployed.

**Comment by syl22-00** [comment]
Actually as Ben mentionned, there is a bette way to do that, which I implemented in branch gh-2520-retry

I do not think the original PR (https://github.com/pculture/unisubs/pull/2538) was merged, the solution in this new branch is probably better.

**Comment by bendk** [comment]
One last nit with the gh-2520-retry branch is that if you use the linebreaksfilter, I don't think you should put things in a `<p>` tag since the filter will add the tags itself.

**Comment by PCF-Testing** [comment]
Verified on staging branch, looks really neat!

**Comment by PCF-Testing** [comment]
Deployed.
