### ISSUE TITLE
Chinese Language Code Discrepancy between YouTube and Amara

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#2525]
There's a discrepancy between Amara and YouTube language codes for Chinese, which is resulting in some unexpected issues when Chinese subtitles sync to YouTube.

Amara's language codes for Chinese Simplified is zh-cn, and Chinese Traditional is zh-tw On YouTube, the codes are zh-Hans and zh-Hant, respectively.

**Comment by bendk** [comment]
I actually made this one myself: #2523
