### ISSUE TITLE
Task list API doesn't handle delete correctly

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2527]
If you delete a task via the normal UI, we don't actually delete it from the database, we just set the deleted flag.  There are 2 related issues with the tasks API with this:

 - If you delete via the normal team UI, the task still appears on the task list
 - If you delete via the tasks API, then we delete from the database rather than keep the task and set the deleted flag

**Comment by bendk** [comment]
I'm going to deploy this one directly because we want to fix it quick for our partner.  I'm going to move it to the testing pipeline since it should still be tested.  If it looks okay, then just close the ticket.

**Comment by PCF-Testing** [comment]
Checked on production - works as described on both counts.
