### ISSUE TITLE
Task Detail API Endpoint can cause tasks to be complete

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2528]
If you hit the details API endpoint for a task, it causes the complete() method to be called.  This is definitely wrong and causes 2 related issues when you open the API endpoint for an incomplete task:

 - If the task is assigned, then this causes the task to be completed and one or more review/approval tasks to be created.
 - If it's unassigned, then the API request fails and the task is flagged as completed but there are no review/approval tasks

Correct behavior is for no data to change.

**Comment by bendk** [comment]
In fact, I think the first issue also happens even if the task is complete.

**Comment by bendk** [comment]
I'm going to deploy this one directly because we want to fix it quick for our partner.  I'm going to move it to the testing pipeline since it should still be tested.  If it looks okay, then just close the ticket.

**Comment by PCF-Testing** [comment]
Works as described on production.

**Comment by wivaku** [comment]
Thanks @bendk. Not sure if related, but the automatic Approve in our API workflow does not work anymore. 
What should the body be to approve this task?
https://staging.amara.org/api/teams/netinnederland-staging/tasks/1019274/
```
{
    "id": 1019274,
    "video_id": "OlkmfWNog1wv",
    "language": "nl",
    "type": "Approve",
    "assignee": null,
    "priority": 0,
    "completed": null,
    "approved": null,
    "resource_uri": "https://staging.amara.org/api/teams/netinnederland-staging/tasks/1019274/"
}
````
I assumed:
`{"approved":"Approved","completed":true}`

But this sets "approved" to "Approved", but completed stays null. And the task stays open.

**Comment by unisubs-transifex** [comment]
I believe it's complete (no d)

**Comment by wivaku** [comment]
So the resulting JSON shows "completed", but the body should be "complete"?
In any case, I tried both. Do you have a complete example that works?

**Comment by wivaku** [comment]
Thanks to our other developer, it is now working. No further action needed.
Now sending the approve task directly:
`https://staging.amara.org/api/videos/lhIYdznK76GZ/languages/nl/subtitles/actions/`
`{"action":"approve"}`

**Comment by bendk** [comment]
completed is the date/time when the task was completed.  complete is the field used to signal that you want to complete the task.  I believe all you need to send is `{"complete": "true"}`.  That said, if you have the subtitles API working, I would recommend you continue with that.  That endpoint is newer and nicer to use IMO.

**Comment by wivaku** [comment]
thanks @bendk . `{"complete": "true"}` is what I used in the past. But this weekend I noticed it was not working anymore. Agreed, the `subtitles/actions/` endpoint is nicer and more direct, so no problem using that one now.
