### ISSUE TITLE
Add Cook Islands Māori language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2529]
https://en.wikipedia.org/wiki/Cook_Islands_M%C4%81ori

ISO 639 code: rar
Directionality: ltr
Request: http://support.amara.org/helpdesk/tickets/84297

**Comment by bendk** [comment]
I added this to unisubs.  It should be live on the current staging.amara.org site.

**Comment by PCF-Testing** [comment]
Verified locally on activity2 branch. Staging.amara.org does not have it yet.

**Comment by PCF-Testing** [comment]
Deployed.
