### ISSUE TITLE
Allow teams to filter activity by language

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2539]
Should we also allow this on the user page?

**Comment by deanjansen** [comment]
I vote we keep this one as narrow as possible, for now, and it in the future (when we're doing the new collaboration style)

**Comment by bendk** [comment]
Fixing this one is going to require some changes to the DB schema for activity.  I think we should use this time to clarify some of our behavior.  The main tricky issue is what happens for team activity when a video moves from team to team?

1. Right now the activity moves with the video, so the old team loses activity and the new team gains it.  The way we do it also results in extra joins at the database level and is pretty slow.  However, I think there's a way to do this without performance issues if it's actually what we want.
2. Another option is to keep the activity in the old team, so the new team activity page would see that the video got moved to their team, but none of the activity before it.  Team members could still see the activity on the video page.  I think this one is pretty logical, especially since much of the old activity will be burried pretty far down in the list anyways.  Also the existing activity stays on the old team's page.
3. The last option is copying the activity, so both teams see it in their activity page.

I personally think 2 or 3 are the best options.  I don't like removing activity from the old team.  Personally I think 2 is the most logical, but we could also go with 3 if that worked better for our expected use cases.  Again, all 3 of these options would have essentially the same performance.

**Comment by bendk** [comment]
I think the consensus was to implement 3.

**Comment by bendk** [comment]
Should this include both subtitle language and video language?  The way I think these filters work are:

 - Filter by subtitle language gives you actions like version-added, version-approved, etc. In that language
 - Filter by video language gives you all actions for videos with the primary audio language set to that language

**Comment by bendk** [comment]
I just pushed the activity branch for this, which implements this one along with a bunch of other activity-related changes.

I still need to write a migration script, so you can only test against activity created after switching to the branch and running migrate.

**Comment by bendk** [comment]
This should be working now.

**Comment by PCF-Testing** [comment]
Looks good locally.

**Comment by PCF-Testing** [comment]
Deployed.
