### ISSUE TITLE
Issues with trying to make a staff/non-superuser user

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2542]
We want to make some users staff, but not superusers.  This means they can access the django admin, but don't have full permissions (their permissions will be based on their group).

The main issue is that our is_anonymous property is messing with django's is_anonymous() method:

```
_user_has_module_perms /usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py:215
-----------------------------------------------------------------------------------------------
user: <CustomUser: 139776442807824>
app_label: 'teams'

  
  def _user_has_module_perms(user, app_label):
*     anon = user.is_anonymous()
      active = user.is_active
      for backend in auth.get_backends():
```

We should also take a quick look at various pages we have in the /staff area and decide if staff users should see them, or only superuser.

**Comment by deanjansen** [comment]
For pages in staff area, the AoD Dash and the Provider Dash would both be useful, but the rest can be only available to SU's. Also, would be great to keep the context-sensitive overlay on the bottom of amara.org pages available.

**Comment by syl22-00** [comment]
This was fixed in branches gh-2542 and gh-unisubs-2542 by changing our own anonymous-related method/property names.
Staff users can now connect to admin, but not see/modify anything as we need to give them specifically access.

**Comment by PCF-Testing** [comment]
@deanjansen: on the branch, staff non-SU users are not capable of creating teams - is this something that is needed for them?

**Comment by bendk** [comment]
That should be okay.  The way we're going to implement that is creating a group, giving it certain permissions like add team, then assigning the users to the group.

**Comment by PCF-Testing** [comment]
Tried this method. This will enable group members to create teams through the admin pages, but not through /teams/create/ UI page - will it be acceptable for them?

Also, I see that with the AoD Pm permissions some lookups will be unavailable (e.g. team video and assignee selectors on Add Task admin page) - a 403 page will be displayed instead of the desired list.

**Comment by bendk** [comment]
Ahh, I see.  There's a check in the create() view function for is_superuser.  We probably should check that to only checking if the user has create team permission.

I'm not sure about the other ones, but I'm guessing we should do something similar.  I think that check should be if you're a team admin, it shouldn't depend on the django permissions.

**Comment by bendk** [comment]
@syl22-00 can you give this one a look and fix the last bits?  I think it should be pretty simple.

For pculture/amara-enterprise#626 I used this code for the check: `user.has_perm('teams.add_team')`.  I think that should work fine for the create view as well.

Still not sure what the issue is on the lookups, but I'm guessing it should also be easy to fix.

**Comment by syl22-00** [comment]
The create team issue was fixed in the branch, how about the billing page?

**Comment by bendk** [comment]
I'm not sure what the billing page issue was.

**Comment by PCF-Testing** [comment]
A user with partner, non-SU, non-staff permissions can see Start a Team button, but when clicking it, gets redirected to the login page. Partners should not see this button at all and should only be able to create teams via API.

**Comment by syl22-00** [comment]
The existing permission functions allowed it for users with that django permission, and for partners. I pushed a fix with a new permission function.

**Comment by PCF-Testing** [comment]
Looks generally good to me now. Staff users may have some trouble when trying to lookup data that are out of bounds, such as team video ID - but I think we should merge and deploy this as is and change it later basedon the feedback.

**Comment by PCF-Testing** [comment]
Reminder: set permissions for actual users once this change goes live.

**Comment by aungtun1988** [comment]
good

**Comment by aungtun1988** [comment]
free

**Comment by PCF-Testing** [comment]
Deployed.
