### ISSUE TITLE
Consider changing the "delete subtitle" shortcut

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2547]
Current shortcut is Alt+Backspace. On text processors this shortcut deletes the previous word. On Amara it deletes the subtitle with no undo option, so it's a problem for users with that muscle memory.

On text processors, Ctrl+Shift+Backspace deletes the last sentence. This may be more suitable for the delete subtitle shortcut, as long as it doesn't conflict with anything else on the various browsers.

**Comment by bendk** [comment]
We've done this one in the experimental editor.
