### ISSUE TITLE
Rejected revision listed as a published one

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#255]
A subtitle revision with Moderation status: Rejected is listed in the list of revisions without "(draft)" label

Please compare (Revision #1, ID=156481):
http://www.universalsubtitles.org/en/videos/U7nug0p1xZ5a/ja/293830/#revisions
vs.
http://www.universalsubtitles.org/en/videos/U7nug0p1xZ5a/ja/293830/156481/
vs.
http://www.universalsubtitles.org/en/admin/videos/subtitleversion/156481/

**Comment by PCF-Testing** [comment]
This does not seem to be happening anymore.
