### ISSUE TITLE
Clarify and test task-related actions

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2553]
When testing #2349 we need to check that we create the same activity with the new system as the old system.  One really tricky/annoying part of this is the task-related actions.  I'm breaking that part out into this ticket since it's a bit complex.

Here's how I believe we generate actions using the current code:
 - APPROVE_VERSION (8)
    - When an approve task is approved
    - When a review task is approved and there is no approval step
    - Not when a subtitle/translation task is completed and there is no review/approval step
 - REJECT_VERSION (10)
   - When an Approve task is sent back
 - REVIEW_VERSION (12)
   - Never
 - ACCEPT_VERSION (13)
   - When a review task is approved and there is an approval step
 - DECLINED_VERSION (14)
    - When a review task is sent back

So based on this, there's a couple questions:
  - Is this list accurate in terms of the current behavior?
  - Is this behavior what we want?
  - Does the new code implement things correctly?

**Comment by bendk** [comment]
So I believe what I described above is implemented on the activity branch.  We need to a) double-check that that's the correct behavior and b) test that it's working correctly on the branch.

**Comment by PCF-Testing** [comment]
This works as described on the branch.

The only question I have, is there a sound reason to log accepting a review task in the absence of approval task as approving? This bit looks a bit confusing because of the mixup of terms - but, given that tasks are going away very soon, perhaps it is a waste of time to look deeper into this...

**Comment by bendk** [comment]
I think the reason is that they wanted approved to always mean that all tasks were complete.  I agree it's totally confusing and when we implement it with the collab system, we should have separate activities for an assignment was endorsed and the collaboration is complete.

**Comment by PCF-Testing** [comment]
Deployed.
