### ISSUE TITLE
Popcorn wrapper: code sample & documentation

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#2554]
To help video hosting platforms that would like to integrate their player interface directly with the Amara editor, we'd like to provide a bit of code and some guidelines for creating a functional popcorn.js wrapper. 

Would be great to include:
1) Code sample for a video player wrapper (should it be YouTube?)
2) Basic documentation to give a developer a high-level understanding of how to integrate a video player with popcorn/Amara

**Comment by bendk** [comment]
For 1) it's hard because most of the code is not all that clear.  Maybe the one that @syl22-00 wrote would be best?

For 2) The main idea is to create an object that wraps the existing video player code to implement the HTML5 video interface.

**Comment by syl22-00** [comment]
This was done
