### ISSUE TITLE
Permissions on user activity

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2556]
As far as I can tell, with both the profile page and the activity API, any user can see all activity for any other user.  I think this includes more info than we'd like to list, for example the work that on-demand users are doing.

I think we should change it so only staff users and the user themselves can see the activity.

**Comment by bendk** [comment]
@PCF-Testing points out that some users like their activity to be public.  There are a couple other possible solutions here:

 - Define a private account that the od team uses.  Only change the behavior for those accounts.
 - Only display activity for public teams.

**Comment by bendk** [comment]
I think the best solution is on the activity2 branch.  I made it so we filter out activity for private teams that the user viewing the profile page is not part of.  Superusers see everything.

**Comment by PCF-Testing** [comment]
When viewing users' activity on the UI profile pages, it works on the branch as described.

However, in the API user's activity is not filtered down to the actions the viewer is permitted to see - instead, all the target user's activity is displayed.

**Comment by bendk** [comment]
The API issue is a separate case.  I complete agree on the issue, but it's harder to change the API because someone might be relying on it.  I think there are several options there, but we should investigate them in a separate ticket.

For staff users, if we want to allow them to see things, we can define a permission for it.  Then you can choose to give or not give the permission to the group they're in (or individual user accounts).  I also think this should be a separate thing issue though.

**Comment by PCF-Testing** [comment]
OK - created a separate ticket for the API issue.

**Comment by PCF-Testing** [comment]
Deployed.
