### ISSUE TITLE
Unify team activity again

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2559]
Right now we have a split between "team activity" and "team video activity".  The meaning is pretty obscure, team activity is activity related to a team, but not related to any video like member-join/member-leave.  We should re-unify these things back together and just have plain team activity.

**Comment by bendk** [comment]
This is implemented on the activity branch

**Comment by PCF-Testing** [comment]
Verified locally on activity branch.

**Comment by PCF-Testing** [comment]
Deployed.
