### ISSUE TITLE
Developer support request: Ability to control embed player via JS

### ISSUE THREAD

**Issue by patcon** [pculture/unisubs#2567]
Any pointers? Not sure where to start looking :)

**Comment by syl22-00** [comment]
Currently, ther is no JavaScript API to interact with the embedder, but it is possible to make one. It would require to adjust the [iframe controller](https://github.com/pculture/unisubs/blob/staging/templates/embedder-iframe.js) and the [embedder itself](https://github.com/pculture/unisubs/blob/staging/media/src/js/embedder/embedder.js).

We do not plan to do this, but would be happy to merge if somebody submits a pull request that implements it.

**Comment by patcon** [comment]
Thanks @syl22-00 -- if I get amara integrate into our toronto councilmatic instance after launch, I'll loop back to work on this.

**Comment by bendk** [comment]
Looks like there's not too much interest in this one.  Let's close it.
