### ISSUE TITLE
Don't include obsolete activity types in the team selector

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2568]
We shouldn't allow team members to filter by things like video title changed, since we aren't creating that activity type anymore.

**Comment by bendk** [comment]
Implemented in the activity2 milestone.

**Comment by PCF-Testing** [comment]
Looks generally OK, but would like to have another pass once enterprise-637 is fixed.

**Comment by PCF-Testing** [comment]
Verified, with the caveat that Version Accepted, Version Approved, Version Declined, Version Rejected never occur in collab-type teams. Video Deleted records could not be produced on old-style teams because the feature is not functioning. On new teams, deleting videos is not available.

**Comment by bendk** [comment]
I think the video deleted thing is fine.  It's just not possible on new-style teams because we haven't implemented it deleting a video when you remove it.  As far as I know we're planning to do that.

**Comment by PCF-Testing** [comment]
Deployed.
