### ISSUE TITLE
Update info on Create page

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#2571]
TDS would like to update some of the wording on this page: http://amara.org/en/videos/create/

![screen shot 2016-06-01 at 12 13 50 pm](https://cloud.githubusercontent.com/assets/216145/15716863/576731cc-27f2-11e6-9e4c-7ad9e596bb21.png)

Updated text: "Enter a video URL to use the Amara Editor. It will appear and remain on your public profile. [Learn more](https://support.amara.org/solution/articles/218220-what-does-adding-a-video-to-amara-do-)"

Updated learn more link: https://support.amara.org/solution/articles/218220-what-does-adding-a-video-to-amara-do-

**Comment by PCF-Testing** [comment]
Change verified locally on staging.

**Comment by PCF-Testing** [comment]
Deployed.
