### ISSUE TITLE
Add 3 new languages

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2572]
1) Amis (https://en.wikipedia.org/wiki/Amis_language)
ISO 639 code - ami
Directionality - LTR

2) Yami (Tao) (https://en.wikipedia.org/wiki/Yami_language)
ISO 639 code - tao
Directionality - LTR

3) Seediq (https://en.wikipedia.org/wiki/Seediq_language)
ISO 639 code - trv
Directionality - LTR

Request: https://pculture.freshdesk.com/helpdesk/tickets/85293

**Comment by bendk** [comment]
This should be implemented.  You'll need to update unilangs to get the changes.

**Comment by PCF-Testing** [comment]
Verified locally.

**Comment by PCF-Testing** [comment]
Deployed.
