### ISSUE TITLE
Importing subtitles from YouTube gets stuck

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2579]
Observed on production.
When importing subtitles for https://youtu.be/3_petnJUYqk (55 CC languages), languages get imported to Amara in alphabetical order ordered by language code, and the process stalls after 39 languages. The last successfully imported language is Polish. Pt-br and pt-pt do not get imported, and neither do the rest of the languages till the end of the alphabet.
Video on Amara: https://www.amara.org/en/videos/gexP9wFyNJId/info/steveston-6/

**Comment by syl22-00** [comment]
This might be the same issue as https://github.com/pculture/amara-enterprise/issues/915 so it might have just been fixed.

**Comment by PCF-Testing** [comment]
@syl22-00: it is definitely still a problem on production. Where else can I check it?

**Comment by syl22-00** [comment]
Thanks for looking at it @PCF-Testing I believe it is related though, probably a missing pass via mapping, I will check that.

**Comment by syl22-00** [comment]
There was indeed another issue that prevented importing subtitles to work well. I fixed it in branch gh-2579, it seems to work well when I run it.

**Comment by kslottow** [comment]
Darren mentioned again on 1/3/17 - high priority to get this deployed.

**Comment by PCF-Testing** [comment]
Tried this locally.

Generally, subtitle import works well for me. The few exceptions I have noticed:

- [ ] Spanish (Spain) with the language code es-ES always gets skipped during import. Not sure if we should map it to the regular 'es' on Amara. For comparison, 'pt-PT' imports as regular 'pt'.

- [ ] If a subtitle track on YouTube is poorly formatted/timed (e.g. uploaded from untimed file with 99.59.59 timestamps), the subtitle import process stalls and the next subtitle tracks (in alphabetical order by language code) would not get imported. If possible, this should be fixed so that the troublesome language just gets skipped and the process continues with the remaining languages.

**Comment by PCF-Testing** [comment]
- [ ] One more issue when adding a subtitled video to an old-style team with tasks. Subtitles fail to get import, the logs say:

worker_1  | ERROR 2017-01-09 07:31:52,156 celery.worker.job Task externalsites.tasks.fetch_subs[0d1e91d7-245d-485b-b2c9-2ef87f1771c5] raised exception: AttributeError("'NoneType' object has no attribute 'is_authenticated'",)
worker_1  | Traceback (most recent call last):
worker_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 224, in trace_task
worker_1  |     R = retval = fun(*args, **kwargs)
worker_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 403, in __protected_call__
worker_1  |     return self.run(*args, **kwargs)
worker_1  |   File "/opt/apps/amara/apps/externalsites/tasks.py", line 135, in fetch_subs
worker_1  |     subfetch.fetch_subs(VideoUrl.objects.get(id=video_url_id))
worker_1  |   File "/opt/apps/amara/apps/externalsites/subfetch.py", line 55, in fetch_subs
worker_1  |     fetch_subs_youtube(video_url)
worker_1  |   File "/opt/apps/amara/apps/externalsites/subfetch.py", line 84, in fetch_subs_youtube
worker_1  |     origin=ORIGIN_IMPORTED)
worker_1  |   File "/opt/apps/amara/apps/subtitles/pipeline.py", line 537, in add_subtitles
worker_1  |     created, note, origin, metadata, action)
worker_1  |   File "/opt/apps/amara/apps/subtitles/pipeline.py", line 402, in _add_subtitles
worker_1  |     _perform_team_operations(version, committer, action)
worker_1  |   File "/opt/apps/amara/apps/subtitles/pipeline.py", line 98, in _perform_team_operations
worker_1  |     _update_visibility_and_tasks(team_video, version, committer, complete)
worker_1  |   File "/opt/apps/amara/apps/subtitles/pipeline.py", line 306, in _update_visibility_and_tasks
worker_1  |     committer, complete)
worker_1  |   File "/opt/apps/amara/apps/subtitles/pipeline.py", line 207, in _handle_outstanding_tasks
worker_1  |     task.complete()
worker_1  |   File "/opt/apps/amara/apps/teams/models.py", line 2360, in complete
worker_1  |     }[Task.TYPE_NAMES[self.type]]()
worker_1  |   File "/opt/apps/amara/apps/teams/models.py", line 2425, in _complete_subtitle
worker_1  |     if self.workflow.requires_review_or_approval and not self._can_publish_directly(sv):
worker_1  |   File "/opt/apps/amara/apps/teams/models.py", line 2374, in _can_publish_directly
worker_1  |     self.language) and
worker_1  |   File "/opt/apps/amara/apps/teams/permissions.py", line 708, in can_publish_edits_immediately
worker_1  |     return can_approve(team_video, user, lang)
worker_1  |   File "/opt/apps/amara/apps/teams/permissions.py", line 644, in can_approve
worker_1  |     role = get_role_for_target(user, team_video.team, team_video.project, lang)
worker_1  |   File "/opt/apps/amara/apps/teams/permissions.py", line 98, in get_role_for_target
worker_1  |     member = get_member(user, team)
worker_1  |   File "/opt/apps/amara/apps/teams/permissions.py", line 79, in get_member
worker_1  |     return team.get_member(user)
worker_1  |   File "/opt/apps/amara/apps/teams/models.py", line 473, in get_member
worker_1  |     if not user.is_authenticated():
worker_1  | AttributeError: 'NoneType' object has no attribute 'is_authenticated'

**Comment by franontanaya** [comment]
We have a language code for "es-ES" distinct from "es".

In practice there's almost never a "Generic Spanish" produced along Spain's / Latinamerican Spanish, and castillian Spanish with maybe one or two words avoided due to pejorative meaning in Latinamerica is used as generic i.e. the difference is so small it's never cost effective.

We'd be likely to see channels where the Spanish subtitles were added to "es" in some videos and to "es-es" to others, making things a bit more complicated in the team when people search for collaborations or fetch reports, etc.

Commonly when we import a channel existing tracks are used as "the source language", so the specific dialect they are in it's not so relevant. But then if an user imports a video with "es-ES", it gets converted to "es", edits it and expects it to sync back to "es-ES" in the source video it'd be an issue.

I think I'd rather be able to set an import rule for the team ("Import x as y") than have a hardcoded language code coercion

**Comment by PCF-Testing** [comment]
Defining import rules for each team sounds like a complicated feature that would be not easy to implement, test, and maintain in the long run. How about doing instead the following:

A. By default, skip the languages not supported by Amara, blacklisted languages for the team, ASR subtitle tracks.
B. Add the option to manually pull in any specific subtitle from YT (including ASR) at any time and specify how exactly it should be imported (e.g. "es-ES" -> "es") - see https://github.com/pculture/unisubs/issues/1938. This feature could be first implemented as an API method (https://github.com/pculture/unisubs/issues/2703) and then get some nice UI for users' convenience.

Would such a solution make sense?

**Comment by syl22-00** [comment]
Right now, for Spanish, in the language codes we support, we have 'es', 'es-AR', 'es-MX', 'es-NI'. Other regions are ignored.

**Comment by syl22-00** [comment]
So Ipushed the changes in gh-2579, it wont break if one channel fails.

**Comment by PCF-Testing** [comment]
The messed up language from https://www.youtube.com/watch?v=3_petnJUYqk, pt-br, actually got imported from YouTube with all timestamps set to 0. Is this the correct behaviour we'd like to keep in this case?

In any case, the current behaviour is an improvement compared to the original error - import process no longer gets interrupted, and all the languages get successfully imported.

For the remaining issue with import to team with tasks, I have created https://github.com/pculture/unisubs/issues/2722.

**Comment by kslottow** [comment]
@PCF-Testing is this ready to deploy?

**Comment by kslottow** [comment]
@syl22-00 looks like there's an outstanding question:

> The messed up language from https://www.youtube.com/watch?v=3_petnJUYqk, pt-br, actually got imported from YouTube with all timestamps set to 0. Is this the correct behaviour we'd like to keep in this case?

**Comment by syl22-00** [comment]
What I just changes is the fact that we do not stop once one language fails. I believe that fixes this ticket. If we want to improve the way "incorrect" subtitles are parsed, we should probably do it as part of another ticket.

**Comment by PCF-Testing** [comment]
Marking as Waiting for Deploy.

**Comment by PCF-Testing** [comment]
Deployed.
