### ISSUE TITLE
Videos added don't appear in the search index

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2585]
When you add a video, it doesn't appear in the search index.  This is related to issues where team videos don't appear in the search.

**Comment by bendk** [comment]
I snuck a fix into staging for this.  It should be live on the next deploy.

**Comment by PCF-Testing** [comment]
Hmm, on my local instance of staging videos added to an old-style private team appear on /videos/watch/ page, although they aren't supposed to.

**Comment by PCF-Testing** [comment]
This has been deployed.

To do: run index videos script to update the search index where it was missing.

**Comment by PCF-Testing** [comment]
Videos re-indexed. Marking as closed.
