### ISSUE TITLE
New activity labels

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2586]
For our new design we want to make activity listed in tables in a slightly different way.  Something like:

| User | Action | Object | When |
| --- | --- | --- | --- |
| Alice | edited subtitles | My Video Title / French | 2 days ago |
| Bob | removed member | Carrie | 1 days ago |

The github table doesn't do it credit, but basically for every activity type we want to know the following info:
- action type label ("edited subtitles")
- "related object".  This is a team, video URL, subtitle language, etc.  Basically some object in the database related to the action, but _not_ a video.  The video is handled specially.  For some actions, like video-added, this might be null.

We need to this for all activity types, here they are:
- video-added
- video-title-changed
- comment-added
- version-added
- video-url-added
- translation-added
- subtitle-request-created
- version-approved
- member-joined
- version-rejected
- member-left
- version-reviewed
- version-accepted
- version-declined
- video-deleted
- video-url-edited
- video-url-deleted

**Comment by kslottow** [comment]
closing because we're deciding not to use the table layout https://github.com/pculture/amara-design/issues/167
