### ISSUE TITLE
Video index not updated when video is moved between teams

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2590]
Steps to reproduce:

1. Submit a video to Team One.
2. Move this video to Team Two.
3. Return to Team One and attempt to submit the same URL again. The error message will say: "This video already belongs to the Team One team (view video)", although in reality the video is in Team Two.

Expected: the error message correctly indicates the location of the video.

**Comment by bendk** [comment]
I just pushed a fix directly to staging that should fix the error message.  I don't think it was a video index issue, just an issue with the form.  Are there any other behaviors that need fixing?

**Comment by PCF-Testing** [comment]
No, this was the only issue.

Verified locally on staging branch, looks good to me.

**Comment by PCF-Testing** [comment]
Deployed.
