### ISSUE TITLE
DFXP subtitles in TimedText 1.0 format uploadable but not editable

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2591]
DFXP (XML) subtitles created offline in SubtitleEdit in TimedText 1.0 format can be sucsessfully uploaded to Amara, but on attempt to edit these subtitles online in Amara editor and save the edits an error message is displayed.

TimedText 1.0 has a header that is different from the regular Amara DFXP subtitles.

TimedText Draft 2006-04 format does not have this problem - subtitles are uploadable and editable.

**Comment by kslottow** [comment]
needs prioritization

**Comment by kslottow** [comment]
@PCF-Testing is this blocking many users/is this format used often?

@bendk if it's important, it seems like this could be one for Amelia or Deborah, right?

**Comment by bendk** [comment]
Seems reasonable, we should upload a sample document to use first though.

**Comment by PCF-Testing** [comment]
Sample file: https://drive.google.com/open?id=0B7j578ppG4loWGt6QnVlOWJWLTA

**Comment by PCF-Testing** [comment]
Verified the fix.

**Comment by PCF-Testing** [comment]
Deployed.
