### ISSUE TITLE
Durations don't seem to be getting set from the editor

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2594]
We have code to set the duration based on the value seen in the editor, however it seems like maybe it's not firing.

If it's not obvious what the issue is, ask @darren-bridenbeck for examples.

**Comment by syl22-00** [comment]
Actually, there is not much code about this. The client (editor) does not send the duration and the API does not adjust the duration either, even is sent together with new subtitles versions.
It can be added though, possibly from the embedder too, but I do not think there is any benefit from having it from the embedder.

**Comment by syl22-00** [comment]
Done in branch gh-2584.
Duration is set from editor only if:

* it is not set yet (via existing duration retrieval when video is added) and
* user is authenticated.

**Comment by PCF-Testing** [comment]
Works with most video formats supported by Amara. Exception: Brightcove, e.g. http://link.brightcove.com/services/player/bcpid1530901030001?bckey=AQ~~,AAABZBJSQZE~,4_PvRAOLkj_8mSVAWmXGzIfCcj8wJStT&bctid=1651198799001


A bunch of tests are broken on the branch. The errors are in the two following types:

======================================================================
ERROR: test_video_language_filter (enterpriseapi.tests.test_provider_queue.ProviderQueueTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/amara-enterprise/enterpriseapi/tests/test_provider_queue.py", line 32, in setUp
    'enterpriseapi:provider-queue-items-available')
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/reverse.py", line 51, in reverse
    url = _reverse(viewname, args, kwargs, request, format, **extra)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/reverse.py", line 64, in _reverse
    url = django_reverse(viewname, args=args, kwargs=kwargs, **extra)
  File "/opt/apps/amara/apps/localeurl/__init__.py", line 18, in reverse
    path = django_reverse(viewname, urlconf, args, kwargs, prefix, current_app)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 498, in reverse
    key)
NoReverseMatch: 'enterpriseapi' is not a registered namespace

======================================================================
ERROR: test_basic_rollback (subtitles.tests.test_pipeline.TestRollbacks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/subtitles/tests/test_pipeline.py", line 666, in test_basic_rollback
    rb = pipeline.rollback_to(v, 'en', 1)
  File "/opt/apps/amara/apps/subtitles/pipeline.py", line 600, in rollback_to
    rollback_author)
  File "/opt/apps/amara/apps/subtitles/pipeline.py", line 456, in _rollback_to
    version = _add_subtitles(**data)
TypeError: _add_subtitles() takes exactly 17 arguments (16 given)

**Comment by syl22-00** [comment]
The tests are now fixed in the branch.

As for the brightcove video, it seems to me that it is also broken in the editor. Is it a regression?

**Comment by PCF-Testing** [comment]
Verified that the tests pass now.

Regarding the Brightcove video, it is hard to tell. I took the link from production (http://www.amara.org/en/videos/5pJS4PX9cvlR/info/) where it was successfully subtitled.  However, on production the video does not play in the editor either. Could it be that there was a change on the BC side?

**Comment by PCF-Testing** [comment]
Deployed.
