### ISSUE TITLE
Timeline in editor stops after adjusting a couple of timestamps

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2595]
Reported by a user (Veronica? of TDS).

Screencast: https://www.dropbox.com/s/mcybkyzfgo9jo28/Amara.mov?dl=0
JS errors in console: https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/28304914/original/_86262.png?1467271508
Video: http://www.amara.org/en/videos/NdBJjN8KKtN3/ja/1359444/
Environment: Chrome / Mac OS X
Chrome and Flash Player are up to date.

**Comment by VeronicaPCF** [comment]
Additional info from user: I'm currently avoiding Chrome as a workaround as it is now always happening at some point in the session if I use Chrome, but if you could flag this up for your technicians to look at in the near future that'd be appreciated.

**Comment by kslottow** [comment]
@nslottow Nate, if this scope is too big then we can replace it with something.

**Comment by nslottow** [comment]
Hi @VeronicaPCF, I started looking into this and was unable to reproduce the problem on the latest Chrome on my Mac mini.  The screencast link appears to be missing so I'm not sure we can do much without more information.  Would you mind checking if this is still an issue for you, and if so, uploading another screencast?

**Comment by VeronicaPCF** [comment]
Hi! I contacted the user again, and he confirmed that the issue has been resolved!
Thank you, this ticket can be closed now. 
Veronica
