### ISSUE TITLE
Move / Remove videos dialog gone

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2597]
Observed on gh-2592, gh-enterprise-651.

On new team video list, Move / Remove dialog is not displayed.

**Comment by bendk** [comment]
Pretty sure this is an issue in staging. It shouldn't block those branches.  I'll check it out on monday.

**Comment by PCF-Testing** [comment]
Works on staging.amara.org and locally on the latest version of staging.

**Comment by bendk** [comment]
Ahh, it was an issue on staging, but I fixed it.  It should get fixed once we either merge the branch to staging or staging to the branch.
