### ISSUE TITLE
Add Egyptian Arabic language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2602]
https://en.wikipedia.org/wiki/Egyptian_Arabic
ISO 639 code: arz
Directionality: RTL

Reason: https://pculture.freshdesk.com/helpdesk/tickets/86428

**Comment by syl22-00** [comment]
Done

**Comment by PCF-Testing** [comment]
Should be RTL. In the current version, it is LTR.

**Comment by syl22-00** [comment]
Just changed this on unisubs, in branch gh-2602. I also fixed Tunisian Arabic which was set to LTR.

**Comment by PCF-Testing** [comment]
Tunisian Arabic should be LTR because it was requested by users of Latin script: https://github.com/pculture/unisubs/issues/1896.

See, for example, http://www.amara.org/en/videos/QoJZksuJnUw6/aeb/977495/2043891/

**Comment by syl22-00** [comment]
Sorry about that. So I made the change directly on staging

**Comment by PCF-Testing** [comment]
Deployed.
