### ISSUE TITLE
Video Duration Missing in New Reports

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#2603]
This has been observed for Vimeo, Brightcove, Kaltura, and hosted .mp4 files.

Note that the Old Billing report will sometimes capture duration accurately for a video, where the new report does not.

Example: 
Video: http://amara.org/en/videos/qejhZWIrOsb5/info/cdnhopetvorghss_2016_q2_e12v2mp4/
Language: English
Team: Team Adventist - http://amara.org/en/teams/adventist/

To test this, pull Junes billing report in the new system: http://amara.org/en/billing/

And pull 2016-06-01 to 2016-06-30 in the old system for Team Adventist: http://www.amara.org/en/admin/billing/

**Comment by bendk** [comment]
Ahh yeah, because the old system guessing the duration based on the time of the last subtitles.

Maybe we should implement that in the new system.  I think the code to update it based on the time we get during the editing session could be better though.

**Comment by deanjansen** [comment]
Switching this to the Enterprise Repo
