### ISSUE TITLE
Add the option to move subtitles in onsite/offsite video player

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2604]
When subtitles are overlayed on the bottom part of the video screen, they sometimes obscure important parts of the picture or screen text. 

It would be awesome to have the option to move the captions out of the video player area and have them displayed right under the video (or between the video and the transcript viewer when it is on). By default, the CC should be in their usual position in the bottom part of the video, but by clicking a button the user should be able to reposition them out of the video without interrupting the video playback. A second click on the same button should return CC to the regular position.

**Comment by kslottow** [comment]
additional info: we already have the $$ positioning to make sure they don't overlap in the finished product, but it can still be an issue while subtitling.

**Comment by kslottow** [comment]
This could be included in a Rich Editor down the road

**Comment by kslottow** [comment]
seems fixed by positioning
