### ISSUE TITLE
Leave Team command broken

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2612]
1. Go to amara.org, your user menu, "Your Teams" to get to the team directory
2. a click on Leave Team link creates Member Left activity entry but does not delete team membership for the user, so user effectively remains the member of the team.

Example:
http://www.amara.org/en/teams/maggie-collab-test/activity/?type=member-left&video_language=&subtitle_language=&sort=-created
http://www.amara.org/en/admin/teams/application/52392/
http://www.amara.org/en/admin/teams/teammember/210234/

Expected: Leave Team should actually remove the member from the team

**Comment by asabine** [comment]
the `leave_team` view never actually called delete on the team member; added that in and it seems to work as expected now.

**Comment by PCF-Testing** [comment]
Cannot start branch gh-2612 with master, raises the following exception on start:

worker_1   | Traceback (most recent call last):
worker_1   |   File "/opt/apps/amara/manage.py", line 42, in <module>
worker_1   |     execute_from_command_line(sys.argv)
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
worker_1   |     utility.execute()
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
worker_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/djcelery/management/commands/celery.py", line 22, in run_from_argv
worker_1   |     ["%s %s" % (argv[0], argv[1])] + argv[2:])
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 890, in execute_from_commandline
worker_1   |     super(CeleryCommand, self).execute_from_commandline(argv)))
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 179, in execute_from_commandline
worker_1   |     return self.handle_argv(prog_name, argv[1:])
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 882, in handle_argv
worker_1   |     return self.execute(command, argv)
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 857, in execute
worker_1   |     return cls(app=self.app).run_from_argv(self.prog_name, argv)
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 142, in run_from_argv
worker_1   |     return self(*args, **options)
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 112, in __call__
worker_1   |     ret = self.run(*args, **kwargs)
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 214, in run
worker_1   |     return self.target.run(*args, **kwargs)
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celeryd.py", line 153, in run
worker_1   |     return self.app.Worker(**kwargs).run()
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/apps/worker.py", line 157, in run
worker_1   |     self.app.loader.init_worker()
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 116, in init_worker
worker_1   |     self.on_worker_init()
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/djcelery/loaders.py", line 127, in on_worker_init
worker_1   |     self.close_database()
worker_1   |   File "/opt/apps/amara/apps/amaracelery/loaders.py", line 27, in close_database
worker_1   |     connection.cursor().execute("COMMIT")
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 317, in cursor
worker_1   |     cursor = self.make_debug_cursor(self._cursor())
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 377, in _cursor
worker_1   |     if settings_dict['HOST'].startswith('/'):
worker_1   | AttributeError: 'NoneType' object has no attribute 'startswith'
unisubssecond_worker_1 exited with code 1

**Comment by PCF-Testing** [comment]
Looks good. @asabine, could you please make a PR?

**Comment by PCF-Testing** [comment]
Deployed.
