### ISSUE TITLE
Only present activity types actually present in a team

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2614]
Now that we're adding collab activity, there's going to be lots of activity types and a team may or may not use all of them.  We should only include values in the filter that are actually on the team.

I think we should probably cache the values to avoid a query every time you open the activity page.

**Comment by bendk** [comment]
I thought about this one more and I don't think that this is the solution.  Here's why:

 - The query is 5 seconds long.  Even if we cache it, there's still going to be a time when it's not cached and this is fairly expensive.
 - For teams like TED, this solution isn't going to be enough because they will have both task-related activity and collab-related activity in their activity streams.  That's still a lot of types and also they could get confused.

So instead what I did was make it so we change the list based on the team workflow types.  Right now there's 3 options:
  - By default we only list basic actions, nothing related to tasks or collab.  This is the case for old-style, non-task teams, and also new-style simple teams.
  - For task teams, we also list task-related activity types
  - For collab teams, we also list collab-related activity types.

This seems like a relatively good system.  A nice side effect is that it makes the ordering more sensible.  It also opens the door for more customized lists.  Like for example, if we end up with TED having both task and collab related activity, then we could give them a customized list that includes both, but uses optgroups or something to keep the interface understandable.

**Comment by bendk** [comment]
This is all implemented in the collab-activity branches.

**Comment by PCF-Testing** [comment]
The behaviour on collab-activity makes sense: Collab and Customer team types have collab-related activity, Simple, E-e and V-o types neither collab nor task actions, and Old style teams vary depending on whether tasks are enabled.

**Comment by PCF-Testing** [comment]
Deployed.
