### ISSUE TITLE
Add bullet to dialog for YouTube sync

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#2616]
Additional information for YouTube syncing (found on [this page](http://www.amara.org/en/profiles/account/)), to clarify the behavior of syncing to YouTube. Let's add a new bullet in the top section of existing modal (it can go second in the top list of bullets): 

• We **display all of your YouTube videos** on your public Amara profile.

![enablecrowdsubtitlesonyourpersonalyoutubechannel-1](https://cloud.githubusercontent.com/assets/216145/17762153/c985935e-64db-11e6-906b-83503cf1b15f.png)

**Comment by PCF-Testing** [comment]
Deployed.
