### ISSUE TITLE
API: add "modified" parameter to Task resource

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2619]
- [x] Add "modified" read-only parameter to Task resource. It should return the task's last update time 

- [x] Allow sorting tasks by the value of "modified". The default sorting order should be reverse chronological (last to earlier)

- [x] Update the API docs to reflect the change.

**Comment by bendk** [comment]
Implemented in the more-api-changes branches.  The docs are updated and the readthedocs page will get updated once the branches are merged.

**Comment by PCF-Testing** [comment]
"modified" parameter looks good, and sorting "order_by=-modified" / "order_by=modified" works as expected.

The only thing that is missing is that by default tasks are sorted by task ID in ascending order. The requirement was to make them by default sorted by the time of the last modification (last modified tasks listed first, i.e. order_by=-modiified).

**Comment by PCF-Testing** [comment]
Deployed.
