### ISSUE TITLE
Log task management actions

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2620]
Add the following activity types and log the related events:
- task-assigned
- task-reassigned
- task-declined
- task-expired
- transcription-completed
- translation-completed

Notes:
1. Task-assigned action should correspond to a user starting an available task by their own initiative (through Task-> Start menu). 'user' field should be populated with the name of assignee.
2. Task-reassigned action should correspond to a manager/admin reassigning a task through task assignment pick tool. 'user' field should be populated with the name of manager/admin who performed the action.
3. Transcription-completed corresponds to completing (submitting) a transcription task.
4. Translation-completed corresponds to completing (submitting) a translation task.

**Comment by kslottow** [comment]
needs prioritization

**Comment by kslottow** [comment]
@PCF-Testing @bendk double-checking to make sure we did not already do this.  If it hasn't been done, I feel like we should check with Alex before scheduling it, because the new integration from the TED side might not have the same needs as they did when they requested this in August.  Does that sound right?

**Comment by PCF-Testing** [comment]
This has not been done.

**Comment by kslottow** [comment]
Thanks!

**Comment by bendk** [comment]
It's really hard to estimate for task-related features.  8 hours is my best guess for the work, assuming there will be a lot of back and forth between Maggie and the implementer.  There also might be some more work needed once we deploy and it gets tested in the real world.

**Comment by kslottow** [comment]
Thanks!
