### ISSUE TITLE
Login with the use of FB account does not work

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2624]
Observed on production, staging, and local instance.

On the local instance got the following error:

FacebookError at /auth/facebook_login_done_confirm/Lw==/
Error 12: REST API is deprecated for versions v2.1 and higher (12)
Request Method: GET
Request URL:    http://unisubs.example.com:8000/en/auth/facebook_login_done_confirm/Lw==/?code=AQABY_nLEr-WJBbdaWeSNdNx83zSMVxQbM7Oe-PjY26zArCZmhm6bxJnfwS8dNCGMf1AaG8JJdG_YIwcx8O6kdymhvcYPSbaVbNncOFYldZKxWM53oBGpsNBMwAgWWUMlYXRC3Jz_Nmtf2Ac0wQ_vLz0Mj6-taA_1V1LhDjrJJkr6Sn8DaG2skgQndjmLHnqYqZofCWCSX98YNF2_hb40bpNzfHtwikkCd2FZk6YT7qqVgNOGejb0wenz905wx8ZZF7qeEWb3I5ZQHlxtQdYN-Dmexp-R-AVUEhY6QB9SckQFq5eoou-3QB2lnfdhq1KYoWrbbZb4V4Uy4bo7kF7js3p
Django Version: 1.4.21
Exception Type: FacebookError
Exception Value:  
Error 12: REST API is deprecated for versions v2.1 and higher (12)
Exception Location: /usr/local/lib/python2.7/dist-packages/facebook/**init**.py in _check_error, line 1438

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
1.                         response = callback(request, _callback_args, *_callback_kwargs)
   File "/opt/apps/amara/apps/thirdpartyaccounts/views.py" in facebook_login_done
2.         (exist, suggested_email) = FacebookAuthBackend.pre_authenticate(fb, request)
   File "/opt/apps/amara/apps/thirdpartyaccounts/auth_backends.py" in pre_authenticate
3.         facebook.uid = facebook.users.getLoggedInUser()
   File "/usr/local/lib/python2.7/dist-packages/facebook/**init**.py" in facebook_method
4.         return self(method_name, params, signed=signed)
   File "/usr/local/lib/python2.7/dist-packages/facebook/**init**.py" in **call**
5.         return self._client('%s.%s' % (self._name, method), args, signed=signed)
   File "/usr/local/lib/python2.7/dist-packages/facebook/__init__.py" in **call**
6.         return self._parse_response(response, method)
   File "/usr/local/lib/python2.7/dist-packages/facebook/__init__.py" in _parse_response
7.             self._check_error(result)
   File "/usr/local/lib/python2.7/dist-packages/facebook/__init__.py" in _check_error
8.             raise FacebookError(response['error_code'], response['error_msg'], response['request_args'])

Exception Type: FacebookError at /auth/facebook_login_done_confirm/Lw==/
Exception Value: Error 12: REST API is deprecated for versions v2.1 and higher (12)

**Comment by syl22-00** [comment]
The issue is that we were using the REST API which was deprectaed in Graph API version 2.1. So we were on Graph API v 2.0 which has just been deprecated on Aug 7.

To do Facebook authentication, we now need to switch to the [JavaScript SDK](https://developers.facebook.com/docs/facebook-login/web).

**Comment by kslottow** [comment]
@syl22-00 is this issue resolved/can it now be closed?

**Comment by kslottow** [comment]
or do we still need to switch to JavaScript SDK?

**Comment by PCF-Testing** [comment]
@kslottow: no, not resolved yet

**Comment by kslottow** [comment]
@PCF-Testing @syl22-00 who is responsible for the next step on this issue/what needs to be done?

**Comment by PCF-Testing** [comment]
gh-2624 branch would not start locally, it seems to be out of sync with master. @syl22-00, could you please merge staging into this branch?

**Comment by PCF-Testing** [comment]
Checked on gh-2624-redo.

- [ ] Is it absolutely necessary to use the new button? The older one looked nicer and fit into SocialAuth login panel better:

![newfbloginbutton](https://cloud.githubusercontent.com/assets/288455/21805834/202335c8-d6eb-11e6-9fab-947d10758656.png)

- [ ] New user accounts created with the use of FB button have a different username pattern - Firstname.Secondname.fb_user. Before, it used to be FirstnameNN, where NN is an ordinal number. I think the older way was better because it did not expose the family name in the username and allowed creating user accounts for FB users with identical names (think of several people named John Smith or Wang Ying Ying)

- [ ] Deactivating a FB-based Amara account and creating a new one with the use of the same FB account causes the following exception:

ValueError at /auth/facebook_login_confirm/m.shamraeva@gmail.com/
The view thirdpartyaccounts.views.facebook_login didn't return an HttpResponse object.
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/auth/facebook_login_confirm/[fb_account_email]/
Django Version:	1.4.21
Exception Type:	ValueError
Exception Value:	
The view thirdpartyaccounts.views.facebook_login didn't return an HttpResponse object.
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in get_response, line 127

**Comment by syl22-00** [comment]
@PCF-Testing I made those changes in the branch.

For the second item, I did have the additional numbers at the end in case of overlaps.

**Comment by PCF-Testing** [comment]
Found 2 problems this time:

- [ ] Exception on username duplication:
IntegrityError at /auth/confirm_create/facebook/m.shamraeva@gmail.com/

(1062, "Duplicate entry 'Margarita' for key 'username'")

Request Method: 	POST
Request URL: 	http://unisubs.example.com:8000/en/auth/confirm_create/facebook/m.shamraeva@gmail.com/
Django Version: 	1.4.21
Exception Type: 	IntegrityError
Exception Value: 	

(1062, "Duplicate entry 'Margarita' for key 'username'")

Exception Location: 	/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py in defaulterrorhandler, line 36

- [ ] After signing up with FB account and deactivating it, could not sign in with the same FB account anymore

**Comment by syl22-00** [comment]
Both were fixed in the branch:

* Fixed race condition when trying to create an account with existing username
* If a FB account is associated with an inactive amara account, we delete the association and create a new user

**Comment by PCF-Testing** [comment]
Looks great to me now, except for https://github.com/pculture/unisubs/issues/2727, which can be handled as a separate issue. Making a PR.

**Comment by PCF-Testing** [comment]
Deployed.
