### ISSUE TITLE
Use stable ids instead of usernames

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2625]
Users can change their usernames in amara, this poses issues whenever we want to use the username as an identifier.  Particularly in the API.

For example, suppose I get a username returned in the video.added_by field, or as one of the collaborators in the subtitle request field.  If I try to look up info on that user later, there's no guarantee that they will still have the same username.  In fact, it's possible that a totally different user now has the username.

One fix for this is to start using a different identifier that doesn't change.  The id field could be used, although I don't know how great that is since it's an auto-increment field so someone could easily guess them.  I can't think of a particular security issue with that, but there's a possibility.  I think the best way would be either to create a new field that stores a random value, or to encrypt the userid field using our secret key.

We then would need to update the API code:
  - Return the identifier in all API responses rather than the username
  - Allow both usernames and user identifiers in the `/api/users/` resource.
   - To do this, we need a way of differentiating usernames from user ids.  Maybe we make all user ids start with a special character.  The only issue is what character, `$` and `@` are in use.  `%` is open, but that's an sql operator so maybe it's not the best.  `!` and `*` are open, although they seem a bit ugly to me.
   - An alternative is to use a different path like `/api/users/ids/`.  Seems a bit ugly to me
   - One more alternative is to add a query param, like `?lookup=id`.  I don't love that changing the querystring changes what resource is referred to, but I think it would work.
   - One nice thing about any of these schemes is that we could extend them to work with alternate identifiers.  For example, we store identifiers for some of our partners.  We could extend the scheme to allow them to use those ids instead of our own ids, or usernames.

There's also the non-api issues.  These seem less important, but there could be problems here.
  - We several batch import methods that use usernames to identify users
  - The various ways users interact in a team.  For example, I remember working with "babyface123" on a previous collaboration.  But if I now see that username again, maybe it's a different user

**Comment by PCF-Testing** [comment]
Using an immutable GUID to identify a user sounds good to me.

The non-API issues do not seem to be of much concern to me. Batch import is used by Amara staff on users whose usernames have been pre-arranged, stored on a special list and not supposed to change without the other party knowing it. In team collaboration environment, if the collaborator's personality matters, there are ways to check the user by full name, avatar, activity history, personal data, TED profile URL, video submissions. Finally, in real world usernames are unlikely to be changed often at whim; normally, the need to change would occur before retiring from Amara and deactivating the account, or for replacing Google/FB usernames (e.g. John456 or username@gmail.com) with something more convenient.

**Comment by bendk** [comment]
Okay I just pushed this in the ted-api-changes branches on both unisubs and amara-enterprise.  I need to write up a description of the changes for the API users email, so I figure now is a good time.  Read here for a description of the changes:

https://docs.google.com/document/d/1UHdLdi8vB8UOBe88JRix_Aeh5I-TFNCNArhw91jCI4w/edit#

I plan to add a couple more API changes to this branch and update that doc to reflect them.  But for this issue, we can just focus on the user changes.

**Comment by PCF-Testing** [comment]
Attempt to change team member's role with PUT /teams/[team-slug]/members/[username]/ through HTML form always produces 400 Bad Request - Invalid user.

The same action through Raw Data tab causes the following exception:

AttributeError at /api/teams/work-team/members/subtitler1/
'dict' object has no attribute 'split'
Request Method:	POST
Request URL:	http://192.168.1.133:8000/api/teams/work-team/members/subtitler1/
Django Version:	1.4.21
Exception Type:	AttributeError
Exception Value:	
'dict' object has no attribute 'split'
Exception Location:	/opt/apps/amara/apps/api/userlookup.py in lookup_user, line 59

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/apps/api/views/apiswitcher.py" in view
  44.                 response = old_view(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py" in wrapped_view
  77.         return view_func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py" in view
  87.             return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in dispatch
  464.             response = self.handle_exception(exc)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in dispatch
  461.             response = handler(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py" in update
  69.         serializer.is_valid(raise_exception=True)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in is_valid
  197.                 self._validated_data = self.run_validation(self.initial_data)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in run_validation
  391.         value = self.to_internal_value(data)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in to_internal_value
  421.                 validated_value = field.run_validation(primitive_value)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py" in run_validation
  641.         return super(CharField, self).run_validation(data)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py" in run_validation
  430.         value = self.to_internal_value(data)
File "/opt/apps/amara/apps/api/fields.py" in to_internal_value
  58.                 return userlookup.lookup_user(identifier)
File "/opt/apps/amara/apps/api/userlookup.py" in lookup_user
  59.     parts = identifier.split('$', 1)

Exception Type: AttributeError at /api/teams/work-team/members/subtitler1/
Exception Value: 'dict' object has no attribute 'split'

**Comment by PCF-Testing** [comment]
/videos/[video-id]/languages/[language_code]/subtitles/notes/ still has "user" parameter that returns username as the value. Example:

       {
            "user": "evaluator1",
            "created": "2016-07-12T09:14:49Z",
            "body": "test"
        }

**Comment by bendk** [comment]
First question: are you using the api-future paramater?  If not you're going to get the old API version.  To test please make sure that without that parameter the API doesn't change, and with with `api-future=20161201` you get the new version.

I just pushed several fixes:

  - Fixed the old version of the team member resource.   I think that's the bug you were hitting
  - Fixed the subtitle language resources so that it returns the old version if the api-future param isn't present.
  - Note that I didn't do this for the the subtitles resource since the author field wasn't present before, so adding it with the new data is backwards compatible.  I updated the google doc with notes on what is effective immediately and doesn't need the api-future flag.
  - Fixed the user field in the new version of the subtitle notes resource

**Comment by PCF-Testing** [comment]
Cannot start the local instance after the latest updates on the branch - start fails with the following exception:
worker_1 | Traceback (most recent call last):
worker_1 |   File "/opt/apps/amara/manage.py", line 37, in <module>
worker_1 |     startup.startup()
worker_1 |   File "/opt/apps/amara/startup.py", line 68, in startup
worker_1 |     run_startup_modules()
worker_1 |   File "/opt/apps/amara/startup.py", line 58, in run_startup_modules
worker_1 |     __import__('%s.startup' % app)
worker_1 |   File "/opt/apps/amara/amara-enterprise/ted/startup.py", line 3, in <module>
worker_1 |     from ted import apiextra
worker_1 |   File "/opt/apps/amara/amara-enterprise/ted/apiextra.py", line 55, in <module>
worker_1 |     @extra.user.handler('ted_id')
worker_1 | AttributeError: 'module' object has no attribute 'user'

**Comment by PCF-Testing** [comment]
- [ ] Activity endpoint only includes old-style usernames:

GET /api/activity/?api-future=20161201
        {
            "id": 783,
            "type": 4,
            "type_name": "version-added",
            "created": "2016-09-01T13:43:53Z",
            "video": "nYbaGAvARgxg",
            "video_uri": "http://192.168.1.133:8000/api/videos/nYbaGAvARgxg/",
            "language": "en",
            "language_url": "http://192.168.1.133:8000/api/videos/nYbaGAvARgxg/languages/en/",
            "user": "HanUser",
            "comment": null,
            "new_video_title": null,
            "resource_uri": "http://192.168.1.133:8000/api/activity/783/"
        }

- [ ] Tasks endpoint - when assigning tasks, will it be necessary to update every field in the user dict? It seems pretty awkward. I haven't found a good way to actually try that because PUT request does not go well with ?future-api=20161201 query in the URL. Same question for assigning subtitle-requests.

**Comment by bendk** [comment]
That first exception should be fixed, I forgot to push the branch on unisubs, but I did that yesterday.

For all endpoints, when you send the data you can either send a username, or the ID in the form of `id$[user-id]`.  Just a single string, no need for a dict.  You can also use the partner-specific form that we set up.

What's happening with PUT requests?  It should work.  I'm guessing if you're seeing an issue it's with the browsable API.  We should fix that if it's not too much work since people will probably try to test with that.

**Comment by PCF-Testing** [comment]
Confirming that the exception has been fixed. Also figured out the way to update assignees for tasks / subtitle requests - should provide just one string value for "assignee" parameter, e.g. {"assignee":"TestUser"}; this works both through the browser and in a Python script.

The only remaining question is related to Activity endpoint - it still only provides the username of the user who performed the action. Is it going to get changed?

**Comment by bendk** [comment]
Yes, I need to fix the activity endpoint.  It should get changed to match the rest.

**Comment by bendk** [comment]
I just pushed a bunch of changes:

- Updated the activity endpoint.
- Updated the messages endpoint.  This doesn't change much, but it makes it possible to send messages using a user ID rather than a username
- Updated that google doc, can you take a look at it and tell me if it looks okay?
- Updated the API docs.  The new API is documented here: http://amara.readthedocs.io/en/newapi/.  I considered linking from the old API docs to that page, but it's a lot of work.  I think we should just point our partners to those pages instead.

**Comment by PCF-Testing** [comment]
- Messages can be sent to "user":"id$"+user_id. Messaging to "user":user_id causes "Invalid user" error.

- At http://amara.readthedocs.io/en/newapi/ I only see "Sorry, this page does not exist yet". Does it require authorization for viewing the content?

- Filtering tasks by user ID without id$ prefix (e.g. /teams/ted/tasks/?api-future=20161201&assignee=lrndHN2lnJRjVt24yf5dXCYFWas-8uvGBURCZhjyg2o) causes an exception:

DatabaseError at /api/teams/ted/tasks/
(1242, 'Subquery returns more than 1 row')
Request Method:	GET
Request URL:	http://192.168.1.133:8000/api/teams/ted/tasks/?api-future=20161201&assignee=lrndHN2lnJRjVt24yf5dXCYFWas-8uvGBURCZhjyg2o
Django Version:	1.4.21
Exception Type:	DatabaseError
Exception Value:	
(1242, 'Subquery returns more than 1 row')
Exception Location:	/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py in defaulterrorhandler, line 36

Shouldn't the endpoint just gracefully return 0 objects if the user id does not match the expected format?
Same thing happens when filtering applications to team.

**Comment by bendk** [comment]
- The first bullet above is correct behavior.  If you don't include the `id$` prefix, then we lookup by username.  This allows us to keep API compatibility with existing code.
 - I fixed things so the readthedocs builds again
 - I just pushed a fix so that we return 0 objects in those cases

**Comment by PCF-Testing** [comment]
The fixes look good, but after the latest changes Videos resource gives the following exception:

GET /api/videos/?team=ted
KeyError at /api/videos/
'public'
Request Method:	GET
Request URL:	http://192.168.1.133:8000/api/videos/?team=ted
Django Version:	1.4.21
Exception Type:	KeyError
Exception Value:	
'public'
Exception Location:	/usr/lib/python2.7/collections.py in pop, line 143

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/apps/api/views/apiswitcher.py" in view
  44.                 response = old_view(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py" in wrapped_view
  77.         return view_func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py" in view
  87.             return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in dispatch
  464.             response = self.handle_exception(exc)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in dispatch
  461.             response = handler(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py" in list
  45.             return self.get_paginated_response(serializer.data)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in data
  658.         ret = super(ListSerializer, self).data
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in data
  223.                 self._data = self.to_representation(self.instance)
File "/opt/apps/amara/apps/api/views/videos.py" in to_representation
  325.         return super(VideoListSerializer, self).to_representation(videos)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in to_representation
  598.             self.child.to_representation(item) for item in iterable
File "/opt/apps/amara/apps/api/views/videos.py" in to_representation
  443.         data = super(VideoSerializer, self).to_representation(video)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in to_representation
  456.                 ret[field.field_name] = field.to_representation(attribute)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in to_representation
  598.             self.child.to_representation(item) for item in iterable
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in to_representation
  443.         fields = self._readable_fields
File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py" in __get__
  41.         res = instance.__dict__[self.func.__name__] = self.func(instance)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in _readable_fields
  337.             field for field in self.fields.values()
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in fields
  323.             for key, value in self.get_fields().items():
File "/opt/apps/amara/apps/api/views/videos.py" in get_fields
  709.         fields['visible'] = fields.pop('public')
File "/usr/lib/python2.7/collections.py" in pop
  143.             raise KeyError(key)

Exception Type: KeyError at /api/videos/
Exception Value: 'public'

**Comment by bendk** [comment]
That last issue should be fixed now.

**Comment by PCF-Testing** [comment]
Verified the fix.

Stumbled on yet another exception when looking up a subtitle request:
GET /api/subtitle-requests/A0P4OQJ/

NoReverseMatch at /api/subtitle-requests/A0P4OQJ/
Reverse for 'users-detail' with arguments '()' and keyword arguments '{'username': u'HanUser'}' not found.
Request Method:	GET
Request URL:	http://192.168.1.133:8000/api/subtitle-requests/A0P4OQJ/
Django Version:	1.4.21
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'users-detail' with arguments '()' and keyword arguments '{'username': u'HanUser'}' not found.
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 422
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py" in wrapped_view
  77.         return view_func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py" in view
  48.             return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in dispatch
  464.             response = self.handle_exception(exc)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in dispatch
  461.             response = handler(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/generics.py" in get
  256.         return self.retrieve(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py" in retrieve
  58.         return Response(serializer.data)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in data
  487.         ret = super(Serializer, self).data
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in data
  223.                 self._data = self.to_representation(self.instance)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in to_representation
  456.                 ret[field.field_name] = field.to_representation(attribute)
File "/opt/apps/amara/amara-enterprise/enterpriseapi/views/collab.py" in to_representation
  261.             }, request=self.context['request'])
File "/usr/local/lib/python2.7/dist-packages/rest_framework/reverse.py" in reverse
  51.         url = _reverse(viewname, args, kwargs, request, format, **extra)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/reverse.py" in _reverse
  64.     url = django_reverse(viewname, args=args, kwargs=kwargs, **extra)
File "/opt/apps/amara/apps/localeurl/__init__.py" in reverse
  18.             path = django_reverse(viewname, urlconf, args, kwargs, prefix, current_app)
File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py" in reverse
  502.     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py" in _reverse_with_prefix
  422.                 "arguments '%s' not found." % (lookup_view_s, args, kwargs))

Exception Type: NoReverseMatch at /api/subtitle-requests/A0P4OQJ/
Exception Value: Reverse for 'users-detail' with arguments '()' and keyword arguments '{'username': u'HanUser'}' not found.

In http://amara.readthedocs.io/en/newapi/api.html#tasks-resource, the description of assignee parameter looks broken:
assignee (user-identifier) – Task assignee (:ref:`user_ids`)
Was it supposed to link to http://amara.readthedocs.io/en/newapi/api.html#user-identifiers?

http://amara.readthedocs.io/en/newapi/api.html#get--api-teams-(team-slug)-applications-(application-id)-- has an unwanted colon at the end.

**Comment by bendk** [comment]
That NoReverseMatch exception should be fixed now and I also updated the newapi docs.

**Comment by PCF-Testing** [comment]
Looks good now.

**Comment by PCF-Testing** [comment]
Deployed.
