### ISSUE TITLE
Start migration towards experimental editor

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2626]
We want to support an experimental editor to test out new, radical, changes and get feedback from users.  However, this is tricky to do when we already have the legacy editor as an option.  We don't want to overwhelm users with lots of options.

Initially, I think we should work it like this:
  - The "normal" editor is the default
  - If `?legacy` is present in the URL, then we load the legacy editor.  On the normal editor is a button that links to that
  - If `?experimental` is present, then we load the experimental editor.  Users need to manually add that to the URL to see the experimental editor.

Eventually, we can reverse the situation and make the button from the normal editor point to the experimental editor and but allow users to get to the legacy editor by manually adding `?legacy` to the URL.

What should happen code-wise when the experimental editor is enabled?
  - In the template code, we set the `experimental` variable to be true.  This allows us to change things in the templates.
  - One of the differences is that we load a different CSS file.  I'm thinking we can use SASS to minimize the effort required to support this. 
  - We also load a different JS file.  Likewise I think we can use angular to minimize the work needed here -- the 2 JS files can be basically the same, except for a small number of modules.

**Comment by PCF-Testing** [comment]
Is this implemented on dev branch? I don't seem to find another suitable match in the list of branches...

**Comment by bendk** [comment]
It is implemented, although there's no experimental editor code yet so there's not much to test.  I don't think there really needs to be any testing at all in fact.  Let's just close this one.
