### ISSUE TITLE
Add visible flag to the language resource

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2628]
When you go to the videos resource, you see a visible flag for each language which is True if there is any public version of the language. We should add that flag to the language resource.  We might also consider changing the name at that point, since we don't normally use the term "visible".

**Comment by bendk** [comment]
Implemented in the ted-api-changes branch.  I decided to rename it to "public".  See notes in that google doc.

**Comment by PCF-Testing** [comment]
Verified locally.

**Comment by bendk** [comment]
I actually just changed the new name to "published".  This matches the term we use in the subtitle version data.

**Comment by PCF-Testing** [comment]
On Videos endpoint, the flag is named "visible":

"languages": [
                {
                    "code": "en",
                    "name": "English",
                    "dir": "ltr",
                    "subtitles_uri": "http://192.168.1.133:8000/api/videos/7phhOwutVrkG/languages/en/subtitles/",
                    "resource_uri": "http://192.168.1.133:8000/api/videos/7phhOwutVrkG/languages/en/",
                    "visible": true
                }
            ],

Is this as expected?

**Comment by bendk** [comment]
That's not expected.  Did you use the api-future param?

**Comment by PCF-Testing** [comment]
Ah, no - this was the culprit. With api-future, Videos also display "public" parameter for languages. Language endpoint always has "public", regardless of api-future in the URL.

**Comment by bendk** [comment]
That sounds right to me.  The video endpoint is losing the old key, so it needs the api-future param.  The language endpoint is just getting a new key, which should be okay to change without warning.

**Comment by PCF-Testing** [comment]
Deployed.
