### ISSUE TITLE
Broken link in Provider Submitted Subtitles action record

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2631]
Observed on staging: http://staging.amara.org/en/teams/work-team/videos/rLt5MNSdiOM4/collaborations/en

Entry: 
provider submitted the English subtitles request for a href="/en/videos/rLt5MNSdiOM4/info/stone-forest-kunming-china-in-4k-ultra-hd/">Stone Forest, Kunming, China in 4K (Ultra HD)

![brokenlinkprovidersubmittedsubtitlesaction](https://cloud.githubusercontent.com/assets/288455/18204450/b52f93e4-70d1-11e6-94c4-6618c03f5643.png)

**Comment by PCF-Testing** [comment]
Same problem with Provider Accepted Subtitle Request:

http://staging.amara.org/en/teams/provider-queue-test/activity/?type=collab-provider-accept&video_language=&subtitle_language=&sort=-created

PCF QA provider accepted the English subtitles request for a href="/en/videos/qn7WWpEtPcyX/info/rare-black-bear-in-vancouver/">Rare black bear in Vancouver

and with Unassigned Subtitle Request from Provider:

http://staging.amara.org/en/teams/provider-queue-test/activity/?type=collab-provider-unassign&video_language=&subtitle_language=&sort=-created

Maggie S unassigned the provider for the English subtitles request for a href="/en/videos/qn7WWpEtPcyX/info/rare-black-bear-in-vancouver/">Rare black bear in Vancouver

**Comment by bendk** [comment]
This was pretty simple.  I pushed the fix directly to master.

**Comment by PCF-Testing** [comment]
Verified locally.

**Comment by PCF-Testing** [comment]
Deployed.
