### ISSUE TITLE
Allow deleting subtitle requests / subtitle languages via the API

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2635]
We should allow API clients to delete these via the API

- Deleting a subtitle language means calling SubtitleLanguage.nuke_language().
- Deleting a subtitle request means removing it from the database.

For both of these, we should allow this only if the user is an admin of the team that owns the video.

**Comment by bendk** [comment]
Deleting subtitle languages is implemented in the more-api-changes branches.  You can do it by sending a DELETE request to the subtitles resource.

When testing this one, can you also check that deleting a language using the regular form still works?  I made some changes to the permission checks there that should be tested.

**Comment by PCF-Testing** [comment]
Deleting subtitles works on the branch as follows:
- Team admins may delete subtitles for their team's videos
- Superusers can delete subtitles for standalone (non-team) videos
- Subtitles can be deleted with the use of regular form; languages cannot
- Deleted subtitles are marked as deleted (with visibility override setting) in the DB
- Deletion does not get logged (it probably should)
- Subtitle requests for the deleted subtitles remain in the DB
- Deleting subtitle requests is not allowed (405)

**Comment by PCF-Testing** [comment]
Deployed.
