### ISSUE TITLE
As a captioner, I want an easier process for splitting subtitle lines

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#2640]
Currently, you can: 
Pause-->put the cursor where you want to split the line-->hit shift+enter

However, if it's the second line in the subtitle that needs to split, you also have to:
Select and copy the extra words--> paste in next line or subtitle-->skip back 4/8 sec to replay-->adjust subtitle timing by dragging.  
- [ ] find out captioners' methods/process of line splitting, in what stage of subtitling do they do it?
- [ ] determine if the following would be useful: hotkey or automatic split subtitle in two (not grammatical)? Keyboard shortcut that creates a new subtitle with all the text after the cursor?  Feature to automatically create new subtitle or move lines down into following subtitles when needed?

More info on these forum topics: 
https://support.amara.org/support/discussions/topics/313472; https://support.amara.org/support/discussions/topics/28857/page/7?url_locale=; 
https://support.amara.org/support/solutions/articles/192394-how-do-i-split-a-subtitle-into; https://support.amara.org/support/discussions/topics/28857/page/8?url_locale=

**Comment by PCF-Testing** [comment]
SHIFT+ENTER merely inserts a line break into a subtitle, it does not split the subtitle into two. Line breaks should better be left as they are.

We have several tickets for implementing splitting and merging subtitles:
https://github.com/pculture/unisubs/issues/1008
https://github.com/pculture/unisubs/issues/2246

**Comment by kslottow** [comment]
Duplicate of https://github.com/pculture/unisubs/issues/2246
