### ISSUE TITLE
Raise character limit for team application form

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#2659]
There's currently a 4k character limit on the customizable text shown in a team application. Let's raise this to 15k.

**Comment by syl22-00** [comment]
Done in branch gh-2659. This only applies to the customizable text shown in a team application, please let me know if we should apply this to other fields too.

**Comment by PCF-Testing** [comment]
Works as expected, although 15K long messages look awkward on the application page.

**Comment by PCF-Testing** [comment]
Deployed.
