### ISSUE TITLE
Display JS browser alert for FB login button

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#2664]
As we're still in the process of repairing the FB auth system, let's try to do a quick deploy of a JS browser alert that will appear when the FB login button is clicked. It should read:

We are working re-enable the Facebook authorization and appreciate your patience.

If you have used Facebook to log into Amara before, please email support@amara.org for help accessing your account (include your Facebook login email address). Otherwise, please select a different authorization method.

**Comment by syl22-00** [comment]
Done in branch gh-2664

**Comment by PCF-Testing** [comment]
Verified locally.

**Comment by PCF-Testing** [comment]
Deployed.
