### ISSUE TITLE
Layout, timing issue with MP3 audio (production)

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#267]
http://www.universalsubtitles.org/en/videos/fqdecMJPYau6/info/International%20Mother%20Language%20Day,%2021st%20February%202012%20-/
1. Flowplayer is out of bounds in subtitle view - http://www.universalsubtitles.org/en/videos/fqdecMJPYau6/en/240750/.
2. In subtitling dialog, the player incorrectly shows the duration of the video equal to 2:46:40 (the actual duration is just 1:51).

**Comment by bendk** [comment]
That example link is working now, I'm guessing this got fixed along the way.
