### ISSUE TITLE
Messages to teams not delivered to recipients by email

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2673]
For team-wide messages, only onsite (IM) copies get delivered. Email copies do not get sent. They stopped getting sent recently - on Oct 11, they were still fuctioning.

This happens only for team-wide messaging. Individual user-to-user messages get delivered by IM and by email as usual.

**Comment by bendk** [comment]
I just pushed several tries to fix this one, but the last finally worked.  The problem seemed to be related to how we create bulk messages and then notify users of them.  One potential issue with the new code is it might be slower and that could affect really large teams.  I'm pretty sure it will be fine, but we should test with a really big team to see if there are any noticeable issues.
