### ISSUE TITLE
general notifications

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#2679]
We should set up a system that includes multiple notification types, which we can offer to current and new client teams and AoD.  Currently we only have the TED and Google callback types.  We need to create callback types for other teams.

**We need to know** what data we should be sending to other teams/which teams.  To start with, let's include the following in the system:
- video-added
- video-removed
- subtitles-added
- subtitles-completed (all stages completed, including evaluations if enabled)

@bendk the following notifications are highly requested, but since we don't use them already I'm thinking they should go in a separate issue.  Does that sound right?
- notify admins when subtitles are endorsed/ready for approval (this is a highly asked about feature from AE clients)
- notify translators once the original language is completed for a video, and translations are needed (for teams where translators self-assign assignments)

For reference, the following http notifications were implemented for TED in #2674:
- videos are added (`video-added`)
- videos are removed (`video-removed`)
- subtitles are added to a video (`subtitles-added`)
- subtitles are published (`subtitles-published`)
- subtitles are unpublished (AKA the language_deleted signal) (`subtitles-unpublished`)
- team member added (`member-added`)
- team member removed (`member-removed`)
- team profile info changed (`member-profile-changed`)

To test the current TED-only functionality:
- Go to the notifications section on the admin page. Create a TeamNotificationSetting for a some team. - Pick a URL and select "ted" as the type (this is the only choice at this point)
- Do some of the above actions. You should see notifications POSTed to the URL you picked.
- You can also test out the API at /api/teams/[slug]/notifications.
  Check out the updated documentation here: http://amara.readthedocs.io/en/gh-amara-enterprise-729/teams-callbacks.html

**Comment by kslottow** [comment]
Some to consider:
- notify admins when languages are complete (this is a highly asked about feature from AE clients)
- notify translators once the original language is completed for a video, and translations are needed (for teams where translators self-assign assignments)

**Comment by kslottow** [comment]
@darren-bridenbeck FYI - feel free to add any other suggestions here

**Comment by asabine** [comment]
added a new notification type `general` that includes all of the notifications from the TED teams listed above; i can take out the extras if we want but it didn't require much to include them. tested using a little python server script (all it does is listen on a port and print the http requests) to receive the notifications and they all worked as expected

**Comment by PCF-Testing** [comment]
Verified.

The implementation includes only HTTP callbacks. Messaging to admins and to translators are not covered.

**Comment by PCF-Testing** [comment]
Deployed.
