### ISSUE TITLE
Google sign-in is not working

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#2683]
Steps to reproduce:

Attempt to log in to www.amara.org or amara.org with Google Single Sign-on: gmail or google account.

**Comment by kslottow** [comment]
@bendk maybe we can see if this is fixed by rolling back #1943 ?

**Comment by bendk** [comment]
The issue was that we were using www.amara.org still when communicating with google.  I fixed it by:
  - Updated the site URL in the initial_data.yaml
  - Updated the site URL in our production DB using the admin
  - Updated the URL in the credentials section on the google console.
