### ISSUE TITLE
Amara Uploader showing duplicate Enterprise teams and no AoD teams

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#2684]
Steps to reproduce:

1) log into https://uploader.amara.org/

No On Demand teams will show under Team (mandatory) but each Enterprise team shows 10 times.

Expected: 
On Demand team shown to add the videos in mp4

From Jenny:
You'll see that none of the teams are On Demand... --- we are up to Team 615

**Comment by bendk** [comment]
The API url was www.amara.org.  I think this should be fixed, but I don't have a login to test.

**Comment by kslottow** [comment]
@bendk having Jenny from AoD test now

**Comment by PCF-Testing** [comment]
Works for me.

**Comment by kslottow** [comment]
@PCF-Testing thanks Maggie!
