### ISSUE TITLE
Add Nigerian Pidgin language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2686]
Language - Nigerian Pidgin
ISO 639 code - pcm
Directionality - LTR
https://en.wikipedia.org/wiki/Nigerian_Pidgin
Reason - request in https://pculture.freshdesk.com/helpdesk/tickets/89261

**Comment by kslottow** [comment]
@deanjansen any reason not to go ahead with this and other not-yet-supported languages?

**Comment by deanjansen** [comment]
@kslottow As long as @PCF-Testing feels good about these, I'm thumbs up too.

Would love to see what next steps are for adding Google requested languages as well: https://github.com/pculture/amara-enterprise/issues/758

**Comment by syl22-00** [comment]
This was added on unilangs in the master branch.

**Comment by PCF-Testing** [comment]
Deployed.
