### ISSUE TITLE
Some non-ASCII characters garbled in email messages from Amara

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2693]
Reported in https://pculture.freshdesk.com/helpdesk/tickets/89328

Email messages from Amara garble some non-ASCII (Japanese) characters. On the screenshot below, "問" character is displayed as "å ��".This happens for emails only; onsite messages look good.

![japanesegarbled](https://cloud.githubusercontent.com/assets/288455/20410132/b462096e-ad2c-11e6-9c8e-acd91d18166d.png)

To reproduce, send the following text as a personal message through Amara and check the email copy:

日本国内の各地でメンバーが集まる機会が相次いでいますが、国外在住のみなさんも集まってみませんか？ というわけで、オンラインミーティングのご案内です。顔合わせや翻訳にまつわる意見交換はもちろん、「世界のどこから参加してるかマップ」「ビデオ通話＆チャット」「記念スクリーンショット」など、オンラインならではの企画を考えています。LCからは庄子、広田、神谷が参加します。
初回の今回はヨーロッパ・アメリカの方に参加していただきやすい時間帯で設定しました。それ以外の地域の方もぜひご参加ください。
・開催日：2016年11月26日（土）
・開始時刻：英国 8pm/ 米東部 3pm/ 米太平洋 12 noon
その他の現地時刻は↓でご確認ください。
http://www.timeanddate.com/worldclock/converter.html
※開始前1時間を”Sandbox Time”とし、カメラやマイクのテスト、チャットの練習などをしていただけるようにご用意します。オンラインミーティング未経験の方にも安心してご参加いただけます。
※終了予定時刻は開始から1時間半（90分）後です。
・定員：10名（先着順）
国外の方を優先しますが、人数に余裕があれば日本国内の方からのお申込みも受け付けます。
・参加費：無料
イメージだけはドリンク片手にカジュアルに語る場なのですが、実際は遠隔につき、何のおもてなしもできません。お飲み物等、各自でご用意ください。
・申込方法：下記のフォームに必要事項をご記入のうえ送信してください。受付は11/19までですが、定員に達した時点で締め切りますのでご希望の方はどうぞお早めに。
ご提案やご質問等もぜひ積極的にご記入ください。できるだけ反映させ、参加者のみなさんでつくる会にしたいと思っています。
お申込み、お待ちしています！
https://goo.gl/forms/LEZTJUSCZO1c0VeM2

TED Translators 日本語 LC チーム
lc@ted-ja.com

**Comment by syl22-00** [comment]
My understanding of what was happening is that the SMTP server actually encodes the message characters using base64. There seems to be bugs in that encoding, probably due to variable length of characters and/or padding. Different smtp servers will exibit different issues.
So I made a fix which is to first encode non-ascii characters using HTML markup. That seems to resolve that issue.

**Comment by PCF-Testing** [comment]
Looks good for this particular Japanese text, but fails on other non-ASCII characters.

Example:
Source text:
РЖД планируют запустить высокоскоростную магистраль Москва-Казань до 2022 года, сообщил глава компании Олег Белозеров.
Изначально "Российские железные дороги" рассчитывали запустить скоростную линию к чемпионату мира по футболу в 2018 году, но затем сроки начала эксплуатации были сдвинуты на 2020 год.
По словам Белозерова, сейчас подготовка проекта находится в финальной стадии. В ближайшее время участок от Москвы до Владимира будет сдан на государственную экспертизу.
"Мы прошли очень большой путь с нашими китайскими и европейскими коллегами по осмыслению этого проекта и считаем, что до 2022 года сможем доехать не только до Владимира, а вероятно, и до Казани", - сказал глава компании.

Emailed version has escaped sequences:
РЖД планируют запустить высокоскоростную магистраль Москва-Казань до 2022 года, сообщил глава компании Олег Белозеров. 
Изначально "Российские железные дороги" рассчитывали запустить скоростную линию к чемпионату мира по футболу в 2018 году, но затем сроки начала эксплуатации были сдв&#10 80;нуты на 2020 год. 
По словам Белозерова, сейчас подготовка проекта находится в финальной стадии. В ближайшее время участок от Москвы до Владимира будет сдан на государственную эксп&# 1077;ртизу. 
"Мы прошли очень большой путь с нашими китайскими и европейскими коллегами по осмыслению этого проекта и считаем, что до 2022 года сможем доехать не только до Владимира, а вероятно, и до Казани", - сказал глава компании.

**Comment by syl22-00** [comment]
This seems to be another issue with the SMTP server: it cuts long lines inside the body, even in the middle of an html-encoded character. I pushed a fix, limiting line length before they are sent.

**Comment by PCF-Testing** [comment]
This time the emailed version has no escaped sequences, but spaces in wrong places (the text is the same as in the previous comment):

РЖД планируют запуст ить высокоскоростную магистраль Москва-К азань до 2022 года, сообщил глава компан ии Олег Белозеров. 
Изначально "Российск ие железные дороги" рассчитывали запусти ть скоростную линию к чемпионату мира по футболу в 2018 году , но затем сроки нач ала эксплуатации был и сдвинуты на 2020 г од. 
По словам Белозерова , сейчас подготовка проекта находится в финальной стадии. В ближайшее время учас ток от Москвы до Вла димира будет сдан на государственную экс пертизу. 
"Мы прошли очень бол ьшой путь с нашими к итайскими и европейс кими коллегами по ос мыслению этого проек та и считаем, что до 2022 года сможем до ехать не только до В ладимира, а вероятно , и до Казани", - ск азал глава компании.

**Comment by syl22-00** [comment]
Ah, sorry, so I made a fix to change spaces into new lines if HTML lines are long. That seems to work.

**Comment by PCF-Testing** [comment]
Some tests display:
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

Otherwise, looks good.

**Comment by PCF-Testing** [comment]
Deployed.
