### ISSUE TITLE
Site-wide and team-wide search not functioning

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2694]
Happens on production only.

On attempt to search for a keyword through Watch page, a red growl message ("Cannot connect to server...") appears, search produces no results.

On attempt to search in a team, a 500 error page is returned. Error: https://logs.amara.org/app/kibana#/doc/logstash-*/logstash-2016.11.30/log?id=AVizZwI0ENdhSYghp9mi&_g=()

**Comment by syl22-00** [comment]
This was a database issue which is now fixed.

**Comment by syl22-00** [comment]
@PCF-Testing could you double check before closing it?

**Comment by PCF-Testing** [comment]
Things are back to normal now, thanks!
