### ISSUE TITLE
Encoding issues in video title and description

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2699]
My understanding is as follow:

MySQL has a limitation for UTF-8 encoded columns for characters up to 3 bytes, and does not support unicode characters on 4 bytes. That has been addressed since version 5.5 but the format utf8mb4 has consequences on the max length of indexes. Migrating to this collation would be also quite invasive.

The consequences of that issue right now are different on dev and production (I do not know why they are different):
* In dev environment, if a video is added and has title or description that includes 4-byte unicode characters, the video is added but title and description are empty (title is just the URL) and there is a server error right away, while trying to add the video to the index (index is not added).
* On production, the video is added, index as well, but title and description only include the text up to the first 4-bytes unicode character.

An example video that includes 4-bytes characters in both title and description (the small contry flags):

https://www.youtube.com/watch?v=jgj_TpQkUCc

**Comment by syl22-00** [comment]
This was fixed in branch gh-2699 by replacing those 4-bytes characters with `\uFFFD`, which seems to be the "right" way to do it.

**Comment by PCF-Testing** [comment]
Looks good.

**Comment by PCF-Testing** [comment]
Deployed.
