### ISSUE TITLE
Fix 'Improve this Translation' widget menu item behavior

### ISSUE THREAD

**Issue by cz** [pculture/unisubs#27]
Margarita:

> It is currently accepted that _Improve These Subtitles_ item from the widget tab menu opens the selected subtitle set for editing without prompting the user to specify To and From languages through the start dialog..

> However, _Improve This Translation_ menu item, which is displayed to the right of the widget tab when an incomplete translation reaches its end during the video playback, does invoke the start dialog. It shouldn't.

> Steps to reproduce:
> 1. Open http://dev.universalsubtitles.org/en/pagedemo/blog_youtube_embed page.
> 2. From the widget tab, select Bulgarian (or another language with ~1% completeness).
> 3. Click Play and wait 3-4 min or pull the progress slider to the middle of the video.
> 4. Click Improve This Translation button to the right of the widget tab.

_Migrated from Pivotal [#13466289](https://www.pivotaltracker.com/story/show/13466289)_

**Comment by PCF-Testing** [comment]
This one is for old style embedder, which is no longer in use. Marking as closed.
