### ISSUE TITLE
subtitle_import_completed callback

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#2703]
Google wants a notification for  subtitle_import_completed:

- Callback url
  -	Production: https://gloc-lqa.appspot.com/amara/video-callback/
  -	Staging: https://video-dot-dev-gloc-10.appspot.com/amara/video-callback/
- Payload
  - type: "subtitles_import_completed"
  - Video ID
  - Video Name
  - Team
  - Languages imported (list)

**Comment by bendk** [comment]
I think we should offer 3 options:

- Sync and fetch (current behavior)
- Sync only
- Fetch only

**Comment by kslottow** [comment]
Google's current workaround is to move a video from one team (with YouTube integration) to another team for work (without YouTube integration)

**Comment by kslottow** [comment]
The team setting would be nice eventually, but we should go with the callback for now because:

- The callback is separate and helpful regardless of whether they are moving videos between teams
- Preference not to change the dual team workflow YET (not change too many things at once)

**Comment by kslottow** [comment]
@bendk @syl22-00 looking ahead on this one - are the requirements for the callback sufficiently clear for Sylvain to take this one on?  It will either replace pculture/amara-enterprise/issues/980 in this Sprint, or be scheduled for Sprint 5

**Comment by bendk** [comment]
I just updated the description some.

I removed the stuff about fetching subtitles without syncing them.  I made #2732 for that.

I believe after discussing things with them, we decided on a single URL for all google callbacks and a type field to differentiate them.  I added the type field, but didn't remove the part about the URLs just in case we needed that data.

**Comment by syl22-00** [comment]
Issue moved to [pculture/amara-enterprise #1069](https://github.com/pculture/amara-enterprise/issues/1069) via [**ZenHub**](https://www.zenhub.com/)
