### ISSUE TITLE
Brightcove videos: in Chrome, playback freezes on pressing TAB key

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2706]
In Chrome, Brightcove videos would not play properly in subtitle editor when TAB key is pressed. After a second or two, the video and timeline freeze. The video can only be played by clicking Play control on the video player.

This is not the case in FF, where the video can be played without issues.

Example: http://amara.org/en/videos/h1nAyEGGBVYA

**Comment by kslottow** [comment]
@PCF-Testing is this still an issue?

**Comment by PCF-Testing** [comment]
Works for me now. Also, we now embed BC videos in a different way.
