### ISSUE TITLE
Subtitle editor: upload fails during post-publish edit

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2710]
Uploading subtitles while making a post-publish edit fails - the upload dialog returns an error about file format not being supported.

**Comment by syl22-00** [comment]
The issue is that we push subtitles via the API with a "save-draft" action name. But this action is not valid after subtitles are published.

In branch gh-2710, this was fixed by not setting the action name, it should be set automatically.

**Comment by PCF-Testing** [comment]
Works for me on production.
