### ISSUE TITLE
Youtube video added via team video adding form do not always get their title and description correctly set

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2712]
When adding a video via the form in a team, the title, description and thumbnail are usually (but not always) not set correctly. Videos added via the form on home page are fine.

**Comment by syl22-00** [comment]
Fix is actually deployed already

**Comment by PCF-Testing** [comment]
Tried this out on production with a bunch of videos that had had the problem with pulling in titles and descriptions before - the issue does not happen anymore. Marking as closed.
