### ISSUE TITLE
Google OAuth login not functioning

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2716]
Clicking on Google button on Sign In page results in a 500.

**Comment by syl22-00** [comment]
It seems like the token Google returns when doing oauth has changed a little bit and does not include 'openid_id' anymore, which apparently does not matter.
So I just took this out in branch gh-2716 and that seems to fix the issue.

**Comment by PCF-Testing** [comment]
For creating new Google accounts, after the email entry screen the user is redirected back to Google account selection screen. An account gets created, but a red banner error message "Error while linking. Please try again." appears; the logs have the following exception:

app_1     | WARNING 2017-01-11 12:18:49,603 externalsites.google handle_callback: no authorization code (<QueryDict: {}>)
app_1     | ERROR 2017-01-11 12:18:49,603 root google_callback: Error while linking.  Please try again.

**Comment by PCF-Testing** [comment]
Deployed.
