### ISSUE TITLE
Revert code for issue #251

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#2717]
#251 
Since we didn't do any documentation or clues in the UI of how to use the enter key in the new context, lots of translators are getting confused by it.  

We should just revert it now and I'll put the original issue in the icebox, because we didn't find an appropriate solution for it.

**Comment by bendk** [comment]
#2719

**Comment by PCF-Testing** [comment]
Looks OK on staging.

**Comment by PCF-Testing** [comment]
Deployed.
