### ISSUE TITLE
Accommodate custom Vimeo URLs

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#273]
For Vimeo videos that have custom URLs, add the option to store the custom URL as a secondary URL, so that a custom URL could be used in embed code.

Example:
http://vimeo.com/19447662 - regular ("numeral") Vimeo URL
http://vimeo.com/kirbyferguson/everything-is-a-remix-part-2 - custom Vimeo URL for the same video

Reason why this is necessary: when embedded into a third party page, Vimeo videos with custom URL display only custom URLs under Share link. The "regular" URL may be not publicized.
https://universalsubtitles.tenderapp.com/discussions/problems/1990-2-issues-with-vimeo-videos-2-other-things

**Comment by bendk** [comment]
Decided this wasn't creating enough problems to fix.  Let's close.
