### ISSUE TITLE
More granular settings for youtube integrations

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2732]
When you link a youtube account to a team we always fetch subtitles for it and always sync subtitles for videos on that team.  We should allow users to turn this on/off.

I think that this means two additional checkboxes:
  - [x] Sync subtitles for <team-name> videos
  - [x] Fetch initial subtitles from YouTube.

I think this would go above the checkboxes for syncing for additional teams.  As a side note, I think we should change that label to read "Sync subtitles for videos from these teams:"  That's more clear in my mind, and matches the wording above.

**Comment by kslottow** [comment]
MUST be deployed by the Monday following Sprint 14; but if we can get a head start in Sprint 13 that would be a plus, so I put it at the bottom of the TODO pipeline just in case

**Comment by syl22-00** [comment]
Done in branch gh-unisubs-2732, based on futureui. It includes a migration.

**Comment by PCF-Testing** [comment]
- [ ] The options on Integrations page could use a bit more detailed description:
* Sync subtitles from Amara to YouTube
* Fetch initial subtitles from YouTube when videos are submitted to Amara

- [ ] When subtitle syncing is disabled, Sync History tab still has Success entries appearing in it, "Resync" button on Sync History tab is active

Expected: no entries on Sync History tab when subtitles do not sync to YT, Resync button should be hidden or disabled

**Comment by syl22-00** [comment]
Those have been implemented in the branch

**Comment by syl22-00** [comment]
I merged staging into the branch.

**Comment by PCF-Testing** [comment]
Works as expected.

**Comment by PCF-Testing** [comment]
Deployed.
