### ISSUE TITLE
Add Wauja language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2733]
https://en.wikipedia.org/wiki/Waur%C3%A1_language
ISO 639-3 code - wau
Directionality - LTR
Reason - request in https://pculture.freshdesk.com/helpdesk/tickets/90730

**Comment by syl22-00** [comment]
Made this early as it just took a few minutes and made it easier to test it together with https://github.com/pculture/amara-enterprise/issues/758

**Comment by PCF-Testing** [comment]
Verified on the branch.

**Comment by PCF-Testing** [comment]
Deployed.
