### ISSUE TITLE
Time filters on Activity resource not functioning without timezone

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2734]
Examples:
/api/users/@PCFQA/activity/?before=2017-01-01 (vs. /api/users/@PCFQA/activity/)
/api/teams/volunteers/activity/?after=2013-01-01 (vs. /api/teams/volunteers/activity/)

**Comment by kslottow** [comment]
Is this for v1.7 or v1.8?  

@bendk @PCF-Testing what's the urgency of this bug?

**Comment by bendk** [comment]
I'm pretty sure the issue is you need to include the timezone on the before/after time

This works: before=2017-02-11T10:57:25Z
But this doesn't: before=2017-02-11T10:57:25

I think this is fairly high prioritiy, since it's an API bug.

**Comment by syl22-00** [comment]
This was done in branch gh-unisubs-2734. I made sure filters can be set with or without time zone, and also as dates (without time).

**Comment by PCF-Testing** [comment]
Tested locally, worked well.

**Comment by PCF-Testing** [comment]
Deployed.
