### ISSUE TITLE
Support notifications for multiple teams

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2739]
Right now the TeamNotificationsSettings model in the notifications app only supports one team.  We have many partners that have multiple teams.  We should support firing the events for multiple teams

I think the best way is to keep the team field and an extra one-to-many field called "extra_teams" or something.

- The team in the team field should still be considered the "primary team".  Meaning:
  - We calculate the numbers based on that team
  - The API endpoints use that team's slug
  - The other teams are simply there to cause extra notifications to fire when things happen on those team's videos.

**Comment by bendk** [comment]
@syl22-00 can you prioritize this one?  It would make things simpler with the google integration.

**Comment by syl22-00** [comment]
This was done in branch gh-unisubs-2739 in unisubs repo. It inlcudes a migration. extra teams can be added from the admin ui.

**Comment by syl22-00** [comment]
I just pushed some fixes and tests.

One thing I am not sure: shall the TeamNotification object still point to the primary team or the team that actually fired the notification. And how about the number, I am not 100% sure what that means to compute the number based on the primary team.

What I pushed is that the created TeamNotification still all point to the primary team, even if fired from another team (clients should be able to get the proper team that fired from the data field), hence the notification number keeps getting up every time a notification fires, be it from primary or extra team.

**Comment by PCF-Testing** [comment]
@bendk: @syl22-00: "team" parameter returns the team the notification setting is tied to, not the team where the event has actually happened. Is this the correct behaviour? I don't think so.

Example - sample callback for video-added event in team-two (which shares the same notification settig with team-one):
{"number": 3, "youtube_video_id": null, "project": "project-one", "team": "team-one", "amara_video_id": "LbNam5jwoHxP", "event": "video-added"}

**Comment by syl22-00** [comment]
@PCF-Testing So I just pushed a change for this: in TED's notifications, team now matches the team that really triggered the notification, not the primary team. If they are different, I added a primary_team field.

This requitres also amara-enterprise on branch gh-unisubs-2739

**Comment by PCF-Testing** [comment]
Works as expected now.

**Comment by PCF-Testing** [comment]
Deployed.
