### ISSUE TITLE
API: Unassign user from collab expects empty array/dict, docs ask for null

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2741]
https://amara.readthedocs.io/en/latest/api.html#updating-requests

Currently the docs say you have to pass null to unassign the user, but the request only succeeds on passing an empty array/dict.

The same key expects a string type for assigning an username, not a string inside an array/dict. Aside from updating the docs, as API user I'd expect it to be either string / null, or array(string) / array(), but not string / array()

**Comment by bendk** [comment]
This seems to be working now.  If I'm wrong, please re-open and give me a specific example request.
