### ISSUE TITLE
Some characters in video description cause video page to 500

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2743]
Error log: https://logs.amara.org/app/kibana#/doc/logstash-*/logstash-2017.02.06/log/?id=AVoVGQTzENdhSYghigKp

Square brackets in the video description caused a 500 error on the video page. The same page with the brackets removed is displayed nicely.

>Creator of the ...

>[AV and event video provided by http://repertoireproductions.com].  

>...

>This talk was given at a TEDx event using the TED conference format but independently organized by a local community. Learn more at http://ted.com/tedx

**Comment by PCF-Testing** [comment]
https://pculture.freshdesk.com/helpdesk/tickets/91017

**Comment by bendk** [comment]
This is another instance of #1112.  We closed that one because we thought we would update django, but that hasn't happened yet.

**Comment by PCF-Testing** [comment]
Works on rebuilt staging branch locally.

A few tests are broken though:

======================================================================
FAIL: test_fetch_subs (externalsites.tests.test_subfetch.SubFetchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/externalsites/tests/test_subfetch.py", line 95, in test_fetch_subs
    mock.call('test-access-token', 'caption-2')
AssertionError: [] != [call('test-access-token', 'caption-1'), call('test-access-token', 'caption-2')]

======================================================================
FAIL: test_fetch_subs_handles_bcp47_codes (externalsites.tests.test_subfetch.SubFetchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/externalsites/tests/test_subfetch.py", line 144, in test_fetch_subs_handles_bcp47_codes
    mock.call('test-access-token', 'caption-1'))
AssertionError: None != call('test-access-token', 'caption-1')

======================================================================
FAIL: test_mapping_from_youtube (externalsites.tests.test_youtube_api.TestYoutubeMapping)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/externalsites/tests/test_youtube_api.py", line 294, in test_mapping_from_youtube
    self.assertEqual(subfetch.convert_language_code('en'), 'en')
AssertionError: None != 'en'

======================================================================
FAIL: test_mapping_to_youtube (externalsites.tests.test_youtube_api.TestYoutubeMapping)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/externalsites/tests/test_youtube_api.py", line 308, in test_mapping_to_youtube
    self.assertEqual(convert_language_code('pt', True), 'pt-PT')
AssertionError: 'pt' != 'pt-PT'

**Comment by bendk** [comment]
The tests are passing for me now.  I think we can close this one.

**Comment by PCF-Testing** [comment]
@bendk: Has this one been deployed yet? We close tickets once the fixes get deployed and included into release notes.

**Comment by bendk** [comment]
Oops, sorry about that.  Not sure what I was thinking.

**Comment by PCF-Testing** [comment]
Deployed.
