### ISSUE TITLE
Make it so when you upload via the subtitle editor, we label it "Uploaded"

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2754]

**Comment by bendk** [comment]
Done in gh-2754 branch.

**Comment by PCF-Testing** [comment]
One test is broken on the branch:

======================================================================
FAIL: test_from_editor (api.tests.test_subtitles.SubtitlesSerializerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/api/tests/test_subtitles.py", line 401, in test_from_editor
    assert_equal(version.origin, ORIGIN_WEB_EDITOR)
AssertionError: 'api' != 'web-editor'


The rest looks good.

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
