### ISSUE TITLE
Moving away from google language ajax api for guessing languages

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#276]
The test  videos.TestTasks.test_notification_sending  has recently began failing.
We need to investigate if there is anything we can do about this right away, or if this is part of moving away from Google's languages api.

One interesting thing to consider is using Python Natural Language Toolkit. It has language detection, amongst other things. It is though, a bit of a resource bloat.

In my local testing, it takes about 20 MB in memory, which is not a small amount.
This code ends up being run a lot, since it is on the video saving task.

One thing to consider is creating a very simple webapp (flask?) that acts as a service and we'd replace the ajax call to Google's service with ours. This has some infrastructural challenges as that would require setting up a server on one of the helper machines (pcf admin, most likely)

**Comment by bendk** [comment]
I don't believe we use this anymore.
