### ISSUE TITLE
Truncate notification history for teams

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2760]
Right now we keep a log of all notifications we ever sent to a team.  This could add up to  a lot of data if we let them build infinitely.  What about this system:

- We keep:
   - The last 1000 notifications for each team.
   - Any notification less than 90 days old
- Other notifications get deleted in a task that runs once a day.

The first step is checking with google and TED to see if this works for them.

Assigning to kenzie since right now we're in the communication step.

**Comment by PCF-Testing** [comment]
1000 notifications/team sounds too few, some teams generate more callbacks in a single day.

**Comment by bendk** [comment]
Yes.  The two clauses should be joined with OR.  So we delete them when they're older than 90 but not the most recent 1000 notifications

**Comment by kslottow** [comment]
Just sent a draft email to engineering and Dean+Aleli to check with Google and TED about this.

**Comment by kslottow** [comment]
Confirmed with TED and Google that this is ok!

**Comment by kslottow** [comment]
@bendk can this be scheduled or does it need to be fleshed out more?

**Comment by bendk** [comment]
I think it's ready.

**Comment by PCF-Testing** [comment]
@bendk: @asabine: gh-unisubs-2760 is a branch created from futureui instead of staging, is it the correct thing to do?

**Comment by bendk** [comment]
I think staging would have been a better base branch, since it isn't tied to the new UI changes.  That said, I think we will merge futureui before we need this code, so I think it's okay.

**Comment by bendk** [comment]
If you want to move so it's based off  the staging branch that's great with me.

**Comment by PCF-Testing** [comment]
Actually I have already set up the test data on the branch spun from futureui and now waiting for the system to delete data from the log.

**Comment by asabine** [comment]
in that case i'll hold off on rebasing it for now. if it becomes necessary to do so later i'll change it over, shouldn't take more than a few minutes so either way is fine for me :)

**Comment by PCF-Testing** [comment]
@asabine: when is the log truncation task supposed to run? I have changed the timestamp in the notification subtracting 91 days, but after almost a day of waiting the notification is still there.

**Comment by asabine** [comment]
it's supposed to run once a day at midnight i believe? unless i'm missing something  in task_settings.py:
```
'prune_notification_history': {                                                                                                                                                                                                       
    'task': 'notifications.tasks.prune_notification_history',                                                                                                                                                                         
    'schedule': crontab(hour=0),                                                                                                                                                                                                           },
```

**Comment by asabine** [comment]
it also only deletes a comment if it's not in the most recent 1000 comments for a given team, so if there's less than 1000 and it's 91 days old it'll remain in the log.

**Comment by PCF-Testing** [comment]
Works as expected locally.

**Comment by bendk** [comment]
@asabine I added a comment to the pull request.  I'm not sure you get notifications for that though.  I just had a small suggestion for the code:

https://github.com/pculture/unisubs/pull/2793

**Comment by asabine** [comment]
hi! i didn't get a notification for it, sorry about that. i'll get that taken care of now :)

**Comment by PCF-Testing** [comment]
Deployed.
