### ISSUE TITLE
Video listing pages are slow

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2766]
The video listing pages run slowly, specifically /videos/watch/latest/.  We should speed them up.

**Comment by bendk** [comment]
The main issue with this was the latest videos query.  I just fixed that. 

Another issue is counting the total number of results, which really should be quick.  I'm going to let that slide for now though and we can continue to monitor it.

**Comment by syl22-00** [comment]
@PCF-Testing found that  http://staging.amara.org/en/videos/watch/ times out. I tried the 2 queries on twitter and did not find significant timing difference (with -id or -created for ordering)

**Comment by bendk** [comment]
It's the recent videos page that I wanted to speed up.  I think that page had "latest/" appended at the end.

All of the pages are pretty slow.  I think the count query is a big factor there.  But I only wanted to change the part that seemed worst.

**Comment by PCF-Testing** [comment]
Deployed.
