### ISSUE TITLE
v1.7: 500 error on subtitle sync tab

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2770]
http://amara.org/en/videos/eSe9MsMdhLnP/en/823416/?tab=sync-history

Error: https://logs.amara.org/app/kibana#/doc/logstash-*/logstash-2017.02.24/log/?id=AVpuB0s3ENdhSYghTQLV

**Comment by kslottow** [comment]
@PCF-Testing this is in v1.7, correct?

**Comment by PCF-Testing** [comment]
> this is in v1.7, correct?
Yes.

**Comment by bendk** [comment]
To reproduce:

 - Sync a youtube channel with an old-style team
 - Add a video from that channel to the team
 - Add subtitles to the video and ensure they sync to youtube
 - Delete the youtube account via the django admin (I think there used to be a way to do this with the UI, but I can't do it anymore)
 - Re-link the youtube channel
 - Go to the sync history tab for the subtitles
 - Resync the version
 - At this point you should see the error

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
