### ISSUE TITLE
Automatic task creation has stopped working

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2773]
Observed on production, can be reproduced.

Steps to reproduce:
1. Open Settings pages for a team with tasks.
2. On Workflow tab (/settings/workflows/), make sure that "Automatically create translation tasks for preferred languages" is ON.
3. On Languages tab (/settings/languages/), add several languages and save.
4. Pick any existing task for this team and complete it.

Expected: new tasks for the languages added in p.3 should have been created.
Observed: no new tasks get created.

**Comment by bendk** [comment]
This works for me when I tested it.  The tasks only get created once the final task for a language is complete -- they won't get created if there's still a review/approval task to complete for the language.  I don't think that part is a regression.  I did confirm that they get created regardless of if the task is a translation or transcription task and also with preferred languages that get added later.

**Comment by PCF-Testing** [comment]
Well, this may be quite a problem with older videos. New languages for translation get added relatively often, while http://www.amara.org/en/videos/PLWRUV8r5D69/ has not had any languages approved and any new tasks created since 2014: https://amara.org/en/admin/teams/task/?q=On+reading+the+Koran. The video had a post-publish edit on one of the languages a couple of months ago, but that did not generate the missing tasks.

We need a better idea when and how to get the missing tasks (or collabs) created reasonably promptly, but without compromising the system's performance. Some possible options could be:
- When a new language is added to the team settings
- When someone touches any collab (e.g joins or leaves a collab or endorses/sends back)
- A periodic task (say, monthly). I suspect this one is the worst choice performance-wise.

**Comment by bendk** [comment]
The first bullet is how it works with the collab model.

We could add a periodic task, that would probably be only a few hours of work.  But unless a partner is complaining, I'd rather skip it and move people to the collab model.

**Comment by PCF-Testing** [comment]
OK, then how about the following solution: the most visible project that is affected by this issue has around 2300 videos. I could make and run a script that would add tasks for the missing languages - should be quick and easy to do and can be re-run, if necessary. This could solve the problem until the switch to collab model.

**Comment by bendk** [comment]
Sounds good to me.  How would you make the script?  I can think of a really easy way with the django shell, but not so easy with the API.

**Comment by PCF-Testing** [comment]
I was thinking of using API for this purpose.

**Comment by bendk** [comment]
I was thinking that would take really long, but if you have a way to do it that doesn't take a lot of your time that's great.  I could do it in about 10 minutes work with the django shell.

**Comment by PCF-Testing** [comment]
Ran the script to create the missing tasks. I believe this should resolve the problem until the switch to collabs.
