### ISSUE TITLE
Add Picard language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2779]
ISO 639-3 code: pcd
Directionality: LTR
https://en.wikipedia.org/wiki/Picard_language

Reason: request in https://pculture.freshdesk.com/helpdesk/tickets/91848

**Comment by syl22-00** [comment]
Done in unilangs directly.

**Comment by PCF-Testing** [comment]
Great, thanks! Marking as Waiting for Deploy.

**Comment by PCF-Testing** [comment]
Deployed.
