### ISSUE TITLE
"Add Translation" button (instead of Edit) on language pages

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#278]
Language pages sometimes display "Add Translation" instead of "Edit Translation" button. Hence, users have to use "Improve These Subtitles" widget menu command instead or click "Add Translation" and select the correct language pair from Create  Subtitles dialog manually before editing.

This is a very old bug, which may be, AFAIK, a bit hard to reproduce. Probably the best way to repro is as follows:
1. Submit a new video (or find one with 0 languages and Original language blank).
2. Click Subtitle Me on the widget tab.
3. In Create Subtitles dialog, select two different languages for Video In and Subtitle Into.
4. Make some subs and save.
5. Open the language page.

Examples:
https://dev.universalsubtitles.org/en/videos/6m7KilG5sdbC/es/37160/
http://www.universalsubtitles.org/en/videos/TVFxHBPXo1XS/sv/192276/

NB: Ideally, fixing this bug should involve a code walkthrough checking all the conditions when "Add Translation" appears instead of "Edit Translation".

**Comment by PCF-Testing** [comment]
We now have "Edit Subtitles" on language pages. Closing.
