### ISSUE TITLE
Accommodate hidden Vimeo videos

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#279]
USubs currently does not support submission and subtitling of hidden videos from Vimeo.com:

1) While Hide from Vimeo.com privacy setting is turned on, the video cannot be submitted to UniversalSubtitles.org - an attempt to do so results in error "This URL appears to be a broken link".
The workaround is to make the video public, submit it to USubs, and then turn the privacy on again (3 steps on 2 websites).

2) Once the video has been submitted, subtitled and made private again, the widget tab can be either displayed nicely or show Subs Unavailable (onsite or offsite). There is no 100% correlation between the current state of the widget and the value of Hide from Vimeo parameter, but in general private videos do tend to "lose" subtitles, turning to Subs Unavailable mode. This may happen as soon as you try to edit or translate subs for a hidden video, or a bit after that with some delay.

2A) If the video is subtitled and translated while public and then the video is made hidden, the subs may remain viewable - probably even as long as no edits are made. One of the videos I played with kept its subtitles for a full day (about 19 hours) and lost them only after I made edits.

2B) If the video is submitted, made hidden and only afterwards gets subtitled - it will most likely display Subs Unavailable immediately after committing an edit or after some delay.

Examples: 
http://www.universalsubtitles.org/en/videos/XNud59TfxP4E/info/Gardner%27s%20Dragon/
http://maggie.mirocommunity.org/gardners-dragon/ (offsite embed)
http://www.universalsubtitles.org/en/videos/kronG7a8zpK1/info/Sharks%20and%20Turtles/
http://www.universalsubtitles.org/en/videos/KasOcl0X3qWQ/
http://maggie.mirocommunity.org/unisubs-vimeo/ (offsite embed)
http://www.universalsubtitles.org/en/videos/toei3MlFAl0B/info/Kitsilano%202010/
http://www.universalsubtitles.org/en/videos/XMuwwEReXZ0Q/info/Seals%20and%20Dolphins/

(The videos from this example are hosted at http://vimeo.com/user8951509)

Expected: 
- At least, USubs should support captioning, translating and editing subs for hidden videos w/o going into Subs Unavailable mode
- Ideally, hidden videos should be submitted to USubs while in private mode.

**Comment by PCF-Testing** [comment]
Integration with Vimeo takes care of this issue. Closing.
