### ISSUE TITLE
YouTube videos do not play in the legacy editor

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2790]
![ytvideosinlegacyeditor](https://cloud.githubusercontent.com/assets/288455/23946596/3bbe5838-0938-11e7-8a06-f9a047d4e5ae.PNG)

**Comment by kslottow** [comment]
Since we have the new editor, would this block anybody?  It would be good to get rid of the legacy editor soon anyway...

**Comment by PCF-Testing** [comment]
Legacy editor provides a more convenient way for syncing subtitles, so some users prefer it to the new editor.

**Comment by kslottow** [comment]
Then I think we should focus on making syncing more convenient in the new editor rather than allowing people to use the old one, right?

**Comment by PCF-Testing** [comment]
+ supporting the video formats not yet supported by the new editor (DailyMotion, Wistia).
