### ISSUE TITLE
team setting for requiring metadata translation before moving on to syncing step

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#2794]
We currently have the following warning message in the editor to alert translators to translate the metadata as well as the subtitles.

![screen shot 2017-03-20 at 3 17 07 pm](https://cloud.githubusercontent.com/assets/22455700/24153965/dc5d1d94-0e1d-11e7-9d6f-690f250275f7.png)

![screen shot 2017-03-20 at 3 20 03 pm](https://cloud.githubusercontent.com/assets/22455700/24153963/db91aace-0e1d-11e7-9f8f-59cc61cb94aa.png)

However, translators are allowed to move on without translating the metadata, because it is only required in some projects, and in others, there is no description in the video language.

How might we ensure that metadata gets translated when required?
- require metadata translation before endorsement
  - if description is empty in source language, do not require
  - the problem with this is that some titles are just numbers and don't need to be translated, but we wouldn't be able to tell which titles
- a team or project-specific setting to require metadata translation before moving on to the syncing step?
-  a team or project-specific setting to require metadata translation before endorsing?

**Comment by PCF-Testing** [comment]
It is not just a warning message. It does block endorsing a translation until the metadata get translated. Is there any use case when this breaks?

**Comment by kslottow** [comment]
thanks - checking with Jenny!

> It does block endorsing a translation until the metadata get translated

There are two situations where this would not be ideal:
- there is no description in the video language
- the title is a bunch of letters and numbers, not actual words

**Comment by kslottow** [comment]
We also have a client concerned that metadata is not being translated, I can check on exactly what they're experiencing after we confirm how it is working for our linguists.

**Comment by PCF-Testing** [comment]
Why would a team want to enforce translation of video metadata if their videos do not have meaningful titles and descriptions?

If an occasional video for some reason is missing metadata, it is still possible to submit a translation by entering Space character into Translated Title and Translated Description fields.

For the client that has a problem with translations, is the team setting requiring metadata translation turned on?

**Comment by kslottow** [comment]
> For the client that has a problem with translations, is the team setting requiring metadata translation turned on?

That's what I was missing, I didn't know there was a setting!  So can you confirm that the way it is expected to work is:
  - if the "require metadata translation" team setting is turned off, then no warning appears
  - if the "require metadata translation" team setting is turned on, then the warning appears and translators are not allowed to continue to the syncing step until they enter something in the title and description for the subtitle language?

> Why would a team want to enforce translation of video metadata if their videos do not have meaningful titles and descriptions?

I am thinking of two different cases that we need to account for:
- case 1 is a team whose videos do have meaningful titles and descriptions, and want to enforce translation of video metadata - sounds like they should have the team setting ON
- case 2 is a team whose videos do NOT have meaningful titles or descriptions (i.e. blank description, title with numbers/letters) - sounds like they should have the team setting OFF

**Comment by kslottow** [comment]
@darren-bridenbeck can you share the detailed steps for endorsing a translation without translating the metadata, on a team with the "require metadata translation" set to ON?

**Comment by PCF-Testing** [comment]
By default, translating metadata is not enforced, so there is no need to turn anything off. Almost all teams on production do not require translating metadata, with the exception of TED and one test team. If any team does want to have this setting enabled, then we Amara team can turn it on for them.

**Comment by kslottow** [comment]
ok - so I will confirm which teams this should be turned on for.  But I do want to check, does the warning message (screenshot on the top) appear for everyone?  It seems like having a warning that says "title and description must be translated" doesn't make sense when it's not required, and that it should only appear when the setting is enabled.

**Comment by PCF-Testing** [comment]
It only appears when the setting is enabled.
