### ISSUE TITLE
Allow delete all blank / empty subtitle cells in editor

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2799]
Some service providers or other platforms (YouTube) create lots of empty/blank subtitle cells when imported to Amara. These currently need to be deleted manually, one by one. 

- [ ] add the ability to delete all blank subtitle cells 
- [ ] add the option "Delete empty subtitles" into the wrench menu:

![screen shot 2018-04-19 at 11 40 25 am](https://user-images.githubusercontent.com/22455700/39005696-80a20f20-43c6-11e8-98dd-6a7bf4179b91.png)

Requested in https://pculture.freshdesk.com/helpdesk/tickets/92438
Also requested by AoD and two other large clients.

**Comment by kslottow** [comment]
Blank subtitles result when the subtitle files are coming from other platforms:

eg. Google devplat subs from YouTube

**Comment by danantonioreyes** [comment]
Implemented in branch https://github.com/pculture/unisubs/tree/gh-unisubs-2799

**Comment by PCF-Testing** [comment]
The feature works beautifully for me. A few small things I would like to have discussed before merging the change:

1) The command removes, together with empty subtitles, subtitles that contain only whitespaces. I have no objections against this behaviour, it makes sense to me, just wanted to double-check that there is no valid use case for keeping such subtitles.

2) Icons for "Clear text" and "Delete empty subtitles" are identical: [ X ]. This icon seems a better match for "Delete empty subtitles" command. For "Clear text", I think something like https://github.com/pculture/amara-assets-legacy/blob/master/glyphicons_all/glyphicons/png/glyphicons_104_text_strike.png (strikethrough letter) or an eraser icon could be a better match. @kslottow, how do we choose icons for the editor commands?

3) The confirmation modal says, "This will remove all subtitles with empty text. Do you want to continue?" @kslottow, does this sound OK or would it be better to say, "This will remove all subtitles without text. Do you want to continue?"

**Comment by kslottow** [comment]
I like the first one, "This will remove all subtitles with empty text. Do you want to continue?"

I like it better because saying "this will remove all subtitles without text" kind of makes me think "this will remove all subtitles without removing the text" which actually doesn't make sense. Just my opinion though

**Comment by PCF-Testing** [comment]
In a slack conversation, we decided to use the strikethrough glyphicon for "Clear text" menu item. "Delete empty subtitles" should stay as is.

**Comment by PCF-Testing** [comment]
Great! Verified.

**Comment by kslottow** [comment]
@PCF-Testing now that undo/redo is deployed this issue is no longer blocked

**Comment by PCF-Testing** [comment]
@danantonioreyes: has the latest dev with editor-fixes been merged in? I have noticed that after you apply Clear Text -> Delete Empty Subtitles, you cannot use "+ New subtitle" link to start subtitling from scratch. I think the latest code from editor-fixes should resolve this issue, but if it doesn't, I think it needs fixing.

**Comment by danantonioreyes** [comment]
I've merged in the `editor-fixes` branch into this one, and yes it did fix the issue. The two branches are in dev together anyway, just tried it out at dev.amara.org and things seem fine

**Comment by PCF-Testing** [comment]
Yeah, looks great now. Thanks!

**Comment by PCF-Testing** [comment]
Deployed.
