### ISSUE TITLE
MP4, MP3 video controls not displayed in embedder

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2800]
Example: http://amara.org/en/videos/LIusPAfOJFxG/
You can start playing the video in the embedder but not pause or stop.

**Comment by syl22-00** [comment]
I think it was a consequence of the drive url for videos change. I fixed it in branch gh-unisubs-2800 on unisubs

**Comment by PCF-Testing** [comment]
Verified locally.

**Comment by PCF-Testing** [comment]
Deployed.
