### ISSUE TITLE
Task assignment on unset language video task in team

### ISSUE THREAD

**Issue by johnmarcou** [pculture/unisubs#2810]
Hi,
I just would like to create a little issue about the team task management.

**Senario:**
A team is set with the task workflow, and the automatic transcribe task creation is set to on.
A manage add a video, then the transcribe task is available for users.
A user can see the task, and click on it.

**Expected:**
The user choose both language, the task assignment is set, and the user is redirected to the editor.

**Error:**
Since the language has not been set, Amara ask for the language (of the video and of the subtitle).
The user choose both language, but he is redirected to a "No authorised access page".
At that stage, I can see the database shows the task is not set to the user.
But if the user click on the task a second time, the language is already set, and the assignment is finally done, the editor is started, and everything is ok.

**What I understood:**
The task dashboard template ```templates/teams/_perform_task_link.html``` says:
```python
{% if task.needs_start_dialog %}
<a href="#multi-video-create-subtitles-modal" class="open-modal perform-task button reduced" {{ task.team_video.video|multi_video_create_subtitles_data_attrs }}>
{% else %}
<a href="{{ task.get_perform_url}}" class="perform-task button reduced">
{% endif %}
```
So the template show the language modal, then redirect directly to the editor. But the assignment is still not set. This is why there is an error to start the editor.

The assignment should be done by the ```perform_task``` method in views ```apps/teams/views.py```, but never called in this case, excepted if the user click on the task again, because the language is already set the second time:
```python
def perform_task(request, slug=None, task_pk=None):
...
    if task.assignee_id != request.user.id:
        task.assignee = request.user
        task.set_expiration()
        task.save()
...
```
**How I found to fix it:**
By removing the ```if task.needs_start_dialog``` in the template to provides always the perform_task. This method redirect to the template ```teams/start-subtitle-task.html``` to set the langage, which is working nice. But I guess this page is an old way ...
I think the modal should actually redirect to the ```perfom_url``` after setting the language.

Thank you for your help.
_Tested on the commit : e50fb23_

**Configuration of the team:**
![screen shot 2017-04-10 at 11 43 01 pm](https://cloud.githubusercontent.com/assets/18156208/25061485/2d06d6ea-21fb-11e7-823e-015d8fb6f60c.png)

**Comment by asabine** [comment]
closing this since we're depreciating and removing task-based teams and moving over to collaboration and simple teams instead
