### ISSUE TITLE
Add Zazaki language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2823]
ISO 639 code - zza
Directionality - LTR
https://en.wikipedia.org/wiki/Zaza_language

Request - https://pculture.freshdesk.com/helpdesk/tickets/93284

**Comment by Vrieann** [comment]
https://pculture.freshdesk.com/helpdesk/tickets/93284

**Comment by PCF-Testing** [comment]
Fixed on unilangs master.

**Comment by PCF-Testing** [comment]
Deployed.
