### ISSUE TITLE
The link to the development mailing list does not work

### ISSUE THREAD

**Issue by lborgman** [pculture/unisubs#2824]
The link to "Development mailing list" on https://github.com/pculture/unisubs/wiki does not work.

**Comment by lborgman** [comment]
Hm, maybe I found some mailing lists (but not the one above). However there are no recent threads on those mailing lists. Where is the discussion and exchange?

**Comment by bendk** [comment]
Yeah, we really don't have much discussion going on at this point.  For now, I'm going to close this one.  If you're interested in getting it started, we can start using the amara-development list again though.
