### ISSUE TITLE
Add Shipibo-Conibo language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2829]
ISO 639 code: shp
Directionality: LTR
https://en.wikipedia.org/wiki/Shipibo_language
http://www-01.sil.org/iso639-3/codes.asp?order=639_3&letter=s
https://www.ethnologue.com/language/shp

Request: https://pculture.freshdesk.com/helpdesk/tickets/93825

**Comment by syl22-00** [comment]
Dine in unilang-master

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
