### ISSUE TITLE
Subtitle editor: auto-pause in Beginner mode should not apply during syncing

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2830]
When auto-pause is set to Beginner mode, video playback automatically stops every 4 seconds during syncing, ending subtitles where they should not end and disrupting the normal flow of syncing.

Steps to reproduce:
1. Submit a new video and open the subtitle editor to transcribe it.
2. Set the auto-pause mode to Beginner.
3. Type in several cells and switch to syncing stage. Start syncing subtitles. The video will stop after 4 seconds, ending the subtitle. Resume. The video will stop in another 4 seconds.

Expected: auto-pause should apply only at the typing step, but not at syncing step.

**Comment by syl22-00** [comment]
Done in branch gh-unisubs-2830 on unisubs

**Comment by PCF-Testing** [comment]
On the branch, once the current subtitle set get a few timestamps, the autopause mode selector gets hidden from the editor UI and autopause stops working - even if the user hides the timeline and continues typing the text. I think this is not the correct behaviour.

As a user, I would expect the editor to behave in the following way:
- Autopause mode selector should be visible at all times
- While the editor is in typing mode (timeline hidden, ENTER adds a new cell), video plays according to the selected autopause mode
- While the editor is in syncing mode (timeline shown, ENTER key does not add a new cell), the video plays continuously and pauses/resumes only when the user presses TAB or clicks the control on the video.

Does this make sense?

**Comment by syl22-00** [comment]
@PCF-Testing so I made the following changes:

* Option to change playback mode is always shown
* Non standard playback mode is only used when timeline is hidden, no matter the stage.

**Comment by PCF-Testing** [comment]
The updated version of the code feels much nicer. One case where it breaks is when timed (or partially timed) subtitles are loaded into the editor on clicking Edit Subtitles button - in this case, the timeline is displayed by default, but the video still plays in 4 sec chunks; then, as the user hides or displays the timeline, the editor behaves as expected.

Is it possible to fix this case of editing timed subtitles, so that they played without the magic pause?

**Comment by syl22-00** [comment]
@PCF-Testing I fixed it in the branch and made a few cleanups in the code:

* Exception in JavaScript console on Firefox
* Subtitles not loading in some cases, for instance if, on dev environment, app is used on localhost and user is not connected on unisubs.example.com:8000.

**Comment by PCF-Testing** [comment]
Verified locally. @syl22-00, could you please make a PR? Thanks!

**Comment by PCF-Testing** [comment]
Deployed.
