### ISSUE TITLE
Update avatar tag code

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2841]
We should update the code in CustomUser that creates avatar tags to match the styleguide code.

Right now we create HTML like this:
```
<img class="avatar avatar-md" src="[url]">
```

We should change that to this:
```
<span class="avatar avatar-md"><img src="[url]"></span>
```

Once we do that, I think we can also update the code in collab/steps.html to use the avatar_alert_tag method.

**Comment by bendk** [comment]
I didn't think this should hold up us merging the code, but it would be good to do when you get a chance.

**Comment by asabine** [comment]
updated the user avatar_tag methods and collab/steps.html; the template is a bit awkward (the image is now inside of two spans; one that handles the complete class if needed as well as the data- attributes and the different titles, and the one which is generated in avatar_tag) but it works fine; not sure of a neater way of doing this without adding template tags and doing some weird context passing or just generating several new user avatar_tag functions.

**Comment by bendk** [comment]
I think the extra span is okay, since it's doing something different from the first one.  One handles the avatar image, the other handles the step, which is a different thing.  Wrapping is always a bit awkward, but it seems okay for it.

The one thing that seems a bit weird to me is that the alert is on the inner span, rather than the outer one.  It seems like it goes together with the completed class more than the avatar size class.  If it was trivial to change this, then it could be nice, but if not I would not bother with it.

**Comment by asabine** [comment]
when avatar-alert is applied to the outer span while the inner span only has avatar, the icon doesn't display at all; the css is written so the style is only applied if avatar-alert is present alongside avatar

**Comment by bendk** [comment]
Yeah, it would mean changing the CSS.  It's probably not worth doing.

**Comment by PCF-Testing** [comment]
Merged.
