### ISSUE TITLE
Notifications not sent to translator when the subtitles are approved

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2843]
Reported in https://pculture.freshdesk.com/helpdesk/tickets/94177. Confirmed on production.

Steps to reproduce:
1. As user 1, pick a translation task, make a translation and submit.
2. As user 2, review, edit, and submit.
3. As user 3, open for approval, edit, and submit.
4. As users 1 and 2, check onsite and email boxes. The reviewer (user 2) receives a notification about the subtitles published; the translator (user 1) does not.

Expected:
If user 3 sends back, notify user 2. If user 3 approves and publishes, notify users 1 and 2.

**Comment by VeronicaPCF** [comment]
Any news on this issue? The TED LC who [created the ticket](https://pculture.freshdesk.com/helpdesk/tickets/94177) confirms it still happens and wants and explanation/fix. :) 
Thank you!

**Comment by VeronicaPCF** [comment]
This issue continues, user filed a new ticket about the same issue, which is merged into: https://pculture.freshdesk.com/helpdesk/tickets/94177

**Comment by VeronicaPCF** [comment]
@kslottow Kenzie, could you please have a look at this issue? Denise (TED LC) doesn't stop writing us about this issue, creating new tickets on a daily basis, even when I already told her we're working on it..

**Comment by VeronicaPCF** [comment]
https://pculture.freshdesk.com/helpdesk/tickets/94177

**Comment by Vrieann** [comment]
Hi Kenzie,

For your reference here is a complete list of all the tickets Denise shared
regarding the notifications failing with me.
Each is a complete description with links for every notice she sent that
has failed recently.
We've both reassured her that you are working on fixing this and we'll
notify her immediatly.


Ticket Id Subject Requester Email
95607 notifications missing rqdenise@gmail.com
95608 notifications missing (2) rqdenise@gmail.com
95609 notifications missing (3) rqdenise@gmail.com
95610 notifications missing (4) rqdenise@gmail.com
95611 notifications missing (5) rqdenise@gmail.com
95612 notifications missing (5) rqdenise@gmail.com
95613 notifications missing (6) rqdenise@gmail.com
95614 notifications missing (7) rqdenise@gmail.com
95615 notifications missing (8) rqdenise@gmail.com
95616 notifications missing (9) rqdenise@gmail.com
95618 notifications missing for Spanish (1) rqdenise@gmail.com
95619 notifications missing (Spanish) (2) rqdenise@gmail.com
95620 missing notifications (Spanish 3) rqdenise@gmail.com
95621 missing notifications (Spanish 3) rqdenise@gmail.com
95644 MISSING NOTIFICATIONS ON PRIVATE MESSAGES rqdenise@gmail.com
95645 MISSING NOTIFICATIONS ON PRIVATE MESSAGES rqdenise@gmail.com

**Comment by syl22-00** [comment]
This was fixed in branch gh-unisubs-2843: When approve task is complete, a message is sent to the reviewer and to original subtitler.

**Comment by PCF-Testing** [comment]
Looks good except the message formatting issue (forwarded emails to show the problem).

**Comment by syl22-00** [comment]
@PCF-Testing I think I found the issue, fixed it in the branch

**Comment by PCF-Testing** [comment]
The formatting thing has indeed been fixed. But the message still lacks the video title:

"Your Spanish subtitles for the video “” have been approved by maggie_s from the Task Team team and they are now published!"

**Comment by PCF-Testing** [comment]
That was due to the title not being translated. When it is, the message has the title.

Looks good now.

**Comment by PCF-Testing** [comment]
Deployed.
