### ISSUE TITLE
Update Brightcove integration to Cloud API

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2848]
Britghtcove's Media API is being deprecated with writes shut down on June 30 2017 and reads on December 2017. For Amara, this affects ~3 teams currently using or planning to use the integration.

Service changes
https://support.brightcove.com/en/video-cloud/docs/changes-video-cloud-service

CMS API
http://docs.brightcove.com/en/video-cloud/cms-api/index.html

https://github.com/pculture/unisubs/search?q=brightcove&type=Code

**Comment by kslottow** [comment]
Clients affected: SciAm, LDS, Team Adventist

LDS having an event on 7/22 for which they will need to use this new integration. So we need to deploy by 7/20 at the latest.

**Comment by syl22-00** [comment]
This should be tested on gh-unisubs-2848.amara.org

**Comment by PCF-Testing** [comment]
Brightcove generates video links in https://bcove.video/2ugAahw format, which are not ingested by the preview on Amara. The links that can be accepted by Amara do not get provided by the preview server, so integration at its current state is not really testable.

**Comment by franontanaya** [comment]
Short BC links are a redirect to a https://players.brightcove.net/706272104001/SyLsK9oCe_default/index.html?videoId=5515571578001 link. E.g. can be resolved with curl using CURLOPT_FOLLOWLOCATION, CURLINFO_EFFECTIVE_URL.

**Comment by PCF-Testing** [comment]
zh-cn subtitles would not sync from staging to BC, unlike other languages:
http://staging.amara.org/en/videos/sPXkqjFCQp8k/zh-cn/1091766/?team=m-collab-test
https://studio.brightcove.com/products/videocloud/media/videos/5519340663001
http://staging.amara.org/en/admin/externalsites/synchistory/

**Comment by PCF-Testing** [comment]
Several unit tests are broken on staging/master:

======================================================================
FAIL: test_forms (externalsites.tests.test_forms.AccountFormsetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/externalsites/tests/test_forms.py", line 405, in test_forms
    'youtube_2',
AssertionError: Items in the first set but not the second:
'brightcovecms'

======================================================================
FAIL: test_team_account (externalsites.tests.test_models.GetSyncAccountTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/externalsites/tests/test_models.py", line 46, in test_team_account
    self.check_get_sync_accounts(video, account)
  File "/opt/apps/amara/apps/externalsites/tests/test_models.py", line 39, in check_get_sync_accounts
    (account, video.get_primary_videourl_obj())
AssertionError: Lists differ: [] != [(<BrightcoveAccount: Brightco...

Second list contains 1 additional elements.
First extra element 0:
(<BrightcoveAccount: Brightcove: publisher>, <VideoUrl: http://bcove.me/services/link/bcpid1234/bctidabc>)

- []
+ [(<BrightcoveAccount: Brightcove: publisher>,
+   <VideoUrl: http://bcove.me/services/link/bcpid1234/bctidabc>)]

======================================================================
FAIL: test_user_account (externalsites.tests.test_models.GetSyncAccountTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/apps/amara/apps/externalsites/tests/test_models.py", line 52, in test_user_account
    self.check_get_sync_accounts(video, account)
  File "/opt/apps/amara/apps/externalsites/tests/test_models.py", line 39, in check_get_sync_accounts
    (account, video.get_primary_videourl_obj())
AssertionError: Lists differ: [] != [(<BrightcoveAccount: Brightco...

Second list contains 1 additional elements.
First extra element 0:
(<BrightcoveAccount: Brightcove: publisher>, <VideoUrl: http://bcove.me/services/link/bcpid1234/bctidabc>)

- []
+ [(<BrightcoveAccount: Brightcove: publisher>,
+   <VideoUrl: http://bcove.me/services/link/bcpid1234/bctidabc>)]

**Comment by syl22-00** [comment]
Tests were fixed directly on staging

**Comment by PCF-Testing** [comment]
Confirming the tests have been fixed.

**Comment by PCF-Testing** [comment]
Deployed.
