### ISSUE TITLE
Disambiguate channels on the linked YouTube accounts page

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2857]
In the http://amara.org/en/teams/{teamslug}/settings/accounts/ the linked accounts list identifies them by title, which sometimes needs to be disambiguated when there's more than one channel with the same title linked to a team. The page source itself only refers to it by Amara's internal ID for that channel.

This can be addressed by making the title of the channel a link to it.

**Comment by PCF-Testing** [comment]
The fix should allow discriminating between channels with identical names, so links to channels need to be added.

**Comment by asabine** [comment]
added the channel links to team-settings-tab.html in addition to new-team-settings-tab.html

**Comment by PCF-Testing** [comment]
Awesome! 

For collab-based teams, would it be too difficult to display the links in a different color, say, in 0f80e2, to make it visible that they are linked? No need to go super fancy about the appearance, the page will be re-designed soon, just a quick fix to let users see where the links are.

**Comment by asabine** [comment]
done; color should be changed for the links now

**Comment by PCF-Testing** [comment]
Terrific, thanks!

**Comment by PCF-Testing** [comment]
Deployed.
