### ISSUE TITLE
Error when attempting to add video to team from a project page

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2859]
Example: https://www.amara.org/en/teams/add/video/testm/?project=2758

Reported: https://pculture.freshdesk.com/helpdesk/tickets/94790

**Comment by PCF-Testing** [comment]
This issue is causing problems for our partner: 
https://pculture.freshdesk.com/helpdesk/tickets/94886
https://pculture.freshdesk.com/helpdesk/tickets/94829

**Comment by bendk** [comment]
Related to the fact is the move videos button doesn't have the project as its initial value.

**Comment by bendk** [comment]
Fixed in gh-2859.

**Comment by PCF-Testing** [comment]
The fix works well.

Hit the following exception on the branch when adding a video from the public pool to a collab-based video with the use of Add this video to one of your teams admin command:

KeyError at /teams/add-video-to-team/KR6MisjMF5Xz/
u'general'
Request Method:	POST
Request URL:	http://unisubs.example.com:8000/en/teams/add-video-to-team/KR6MisjMF5Xz/
Django Version:	1.4.21
Exception Type:	KeyError
Exception Value:	
u'general'
Exception Location:	/opt/apps/amara/apps/notifications/handlers.py in call_event_handler, line 174
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  20.                 return view_func(request, *args, **kwargs)
File "/opt/apps/amara/apps/teams/views.py" in add_video_to_team
  777.             team_video = TeamVideo.objects.create(video=video, team=team, added_by=request.user)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in create
  137.         return self.get_query_set().create(**kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in create
  377.         obj.save(force_insert=True, using=self.db)
File "/opt/apps/amara/apps/teams/models.py" in save
  1111.         super(TeamVideo, self).save(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save
  463.         self.save_base(using=using, force_insert=force_insert, force_update=force_update)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save_base
  565.                 created=(not record_exists), raw=raw, using=using)
File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py" in send
  172.             response = receiver(signal=self, sender=sender, **named)
File "/opt/apps/amara/apps/notifications/signalhandlers.py" in on_team_video_save
  43.                            None)
File "/opt/apps/amara/apps/notifications/handlers.py" in call_event_handler
  174.     handler_class = _registry[notification_setting.type]

Exception Type: KeyError at /teams/add-video-to-team/KR6MisjMF5Xz/
Exception Value: u'general'

**Comment by PCF-Testing** [comment]
Please ignore my previous comment, I figured out why that error happened, it was caused by invalid date left over from testing not yet merged changes. Making PR.

**Comment by kslottow** [comment]
From Maggie on #engineering slack channel:

http://staging.amara.org/en/teams/add/video/testm/?project=2758 still 500's

**Comment by asabine** [comment]
there were two small issues that seemed to be causing 500 errors here: first one (in amara-enterprise/gh-2859) was caused by trying to look up a URL by an old name, so i updated it to use the correct one that is now in use. second issue was trying to lookup projects using the id as a slug, now it uses the actual id and appears to work locally :)

**Comment by PCF-Testing** [comment]
Exception on actually adding the video:

app_1     | ERROR 2017-07-12 12:10:00,231 unhandled_error invalid literal for int() with base 10: 'project-1'
app_1     | Traceback (most recent call last):
app_1     |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
app_1     |     response = callback(request, *callback_args, **callback_kwargs)
app_1     |   File "/opt/apps/amara/utils/__init__.py", line 55, in wrapper
app_1     |     output = func(request, *args, **kw)
app_1     |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
app_1     |     return view_func(request, *args, **kwargs)
app_1     |   File "/opt/apps/amara/apps/teams/views.py", line 793, in add_video
app_1     |     project = Project.objects.get(id=project_id)
app_1     |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 131, in get
app_1     |     return self.get_query_set().get(*args, **kwargs)
app_1     |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 358, in get
app_1     |     clone = self.filter(*args, **kwargs)
app_1     |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 624, in filter
app_1     |     return self._filter_or_exclude(False, *args, **kwargs)
app_1     |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 642, in _filter_or_exclude
app_1     |     clone.query.add_q(Q(*args, **kwargs))
app_1     |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1250, in add_q
app_1     |     can_reuse=used_aliases, force_having=force_having)
app_1     |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1185, in add_filter
app_1     |     connector)
app_1     |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/where.py", line 69, in add
app_1     |     value = obj.prepare(lookup_type, value)
app_1     |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/where.py", line 320, in prepare
app_1     |     return self.field.get_prep_lookup(lookup_type, value)
app_1     |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 310, in get_prep_lookup
app_1     |     return self.get_prep_value(value)
app_1     |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 537, in get_prep_value
app_1     |     return int(value)
app_1     | ValueError: invalid literal for int() with base 10: 'project-1'

**Comment by PCF-Testing** [comment]
Looks good to me on the branch. @asabine, could you please make PRs?

**Comment by PCF-Testing** [comment]
Deployed.
