### ISSUE TITLE
Dailymotion/GrabNetworks videos cannot be correctly processed by USubs

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#286]
Videos from GrabNetworks channel http://www.dailymotion.com/Lifestyle-GrabNetworks#videoId=xkm0c7 cannot be played or subtitled with the use of UniversalSubtitles.

Examples:

https://dev.universalsubtitles.org/en/videos/QaKPsQc5zF65/info/Irish%20captain%20Harrison%20Smith%20comments%20on%20Crist%27s%20transfer/

https://dev.universalsubtitles.org/en/videos/CYWRsaqs185R/info/Holiday%20party%20at%20Howard%20Park/

On attempt to play the video on USubs page, error message:
"No Preset. This video is not available because it has no video stream."
is displayed.

The video is playable from http://www.dailymotion.com/video/xmrrit.

The video's embed code:
<object width="480" height="360"><param name="movie" value="http://player.grabnetworks.com/swf/GrabOSMFPlayer.swf?id=1580979&content=v3b424a69d163820ea21ae8271cc0dccd14b60f19"></param><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param><param name="wmode" value="transparent"></param><embed type="application/x-shockwave-flash" src="http://player.grabnetworks.com/swf/GrabOSMFPlayer.swf?id=1580979&content=v3b424a69d163820ea21ae8271cc0dccd14b60f19" width="480" height="360" wmode="transparent" allowfullscreen="true" allowscriptaccess="always"></embed></object><br /><a href="http://www.dailymotion.com/video/xmrrit_holiday-party-at-howard-park_news" target="_blank">Holiday party at Howard Park</a> <i>by <a href="http://www.dailymotion.com/LocalNews-GrabNetworks" target="_blank">LocalNews-GrabNetworks</a></i>

Other Dailymotion videos (e.g. https://dev.universalsubtitles.org/en/videos/ovKIzSJLNB9j/info/Opposition%20cries%20foul%20in%20Russian%20parliamentary%20polls./) are displayed properly and do not cause any trouble.

**Comment by bendk** [comment]
We're not planning on continuing with daily motion support.
