### ISSUE TITLE
No video submitter when added by feed causes video page to 500 on 1.8

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2868]
The page http://amara.org/en/videos/NSGPLSoexTm5/?team=ondemand054 returns a 500 error when trying to access it with the 1.8 interface, but not with the legacy interface. Other pages for the same video work as expected.

Normally these are a misconfiguration rather than a bug, but failed to find any of the usual culprits — duplicated languages, duplicated collaborations, requests or jobs.

This is a BrightCove URL, but equivalent videos posted previously on the same team don't have this issue.

**Comment by PCF-Testing** [comment]
This page loads nicely for me. What user account has this issue?

**Comment by franontanaya** [comment]
This was visible for all users yesterday, including Jenny and me, even shortly after adding a MP4 proxy. When asked the client said nothing was different on the way they sent the video. It would seem that the issue was transient and some action has fixed it, since the same page does work today.

The only other bit of info I have is that it didn't have a primary language set when it was posted. We may need to see the issue show up again to figure it out.

**Comment by franontanaya** [comment]
Reopened for the issue reproduced on a just posted video in the same circumstances.

http://www.amara.org/en/videos/MljY59svte8B/?team=ondemand054

**Comment by PCF-Testing** [comment]
The issue is caused by the video being submitted to the system via a feed, so there is no user to be listed in video activity history as the submitter of the video.

The error in the logs says "NoneType' object has no attribute 'username'".

**Comment by franontanaya** [comment]
This video displays the same behavior if you add the team argument for it.

https://staging.amara.org/en/videos/fW2V23tc3jz8/

**Comment by syl22-00** [comment]
In branch gh-unisubs-2868 on unisubs, fixed is by falling back to "Somebody (possibly automatically)" to replace username in case user is None.

**Comment by PCF-Testing** [comment]
How about making it read "Anonymous user" (without a hyperlink to profile), to make it consistent with http://amara.org/en/videos/uKOeU66doyQ4/info/keyboard-demo/?team=testm#video_activity?

Or we could create another bot account for Amara system actions not related to YT and use it as the submitter for feeds and in other cases, such as http://staging.amara.org/en/videos/cxPuf0JDdptp/info/around-san-pedro-de-atacama-northern-chile-in-hd/?tab=activity (and other submissions by providers) - would that make sense?

**Comment by syl22-00** [comment]
I agree with your suggestion to create an amara user that would be specific to that, like "Amara bot". But I don't think it is great to make it existing records read "Anonymous user", just because it is not an anonymous user.

Since we already have activity records without users, we could do those two things:
* For existing records with user, make it read "Somebody (probably Amara bot)..."
* For new activity record added via feeds, use a new user called "Amara bot", so we should never have new record without user set.

**Comment by PCF-Testing** [comment]
@bendk: @kslottow: do you feel good about the new look of the activity entries for video submissions through feeds:

![autosubmissionfeed](https://user-images.githubusercontent.com/288455/28869364-4e8e43c6-7731-11e7-8e0b-48875ddf176d.png)

So far, we have used account http://amara.org/en/admin/auth/customuser/10000/ for most automatic activities, such as importing subtitles from YouTube or automatic creation of subtitles by a dummy provider. However, seeing 'youtube-anonymous' as the acting user for importing BC videos would feel weird, so we are about to use something different for userless actions in the system.

**Comment by bendk** [comment]
Looks fine to me.

**Comment by PCF-Testing** [comment]
@syl22-00: could you please make a PR for this one? Thanks!

**Comment by PCF-Testing** [comment]
Deployed.
