### ISSUE TITLE
Language code mapping issue in activity records

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2873]
We can see activity records with language codes such as `zh-CN`, `zh-TW` and `pt-PT`, which should not exist, and are probably consequences of issue with language mappings. Activity records with such language codes can not be displayed and pages that should render them do not load.

**Comment by syl22-00** [comment]
My best guess so far is that those activity records are created from the legacy site. It is easy to fix `zh-CN` and  `zh-TW` but other missing mappings are ambiguous. For instance shall we change `pt-PT` into `pt` or `pt-pt`?

**Comment by syl22-00** [comment]
The data were fixed directly in the server.

**Comment by syl22-00** [comment]
In addition, in branch gh-unisubs-2873, I made sure that in case we have erroneous language codes, those do not break the display of messages.

**Comment by PCF-Testing** [comment]
The branch looks fine, except that it has the problems with projects that got fixed in 1409.

**Comment by PCF-Testing** [comment]
Deployed.
