### ISSUE TITLE
Subtitles with long video titles fail to sync to YouTube

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2874]
When syncing video metadata is enabled, some characters in video titles prevent syncing subtitles to YouTube, raising invalidVideoMetadata error.

For example, the following title will successfully sync to YT:

Por qué la gente cree que no puede dibujar, y como demostrar que pueden hacerlo Graham Shaw TEDxHull

But the following ones won't:

Por qué la gente cree que no puede dibujar, y como demostrar que pueden hacerlo | Graham Shaw | TEDxHull
Por qué la gente cree que no puede dibujar, y como demostrar que pueden hacerlo - Graham Shaw - TEDxHull

For an example of what does get synced and what does not, please check https://amara.org/en/videos/vAjYNntdwjt9/es/1914926/5654470/?tab=sync-history

**Comment by syl22-00** [comment]
I am not sure I saw the issue: I could push the metadata successfully, and the video linked in the ticket does not have any sync history.

**Comment by PCF-Testing** [comment]
@syl22-00: sorry, I have disconnected that channel because I needed it to test something else. Just linked it back and synced a couple of versions, so you can check this link again.

For more info, you can also check http://www.amara.org/en/teams/ted/settings/sync/

**Comment by syl22-00** [comment]
@PCF-Testing I found that the issue was actually on the length of the title. Google limits at 100 characters. In branch gh-unisubs-2874, I just keep the fist 100 characters.

**Comment by PCF-Testing** [comment]
Looks good to me. @syl22-00, could you please make a PR for this one?

**Comment by PCF-Testing** [comment]
Deployed.
