### ISSUE TITLE
option to snap timeline to start time of currently selected subtitle cell in text area

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#2875]
@PCF-Testing I am thinking there is a reason that we don't do this globally. Do you know what it is?

Why is it important for a linguist to be able to edit text in subtitle cells without automatically having the timeline jump around to the selected cell?

**Comment by PCF-Testing** [comment]
I think that constant skipping to the current cell (btw, why to center and not to the start time? start time would make more sense than some point in the middle of the phrase) would just slow down work. When necessary, it is very easy to skip to the beginning of the current subtitle through the cell's menu: https://support.amara.org/support/solutions/articles/210102-subtitle-cell.

**Comment by kslottow** [comment]
> why to center and not to the start time? 

Yeah this makes more sense to me too. Changed the title.

> When necessary, it is very easy to skip to the beginning of the current subtitle through the cell's menu

Great point! I think I will actually close this for now because the seek to subtitle option actually covers this use case so far, to my knowledge. Thanks!!
