### ISSUE TITLE
Resuming session after timeout doesn't work properly

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2885]
From Maggie:

1. In Browser A, sign in as User 1 and open subtitles for a certain public video for editing.
2. Leave the subtitles and the editor untouched (no keystrokes, no mouse movements. You can switch to another browser or tab while leaving the editor open) for 15+ minutes. Once that time elapses, the editor will display a message about the session having timed out ("Your session has ended. You can try to resume, or close the editor.").
3. After the session in Browser A times out, sign in as User 2 In Browser B and open the same subtitles for editing (e.g. through "Edit Subtitles" button on the subtitle page). 
4. In browser A, click Try to Resume Work (this is only supposed to resume the timed out session if nobody else is editing these subtitles). The session resumes. Type something and save a draft.
5. Type something in Browser B and save a draft.
Result: both users can edit the same subtitles concurrently and save different subtitle versions in turn.

**Comment by bendk** [comment]
The issue was that we weren't responding correctly to the resume session button.  Fix in the gh-2885 branch.

**Comment by PCF-Testing** [comment]
Works as expected on the branch.

**Comment by PCF-Testing** [comment]
Deployed.
