### ISSUE TITLE
Add Hawaiian Creole language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2886]
Name - Hawai'i Creole English (or Hawai'i Pidgin)
ISO 639-3 code - hwc
Directionality - LTR

Request: https://pculture.freshdesk.com/helpdesk/tickets/95600

**Comment by syl22-00** [comment]
Done directlu on master on unilangs

**Comment by PCF-Testing** [comment]
The language name is mangled in language selector on 1.8 pages (1.7 is OK):

![hwclanguagelanguageselector18](https://user-images.githubusercontent.com/288455/28969179-5585d088-78d8-11e7-8363-49125e2cd8c8.png)

Will we adjust the language name or make a ticket for fixing the selector?

**Comment by syl22-00** [comment]
I fixed the language selector in branch gh-unisubs-2886 in unisubs

**Comment by PCF-Testing** [comment]
@syl22-00 cannot start that branch, it throws the following exception:

worker_1   | Traceback (most recent call last):
worker_1   |   File "/opt/apps/amara/manage.py", line 42, in <module>
worker_1   |     execute_from_command_line(sys.argv)
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
worker_1   |     utility.execute()
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
worker_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/djcelery/management/commands/celery.py", line 22, in run_from_argv
worker_1   |     ["%s %s" % (argv[0], argv[1])] + argv[2:])
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 890, in execute_from_commandline
worker_1   |     super(CeleryCommand, self).execute_from_commandline(argv)))
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 179, in execute_from_commandline
worker_1   |     return self.handle_argv(prog_name, argv[1:])
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 882, in handle_argv
worker_1   |     return self.execute(command, argv)
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 857, in execute
worker_1   |     return cls(app=self.app).run_from_argv(self.prog_name, argv)
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 142, in run_from_argv
worker_1   |     return self(*args, **options)
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 112, in __call__
worker_1   |     ret = self.run(*args, **kwargs)
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 214, in run
worker_1   |     return self.target.run(*args, **kwargs)
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celeryd.py", line 153, in run
worker_1   |     return self.app.Worker(**kwargs).run()
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/apps/worker.py", line 157, in run
worker_1   |     self.app.loader.init_worker()
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 116, in init_worker
worker_1   |     self.on_worker_init()
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/djcelery/loaders.py", line 127, in on_worker_init
worker_1   |     self.close_database()
worker_1   |   File "/opt/apps/amara/apps/amaracelery/loaders.py", line 27, in close_database
worker_1   |     connection.cursor().execute("COMMIT")
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 317, in cursor
worker_1   |     cursor = self.make_debug_cursor(self._cursor())
worker_1   |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 377, in _cursor
worker_1   |     if settings_dict['HOST'].startswith('/'):
worker_1   | AttributeError: 'NoneType' object has no attribute 'startswith'
unisubssecond_worker_1 exited with code 1

Was caching branch merged into staging? It did require a very special configuration to run...

**Comment by syl22-00** [comment]
@PCF-Testing It does not seem to be related to the changes from that branch, but this branch is out of staging which includes the caching code. Maybe your image must be rebuilt?

**Comment by PCF-Testing** [comment]
Verified locally. @syl22-00, could you please make a PR for this one?

**Comment by PCF-Testing** [comment]
Deployed.
