### ISSUE TITLE
Handle multiple video URLs in the embedder

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2887]
I'm splitting this one of of 2127 since that one is already complex enough.

Once 2127 is implemented, you can now have multiple public amara videos for a single video URL. For example if there's one in the public area, and one on a public team. This presents a question of which video to take subtitles from for the embedder. Here's how we should handle this:
- By default, we should prefer the public video
- We should add an extra parameter when embedding videos, called data-team which allows one to specify which team to take the video from. If that's present, then we should prefer a video from that team
- Otherwise we should just pick an arbitrary video

**Comment by bendk** [comment]
Implemented on the gh-2127 branch

**Comment by PCF-Testing** [comment]
This works as expected, but without the new parameter, data-team, the embedder does not load for me. This is not backward compatible and will break all embedders on our users' pages. Could the embedder script work with data-team skipped? The default behaviour could be that in the absence of data-team, the script would find and use the first publicly available copy of the video from Amara it stumbles upon. If the results are different from the expected, then the video's owner should do something about it - check the docs and update the code so the correct copy of the video is used.

**Comment by PCF-Testing** [comment]
Note: we'll need to update https://github.com/pculture/unisubs/wiki/Embed-Code-Usage-Guide and https://amara.org/es/embedder-offsite/ once 2127 goes live.

**Comment by PCF-Testing** [comment]
@bendk: /embedder-offsite/ page needs an update on the branch. This should be done once we settle on whether data-team will be a mandatory parameter.

**Comment by bendk** [comment]
What test are you using for the embedder?  I tried to make it work without data-team and I thought I tested it.

The /embedder-offsite/ page doesn't work in general with dev builds, since it references video ids from amara production

**Comment by PCF-Testing** [comment]
I embedded a video from a local instance.

<div class="amara-embed" data-height="370px" data-width="620px" data-url="https://www.youtube.com/watch?v=emr4CN8wmck" data-team="public-old-style-team"></div> works well and plays the correct subtitles.

So does <div class="amara-embed" data-height="370px" data-width="620px" data-url="https://www.youtube.com/watch?v=emr4CN8wmck" data-team=null></div>

But <div class="amara-embed" data-height="370px" data-width="620px" data-url="https://www.youtube.com/watch?v=emr4CN8wmck"></div> does not load and looks as shown on the screenshot below:

![screenshot from 2017-10-07 03 03 14](https://user-images.githubusercontent.com/288455/31306791-26a3ff90-ab0c-11e7-8515-5716e0ca59e0.png)

**Comment by bendk** [comment]
So here's the test I did:

 - Add a video in the public area
 - Alter templates/embedder-offsite.html so the data-url attribute of the first amara-embed is set to the youtube URL that I added.  (Don't add data-team)
  - Open /embedder-offsite/

I'm able to see the video in the embedder.  I moved it to a public team and was still able to see it.

Maybe we should just merge this one and test on staging.  It's probably easier to do it there.

**Comment by PCF-Testing** [comment]
I have tried the scenario you've described.

As long as this video is only in the public area, everything is OK.

However, as soon as the same video gets added to a team and subtitled there, /embedder-offsite page gets broken in the same way as shown on the screenshot above - the embedders stop loading and the loading icon spins forever for all the videos on the page.

I think there should be some sensible solution for this case. If multiple copes of the same video exist on the site and data-team is not specified, then it might make sense to use the subtitles from the public version of the video. If no copy is found in the public area, then a random copy from a public team should be used, etc. 

As the result, users may end up with some embeds showing the wrong subtitles, but I still think it is less of a problem than having whole Web pages with all the embeds broken. For non-partner, non-enterprise users pulling the subtitles from the public copy should be a sensible choice. And regarding enterprise users with teams, we will need to notify them that they may need to update the embedded copies of their videos.

Does this make sense?

**Comment by bendk** [comment]
Ahh, I finally get it.  I didn't understand you needed the video in both the public area and on a team.

I fixed it with this solution:
 - If there's a public video, use that for all subtitles
 - Otherwise pick an arbitrary team video and use that for all subtitles

I went with that one since it's pretty simple and I think this is a corner case that we don't need to worry about too much.  If it turns out to be a problem, we can work on that later, but I really want to get 2127 merged.

**Comment by PCF-Testing** [comment]
Looks good now. Moving to Needs Staging Deploy because it does not require a PR and will go live together with 2127.

**Comment by bendk** [comment]
We decided to put this into holding, rather than needs staging deploy.  When it was in needs staging deploy, we got confused and thought it was merged to staging.

**Comment by bendk** [comment]
Just made the PRs, but I connected them to 2127 insead of this issue.

**Comment by PCF-Testing** [comment]
Deployed.
