### ISSUE TITLE
Add English (Australia) to language selectors

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2888]
English (Australia) (en-au) is currently missing from the UI.

Requests can be created through the API and completed successfully, and the language does have a proper label ("English (Australia)") in the language list once created, but the UI to create requests and the filters don't display it.

**Comment by kslottow** [comment]
this was intentionally left as semi-supported (API only) along with several other languages that Google uses. Do we have a list of the semi-supported languages anywhere @PCF-Testing ?

My understanding is that putting these extra regional varieties of the languages in the selector is expected to cause confusion, so we left them out for now.

**Comment by PCF-Testing** [comment]
https://github.com/pculture/unilangs/blob/master/unilangs/unilangs.py

de-at
en-au
en-ca
en-ie
en-in
en-us
es-ec
es-es
fa-af
fr-be
fr-ch
nl-be
pt-pt
zh-hans
zh-hant

**Comment by kslottow** [comment]
great, thank you @PCF-Testing! I seem to remember a broader issue for potentially adding some semi-supported languages to the UI. Can't find it though - I know we did for ES-419 in particular, but if there's another ticket could you reference it here? Thanks!

**Comment by PCF-Testing** [comment]
I don't think we have any open tickets about that, but the matter was being discussed in enterprise tickets 758 and 835, which are now closed.
