### ISSUE TITLE
Searching for a team member fails if member of a team marked as deleted

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2891]
In admin UI, when searching for a team member, it returns a server error if found a team member of a team marked as deleted.

**Comment by syl22-00** [comment]
Made a fix in gh-unisubs-2891

**Comment by PCF-Testing** [comment]
Verified locally.

@syl22-00, could you please make a PR for this one? Thanks!

**Comment by PCF-Testing** [comment]
Deployed.
