### ISSUE TITLE
Resync greyed out on language completed in team before moving to public

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2895]
Steps --

* Set YouTube link on personal account (for public videos)
* Complete a language for a video from the linked YouTube channel in a team (no sync to happen here, as the link is personal not team)
* Remove the video from team to public.

On 1.7, the Sync History tab has a working "resync version 1" button. On 1.8 the resync button is greyed out and no revisions are listed as available to sync.

**Comment by PCF-Testing** [comment]
Is this one for the new subtitle page (with team context)? New 1.8 pages are not supported for public videos yet, 1.7 pages should be used instead.

**Comment by franontanaya** [comment]
New one. I'll close this ticket then.
