### ISSUE TITLE
Sync and fetch settings for YouTube links are disabled when saving accounts page on 1.7

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2897]
The /settings/accounts/ page on the 1.7 UI (i.e. Tasks teams) doesn't have checkboxes for "Sync subtitles from Amara to YouTube" and "Fetch initial subtitles from YouTube when videos are submitted to Amara".

If you Save that page, the backend takes the lack of a value passed for those fields as a "false" and disables the YouTube sync for all the linked accounts.

**Comment by PCF-Testing** [comment]
Steps to reproduce:

1. On /teams/[slug]/settings/accounts/ page, link a YT channel. Fetching and pushing subtitles will be on by default.
2. Click Save button on the page. Fetching and pushing will be turned off.

**Comment by asabine** [comment]
oauth doesn't work locally, so i haven't been able to test this with a synced account but i added the two fields that were missing from the 1.7 UI form, and hopefully that should resolve the problem.

**Comment by PCF-Testing** [comment]
Looks good. @asabine, could you please make a PR?

**Comment by PCF-Testing** [comment]
Deployed.
