### ISSUE TITLE
Add Acehnese language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2911]
ISO 639 code: ace
Name: Acehnese
Directionality: LTR
https://en.wikipedia.org/wiki/Acehnese_language
Request: https://pculture.freshdesk.com/helpdesk/tickets/96132

**Comment by syl22-00** [comment]
Done in the master branch of unilangs

**Comment by PCF-Testing** [comment]
Marking as Waiting for Deploy.

**Comment by PCF-Testing** [comment]
Deployed.
