### ISSUE TITLE
No default embedder size in code snippet breaks embedding

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2918]
Clicking the embed button yields the embed code snippet, the second part of which reads:

`<div class="amara-embed" data-height="px" data-width="px" data-url="..."></div>`

Although the embed instruction indicates "with the width and height of your choosing:", users that paste the code as-is get a failed embed load instead of a default sizes view, which ends filed into a support request.

It would be preferrable to have data-height and data-width prepopulated with some reasonable settings (e.g. 320px 640px) and then have users customize that, and/or have the embedder use minimum defaults when the data-width and data-height don't hold valid values.

The embed itself seems to render with excessive height if the div above isn't given a height, e.g. height="320".

**Comment by PCF-Testing** [comment]
What video type produces embed code with video size not populated? YouTube and MP4 videos seem to yield correct embed code, e.g.:

```
<div class="amara-embed" data-height="370px" data-width="620px" data-url="https://s3.amazonaws.com/ted.conferences/talk/transcript/2017/None/TristanHarris_2017-transcript.mp4">
</div>
```

**Comment by PCF-Testing** [comment]
This happens for collab teams (on new video pages).

**Comment by PCF-Testing** [comment]
This one is obsolete now. We don't use data-height anymore, and data-width is omitted by default (but may be set if the user chooses to). The embedder is resizable and takes the size of the container it is in.

Marking as closed.
