### ISSUE TITLE
No fall back for small thumbnail

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2925]
If a video has a URL-thumbnail and no s3 thumbnail, we fall back to the image at that url, but not for the small version which appears at search result.

**Comment by syl22-00** [comment]
Fixed in branch gh-unisubs-2925

**Comment by syl22-00** [comment]
@PCF-Testing have you had a chance to look at this? I merged staging back into it, so it is up to date.

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
