### ISSUE TITLE
Cannot sign in with the use of Facebook account

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#2935]
Observed on production.

Steps to reproduce:
1. Open http://amara.org/en/auth/login/?next=/
2. Click Facebook button (the associated user account already exists). A 500 error page appears.

**Comment by kslottow** [comment]
@PCF-Testing Amelia mentioned this will be fixed by pculture/amara-enterprise/issues/1691 , so moving to testing for you to confirm. Thanks!

**Comment by PCF-Testing** [comment]
Alas, still not working on staging, so needs further looking.

**Comment by PCF-Testing** [comment]
Verified on staging. Moving to Waiting for Deploy.

**Comment by PCF-Testing** [comment]
Fixed on production.

**Comment by PCF-Testing** [comment]
A problem again: https://sentry.io/pculture/unisubs-staging/issues/527736470/

**Comment by PCF-Testing** [comment]
Back to normal now.

**Comment by PCF-Testing** [comment]
Keep hitting this issue on production, staging, and locally. On the local instance, the error is as follows (keys and email addresses elided for privacy, can share via slack if necessary):

app_1            | ERROR 2018-04-28 05:31:50,735 unhandled_error 'fbsr_XXXXXXXXXXXXXXX'
app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
app_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1            |   File "/opt/apps/amara/apps/thirdpartyaccounts/views.py", line 171, in facebook_login
app_1            |     data = parse_signed_request(request.COOKIES['fbsr_' + settings.FACEBOOK_APP_ID], settings.FACEBOOK_SECRET_KEY)
app_1            | KeyError: 'fbsr_XXXXXXXXXXXXXXX'
app_1            | INFO 2018-04-28 05:31:51,370 access GET /auth/facebook_login_confirm/elided_email@gmail.com/ 500 (0.639s)

**Comment by bendk** [comment]
I'm pretty sure we figured this one out and it's not an issue anymore.  If there still are issues with facebook, let's create a new issue for it anyways.
