### ISSUE TITLE
Embedding Amara / YouTube videos in https page doesn't work

### ISSUE THREAD

**Issue by mspall** [pculture/unisubs#2938]
Amara is using some http resources in the YouTube embed script, so videos embedded in an https page won't play in Firefox or Chrome without allowing unsecured content in Firefox or "load unsafe scripts" in Chrome. Many users won't know how to do this and many would be prohibited by site policies.

**Comment by benroot** [comment]
The initial HTTPS request for the embedder-iframe script is being redirected to an HTTP request.
## Network Flow:
![redirect to http](https://user-images.githubusercontent.com/34732/30087872-f5005d70-9257-11e7-9377-9bc1e37f8d7c.png)
## Headers, Request 1
![screen shot 2017-09-05 at 4 42 24 pm](https://user-images.githubusercontent.com/34732/30088176-9d474b64-9259-11e7-8af0-f14ea23b3ba1.png)

## Headers, Request 2
![screen shot 2017-09-05 at 4 40 33 pm](https://user-images.githubusercontent.com/34732/30088068-218e71aa-9259-11e7-880a-be1014b51251.png)
## Headers, Request 3
![screen shot 2017-09-05 at 4 40 49 pm](https://user-images.githubusercontent.com/34732/30088069-243bd5a0-9259-11e7-9936-a2de338bfa2a.png)

**Comment by bendk** [comment]
I think this was fixed by updating the 08f678f48e0430f4721ecde9a8fa9ca48a96e2a4

**Comment by mspall** [comment]
I can confirm that this has been fixed. Thank you.
