### ISSUE TITLE
Figure out/fix notifications that weren't created

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2941]
When our rabbitmq server went down, it caused notifications not to be sent out.  We should:
 - Investigate why this happened
 - Create a fix for it.

Ideally, I think notifications should be saved in the same transaction that saves the subtitles.  So if there's any issue saving them, then that causes an error saving the subtitles.  This way we catch errors early rather than late.

Note that it's not so bad if we don't send the notifications out, as long as we save them in the DB.  If they're saved, then clients can look through the history using the API and find any that were missed.

**Comment by kslottow** [comment]
is this still relevant @bendk ? Reopen if it is
