### ISSUE TITLE
Load thumbnails of the correct protocol

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2942]
If you open amara using HTTPS, then navigate to a video, we try to load the thumbnail using HTTP.  This results in mixed content errors:

![screenshot from 2017-09-08 08-47-56](https://user-images.githubusercontent.com/1012809/30212329-788bc2b2-9472-11e7-9e9c-76d52c417b94.png)

The same issue happens when users try to load the embedder: https://pculture.freshdesk.com/helpdesk/tickets/96855

**Comment by kslottow** [comment]
@bendk is there a way we should recommend the user in https://pculture.freshdesk.com/helpdesk/tickets/96855 work around this until we fix it, or do we just need to fix it as soon as possible?

Can you estimate the work?

**Comment by bendk** [comment]
I don't think it's so big of a deal since it just affects the thumbnail.  As far as I know there's not much of a workaround, other than using http.

**Comment by kslottow** [comment]
sounds good, it's in the next sprint

**Comment by bendk** [comment]
Just updated the settings to change the MEDIA_URL to not have the http scheme.  That makes the API response use HTTPS and things seem to work.

**Comment by PCF-Testing** [comment]
Seems to have been fixed. Marking as closed.
