### ISSUE TITLE
Remove tastypie dependency

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2957]
We don't need it anymore as it was used only for the old apiv2

**Comment by syl22-00** [comment]
This is done in branches gh-unisubs-2957 on both unisubs and enterprise. Be careful with migrations, you need to migrate back if you want to switch back to another branch as this deleted the api keys from the tastypie table. The backwards migration adds them back.

**Comment by syl22-00** [comment]
This was merged into gh-enterprise-1674, so only that branch needs to be tested.

**Comment by PCF-Testing** [comment]
Deployed.
