### ISSUE TITLE
Remove old code and dependencies

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2961]
In branch gh-unisubs-2961

Dependencies:
* M2Crypto
* pyuca

Code:
* `utils/multipass.py`

**Comment by syl22-00** [comment]
We should just make sure that nothing is obviously broken.

**Comment by syl22-00** [comment]
This was merged into gh-enterprise-1674, so only that branch needs to be tested.

**Comment by PCF-Testing** [comment]
Deployed.
