### ISSUE TITLE
Make generic view for invalid API requests

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2966]
If someone makes a request that starts with "/api/", but doesn't match a view, we currently return an HTML 404 page.  We should return a JSON version instead to work with people's API code better.  The response should:

- Have a 404 status code
- Include the request path somewhere in the body.

**Comment by bendk** [comment]
Once we do this, we should notify Trisha and Alex from TED

**Comment by bendk** [comment]
On the gh-2966 branch.

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.

@bendk, @kslottow: This ticket involves notifying Trisha and Alex from TED. Who is in the best position to do so?

**Comment by kslottow** [comment]
Shared with Trish!
