### ISSUE TITLE
After upload of differently timed original subtitle, all the derived subtitles are out of synchronisation.

### ISSUE THREAD

**Issue by BoQsc** [pculture/unisubs#2969]
**Suggestion:** Make each subtitle of new original language to resynchronise to the nearest time of "derrived subtitle".

# Steps to reproduce a bug:
## Preparation
Have two differently timed subtitle files. (in my case, it's .srt)
https://guides.github.com/features/mastering-markdown/

## Reproduce a bug
1. Select any video to translate
2. by doing that you are directed to the information page about the subtitle. (**//amara.org/en/videos/xxxxxxxxx/info**)
![examplepage](https://user-images.githubusercontent.com/21064622/31319312-94c0b744-ac69-11e7-93c3-4a16966bd4db.png)
3. You click **Already have subtitles for this video? Upload them directly.** and uploading first subtitles file.
![uploadthemdirectly](https://user-images.githubusercontent.com/21064622/31319327-c230a658-ac69-11e7-88dc-8a68f7eb9ba3.png)
4. Then start a new language translation based on the uploaded original by clicking **Add a new language!**
![add a new language](https://user-images.githubusercontent.com/21064622/31319350-57c94b3e-ac6a-11e7-88d1-6dcbf348e071.png)

5. Make some translations using Amara's editor from the original language and save the draft.
6. Now upload second .srt translation file and replace the original translation with it.
7. Open the translation that you made from the original language. You must see desynchronised subtitles as shown in the image below.
![timeline_subtitles](https://user-images.githubusercontent.com/21064622/31319436-1c3b7086-ac6c-11e7-9f73-f56303460724.png)

**Comment by BoQsc** [comment]
# Steps to reproduce a bug:
## Preparation
Have two differently timed subtitle files. (in my case, it's .srt)
https://guides.github.com/features/mastering-markdown/

## Reproduce a bug
1. Select any video to translate
2. by doing that you are directed to information page about the subtitle. (**//amara.org/en/videos/xxxxxxxxx/info**)
![examplepage](https://user-images.githubusercontent.com/21064622/31319312-94c0b744-ac69-11e7-93c3-4a16966bd4db.png)
3. You click **Already have subtitles for this video? Upload them directly.** and uploading first subtitles file.
![uploadthemdirectly](https://user-images.githubusercontent.com/21064622/31319327-c230a658-ac69-11e7-88dc-8a68f7eb9ba3.png)
4. Then start a new language translation based on the uploaded original by klicking **Add a new language!**
![add a new language](https://user-images.githubusercontent.com/21064622/31319350-57c94b3e-ac6a-11e7-88d1-6dcbf348e071.png)

5.

**Comment by PCF-Testing** [comment]
Works as expected. 

You can use Copy Timing command to re-sync the translations to match the timing in the new transcript: https://support.amara.org/support/solutions/articles/195344-commands-available-through-tools-menu-wrench-icon-
