### ISSUE TITLE
Improve amara anonymous user

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2982]
The amara anonymous user is used to tracck actions done by tasks, but we should improve the way is is displayed: we usually keep it as inactive user, so it is displayed as "Retired User", we should keep it inactive but displays well when full name is used.

**Comment by syl22-00** [comment]
In branch gh-unisubs-2982, we have the following changes:

* When amara anonymous user is first created, it uses "amara-bot" as username
* When amara anoymous user is displayed, it show "Amara Bot", even if marked as inactive.

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
