### ISSUE TITLE
Undefined $() in embedder

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#2991]
Amara embed is currently loading the script seen here:

https://github.com/pculture/unisubs/blob/18f9263d7e4bfd971597384f1c77320b36d58750/templates/_experiments.html

This script includes a $(document).ready(function() "dollar function" call, jQuery style, but this is not defined on the user's end when jQuery is not loaded.

Either the call should use the full vanilla JavaScript function or this snippet shouldn't be going out with the embeds.

**Comment by syl22-00** [comment]
This should be inside an iframe, so not interfering with the host page. Have you seen an issue around it?

**Comment by franontanaya** [comment]
Looked at this while trying to debug some video not playing in the embedder, in the end that issue wasn't related to this.

**Comment by bendk** [comment]
looks like we can close this one.
