### ISSUE TITLE
AttributeError in notify_auto_unassignment

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#2994]
https://sentry.io/pculture/unisubs-staging/issues/382598697/

```
AttributeError: 'Collaboration' object has no attribute 'details_url'
  File "collab/notifications.py", line 60, in notify_auto_unassignment
    notify_assignment(collab, title, body, template_name, [user_pk], 'block_collab_auto_unassignments_message')
  File "collab/notifications.py", line 22, in notify_assignment
    'collab_url': collab.details_url(universal=True),

AttributeError: 'Collaboration' object has no attribute 'details_url'
```

**Comment by bendk** [comment]
@syl22-00 I think you made this code, can you take a quick look at it and either fix this one or schedule it for later?

**Comment by kslottow** [comment]
@syl22-00 could you just take a look at this one and see if there's anything Ben or Amelia need to know to take care of it later? Thanks!

**Comment by asabine** [comment]
we decided to replace the outdated details url with the subtitle version details page in the team context

**Comment by PCF-Testing** [comment]
The link in the email version of the message lacks the site part, e.g.: 
en/videos/nYXN61lh9Cju/zh-cn/4/4/?team=collab-test

The onsite version is OK.

**Comment by asabine** [comment]
added the domain and protocol for the details url and set the url to an empty string instead of None in the notification context

**Comment by PCF-Testing** [comment]
Now this looks even more broken than before. Email copies of notifications have no links at all. The onsite copies all point to http://unisubs.example.com:8000/en/messages/ instead of the language page.

Those "Assignment XXX..." links on the screenshot below all point to the Messages page:

![screenshot from 2018-01-26 05 48 01](https://user-images.githubusercontent.com/288455/35442603-b3ba2e98-025c-11e8-9457-868380d726e8.png)

Instead, they should link to the expired assignment, e.g. http://unisubs.example.com:8000/en/videos/ImiEKLEJI7SW/en/857/?team=collab-test

**Comment by asabine** [comment]
i have no idea where the messages links are coming from; there doesn't seem to be anything in the code that points to the messages link as far as i can tell. in either case, i changed the details url to use the video language page if a subtitle version doesn't exist which should fix the empty links

**Comment by PCF-Testing** [comment]
If there is an assignment, then there is always a matching language page. A subtitle version is not needed in this case.

**Comment by PCF-Testing** [comment]
The latest version of the code still behaves as described above - no URLs in emails, the links to the messages page in IM notifications.

**Comment by asabine** [comment]
i figured out the problem; the assignment no longer exists by the time the notification goes out (the notification task is set in the function that deletes the assignment), so the urls return empty at this point. in the case of a translation assignment, there is no more subtitle version or language page for the video, so instead i decided to link to the video page with the team context in this case.

**Comment by PCF-Testing** [comment]
The language page should be OK as long as the collaboration exists, could it be the language page?

**Comment by asabine** [comment]
as far as i'm aware, the language page doesn't exist until the translation is started; if a translation assignment is deleted first, the language page on that video won't exist yet. in this case, we show the video page instead.

**Comment by PCF-Testing** [comment]
See, for example, https://amara.org/en/videos/CILBF7jM5kgG/en/1957734/?team=maggie-collab-test - no subtitle version exists, but the language page is available. If a user is unassigned from this transcription, there is no reason we cannot send her a link to this language page - it provides the fastest way to reclaim the transcription again, if necessary and if it is not yet taken by someone else.

**Comment by asabine** [comment]
the problem i'm having is that there's no way to get the SubtitleLanguage id after it's been deleted; if there's no subtitle version the subtitle language may still exist, but in the case i described there is neither, so any attempt at programmatically getting the SubtitleLanguage.id will fail. in the link shown above, while there may not be a SubtitleVersion, there is a SubtitleLanguage still with the id 1957734.

**Comment by PCF-Testing** [comment]
Works great now, thanks! Verified.

**Comment by PCF-Testing** [comment]
@asabine @bendk: looks like testing this one on staging has produced https://sentry.io/pculture/unisubs-staging/issues/477795606/.

DoesNotExist: Site matching query does not exist.
(3 additional frame(s) were not displayed)
...
  File "collab/notifications.py", line 71, in notify_auto_unassignment
    notify_assignment(collab, title, body, template_name, [user_pk], 'block_collab_auto_unassignments_message')
  File "collab/notifications.py", line 33, in notify_assignment
    'collab_url': _format_collab_url(),
  File "collab/notifications.py", line 29, in _format_collab_url
    Site.objects.get_current().domain,

**Comment by bendk** [comment]
@asabine I think you need to switch that to `settings.HOSTNAME` because of my recent changes.

**Comment by PCF-Testing** [comment]
Deployed.
