### ISSUE TITLE
Vimeo player issue

### ISSUE THREAD

**Issue by syl22-00** [pculture/unisubs#2999]
Vimeo player controls stopped working, making it impossible to transcribe a vimeo video.

**Comment by syl22-00** [comment]
We currently have a couple of workarounds:
* When a vimeo video is open, we try to get a link to a direct file, so they become plain video files when in embedder or editor.
* If the video is not public, this file can not be retrieved, so the player still opens. We found that if the first thing done when editor is open is to seek the progress bar anywhere inside the vimeo player, then the editor will behave nicely. Some people report that this does not work on their end.
* If a video is private and is associated to a public trailer, the trailer opens instead of the video.

**Comment by syl22-00** [comment]
I fixed this, it is in the gh-unisubs-3004 branch (sorry for the name, I confused 2 tabs open on my browser).

**Comment by PCF-Testing** [comment]
Exception on submitting a video (https://vimeo.com/182979922):
TypeError at /videos/create/
expected string or buffer
Request Method:	POST
Request URL:	http://unisubs.example.com:8000/en/videos/create/
Django Version:	1.4.22
Exception Type:	TypeError
Exception Value:	
expected string or buffer
Exception Location:	/opt/apps/amara/apps/videos/models.py in set_values, line 751

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  20.                 return view_func(request, *args, **kwargs)
File "/opt/apps/amara/apps/videos/views.py" in create
  236.     if video_form.is_valid():
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in is_valid
  124.         return self.is_bound and not bool(self.errors)
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in _get_errors
  115.             self.full_clean()
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in full_clean
  271.         self._clean_form()
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in _clean_form
  299.             self.cleaned_data = self.clean()
File "/opt/apps/amara/apps/videos/forms.py" in clean
  252.                 self.cleaned_data['video_url'], self.user)
File "/opt/apps/amara/apps/videos/models.py" in add
  729.             incomplete = video.set_values(vt, video_url, user, team)
File "/opt/apps/amara/apps/videos/models.py" in set_values
  751.             self.description = self.re_unicode.sub(u'\uFFFD', self.description)

Exception Type: TypeError at /videos/create/
Exception Value: expected string or buffer

**Comment by PCF-Testing** [comment]
Videos play well on the branch.

The timeline does not move along with the video in some cases:
- When the video is being skipped forward or back with CTRL+<, CTRL+>, or SHIFT+TAB.
- When the user moves to the next step (start syncing or start review).

Marking as Needs PR, then will move it back to In Progress for the timeline fix.

**Comment by PCF-Testing** [comment]
First fix deployed, marking as In Progress to fix the timeline glitches.

**Comment by PCF-Testing** [comment]
- [ ] One more issue reported for password-protected videos:

The first time the subtitle editor is loaded and the password typed, the Amara player and subtitles do not work. After refreshing the page, everything is back to normal. Screencast: https://we.tl/sVS0IOCZAV
(https://pculture.freshdesk.com/helpdesk/tickets/98429).

**Comment by syl22-00** [comment]
What remains for this ticket is the quirk with password protected videos: to play those, one can enter the password in the editor, but will need to refresh the page to get it working. I'd suggest to open a new ticket for that.

**Comment by VeronicaPCF** [comment]
@PCF-Testing As Sylvain suggests, can a new ticket be opened to fix the issue with the password protected videos? Or can I offer an acceptable work-around to the user (as Sylvain says refreshing the page after entering the password maybe?) Just want to make sure I understand this well before I get back to the user. :) 
Thank you!

**Comment by kslottow** [comment]
@VeronicaPCF I opened #3101 for that, but I would offer that workaround to the user in the meantime. Thanks!
