### ISSUE TITLE
Get readthedocs builds working again

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3005]
They're failing now because of this issue: https://github.com/rtfd/readthedocs.org/issues/3020

We should try to figure out some way to make them work again.

**Comment by bendk** [comment]
So, it's not looking like readthedocs is going to fix this soon.  I think what we need is a service that:
  - Triggers when we push commits to unisubs/production
  - Copies the relevant code from unisubs to another repository.  (I think we would need to copy the docs, apps, and maybe util directory)
  - Makes a commit and pushes that repository

Then we can have readthedocs read from that repository to build its documentation.

**Comment by bendk** [comment]
Okay, so this is working in the dev branch.

I added a script there to pull in changes from the dev, so it should be fairly easy to update them.

I made pculture/infrastructure#104 for automating this.

**Comment by barseghyanartur** [comment]
@bendk:

How did you fix that? It still does not work for me. Any help is highly appreciated.

- https://github.com/rtfd/readthedocs.org/issues/3020

**Comment by bendk** [comment]
@barseghyanartur as far as I know, the issue is still present.  The way we worked around it was:

 - Create a separate branch, without the submodules.  We called ours docs.
 - Create a script to copy the relevent files from the main branch to the docs branch.
 - (still TODO) create a git commit hook that runs the update script, and pushes, whenever there's a new commit on the main branch

**Comment by barseghyanartur** [comment]
@bendk:

What a good idea. That should definitely work for me (until the RTD fixes the issue). Thanks a lot!

**Comment by barseghyanartur** [comment]
@bendk:

I've found even a better solution. Since I host my repositories both on BitBucket and GitHub (versions are in sync), I changed source repository from GitHub to BitBucket for Read the Docs. It worked perfectly well, since I don't have Git sub-modules there.
