### ISSUE TITLE
Make feed updating a managment command

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3010]
Right now we send this through our rabbitmq server, which results in a huge burst of activity.  Since we don't really need anything fancy like multiple consumers, we can skip the queue and just do everything in 1 container:

 - Create a feed_worker management command that:
    - Looks up all feed IDs
    - Goes through them one by one, and updates them
    - Sleeps (either after each feed, or after the entire list), so that we don't process feeds more than once an hour.
- Remove the code to schedule feed tasks once an hour
- Replace the current feed-worker container with a container that runs the feed_worker management command

**Comment by bendk** [comment]
Just implemented this in the gh-3010 branch.

Before testing:
  - Create a a few feeds to test with
  - run `dev build`

To test, run, run `dev up`.  You should see a new entry called `feed-worker_1` or something similar.  It should chug along, update feeds, and print to the logs each time it does it.  Run `docker-compose logs -f feed-worker` to see the logs of just the feed worker.

The command aims to update all the feeds in 1 hour, so it can be a long time between updates.  i.e. if you have 10 feeds, we should update them once every 6 minutes.

**Comment by PCF-Testing** [comment]
I am seeing the following error on the branch:

bin/dev up
Traceback (most recent call last):
  File "bin/dev", line 495, in <module>
    Dev().main()
  File "/home/maggie_s/unisubs-second/bin/command.py", line 187, in main
    self.execute(sys.argv[1:])
  File "/home/maggie_s/unisubs-second/bin/command.py", line 99, in execute
    self.run()
  File "/home/maggie_s/unisubs-second/bin/command.py", line 162, in run
    subcommand.execute(self.args.subcommand_args)
  File "/home/maggie_s/unisubs-second/bin/command.py", line 99, in execute
    self.run()
  File "bin/dev", line 207, in run
    subprocess.run(
AttributeError: 'module' object has no attribute 'run'

**Comment by bendk** [comment]
I think you need to update your python3 version.  I think you need 3.5 or later.

**Comment by PCF-Testing** [comment]
OK, I have updated python as follows:

python --version
Python 2.7.6
python3 --version
Python 3.5.3

Rebuilt the app and executed bin/dev up. feed-worker does appear in the terminal, but crashes at the start:
app_1          | *** uWSGI is running in multiple interpreter mode ***
app_1          | spawned uWSGI master process (pid: 1)
app_1          | spawned uWSGI worker 1 (pid: 14, cores: 1)
app_1          | spawned uWSGI worker 2 (pid: 15, cores: 1)
app_1          | metrics collector thread started
worker_1       | Traceback (most recent call last):
worker_1       |   File "/opt/apps/amara/manage.py", line 42, in <module>
feed-worker_1  | Traceback (most recent call last):
feed-worker_1  |   File "/opt/apps/amara/manage.py", line 42, in <module>
feed-worker_1  |     execute_from_command_line(sys.argv)
feed-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
worker_1       |     execute_from_command_line(sys.argv)
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
feed-worker_1  |     utility.execute()
feed-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
worker_1       |     utility.execute()
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
worker_1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
feed-worker_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/djcelery/management/commands/celery.py", line 22, in run_from_argv
feed-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 196, in run_from_argv
worker_1       |     ["%s %s" % (argv[0], argv[1])] + argv[2:])
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 890, in execute_from_commandline
feed-worker_1  |     self.execute(*args, **options.__dict__)
feed-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 231, in execute
feed-worker_1  |     self.validate()
feed-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 266, in validate
feed-worker_1  |     num_errors = get_validation_errors(s, app)
feed-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/validation.py", line 103, in get_validation_errors
feed-worker_1  |     connection.validation.validate_field(e, opts, f)
feed-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/validation.py", line 14, in validate_field
worker_1       |     super(CeleryCommand, self).execute_from_commandline(argv)))
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 179, in execute_from_commandline
feed-worker_1  |     db_version = self.connection.get_server_version()
feed-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 415, in get_server_version
worker_1       |     return self.handle_argv(prog_name, argv[1:])
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 882, in handle_argv
worker_1       |     return self.execute(command, argv)
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 857, in execute
worker_1       |     return cls(app=self.app).run_from_argv(self.prog_name, argv)
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 142, in run_from_argv
worker_1       |     return self(*args, **options)
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 112, in __call__
worker_1       |     ret = self.run(*args, **kwargs)
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 214, in run
worker_1       |     return self.target.run(*args, **kwargs)
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celeryd.py", line 153, in run
worker_1       |     return self.app.Worker(**kwargs).run()
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/apps/worker.py", line 157, in run
feed-worker_1  |     self.cursor().close()
feed-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 317, in cursor
worker_1       |     self.app.loader.init_worker()
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 116, in init_worker
feed-worker_1  |     cursor = self.make_debug_cursor(self._cursor())
feed-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 387, in _cursor
feed-worker_1  |     self.connection = Database.connect(**kwargs)
feed-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
worker_1       |     self.on_worker_init()
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/djcelery/loaders.py", line 127, in on_worker_init
feed-worker_1  |     return Connection(*args, **kwargs)
feed-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 193, in __init__
feed-worker_1  |     super(Connection, self).__init__(*args, **kwargs2)
feed-worker_1  | _mysql_exceptions.OperationalError: (2005, "Unknown MySQL server host 'db' (0)")
worker_1       |     self.close_database()
worker_1       |   File "/opt/apps/amara/apps/amaracelery/loaders.py", line 27, in close_database
worker_1       |     connection.cursor().execute("COMMIT")
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 317, in cursor
worker_1       |     cursor = self.make_debug_cursor(self._cursor())
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 387, in _cursor
worker_1       |     self.connection = Database.connect(**kwargs)
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
worker_1       |     return Connection(*args, **kwargs)
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 193, in __init__
worker_1       |     super(Connection, self).__init__(*args, **kwargs2)
worker_1       | _mysql_exceptions.OperationalError: (2005, "Unknown MySQL server host 'db' (0)")
unisubssecond_feed-worker_1 exited with code 1
unisubssecond_worker_1 exited with code 1
app_1          | INFO 2017-11-11 04:47:15,403 metrics avg_response_time=0 busy_workers=0 idle_workers=2 total_rss=0

Anything else I might be missing?

**Comment by bendk** [comment]
Looks like an issue with connecting to the database container.  Maybe just try running dev up again.

**Comment by bendk** [comment]
Also, maybe `docker-compose rm db` before running dev up.  Although that will kill all your database data.

**Comment by PCF-Testing** [comment]
Not sure what the issue had been, but after yet another rebuild the branch started successfully. According to the logs, the feeds get checked and updated at intervals.

There are some errors for ted.tasks.ted_check_for_new_videos in the logs, is that to be expected?

worker_1       | KeyError: 'videos.tasks.create_missing_index_objects'
worker_1       | ERROR 2017-11-14 05:47:49,465 celery.worker.consumer Received unregistered task of type u'videos.tasks.update_from_feed'.
worker_1       | The message has been ignored and discarded.
worker_1       | 
worker_1       | Did you remember to import the module containing this task?
worker_1       | Or maybe you are using relative imports?
worker_1       | Please see http://bit.ly/gLye1c for more information.
worker_1       | 
worker_1       | The full contents of the message body was:
worker_1       | {'retries': 0, 'task': u'videos.tasks.update_from_feed', 'eta': None, 'args': [], 'expires': None, 'callbacks': None, 'errbacks': None, 'kwargs': {}, 'id': '5d8959a8-bfe5-4a5b-94e7-3752b2e41acf', 'utc': True} (190b)
worker_1       | Traceback (most recent call last):
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 432, in on_task_received
worker_1       |     strategies[name](message, body, message.ack_log_error)
worker_1       | KeyError: u'videos.tasks.update_from_feed'
worker_1       | ERROR 2017-11-14 05:47:49,468 celery.worker.consumer Received unregistered task of type u'ted.tasks.ted_check_for_new_videos'.
worker_1       | The message has been ignored and discarded.
worker_1       | 
worker_1       | Did you remember to import the module containing this task?
worker_1       | Or maybe you are using relative imports?
worker_1       | Please see http://bit.ly/gLye1c for more information.
worker_1       | 
worker_1       | The full contents of the message body was:
worker_1       | {'retries': 0, 'task': u'ted.tasks.ted_check_for_new_videos', 'eta': None, 'args': [], 'expires': None, 'callbacks': None, 'errbacks': None, 'kwargs': {}, 'id': 'e3f396ba-0226-409c-806b-f18987d32b5d', 'utc': True} (195b)
worker_1       | Traceback (most recent call last):
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 432, in on_task_received
worker_1       |     strategies[name](message, body, message.ack_log_error)
worker_1       | KeyError: u'ted.tasks.ted_check_for_new_videos'
feed-worker_1  | INFO 2017-11-14 05:47:49,715 requests.packages.urllib3.connectionpool Starting new HTTP connection (1): link.brightcove.com
...
feed-worker_1  | Updated http://link.brightcove.com/services/mrss/player3404083053001/2385340575001/tags/26amara
feed-worker_1  | INFO 2017-11-14 05:53:40,930 requests.packages.urllib3.connectionpool Starting new HTTP connection (1): link.brightcove.com
feed-worker_1  | Updated http://link.brightcove.com/services/mrss/player3404083053001/2385340575001/tags/26amara
...
feed-worker_1  | Updated http://feeds.feedburner.com/TedtalksHD
...
worker_1       | ERROR 2017-11-14 06:00:00,004 celery.worker.consumer Received unregistered task of type u'videos.tasks.update_from_feed'.
worker_1       | The message has been ignored and discarded.
worker_1       | 
worker_1       | Did you remember to import the module containing this task?
worker_1       | Or maybe you are using relative imports?
worker_1       | Please see http://bit.ly/gLye1c for more information.
worker_1       | 
worker_1       | The full contents of the message body was:
worker_1       | {'retries': 0, 'task': u'videos.tasks.update_from_feed', 'eta': None, 'args': [], 'expires': None, 'callbacks': None, 'errbacks': None, 'kwargs': {}, 'id': '7aa64001-546c-4c07-8a2d-9f06e99328a0', 'utc': True} (190b)
worker_1       | Traceback (most recent call last):
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 432, in on_task_received
worker_1       |     strategies[name](message, body, message.ack_log_error)
worker_1       | KeyError: u'videos.tasks.update_from_feed'
worker_1       | ERROR 2017-11-14 06:00:00,006 celery.worker.consumer Received unregistered task of type u'ted.tasks.ted_check_for_new_videos'.
worker_1       | The message has been ignored and discarded.
worker_1       | 
worker_1       | Did you remember to import the module containing this task?
worker_1       | Or maybe you are using relative imports?
worker_1       | Please see http://bit.ly/gLye1c for more information.
worker_1       | 
worker_1       | The full contents of the message body was:
worker_1       | {'retries': 0, 'task': u'ted.tasks.ted_check_for_new_videos', 'eta': None, 'args': [], 'expires': None, 'callbacks': None, 'errbacks': None, 'kwargs': {}, 'id': 'bc35e857-1ff2-45a2-9c9a-62ded8778757', 'utc': True} (195b)
worker_1       | Traceback (most recent call last):
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 432, in on_task_received
worker_1       |     strategies[name](message, body, message.ack_log_error)
worker_1       | KeyError: u'ted.tasks.ted_check_for_new_videos'
worker_1       | ERROR 2017-11-14 06:00:00,010 celery.worker.consumer Received unregistered task of type u'stanford.tasks.pool_pending_transcriptions'.
worker_1       | The message has been ignored and discarded.
worker_1       | 
worker_1       | Did you remember to import the module containing this task?
worker_1       | Or maybe you are using relative imports?
worker_1       | Please see http://bit.ly/gLye1c for more information.
worker_1       | 
worker_1       | The full contents of the message body was:
worker_1       | {'retries': 0, 'task': u'stanford.tasks.pool_pending_transcriptions', 'eta': None, 'args': [], 'expires': None, 'callbacks': None, 'errbacks': None, 'kwargs': {}, 'id': '923c7f3f-2603-488d-9dcd-5b5385a46e30', 'utc': True} (203b)
worker_1       | Traceback (most recent call last):
worker_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 432, in on_task_received
worker_1       |     strategies[name](message, body, message.ack_log_error)
worker_1       | KeyError: u'stanford.tasks.pool_pending_transcriptions'
...
feed-worker_1  | Updated https://vimeo.com/eylenda/videos/rss
...
feed-worker_1  | Updated https://vimeo.com/user14284554/videos/rss
app_1          | INFO 2017-11-14 06:15:10,669 metrics avg_response_time=0 busy_workers=0 idle_workers=2 total_rss=0

And I am not seeing imports from YouTube channels linked to personal accounts, have those been affected and how often / when import should happen?

**Comment by bendk** [comment]
These error messages are not a problem:

```
KeyError: u'ted.tasks.ted_check_for_new_videos`
```

It happens when we remove a task, but it's still scheduled in the system.  It's not a big deal, we just need to remove it from the django admin.

Good catch on the youtube feeds.  I updated the task so it runs those too.

One last thing to test, if you can, is provider requests.  There's 2 things:
  - That requests fire at all.  I think you can just test if the dummy provider is working.  It should take about 30 seconds to get the result back.
  -  If retrying failed attempts works.  I'm not sure if you have a way to test this.  If not, don't worry about it.  If the first item works, this one should too.

**Comment by PCF-Testing** [comment]
Provider requests do work, I have tried both with the dummy provider and with MAC with a short video, no issues detected.

The YouTube import still is a problem on my end. YouTube feeds added to teams (such as 
https://www.youtube.com/feeds/videos.xml?channel_id=UC_GiI83OPF1cwYlT9wUpMBw) work without a hitch, pulling in videos almost instantly. However, videos from the personal YouTube channels don't get imported - they typically used to get imported almost instantly. The following test cases keep failing - both the basic https://amara.testlodge.com/projects/23746/suites/111097?expand_section=94078#case_1815556 and the more fragile https://amara.testlodge.com/projects/23746/suites/111097?expand_section=94078#case_1815619.

**Comment by bendk** [comment]
I was able to get importing to work with my personal channel.  I think the tricky part is that it takes limits itself so that it only takes an hour to import all the items.  I just added 2 changes:

 - On dev instances, aim to import all feeds every 5 minutes, rather than every hour
  - The setting is named FEEDWORKER_PASS_DURATION.  You can set it to something even shorter in dev_settings_local, if it helps out testing
 - When a youtube account is added, we import all videos right then.

**Comment by bendk** [comment]
And I realize you definitely need to run dev build when switching between this branch and others.  If you don't run that then the feedworker command won't be the right one.

**Comment by PCF-Testing** [comment]
Confirming import from "personal" YT channels works.

I am seeing some general problems with the branch though:
- Some pages are not available:
NoReverseMatch at /staff/
Reverse for 'community' with arguments '()' and keyword arguments '{}' not found.
Request Method:	GET
Request URL:	http://unisubs.example.com:8000/en/staff/
Django Version:	1.4.22
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'community' with arguments '()' and keyword arguments '{}' not found.
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py in render, line 426
Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/utils/decorators.py" in _checklogin
  41.             return view_func(request, *args, **kwargs)
File "/opt/apps/amara/apps/staff/views.py" in index
  27.         'sections': staff.get_sections(),
File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py" in render
  44.     return HttpResponse(loader.render_to_string(*args, **kwargs),
File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py" in render_to_string
  176.         return t.render(context_instance)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  140.             return self._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py" in instrumented_test_render
  63.     return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  823.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  74.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  123.         return compiled_parent._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py" in instrumented_test_render
  63.     return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  823.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  74.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  62.             result = block.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  823.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  74.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
  155.         return self.render_template(self.template, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render_template
  137.         output = template.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  140.             return self._render(context)
File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py" in instrumented_test_render
  63.     return self.nodelist.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
  823.                 bit = self.render_node(node, context)
File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py" in render_node
  74.             return node.render(context)
File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
  426.                         raise e

Exception Type: NoReverseMatch at /staff/
Exception Value: Reverse for 'community' with arguments '()' and keyword arguments '{}' not found.

- Errors on submitting videos:
IntegrityError at /teams/add/video/maggies-team-one/
(1062, "Duplicate entry '1fc4884c14e4e803572246bead76a376-Y' for key 'videos_videourl_url_hash_460bfa3b228c3ad6_uniq'")
Request Method:	POST
Request URL:	http://unisubs.example.com:8000/en/teams/add/video/maggies-team-one/
Django Version:	1.4.22
Exception Type:	IntegrityError
Exception Value:	
(1062, "Duplicate entry '1fc4884c14e4e803572246bead76a376-Y' for key 'videos_videourl_url_hash_460bfa3b228c3ad6_uniq'")

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/utils/__init__.py" in wrapper
  55.             output = func(request, *args, **kw)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  20.                 return view_func(request, *args, **kwargs)
File "/opt/apps/amara/apps/teams/views.py" in add_video
  847.     if form.is_valid():
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in is_valid
  124.         return self.is_bound and not bool(self.errors)
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in _get_errors
  115.             self.full_clean()
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in full_clean
  271.         self._clean_form()
File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py" in _clean_form
  299.             self.cleaned_data = self.clean()
File "/opt/apps/amara/apps/teams/oldforms.py" in clean
  270.                       self.setup_video, self.team)
File "/opt/apps/amara/apps/videos/models.py" in add
  724.             video, video_url = cls._get_video_for_add(url, user, team)
File "/opt/apps/amara/apps/videos/models.py" in _get_video_for_add
  771.         video_url = video._add_video_url(vt, user, True, team)
File "/opt/apps/amara/apps/videos/models.py" in _add_video_url
  836.                 'videoid': vt.video_id if vt.video_id else '',
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in get_or_create
  134.         return self.get_query_set().get_or_create(**kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in get_or_create
  452.                 obj.save(force_insert=True, using=self.db)
File "/opt/apps/amara/apps/videos/models.py" in save
  2298.         super(VideoUrl, self).save(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save
  463.         self.save_base(using=using, force_insert=force_insert, force_update=force_update)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save_base
  551.                 result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in _insert
  203.         return insert_query(self.model, objs, fields, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in insert_query
  1593.     return query.get_compiler(using=using).execute_sql(return_id)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in execute_sql
  912.             cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
  40.             return self.cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py" in execute
  114.             return self.cursor.execute(query, args)
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py" in execute
  205.             self.errorhandler(self, exc, value)
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py" in defaulterrorhandler
  36.     raise errorclass, errorvalue

Exception Type: IntegrityError at /teams/add/video/maggies-team-one/
Exception Value: (1062, "Duplicate entry '1fc4884c14e4e803572246bead76a376-Y' for key 'videos_videourl_url_hash_460bfa3b228c3ad6_uniq'")

**Comment by bendk** [comment]
The staff page issue was one from a change I made to dev.  I just fixed it both on dev and gh-3010.

The IntegrityError seems related to gh-2127.  Maybe you need to run `dev migrate`?.  Regardless, I think it will go away once we merge the code to dev.

I'm hoping those are the last issues, since I think that would mean we're okay to merge this code to dev.  I'm really hoping to get it out this week.

**Comment by PCF-Testing** [comment]
Staff page has been restored.

However, I do not have enough confidence in the behaviour of the branch. I have the impression that with the introduction of FEEDWORKER_PASS_DURATION parameter, the branch has gone crazy and keeps checking all the feeds and channels know to the system non-stop, so that there are hardly any resources left for anything else. Below is a part of the log; you can see that checks for updates just never stop, happening every minute or even more often (FEEDWORKED_PASS_DURATION is set to 15), and the app regularly crashes:

feed-worker_1  | Imported YouTube: AmaraRocks
feed-worker_1  | Updated http://link.brightcove.com/services/mrss/player3404083053001/2385340575001/tags/26amara
feed-worker_1  | Updated https://vimeo.com/eylenda/videos/rss
feed-worker_1  | Updated https://vimeo.com/user14284554/videos/rss
feed-worker_1  | Updated https://vimeo.com/tragicrelief/videos/rss
feed-worker_1  | Updated https://vimeo.com/greenjellyfilm/videos/rss
feed-worker_1  | Updated https://www.youtube.com/feeds/videos.xml?channel_id=UCb1_fG49A2rDphYMKlofq-A
feed-worker_1  | Updated https://vimeo.com/glassbreakerfilms/videos/rss
feed-worker_1  | Updated https://vimeo.com/user8951509/videos/rss
feed-worker_1  | Updated https://www.youtube.com/feeds/videos.xml?channel_id=UC_GiI83OPF1cwYlT9wUpMBw
app_1          | Tue Nov 21 03:24:00 2017 - *** HARAKIRI ON WORKER 2 (pid: 17, try: 1) ***
app_1          | Tue Nov 21 03:24:00 2017 - HARAKIRI !!! worker 2 status !!!
app_1          | Tue Nov 21 03:24:00 2017 - HARAKIRI [core 0] 172.19.0.1 - GET /en/videos/search-urls/ since 1511256194
app_1          | Tue Nov 21 03:24:00 2017 - HARAKIRI !!! end of worker 2 status !!!
app_1          | DAMN ! worker 2 (pid: 17) died, killed by signal 9 :( trying respawn ...
app_1          | Respawned uWSGI worker 2 (new pid: 20)
feed-worker_1  | Updated http://vimeo.com/inhiraaf/videos/rss
app_1          | INFO 2017-11-21 03:24:03,995 metrics avg_response_time=0 busy_workers=2 idle_workers=0 total_rss=0
feed-worker_1  | Updated https://vimeo.com/noamarmonn/videos/rss
feed-worker_1  | Imported YouTube: AmaraRocks
feed-worker_1  | Imported YouTube: Margarita Shamraeva
feed-worker_1  | Updated http://link.brightcove.com/services/mrss/player3404083053001/2385340575001/tags/26amara
feed-worker_1  | Updated http://feeds.feedburner.com/TedtalksHD
feed-worker_1  | Updated https://vimeo.com/eylenda/videos/rss
feed-worker_1  | Imported YouTube: Don Juan
feed-worker_1  | Updated http://link.brightcove.com/services/mrss/player3404083053001/2385340575001/tags/26amara
feed-worker_1  | Updated https://vimeo.com/user14284554/videos/rss
feed-worker_1  | Imported YouTube: AmaraRocks
feed-worker_1  | Imported YouTube: Margarita Shamraeva
feed-worker_1  | Updated http://link.brightcove.com/services/mrss/player3404083053001/2385340575001/tags/26amara
feed-worker_1  | Updated https://vimeo.com/tragicrelief/videos/rss
feed-worker_1  | Updated https://vimeo.com/greenjellyfilm/videos/rss
app_1          | INFO 2017-11-21 03:24:22,877 access GET /videos/search-urls/ 200 (39.950s)
app_1          | INFO 2017-11-21 03:24:23,781 access GET /media/jsi18catalog/en.js 200 (0.749s)
feed-worker_1  | Updated https://www.youtube.com/feeds/videos.xml?channel_id=UCb1_fG49A2rDphYMKlofq-A
app_1          | INFO 2017-11-21 03:24:26,665 access GET /media/jslanguagedata/en.js 200 (3.370s)
feed-worker_1  | Updated https://vimeo.com/glassbreakerfilms/videos/rss
feed-worker_1  | Updated https://vimeo.com/user8951509/videos/rss
feed-worker_1  | Updated https://www.youtube.com/feeds/videos.xml?channel_id=UC_GiI83OPF1cwYlT9wUpMBw
feed-worker_1  | Updated http://vimeo.com/inhiraaf/videos/rss
feed-worker_1  | Updated https://vimeo.com/noamarmonn/videos/rss
app_1          | INFO 2017-11-21 03:24:34,001 metrics avg_response_time=6100184 busy_workers=1 idle_workers=1 total_rss=229322752
app_1          | INFO 2017-11-21 03:24:35,679 access GET /media/css/amara.css 200 (11.889s)
feed-worker_1  | Imported YouTube: Don Juan
feed-worker_1  | Updated http://link.brightcove.com/services/mrss/player3404083053001/2385340575001/tags/26amara
feed-worker_1  | Imported YouTube: Don Juan
feed-worker_1  | Updated http://feeds.feedburner.com/TedtalksHD
feed-worker_1  | Imported YouTube: Margarita Shamraeva
feed-worker_1  | Updated https://vimeo.com/eylenda/videos/rss
feed-worker_1  | Updated https://vimeo.com/user14284554/videos/rss
feed-worker_1  | Updated https://vimeo.com/tragicrelief/videos/rss
feed-worker_1  | Updated https://vimeo.com/greenjellyfilm/videos/rss
feed-worker_1  | Updated https://www.youtube.com/feeds/videos.xml?channel_id=UCb1_fG49A2rDphYMKlofq-A
feed-worker_1  | Updated https://vimeo.com/glassbreakerfilms/videos/rss

**Comment by PCF-Testing** [comment]
The above problem was caused by FEEDWORKER_PASS_DURATION being in seconds - every 5 or 15 seconds was way too often.

**Comment by PCF-Testing** [comment]
Deployed.
