### ISSUE TITLE
Make styleguide use new amara-assets code

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3019]

**Comment by bendk** [comment]
This is working for me at /styleguide

**Comment by PCF-Testing** [comment]
Is it in the marketing-page-merge branch?

If yes, what is the difference with the current version on production?

Finally, are these pages supposed to be accessible to any user (current behaviour), or should they require special permissions?

**Comment by bendk** [comment]
There shouldn't be any difference.  The issue is just moving the functionality to the new repo.  I think they should be accessible to anyone.

**Comment by PCF-Testing** [comment]
OK, moving to Needs PR queue.

**Comment by PCF-Testing** [comment]
Deployed.
