### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one VideoUrl -- it returned 2! Lookup parameters were {}

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3029]
https://sentry.io/pculture/unisubs-staging/issues/408757751/

```
MultipleObjectsReturned: get() returned more than one VideoUrl -- it returned 2! Lookup parameters were {}
(4 additional frame(s) were not displayed)
...
  File "externalsites/models.py", line 570, in import_videos
    Video.add(video_url, self.user)
  File "videos/models.py", line 724, in add
    video, video_url = cls._get_video_for_add(url, user, team)
  File "videos/models.py", line 761, in _get_video_for_add
    cls._check_prevent_duplicate_public_videos(url)
  File "videos/models.py", line 884, in _check_prevent_duplicate_public_videos
    video_url = qs.get()
  File "videos/models.py", line 2167, in get
    return super(VideoUrlQueryset, self).get(**kwargs)

MultipleObjectsReturned: get() returned more than one VideoUrl -- it returned 2! Lookup parameters were {}
```

**Comment by bendk** [comment]
I'm pretty sure you can reproduce this as follows:
  - Create team A with prevent_duplicate_public_videos set to True
  - Create team B with the same setting
  - Add a video URL to team A
  - Add the same video URL to team B
  - Attempt to add that same video URL to the public area

**Comment by PCF-Testing** [comment]
Could confirm that the above scenario indeed lead to the exception listed in the ticket and that the branch fixed the exception.

Also tried the same scenario on gh-3029 with a small twist:
- Team A was created and managed by Admin A
- Team B was created and managed by Admin B
- The video was submitted to the public space by user C
There was no exception on the user-facing page, just a regular styled 403 page, but the logs had the following unhandled error:
app_1          | INFO 2017-11-30 09:07:35,065 access POST /videos/create/ 302 (0.011s)
app_1          | ERROR 2017-11-30 09:07:35,087 unhandled_error 
app_1          | Traceback (most recent call last):
app_1          |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
app_1          |     response = callback(request, *callback_args, **callback_kwargs)
app_1          |   File "/opt/apps/amara/utils/behaviors.py", line 79, in wrapper
app_1          |     return func(*args, **kwargs)
app_1          |   File "/opt/apps/amara/apps/videos/views.py", line 272, in video
app_1          |     return oldviews.video(request, video_id, video_url, title)
app_1          |   File "/opt/apps/amara/apps/videos/decorators.py", line 59, in wrapper
app_1          |     raise PermissionDenied()
app_1          | PermissionDenied
app_1          | INFO 2017-11-30 09:07:35,105 access GET /videos/UtzxvUrheZ6B/info/vimeocom242570434/ 403 (0.038s)

Does this require a fix?

Unit tests all pass for the branch, but I noticed that Vimeo videos do not pull metadata (titles, thumbnails, duration) on some teams, which is a regression from enterprise-1697.

**Comment by bendk** [comment]
I think that is fine.  Django catches permission denied and turns it into a 403 response, so it's no big deal.

I think the vimeo issue is just because it hasn't been merged yet.

Can I create a PR?

**Comment by PCF-Testing** [comment]
The Vimeo change (enterprise-1697) was actually deployed to production on Nov 1, so it is really weird to see that regression now. But if you think it's normal, I could re-test on staging after merging.

**Comment by bendk** [comment]
Hmm, I'm not sure what's up then, but I don't think this change could affect vimeo stuff.  Does vimeo metadata work for you in dev?  In any case, I made the PR.

**Comment by PCF-Testing** [comment]
Deployed
