### ISSUE TITLE
shell quits unexpectedly

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3074]
When running a shell inside the amara container, I notice it quits at some times when I don't expect it:

 - Invalid management command (`manage foo`)
 - After a successful management command (`manage ensure_db`)
 - Open a dbshell, then hit ctrl-d

It would be nice if this didn't happen.

**Comment by asabine** [comment]
^D is the EOF character in most shells, in bash you can use `set -o ignoreeof` (or add it to the .bashrc probably)

**Comment by bendk** [comment]
Looks fixed as of that last commit.
