### ISSUE TITLE
Speed up search on the admin tasks page

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3075]

**Comment by bendk** [comment]
Implemented on the gh-3075 branch.

I don't know if we can simulate the error, probably the best thing to test is that search still works.

I made it so search only searches against videos.  Before it also team and assignee names.  I hope that's okay.  The good part is that video searching now uses the index, so it matches all the stuff we search for, not just the title.

**Comment by PCF-Testing** [comment]
Verified that search still works.

**Comment by PCF-Testing** [comment]
On staging, I cannot find any tasks by "What do we do when antibiotics don’t work any more?", although you can see matching tasks at the top of https://staging.amara.org/en/admin/teams/task/

**Comment by bendk** [comment]
I think that's just a different search algorithm.  I notice that searching for "antibiotics" works.  I'm not sure the issue, maybe it's the punctiation, or maybe it's just too many search terms.  In any case, it's the same search that we use for the team videos page, so I think it's okay.

**Comment by PCF-Testing** [comment]
Deployed.
