### ISSUE TITLE
Replace brightcove accounts

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3077]
Our non CMS brightcove accounts use use the old Media API to write captions.  According to the docs (https://docs.brightcove.com/en/video-cloud/media/references/reference.html) this will stop working 6/30.  We should contact our partners/users and inform them they need to update.

**Comment by bendk** [comment]
@kslottow I scheduled this for februrary, not sure if you already had a plan for it.

**Comment by syl22-00** [comment]
@bendk I think the old API stopped working in june last year, and at the time we did the switch we contacted people who were using it. The old API credentials can not be seen or added anymore, but we did keep them in the database. Also the old brightcove integration only works for old player videos which are also deprecated.

**Comment by bendk** [comment]
Ahh okay, we can just close this one then.
