### ISSUE TITLE
Test new staging deploy

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3080]
I just created staging2.amara.org -- it's a staging deploy on the new infrastructure.  We should test that everything works the same as staging.

One exception is that some of the account linking code probably won't work, because of the domain name change.

**Comment by PCF-Testing** [comment]
Most pages on staging2 500 with IOError related to images. Example:

https://staging2.amara.org/en/videos/watch/ 
IOError: [Errno 2] No such file or directory: u'/opt/apps/amara/user-data/video/thumbnail/ffdee5b70225b5ba806186f52aedaffaf9d462bb'
(37 additional frame(s) were not displayed)
...
  File "videos/views.py", line 196, in watch_page
    'latest_videos': Video.objects.latest()[:VIDEO_IN_ROW*3],
  File "videos/models.py", line 547, in get_small_thumbnail
    return self.s3_thumbnail.thumb_url(120, 90)
  File "utils/amazon/fields.py", line 27, in thumb_url
    self._create_thumbnail(self._open_image(), size)
  File "utils/amazon/fields.py", line 31, in _open_image
    content = self.storage.open(self.name).read()

**Comment by bendk** [comment]
That should be fixed now.

**Comment by PCF-Testing** [comment]
Experienced several random 502s, but apart from that, things look good to me.

What should I do with this ticket, just close it?

**Comment by bendk** [comment]
Yeah, let's close.
