### ISSUE TITLE
Remove the team admins page

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3081]
From #2137:

> For invitation-only teams, the branch has /teams/[team-slug]/admins/ page which lists the team admins' personal email addresses. It is a violation of Amara's privacy policy that forbids disclosure of users' email addresses. Instead, the page should have email (envelope) icons linking to Create Message page for the admin.

I have no clue what this page is supposed to be for.  Do we even need it?

**Comment by bendk** [comment]
We link to this page in a couple places.  So, for an easy fix we should redirect it for new-style teams to the team member directory with the following querystring: `?q=&sort=recent&role=admin&language=any`

**Comment by asabine** [comment]
@bendk so the old_dashboard view doesn't ever get rendered anywhere as far as i can tell. only reference to it in the entire codebase is it's own definition so i think we can safely remove this. old teams use the dashboard in new_views anyway now; the template for the old dashboard is only referenced by the old view too so we can remove that too.

in the case of the welcome page, it only links to the admin-list page for invitation teams if the user is not a member. in this case they won't be able to see the member directory anyway. in this case, should we have a way to message the admins through the site via a message or without disclosing email addresses? or just remove the text telling users to contact a team admin altogether?

**Comment by bendk** [comment]
I don't really remember the old_dashboard code, but if you take it away and the old team's dashboard still works, then I think it should be fine.

For the second one, maybe @PCF-Testing would know better than me about it.  But my guess is that it's still useful.  Maybe you could add a new view, with a different permissions check, that still used the template code from the member directory?  I'm not really sure if that would work or not.

**Comment by PCF-Testing** [comment]
I think for old teams "Contact a team admin" page works just fine, because it does not expose any personal information. See, for example, https://amara.org/en/teams/demandgeneration/ and https://amara.org/en/teams/demandgeneration/admins/.

For new teams, the link redirects to a page that exposes the team admins' real email addresses. Example: https://amara.org/en/teams/MAC-Demo/admins/ This definitely should not happen. However, it should be OK to replace the real email addresses with links to Send Message page (e.g. https://amara.org/en/messages/new/?user=TED).

**Comment by PCF-Testing** [comment]
The worker on the branch crashes upon start with the following exception:

app_1            | Traceback (most recent call last):
app_1            |   File "/opt/apps/amara/deploy/unisubs.wsgi", line 13, in <module>
app_1            |     startup.startup()
app_1            |   File "/opt/apps/amara/startup.py", line 79, in startup
app_1            |     run_startup_modules()
app_1            |   File "/opt/apps/amara/startup.py", line 68, in run_startup_modules
feed-worker_1    |   File "/opt/apps/amara/startup.py", line 79, in startup
app_1            |     __import__('{}.{}'.format(app, module))
app_1            |   File "/opt/apps/amara/apps/teams/startup.py", line 21, in <module>
feed-worker_1    |     run_startup_modules()
worker_1         | Traceback (most recent call last):
app_1            |     import teams.workflows.startup
feed-worker_1    |   File "/opt/apps/amara/startup.py", line 68, in run_startup_modules
worker_1         |   File "/opt/apps/amara/manage.py", line 37, in <module>
app_1            |   File "/opt/apps/amara/apps/teams/workflows/startup.py", line 28, in <module>
feed-worker_1    |     __import__('{}.{}'.format(app, module))
app_1            |     from teams.workflows.old import OldTeamWorkflow
feed-worker_1    |   File "/opt/apps/amara/apps/teams/startup.py", line 21, in <module>
worker_1         |     startup.startup()
app_1            |   File "/opt/apps/amara/apps/teams/workflows/old/__init__.py", line 3, in <module>
feed-worker_1    |     import teams.workflows.startup
app_1            |     from .workflow import OldTeamWorkflow
feed-worker_1    |   File "/opt/apps/amara/apps/teams/workflows/startup.py", line 28, in <module>
app_1            |   File "/opt/apps/amara/apps/teams/workflows/old/workflow.py", line 35, in <module>
feed-worker_1    |     from teams.workflows.old import OldTeamWorkflow
app_1            |     class OldTeamWorkflow(TeamWorkflow):
feed-worker_1    |   File "/opt/apps/amara/apps/teams/workflows/old/__init__.py", line 3, in <module>
app_1            |   File "/opt/apps/amara/apps/teams/workflows/old/workflow.py", line 51, in OldTeamWorkflow
worker_1         |   File "/opt/apps/amara/startup.py", line 79, in startup
feed-worker_1    |     from .workflow import OldTeamWorkflow
app_1            |     dashboard_view = staticmethod(views.old_dashboard)
worker_1         |     run_startup_modules()
feed-worker_1    |   File "/opt/apps/amara/apps/teams/workflows/old/workflow.py", line 35, in <module>
app_1            | AttributeError: 'module' object has no attribute 'old_dashboard'
worker_1         |   File "/opt/apps/amara/startup.py", line 68, in run_startup_modules
feed-worker_1    |     class OldTeamWorkflow(TeamWorkflow):
app_1            | unable to load app 0 (mountpoint='') (callable not found or import error)
worker_1         |     __import__('{}.{}'.format(app, module))
feed-worker_1    |   File "/opt/apps/amara/apps/teams/workflows/old/workflow.py", line 51, in OldTeamWorkflow
worker_1         |   File "/opt/apps/amara/apps/teams/startup.py", line 21, in <module>
app_1            | *** no app loaded. going in full dynamic mode ***
feed-worker_1    |     dashboard_view = staticmethod(views.old_dashboard)
worker_1         |     import teams.workflows.startup
app_1            | *** uWSGI is running in multiple interpreter mode ***
feed-worker_1    | AttributeError: 'module' object has no attribute 'old_dashboard'
worker_1         |   File "/opt/apps/amara/apps/teams/workflows/startup.py", line 28, in <module>
app_1            | spawned uWSGI master process (pid: 1)
worker_1         |     from teams.workflows.old import OldTeamWorkflow
worker_1         |   File "/opt/apps/amara/apps/teams/workflows/old/__init__.py", line 3, in <module>
worker_1         |     from .workflow import OldTeamWorkflow
worker_1         |   File "/opt/apps/amara/apps/teams/workflows/old/workflow.py", line 35, in <module>
worker_1         |     class OldTeamWorkflow(TeamWorkflow):
app_1            | spawned uWSGI worker 1 (pid: 14, cores: 1)
worker_1         |   File "/opt/apps/amara/apps/teams/workflows/old/workflow.py", line 51, in OldTeamWorkflow
worker_1         |     dashboard_view = staticmethod(views.old_dashboard)
worker_1         | AttributeError: 'module' object has no attribute 'old_dashboard'

**Comment by asabine** [comment]
do you have the latest version of the branch? it's not crashing for me locally but i reset the branch when i started this morning and this looks like an issue that would've happened with the old one. might need to run `git fetch` or reset the local branch before pulling again

**Comment by PCF-Testing** [comment]
Right, I have managed to delete the older version of the local branch and check out the updated version.

It seems that Send Message link is erroneously using the admin's name instead of the username (http://unisubs.example.com:8000/en/messages/new/?user=[FirstName%20SecondName]), which breaks when an admin has a personal name set.

**Comment by asabine** [comment]
yeah my mistake, should be fixed now :)

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
