### ISSUE TITLE
Member profile page gets layed out weird with long video titles

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3093]
![image](https://user-images.githubusercontent.com/1012809/35102961-75f46f4a-fc32-11e7-965e-a4d06fe3d299.png)

**Comment by bendk** [comment]
Should be fixed in gh-3093.  In additon to the member profile page, can you make sure I didn't mess up anything with the assignments history list on the dashboard page?

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
