### ISSUE TITLE
user menu triangle misaligned on the videos/create page

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3094]
![image](https://user-images.githubusercontent.com/1012809/35103005-9c54e55c-fc32-11e7-9bc7-54eea6dddbc6.png)

**Comment by bendk** [comment]
I pushed a quick fix directly to dev/staging for this one.

**Comment by PCF-Testing** [comment]
Verified on staging.

**Comment by PCF-Testing** [comment]
Deployed.
