### ISSUE TITLE
jspScrollbars go crazy when you hit a breakpoint

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#3097]
@bendk commented on [Fri Jan 19 2018](https://github.com/pculture/amara-design/issues/253)

When you hit a breakpoint and the content width shrinks, the scrollbars get positioned in a crazy place:

![screenshot from 2018-01-19 13-20-40](https://user-images.githubusercontent.com/1012809/35165271-ac279436-fd1b-11e7-879b-67997f6fd4dd.png)

Maybe we should just move away from jspScrollbar.

**Comment by kslottow** [comment]
we'll get rid of this library

**Comment by bendk** [comment]
Fixed in the gh-enterprise-1624 branch.

**Comment by bendk** [comment]
The fix was to just use native scrollbars so we don't have the issue.

I also upped the min-height a bit so the video duration filter doesn't need a scrollbar.  I don't think this needs testing, so I'm just going to put it in the needs PR pipeline.

**Comment by PCF-Testing** [comment]
Deployed.
