### ISSUE TITLE
update amara.org sitemap link to blog

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#3102]
The blog is now at blog.amara.org, and old about.amara.org links are redirecting to this new url. We need to change the link on the sitemap to blog.amara.org too.

**Comment by bendk** [comment]
Pushed the change directly to dev/master.

**Comment by PCF-Testing** [comment]
@bendk: staging still has the old link.

**Comment by bendk** [comment]
Oops, I only changed the link on the sitemap.  Deploying a change now that should fix the other ones.

**Comment by PCF-Testing** [comment]
Verified the fix.

**Comment by PCF-Testing** [comment]
Deployed.
