### ISSUE TITLE
unify code that defines layouts between app and marketing page break points

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#3116]
We should merge the layout code between the app and marketing page.

We should have these sizes:
  - `> 1400` large (desktop)
  - `1024-1400` medium (small desktop)
  - `768-1024` small (mobile landscape/tablet portrait)
 - `< 768 ` xtra-small (mobile portrait)

**Comment by bendk** [comment]
I'm going to be doing this one in the gh-enterprise-1981 branch, because that one has a layout that's complex enough to deserve a good foundation.

**Comment by kslottow** [comment]
This will fix the following problem observed on production: https://amara.org/en/teams/judit-testing/manage/requests/
impersonate: kslottow
OS Sierra, Chrome 66

Between screen widths of 1195 and 1331 px, all tabs show on a horizontal line. Once the width gets WIDER than 1332, however, "videos" (the last tab) jumps down one line

![Screen Shot 2018-05-30 at 10.11.20 PM.png](https://images.zenhubusercontent.com/57e968ee95e42b6c5ba978a4/00ee8642-917b-4c16-ae31-522bbe5a9c87)

**Comment by bendk** [comment]
This one is implemented.  The main things to test are:

 - That the UI code responds to those breakpoints and only those breakpoints.  Things shouldn't change except when you transition from one to another (unlike production where you see the "snapping behavior" at weird times)
 - I didn't break any other layout code.

You should only need to test the futureui pages for this one.

**Comment by bendk** [comment]
I made #3271 for the issue with the language selector.  Let's work on that issue separately since it's not a regression.

**Comment by bendk** [comment]
>￼ Subtitle request entries spill over in extra-small screen width

This one isn't a regression from production and we're actually planning on redesigning these lists as a whole anyways, so I think we can ignore this for now.

**Comment by bendk** [comment]
I added back the facebook/twitter icons.  They're slightly different than production since we're using font-awesome for them now.

**Comment by PCF-Testing** [comment]
This is what the Facebook / Twitter icons look like on the branch:

![screenshot from 2018-06-22 07 43 21](https://user-images.githubusercontent.com/288455/41787245-9b6f9b0c-75fc-11e8-8678-84cafaa26576.png)

"Members" page does not respect all the listed breakpoints - spills over the edge of the screen on screen widths smaller than 768 px.

**Comment by PCF-Testing** [comment]
FB/Twitter still a problem, in any browser, and force reloading would not help.

**Comment by bendk** [comment]
What page are you viewing?

**Comment by PCF-Testing** [comment]
Marketing / futureui pages.

**Comment by bendk** [comment]
Hmm, I'm seeing them.  Can we try merging, then checking it out on dev?

**Comment by PCF-Testing** [comment]
OK.

**Comment by PCF-Testing** [comment]
@bendk: So FB and Twitter icons are missing on dev as they were on my local instance.

**Comment by PCF-Testing** [comment]
Deployed.
