### ISSUE TITLE
post-django upgrade work

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3118]
Once we update django (#1903), there are several things we should/must refactor

 - [x] Change startup.py scripts to using the ready() method (https://docs.djangoproject.com/en/2.0/ref/applications/#initialization-process)
- [x] Use QuerySet.as_manager() (https://docs.djangoproject.com/en/2.0/releases/1.7/#calling-custom-queryset-methods-from-the-manager)
- [x] Check our select_related() and prefetch_related() code and consider if we can remove some hacks
- [x] Use index_together, rather than our hacked together code in setup_indexes.
- [ ] Consider using a custom user class instead of CustomUser
- [ ] Use custom lookups instead of some of our manager methods (Video.search, CollabMapping stuff) (https://docs.djangoproject.com/en/2.0/howto/custom-lookups/)

**Comment by bendk** [comment]
I made #3251 for the CustomUser issue

**Comment by bendk** [comment]
I couldn't really find a good way to improve the code using the custom lookups, so let's just skip that for now.

Implemented in the gh-3118 branch.

**Comment by PCF-Testing** [comment]
This doesn't seem to break anything, so I think it should be good to merge. 

Will the Django debug toolbar only be visible in the local environments? I have tried commenting out DEBUG = True in dev_settings.py, but this did not disable the panel.

![screenshot from 2018-06-14 04 28 18](https://user-images.githubusercontent.com/288455/41409640-b6bbdc6c-6f8b-11e8-8022-ec83ea180983.png)

**Comment by bendk** [comment]
@PCF-Testing Yes, we only setup the debug toolbar in dev_settings, so it should not show up for actual deploys.

**Comment by PCF-Testing** [comment]
Deployed.
