### ISSUE TITLE
Clicking Team Header --> Main page

### ISSUE THREAD

**Issue by allison-amara** [pculture/unisubs#3123]
When I am on a Collaboration Team page with the new UI, if I click the team banner/logo it takes me to the Amara home page. It seems like clicking my team banner/logo should take me to the Team Dashboard page instead.![2018-02-08_12h43_40.gif](https://images.zenhubusercontent.com/5a5fb7694b5806bc2bc3298e/f0646ca6-9ceb-43cb-bc23-6c1fc5df9738)

I attempted this on Chrome, Firefox, and Internet Explorer as an admin, manager, and contributor.

Note: With the old UI (in Activity tab, e.g.), clicking the Team name on the top left of the page takes me to the Team Dashboard.

**Comment by bendk** [comment]
Fixed this in dev.  I don't think there's anything that needs testing here.
