### ISSUE TITLE
announcement banners not displaying on futureui or marketing pages

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#3128]
I just added an announcement for legacy editor feedback and discovered the following in Chrome on OS X:

- two announcements are set to visible in django: (1) legacy editor feedback and (2) AoD recruiting
- on old ui and new ui pages, only announcement (1) appears 
  - I checked the user dashboard and collab team activity page
- on futureui and marketing pages, neither announcement (1) nor (2) appear

@PCF-Testing any idea what might be happening? I am pretty sure I actually saw announcement (2) on Amara right before I created announcement (1) today, but now it no longer displays.

**Comment by PCF-Testing** [comment]
The apostrophe in the text was the culprit. It was causing "Uncaught SyntaxError: missing ) after argument list" error in JS console. With the apostrophe removed, the announcement is displayed nicely.

BTW, is it "removing support for our legacy editor" or "removing our legacy editor"? Sounds like it should be the latter option.
