### ISSUE TITLE
upgrade pafy to newest version

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3132]

**Comment by bendk** [comment]
This one is pretty straightforward, I just pushed it directly to dev.

To test, just make sure that youtube-related stuff is still working, especially things that are related to fetching the video/audio direct links.

**Comment by PCF-Testing** [comment]
The only problem with YouTube videos I have noticed is that automatic video import from user-bound channels skips the unlisted videos, which are expected to be imported:

![screenshot from 2018-07-03 05 04 36](https://user-images.githubusercontent.com/288455/42218846-ba79a288-7e7e-11e8-97de-234f661a47b6.png)

Is this one related to the library upgrade?

**Comment by bendk** [comment]
I doubt it, can you check if that's different than production?  I'm not sure how we can import all unlisted videos.

**Comment by PCF-Testing** [comment]
Right, it works the same way on production. I made https://github.com/pculture/unisubs/issues/3306 for this issue. Marking this one as closed.
