### ISSUE TITLE
Couple ui app refactorings

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3141]
There's a few refactors that I think would be nice:

 - Rename `format_time` to `datetime`, since it shows both the date and time.  This is for both the templatetag and the function in the ui.dates module. Also:
   - stop calculating the delta variable, which never gets used.
   - Return the empty string for None values
 - Add a icon template.  So rather than having to spell out the HTML for an icon, you should just be able to do something like `{% include "icon" with name="approve" %}`

**Comment by bendk** [comment]
I added the template in this code, but actually the main work was just deleting a bunch of old collab templates.  I think the main thing to test is that I didn't mess up any of the collab pages.

**Comment by PCF-Testing** [comment]
Looks good to me.

**Comment by PCF-Testing** [comment]
Deployed.
