### ISSUE TITLE
Add Alaskan languages to Amara: Hän, Gwich’in, Holikachuk, Koyukon

### ISSUE THREAD

**Issue by Juditpinol** [pculture/unisubs#3152]
The org doing work with endangered Alaskan languages asked us to add the following languages:

- [x] Hän
ISO 639-3 code - haa
Directionality - LTR
https://en.wikipedia.org/wiki/H%C3%A4n_language

- [x] Gwich’in 
ISO 639-3 code - gwi
Directionality - LTR
https://en.wikipedia.org/wiki/Gwich%E2%80%99in_language

- [x] Holikachuk 
ISO 639-3 code - hoi
Directionality - LTR
https://en.wikipedia.org/wiki/Holikachuk_language

- [x] Koyukon 
ISO 639-3 code - koy
Directionality - LTR
https://en.wikipedia.org/wiki/Koyukon_language

**Comment by kslottow** [comment]
@Juditpinol thank you! I've just added this to the top of the backlog

**Comment by kslottow** [comment]
@PCF-Testing any other info needed to add these languages?

**Comment by bendk** [comment]
Just added these to dev.

**Comment by PCF-Testing** [comment]
Deployed.
