### ISSUE TITLE
Better openID error handling

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3162]
I believe the code to handle generic OpenID and Udacity logins hasn't been working for a long time.  We should make it fail more gracefully.  This means:

  - Better error message for the user
  - Stop this error from happening: `exceptions:TypeError: <openid.yadis.manager.YadisServiceManager object at 0x7f6bdb844290> is not JSON serializable`.

Steps to reproduce:

Open the home page.
Click LOGIN.
Click OpenID button.
Enter an OpenID URL (I use one from blogspot.ca). Click the button to proceed.
Error: error:Invalid AuthRequest: 0x301: Realm verification failed (8) for: https://amara.org/ ns:http://specs.openid.net/auth/2.0

Reported in https://pculture.freshdesk.com/helpdesk/tickets/98392.

**Comment by bendk** [comment]
I think the best way to handle this is to just remove the code, and all other code in the really ancient socialauth app.

Should we try to contact users?  Considering that it hasn't been working for quite a while, I think maybe it's fine not to.  What do you think @kslottow @PCF-Testing

**Comment by kslottow** [comment]
I think it's fine not to contact users, we will hear complaints if there's a lot of use we didn't know about. But want to send an email to check if there are any clients we know of using it.

**Comment by kslottow** [comment]
we can get rid of this single sign in! Confirmed by Dean and TDS.

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
