### ISSUE TITLE
Add Santali, Ho languages

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3164]
Language name: Santali
ISO 639-3 code: sat
Directionality: LTR
https://en.wikipedia.org/wiki/Santali_language

Language name: Ho
ISO 639-3 code: hoc
Directionality: LTR
https://en.wikipedia.org/wiki/Ho_language

Requested in: https://pculture.freshdesk.com/helpdesk/tickets/101253

**Comment by bendk** [comment]
There's one extra step with adding languages now that we're on a newer django version, so I think this should get a little testing.  Made the gh-3164 branch for it.

**Comment by bendk** [comment]
Actually, I don't think it's worth your testing time.  I'm just going to merge to dev.

**Comment by PCF-Testing** [comment]
Deployed.
