### ISSUE TITLE
Add Stoney (Nakoda) language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3169]
Language name: Stoney (Nakoda)
ISO 639-3 code: sto
Directionality: LTR
https://en.wikipedia.org/wiki/Stoney_language

Requested in https://pculture.freshdesk.com/helpdesk/tickets/101295

**Comment by bendk** [comment]
Added to dev.

**Comment by PCF-Testing** [comment]
Deployed.
