### ISSUE TITLE
new-style language switcher doesn't persist

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3170]
I'm not sure exactly what happened, but I'm cuurrently stuck on non-english locales for both staging and production.  I believe that's because I switched languages using the old language switcher, and now when I use the new one it's not saving my new choice.

**Comment by bendk** [comment]
Fixed in the gh-3170 branch.

**Comment by bendk** [comment]
- Open the homepage
- Select any non-english language
- Open up the home page without any language (something like unisubs.example.com:8000)
- You should be redirected to the language you selected, but you'll be redirected to something else, probably english, or whatever you last selected on an old-style page.

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Sorry, this does not work for me on staging.  Did it get merged properly?

What I did:
1. Open Account page.
2. Select Spanish from the UI language selector. 
3. Clicked through a couple more old-style pages.
4. Opened homepage and selected Russian from the UI language selector.
5. Opened homepage without the language in the URI. The page's language turned to Spanish again.

**Comment by bendk** [comment]
I think this should be working now.  Redeploying staging.

**Comment by PCF-Testing** [comment]
Verified on staging.

**Comment by PCF-Testing** [comment]
Deployed.
