### ISSUE TITLE
Visual cue in subtitles list for positioning

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3176]
We should have a way in the subtitles list to indicate what position (top/bottom) each subtitle is in.  I'm thinking it would be some sort of icon in the box for the subtitles.

Maybe we could only render an icon for top-positioned subs since bottom positioning is the default are the default

**Comment by PCF-Testing** [comment]
Also related: https://github.com/pculture/unisubs/issues/2604.

**Comment by kslottow** [comment]
Issue moved to [pculture/amara-design #292](https://github.com/pculture/amara-design/issues/292) via [**ZenHub**](https://www.zenhub.com/)
