### ISSUE TITLE
Subtitles disappearing from the timeline during the syncing step

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3196]
Observed on staging.

As you start syncing subtitles, after syncing about 3 subtitles they start disappearing from the timeline.

Screencast is available at https://www.youtube.com/watch?v=76ivOYOIqck. The problem starts at 0:12.

**Comment by bendk** [comment]
e188959893af99fa715143da5a7ebccc82dfebfb should fix this one.

**Comment by PCF-Testing** [comment]
Verified on staging.

**Comment by PCF-Testing** [comment]
Closing.
