### ISSUE TITLE
Fix issues when splitting unsynced subtitles

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3200]
Right now we allow this, but it's very buggy.  To see weird behavior:

- Add a single subtitle
- Split it
- Move to syncing stage
- Try to drag the subtitle around the timeline.

**Comment by bendk** [comment]
Deploying a change that I think should fix this.

@PCF-Testing can you test locally and make sure it works for you?

**Comment by PCF-Testing** [comment]
Deployed. Marking as closed.
