### ISSUE TITLE
ITT fails to upload with literal musical character

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#3204]
Sample attached.

The literal ♪ character prevents the file from successfully uploading to Amara.
[sample.itt.zip](https://github.com/pculture/unisubs/files/1981230/sample.itt.zip)

**Comment by bendk** [comment]
This was a really easy one to fix.  I just pushed the fix directly to dev.

**Comment by PCF-Testing** [comment]
Fixed inside the subtitle editor, but not in Upload dialog on the video details page.

**Comment by PCF-Testing** [comment]
Verified for in-editor, upload dialog, and API uploads.

When downloading an ITT file, the music symbol is escaped as &#9834;

**Comment by danantonioreyes** [comment]
I thought there were still some things to review here, seems like I am too late to the party.

**Comment by PCF-Testing** [comment]
Deployed.
