### ISSUE TITLE
Couple of user activity API fixes

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3209]
- [x] We should make it so the user activity URI only shows up if you have permission to view it.
- [x] We should make the activity API filters work with both user ids and usernames

**Comment by PCF-Testing** [comment]
The user's activity can be viewed by the user herself and by the superuser. For other users, the HTTP response does not include /activity/ endpoint; when queried, /activity/ is not returned. Marking as Needs PR.

**Comment by PCF-Testing** [comment]
Deployed.
