### ISSUE TITLE
Ampersand character breaks ITT export

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#3210]
Exporting ITT file type subtitles fails if there's an ampersand character in the subtitles. (for example, it used to be that when you downloaded subtitles in ITT format, an error occurs if the subtitles contained `&` characters--this is now fixed)

Reproduced both on UI and API. There's no json error response for the API request, it sends the regular "We have encountered an error" full page.

**Comment by danantonioreyes** [comment]
Fixed in https://github.com/pculture/unisubs/tree/gh-unisubs-3210

I just enabled XML escaping for the ITT generator. Quoting from the w3 documentation for XML:

> Theampersand character (&) and the left angle bracket (<) must not appear in their literal form, except when used as markup delimiters, or within a comment, a processing instruction, or a CDATA section.

https://www.w3.org/TR/REC-xml/#syntax

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
