### ISSUE TITLE
Team owners should be able to delete their own teams

### ISSUE THREAD

**Issue by danantonioreyes** [pculture/unisubs#3219]
When a user is an owner of a team, he/she should be able to delete/deactivate the team.

Deactivating a team:
- displays that team as "retired team" and the team dashboard (and all team pages for that team) become inaccessible.
- removes all members from the team
- unlinks YouTube, Vimeo, Kaltura, Brightcove accounts
- in case they want to reactivate, saves the following information:
  - user membership
  - activity history
  - settings
  - team info

We give an option to delete all team data, which is permanent and irreversible:
- delete user membership information
- team info (from general settings page)
- team activity history
- settings

We give an option to either DELETE or REMOVE videos that were on the team:
- deleting is permanent and irreversible. 
  - Maybe we need to offer an option to bulk download the subtitles on the team when you do this? 
  - do we need to make it so they can choose which subtitles to download, or can it be all or none?
- removing videos that were on the team
  - make them public videos with public subtitles, in the public area
    - need to decide what to do if there is already a video in the public area
  - do we need to make it so they can choose which subtitles become public, or can it be all or none?

Based this on [Deactivating your Amara Account ](https://support.amara.org/support/solutions/articles/216336-deactivating-your-user-account)

**Comment by kslottow** [comment]
Issue moved to [pculture/amara-enterprise #2123](https://github.com/pculture/amara-enterprise/issues/2123) via [**ZenHub**](https://www.zenhub.com/)
