### ISSUE TITLE
allow undoing text edits before edit is saved

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#3226]
Improvement to #395 

Right now, undo works for syncing and all other editor actions, except the text currently being edited in a subtitle cell. This is because while you are still typing in a subtitle cell, the edit is technically not done yet. To undo text edits, you currently need to either press ENTER to exit the cell, then use the UNDO shortcut, or press ESC to abort the current changes you're making.

We should make it so that both ESC and CTRL+Z should abort the changes made to the current subtitle.

____________________________________

What's not intuitive about current behavior:

This leads to some behavior that may be confusing:
- ctrl+Z seems like its function is to creates a new subtitle when the last subtitle is being edited in Typing Mode
  - this is because the last action BESIDES editing the text was to create a new subtitle
- ctrl+Z for undoing text only works once the subtitle is no longer being edited
  - place the cursor in any subtitle
  - type another word in the subtitle
  - press ctrl+z; nothing happens (expected: the word disappears)
  - press enter or escape to exit edit mode for the current subtitle
  - press ctrl+z; now the word you added will disappear

**Comment by bendk** [comment]
Fixed in the editor-fixes branch.

**Comment by PCF-Testing** [comment]
With this change, undo-ing feels a bit strange. Consider the following scenario:

1. Submit a new video.
2. Open the editor to start transcribing.
3. Start typing some text, e.g. "This is the first subtitle".
4. Press ENTER to start a new subtitle.
5. Type some more, e.g. "This is the second one". Stay in the subtitle.
6. Press CTRL+Z. This removes the text AND the cell of the second subtitle.
7. Press CTRL+Z again. This reinstates the second subtitle cell without the text.
8. Press CTRL+Z again. This removes the second subtitle cell.
9. Press CTRL+Z again. This removes the text from the first subtitle.

I would expect the undo sequence to be: remove text of the second subtitle -> remove the second subtitle cell -> remove the text of the first subtitle.

Another problem is that if you CTRL+Z the text in the subtitle you are currently typing in, CTRL+Y does not return it.

We can discuss this, but I am not sure this behaviour is better than the original algorithm used in 395.

**Comment by bendk** [comment]
I'm pretty sure I can make things work intuitively in the sequence you listed.  There are still going to be some edge cases though:
  - Hit ENTER to start a new subtitle
  - Click outside the subtitle, this will delete the new subtitle
  - Hit Ctrl-Z... what should happen?  Should we re-create the empty subtitle, or treat the last 2 actions as ephemeral and undo the one before it?

I don't think there's going to be a good answer for everyone here.  My initial plan will be to undo deleting the empty subtitle.


A third issue is with the following sequence:

 - Start editing a subtitle, appends some text
 - while the text entry is still active, drag a subtitle in the timeline to change its timings
 - Hit ctrl-Z

I would expect that to undo the timing change, but it actually undoes the text change.

I'm pushing a fix for that right now.

**Comment by bendk** [comment]
One more corner case I think we should deal with:

 - User types in some text
 - User hits escape to cancel the edit
 - User hits ctrl-Z.. what should happen?

I'm going to make it undo the escape action -- i.e. restore the text that was there before escape was hit.

**Comment by PCF-Testing** [comment]
This one breaks for me in the most straightforward use case: open timed subtitles for editing, append (type) some new text to one of the subtitles, then press CTRL+Z to undo. Nothing happens. I believe we have agreed that this should act as ESC, abandoning the text changes.

**Comment by bendk** [comment]
Fixed that case.

**Comment by PCF-Testing** [comment]
Works as expected in all the listed cases.

**Comment by PCF-Testing** [comment]
Deployed.
