### ISSUE TITLE
Add ncj and st languages to the language selectors in the UI

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3227]
These languages are currently recognized by the system, but not available for selection in drop-down lists of available languages in the UI. They should be added.

**Comment by danantonioreyes** [comment]
Added in https://github.com/pculture/unisubs/tree/gh-unisubs-3227

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
