### ISSUE TITLE
Very short videos have a long timeline

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3229]
@bendk commented on [Wed May 30 2018](https://github.com/pculture/infrastructure/issues/160)

I have a 6 second video, but when I try to edit it in the editor, the timeline goes way past 6 seconds.  I think it goes to 60 seconds or so.

**Comment by bendk** [comment]
The issue there was that we never drew the last second on the timeline.  Just made a fix for that.

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
