### ISSUE TITLE
Update info tray after ctrl-Z

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3230]
@bendk commented on [Thu May 31 2018](https://github.com/pculture/infrastructure/issues/161)

**Comment by PCF-Testing** [comment]
Verified.

**Comment by bendk** [comment]
I just changed things so that when you undo, the current edit stops which causes the info tray to be hidden.

I hope that this is still okay.  It seems to me that the worst part of this bug was that it had incorrect information, not that users needed to see the change right after they hit undo.

This is one of the cases where I think it could be good to have a concept of the "selected subtitle", separate from whether it's being edited or not.

**Comment by PCF-Testing** [comment]
Deployed.
