### ISSUE TITLE
Editor fixes

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3231]
This epic is for a bunch of editor fixes that we're doing after the last deploy.  Most of them are to fix issues discovered because of the undo changes, but some are just editor bugs that need fixing.

**Comment by PCF-Testing** [comment]
Created 3258 - seems annoying enough to make the editor a pain to use.

**Comment by PCF-Testing** [comment]
Looks good to me now, didn't notice anything that feels obviously wrong.

**Comment by PCF-Testing** [comment]
All the fixes have been deployed. Closing.
