### ISSUE TITLE
Make dragging subtitles reliably update the subtitle list

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3233]
We should make it so when you drag subtitles, everything in the subtitle list gets updated with the new times.  In particular, we should handle these corner cases:

  - The info tray should get updated as you drag
  - The start time on the subtitle list should be updated as you drag
  - The ! icon should be updated as you drag
  - When you drag the start/end times and bump the previous/next subtitle, the info for both subtitles should be updated

**Comment by bendk** [comment]
Fixed in the editor-fixes branch.

**Comment by PCF-Testing** [comment]
Verified the fix.
