### ISSUE TITLE
Handle undo with editing a subtitle and dragging the timeline

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3234]
Currently we can have a weird case where you have you are editing subtitle content and timings at the same time:

 - Click in a subtitle cell to start an edit
 - Drag a subtitle in the timeline to change it's timings -- don't let go of the mouse button
 - Type some content on the keyboard to change the subtitle content
 - Drag the subtitle in the timeline more then let go

You've now created a really weird situation for undo.  I think the best way to handle it is:
 - The first undo reverts the second timing change
 - The second undo reverts the content change
 - The third undo reverts the first timing change

In general, I think what should happen is whenever you make a timing change by dragging a subtitle, and there are changes in the text entry, we should commit those changes, adding a new undo entry.

**Comment by PCF-Testing** [comment]
Works on the scenario described in the ticket, but breaks on a slightly different scenario:
1. Click in a subtitle cell to start an edit
2. Type some content on the keyboard to change the subtitle content
3. Drag a subtitle in the timeline to change it's timings -- don't let go of the mouse button
4. Type some content on the keyboard to change the subtitle content
5. Drag the subtitle in the timeline more then let go

In this case, step 5 can be undone, but step 4 remains stuck, CTRL+Z does not seem to take effect.

**Comment by bendk** [comment]
This one should be working again.

**Comment by PCF-Testing** [comment]
Confirming it is fixed.

**Comment by PCF-Testing** [comment]
Deployed.
