### ISSUE TITLE
Incorrect value in tts:origin for ITT preventing YouTube from loading position style

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#3241]
The current ITT export layout is:

```
<region xml:id="bottom" style="amara-style" tts:origin="0 80%" tts:extent="100% 20%"/>
<region xml:id="top" style="amara-style" tts:origin="0 0" tts:extent="100% 20%"/>
```

The tts:origin (and tts:extent) values have to be either scalars with units or percentages. A scalar without units is explicitly an error and YouTube's parser doesn't allow it.

https://www.w3.org/TR/2018/CR-ttml1-20180424/#style-value-length

The fix is changing the layout export to

```
<region xml:id="bottom" style="amara-style" tts:origin="0% 80%" tts:extent="100% 20%"/>
<region xml:id="top" style="amara-style" tts:origin="0% 0%" tts:extent="100% 20%"/>
```

**Comment by danantonioreyes** [comment]
Implemented fix in https://github.com/pculture/unisubs/tree/gh-unisubs-3241

**Comment by PCF-Testing** [comment]
The ITT files exported from the branch can be successfully uploaded to YouTube with preserving the subtitle position and to Amara. DFXP files also use percentages for tts:origin. I believe this verifies the ticket.

**Comment by PCF-Testing** [comment]
Deployed.
