### ISSUE TITLE
Issue with undoing Split subtitle.

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3242]
Observed on editor-fixes branch.

Steps to reproduce:
1. Suppose you have a subtitle with some text. e.g. "long sentence".
2. Click in the middle of that text and press CTRL+ENTER to split.
3. Click the top subtitle to view the info tray.
4. Press CTRL+Z to undo. The bottom subtitle goes away, the upper subtitle recovers its full duration, but not the text - still has "long" without the "sentence" part.

**Comment by bendk** [comment]
This one was the in the same class as a lot of other ones -- undo didn't work properly when you were editing a subtitle.  Now that we cancel the current edit, they should all be fixed.

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
