### ISSUE TITLE
Typing in editor: Subtitle text displayed in the video overlay with a huge lag

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3258]
Observed on editor-fixes branch.

Steps to reproduce:
1. Submit a new video.
2. Start transcribing it. Type something into the first subtitle cell. Press ENTER to add another cell.

As you are typing, the last letter appears on the video player with a very long delay.

Screencast:
https://drive.google.com/file/d/1Yln8ArdOLPzMaXZhccZgjJ5GnlLosqzI/view
Happens for me with any text I try to type.

**Comment by bendk** [comment]
Fixed in editor-fixes.

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
This bug was first introduced in editor-fixes branch, the problem does not exist in production, so just made sure it does not happen on dev and marking as closed now.
