### ISSUE TITLE
Twitter sign in has stopped working

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3268]
When you click "Twitter" button on Sign In page, nothing happens. This worked a couple of days ago.

Twitter.com were planning a change on their side for 06/19/2018: https://www.cnet.com/news/twitter-says-it-wont-break-third-party-twitter-apps-june-19/

**Comment by VeronicaPCF** [comment]
Ticket for reference: https://pculture.freshdesk.com/helpdesk/tickets/102507

**Comment by asabine** [comment]
updated the twitter oauth code to use a new library and removed outdated/unused stuff. if you test locally with new API keys it should work. the callback url needs to be set in the application permissions as well but i don't think that reflects a change from how it worked before.

**Comment by PCF-Testing** [comment]
@asabine: could you please share the new credentials for Twitter via slack? Then I'll be able to check this one today. Thanks!

**Comment by PCF-Testing** [comment]
I am getting the following exception on gh-3268:

app_1            | ERROR 2018-07-30 19:23:30,213 unhandled_error 'NoneType' object has no attribute '__getitem__'
app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
app_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1            |   File "/opt/apps/amara/apps/thirdpartyaccounts/views.py", line 61, in twitter_login
app_1            |     resource_owner_key = credentials.get('oauth_token')[0]
app_1            | TypeError: 'NoneType' object has no attribute '__getitem__'
app_1            | INFO 2018-07-30 19:23:30,374 access GET /auth/twitter_login_confirm/ 500 (1.098s)

**Comment by VeronicaPCF** [comment]
User confirms that she still experiences issues: I tried Opera, Firefox and
Internet Explorer.
_When I click the Twitter button after I clicked on a subtitle language
to edit it, you can see it loads something in the background but
noghting appears. Is it maybe still hidden?_
https://pculture.freshdesk.com/helpdesk/tickets/102507

**Comment by asabine** [comment]
yeah the issue still isn't fixed; it's a problem with the API keys so the browser won't have any effect on it. there's a separate infrastructure issue to make new accounts for this in addition to the refactoring here that i need to finish and that needs to be tested

**Comment by asabine** [comment]
@PCF-Testing it looks like the problem was that the network error wasn't getting caught properly; it should return a valid credential, unless there's a problem with the request to twitter, in which case it _should_ display an error message instead of trying to get the credential itself. i think the problem might be that the callback url isn't properly set by the account which isn't code specific

**Comment by PCF-Testing** [comment]
The branch fails to start with the following error:

feed-worker_1    |     __import__(name)
feed-worker_1    |   File "/opt/apps/amara/urls.py", line 31, in <module>
feed-worker_1    |     from auth.views import login as user_login
feed-worker_1    |   File "/opt/apps/amara/apps/auth/views.py", line 56, in <module>
feed-worker_1    |     from thirdpartyaccounts.views import facebook_login, twitter_login
feed-worker_1    |   File "/opt/apps/amara/apps/thirdpartyaccounts/views.py", line 32, in <module>
feed-worker_1    |     from thirdpartyaccounts.lib.oauth_twitter import TwitterOAuth1
feed-worker_1    |   File "/opt/apps/amara/apps/thirdpartyaccounts/lib/oauth_twitter.py", line 46
feed-worker_1    |     except URLError, requests.exceptions.RequestException as e:
feed-worker_1    |                                                            ^
feed-worker_1    | SyntaxError: invalid syntax
worker_1         |     __import__(name)
worker_1         |   File "/opt/apps/amara/urls.py", line 31, in <module>
worker_1         |     from auth.views import login as user_login
worker_1         |   File "/opt/apps/amara/apps/auth/views.py", line 56, in <module>
worker_1         |     from thirdpartyaccounts.views import facebook_login, twitter_login
worker_1         |   File "/opt/apps/amara/apps/thirdpartyaccounts/views.py", line 32, in <module>
worker_1         |     from thirdpartyaccounts.lib.oauth_twitter import TwitterOAuth1
worker_1         |   File "/opt/apps/amara/apps/thirdpartyaccounts/lib/oauth_twitter.py", line 46
worker_1         |     except URLError, requests.exceptions.RequestException as e:
worker_1         |                                                            ^
worker_1         | SyntaxError: invalid syntax
app_1            | spawned uWSGI worker 1 (pid: 14, cores: 1)
app_1            | spawned uWSGI worker 2 (pid: 15, cores: 1)
app_1            | metrics collector thread started
unisubs_worker_1 exited with code 1

**Comment by asabine** [comment]
have you rebuilt the containers? there's new dependencies which need to be installed

**Comment by PCF-Testing** [comment]
Rebuilt as bin/dev build --no-cache.

The error on start is as follows:

app_1            | Traceback (most recent call last):
app_1            |   File "/opt/apps/amara/deploy/unisubs.wsgi", line 13, in <module>
app_1            |     startup.startup()
app_1            |   File "/opt/apps/amara/startup.py", line 70, in startup
app_1            |     setup_django()
app_1            |   File "/opt/apps/amara/startup.py", line 59, in setup_django
app_1            |     django.setup()
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
feed-worker_1    | Traceback (most recent call last):
feed-worker_1    |   File "/opt/apps/amara/manage.py", line 37, in <module>
feed-worker_1    |     startup.startup()
feed-worker_1    |   File "/opt/apps/amara/startup.py", line 70, in startup
feed-worker_1    |     setup_django()
feed-worker_1    |   File "/opt/apps/amara/startup.py", line 59, in setup_django
feed-worker_1    |     django.setup()
feed-worker_1    |   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
worker_1         | Traceback (most recent call last):
worker_1         |   File "/opt/apps/amara/manage.py", line 37, in <module>
worker_1         |     startup.startup()
worker_1         |   File "/opt/apps/amara/startup.py", line 70, in startup
worker_1         |     setup_django()
worker_1         |   File "/opt/apps/amara/startup.py", line 59, in setup_django
worker_1         |     django.setup()
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
feed-worker_1    |     apps.populate(settings.INSTALLED_APPS)
feed-worker_1    |   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
app_1            |     apps.populate(settings.INSTALLED_APPS)
worker_1         |     apps.populate(settings.INSTALLED_APPS)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
feed-worker_1    |     app_config.ready()
feed-worker_1    |   File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/apps.py", line 15, in ready
app_1            |     app_config.ready()
worker_1         |     app_config.ready()
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/apps.py", line 15, in ready
app_1            |   File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/apps.py", line 15, in ready
worker_1         |     dt_settings.patch_all()
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/settings.py", line 228, in patch_all
app_1            |     dt_settings.patch_all()
app_1            |   File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/settings.py", line 228, in patch_all
feed-worker_1    |     dt_settings.patch_all()
feed-worker_1    |   File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/settings.py", line 228, in patch_all
feed-worker_1    |     patch_root_urlconf()
feed-worker_1    |   File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/settings.py", line 216, in patch_root_urlconf
worker_1         |     patch_root_urlconf()
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/settings.py", line 216, in patch_root_urlconf
worker_1         |     reverse('djdt:render_panel')
worker_1         |   File "/opt/apps/amara/apps/localeurl/__init__.py", line 18, in reverse
worker_1         |     path = django_reverse(viewname, urlconf, args, kwargs, prefix, current_app)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 522, in reverse
feed-worker_1    |     reverse('djdt:render_panel')
feed-worker_1    |   File "/opt/apps/amara/apps/localeurl/__init__.py", line 18, in reverse
feed-worker_1    |     path = django_reverse(viewname, urlconf, args, kwargs, prefix, current_app)
feed-worker_1    |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 522, in reverse
app_1            |     patch_root_urlconf()
app_1            |   File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/settings.py", line 216, in patch_root_urlconf
app_1            |     reverse('djdt:render_panel')
app_1            |   File "/opt/apps/amara/apps/localeurl/__init__.py", line 18, in reverse
app_1            |     path = django_reverse(viewname, urlconf, args, kwargs, prefix, current_app)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 522, in reverse
worker_1         |     app_list = resolver.app_dict[ns]
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 329, in app_dict
worker_1         |     self._populate()
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 269, in _populate
worker_1         |     for pattern in reversed(self.url_patterns):
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 372, in url_patterns
worker_1         |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
worker_1         |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in urlconf_module
worker_1         |     self._urlconf_module = import_module(self.urlconf_name)
worker_1         |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
app_1            |     app_list = resolver.app_dict[ns]
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 329, in app_dict
app_1            |     self._populate()
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 269, in _populate
app_1            |     for pattern in reversed(self.url_patterns):
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 372, in url_patterns
app_1            |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in urlconf_module
app_1            |     self._urlconf_module = import_module(self.urlconf_name)
app_1            |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
feed-worker_1    |     app_list = resolver.app_dict[ns]
feed-worker_1    |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 329, in app_dict
feed-worker_1    |     self._populate()
feed-worker_1    |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 269, in _populate
feed-worker_1    |     for pattern in reversed(self.url_patterns):
feed-worker_1    |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 372, in url_patterns
feed-worker_1    |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
feed-worker_1    |   File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in urlconf_module
feed-worker_1    |     self._urlconf_module = import_module(self.urlconf_name)
feed-worker_1    |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
feed-worker_1    |     __import__(name)
feed-worker_1    |   File "/opt/apps/amara/urls.py", line 31, in <module>
worker_1         |     __import__(name)
worker_1         |   File "/opt/apps/amara/urls.py", line 31, in <module>
worker_1         |     from auth.views import login as user_login
worker_1         |   File "/opt/apps/amara/apps/auth/views.py", line 56, in <module>
worker_1         |     from thirdpartyaccounts.views import facebook_login, twitter_login
worker_1         |   File "/opt/apps/amara/apps/thirdpartyaccounts/views.py", line 32, in <module>
app_1            |     __import__(name)
app_1            |   File "/opt/apps/amara/urls.py", line 31, in <module>
feed-worker_1    |     from auth.views import login as user_login
feed-worker_1    |   File "/opt/apps/amara/apps/auth/views.py", line 56, in <module>
feed-worker_1    |     from thirdpartyaccounts.views import facebook_login, twitter_login
feed-worker_1    |   File "/opt/apps/amara/apps/thirdpartyaccounts/views.py", line 32, in <module>
feed-worker_1    |     from thirdpartyaccounts.lib.oauth_twitter import TwitterOAuth1
feed-worker_1    |   File "/opt/apps/amara/apps/thirdpartyaccounts/lib/oauth_twitter.py", line 46
feed-worker_1    |     except URLError, requests.exceptions.RequestException as e:
feed-worker_1    |                                                            ^
feed-worker_1    | SyntaxError: invalid syntax
worker_1         |     from thirdpartyaccounts.lib.oauth_twitter import TwitterOAuth1
worker_1         |   File "/opt/apps/amara/apps/thirdpartyaccounts/lib/oauth_twitter.py", line 46
worker_1         |     except URLError, requests.exceptions.RequestException as e:
worker_1         |                                                            ^
worker_1         | SyntaxError: invalid syntax
app_1            |     from auth.views import login as user_login
app_1            |   File "/opt/apps/amara/apps/auth/views.py", line 56, in <module>
app_1            |     from thirdpartyaccounts.views import facebook_login, twitter_login
app_1            |   File "/opt/apps/amara/apps/thirdpartyaccounts/views.py", line 32, in <module>
app_1            |     from thirdpartyaccounts.lib.oauth_twitter import TwitterOAuth1
app_1            |   File "/opt/apps/amara/apps/thirdpartyaccounts/lib/oauth_twitter.py", line 46
app_1            |     except URLError, requests.exceptions.RequestException as e:
app_1            |                                                            ^
app_1            | SyntaxError: invalid syntax
app_1            | unable to load app 0 (mountpoint='') (callable not found or import error)
app_1            | *** no app loaded. going in full dynamic mode ***
app_1            | *** uWSGI is running in multiple interpreter mode ***
app_1            | spawned uWSGI master process (pid: 1)
app_1            | spawned uWSGI worker 1 (pid: 14, cores: 1)
app_1            | spawned uWSGI worker 2 (pid: 15, cores: 1)
app_1            | metrics collector thread started
asset-builder_1  | [13:09:28] Finished 'fonts' after 12 s
unisubs_worker_1 exited with code 1
unisubs_feed-worker_1 exited with code 1

**Comment by PCF-Testing** [comment]
On attempt to sign in with the use of Twitter account, the following exception occurs:

app_1            | ERROR 2018-08-15 06:55:23,387 unhandled_error 'NoneType' object has no attribute '__getitem__'
app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
app_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1            |   File "/opt/apps/amara/apps/thirdpartyaccounts/views.py", line 61, in twitter_login
app_1            |     resource_owner_key = credentials.get('oauth_token')[0]
app_1            | TypeError: 'NoneType' object has no attribute '__getitem__'
app_1            | INFO 2018-08-15 06:55:23,554 access GET /auth/twitter_login_confirm/ 500 (0.584s)

**Comment by asabine** [comment]
it should now show an error message instead of an exception when this fails instead of continuing through. the problem is still the twitter callback url, but now the url on twitter's end should only the `<site-name>/auth/twitter_login_done_confirm` without the language code. until this is updated for the account credentials you are logging in with this error will still occur.

**Comment by PCF-Testing** [comment]
Verified locally with a Twitter app of my own.

The only small issue I am seeing is that when a new Twitter account gets created, the avatar does not get pulled from Twitter to Amara. However, I think we can live with it. Marking as Needs PR.

**Comment by PCF-Testing** [comment]
Deployed, but sign in does not work yet - needs API creds to work.

**Comment by Rieann** [comment]
https://support.amara.org/a/tickets/103231
Issue reported again 9/15/2018 - still not working

**Comment by asabine** [comment]
@PCF-Testing this was deployed already; did it break on production?

**Comment by PCF-Testing** [comment]
@asabine: "Problem connecting to Twitter. Try again." :(

**Comment by PCF-Testing** [comment]
@asabine: something has changed in the Twitter authentication process on production. Instead of displaying the error message ("Problem connecting to Twitter..."), it asks for the permission to authenticate and then gets stuck redirecting:
https://amara.org/en/auth/twitter_login_done_confirm/?email=&next=/a&oauth_token=[elided]&oauth_verifier=[elided]
This page isn’t working
amara.org redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

(Yes, I did try clearing the cookies, but that did not help, still was unable to sign in.)

**Comment by asabine** [comment]
added the locale independent paths to varnish; this should resolve the issue

**Comment by PCF-Testing** [comment]
Works great now, thanks a lot!
