### ISSUE TITLE
If the only changes made to subtitles are the position changes, they don't save

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3270]
Steps to reproduce:
1. Open a subtitle set for editing.
2. Seek to a couple of subtitles and change their position. Do not make any other changes, do not even click inside a subtitle cell.
3. Click "Publish" ("Save draft" will be disabled). 
4. Play the edited subtitles in the embedder or download a VTT file to see that the changes have not been saved.

**Comment by bendk** [comment]
implemented in gh-3270

**Comment by PCF-Testing** [comment]
Deployed.
