### ISSUE TITLE
experimental editor: improvements to syncing expectations and precision

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#3272]
**Problems:**

**Mismatched expectation of down arrow:**
- When first syncing, the use learns to expect the down arrow to set a start time for what they perceive as the “next subtitle.” 
- When reviewing the syncing, this causes mismatched expectations:
  - Imagine subtitle A and B are adjoining (no space in between). Subtitle B starts too late. To correct this, the user backs up a few seconds, to where subtitle B is supposed to start, and presses the down arrow. 
  - Instead of adjusting the start time of subtitle B, you have adjusted the start time of subtitle A.
  - The “correct” way to adjust the start time of subtitle B is pretty clunky: when you hear the start of subtitle B, press up and then down immediately after. This is necessarily inaccurate (you’ll have to drag to get more accuracy)

**Adjusting start and end times**
- Some users want to push in one direction or the other, but some expect both to move when they move an intersection of two subtitles
- user says: “Would be nice if the default functionality were just to do both directions; then if I wanted to separate, you would move the edges separately.”
- handles are too small

**Solutions:**
  - **Allow a new mode of dragging, which moves both end time of one subtitle and start time of another**.
     - It starts by pressing the mouse button in-between two subtitles whose start/end times are the same
     - We use a new pointer icon when you're hovering in that area to indicate it's a different type of drag
     - We should make the handles wider to make dragging less tricky
     - The user also might want to know things like the CPS for both subtitles being adjusted, so we also show the info tray for the second subtitle, on the left side of the subtitle list.
     - This mode should replace the old behavior where you could adjust the start/end times and then "push" the adjacent subtitle's timings
  - **Support "nudging mode", which allows you to use the keyboard to adjust timing with more precision**
    - It starts when one of the when one of these hitboxes is clicked, rather than held down
    - In this mode, you can use left and right arrows to adjust timing by a small amount (100 ms?)
    - You can also use shift-left/right to adjust it by even small (5ms?)
    - We leave nudging mode when you play/pause a video, select a new subtitle etc..  This should work just like how we cancel the text edit.
  - **Make up/down only work with unsynced subtitles**.
      - Add a new keyboard shortcut for enter, that finds the start/end time nearest to the current time and syncs that to the current time.
     - If there is no time within 1 second, we should not do anything
     - If there is a start and end time together at the same time, then we should adjust both times
  - **Allow snap to the current time in review mode**.  If you drag the subtitle to around the current time, we set it to exactly the current time.

previous discussion notes: https://docs.google.com/document/d/1eRsTgI1Q1TMm5dt5CJBHOEDwRwK_O9-k-gEJFCqgZ5s/edit

**Comment by PCF-Testing** [comment]
What key(s) should be used instead of arrows to snap the start or end time of the previous or next subtitle to the current time?

**Comment by bendk** [comment]
The keyboard doesn't snap because you can be very precise with it naturally -- especially with the shift key.  I believe this is pretty common, I think it's how final cut does it.  I know it's how GIMP handles snapping to grid.

**Comment by PCF-Testing** [comment]
Does this mean that the subtitle edges should be drag-dropped instead?

**Comment by bendk** [comment]
It depends what you want to do.  If you want to snap to exactly the current time, you should drag and drop.  However, I think using the keyboard is more precise than snapping to the current time, since that depends on when you pause the video.

**Comment by PCF-Testing** [comment]
- [ ] If you enter the nudging mode and then start playing the video by pressing TAB key, the balloon edges still remain in the nudging mode and an Arrow Right / Left keystroke moves them. This goes against the spec in the description of this ticket.

- [ ] How about highlighting the subtitle edge that is in the nudge mode in a higher contrast, more visible color, e.g. purple (such as the background under the TAB button on Keyboard Controls panel)? The current highlight color is teal, which is not much different from the regular edge color and does not help the feature to be easily discoverable.

- [ ] An Undo (CTRL+Z) cancels the whole series of nudges, not just the last keystroke. Personally I am okay with that, just wanted to double-check about it because it might be a source of confusion for some users.

- [ ] If possible, having some visual help about the nudging keys would be awesome. Ideally, I'd love to see Arrow Right / Arrow Left and SHIFT+Arrow Right / SHIFT+Arrow Left in the keyboard control panel when a subtitle edge goes into the nudging mode, but if it is too difficult to do, they should at least be listed in Keyboard Shortcuts modal.

**Comment by bendk** [comment]
>￼ An Undo (CTRL+Z) cancels the whole series of nudges, not just the last keystroke. Personally I am okay with that, just wanted to double-check about it because it might be a source of confusion for some users.

Good point.  I just copied the mouse dragging behavior, but it would be easy to switch it the other way.   I just checked with GIMP and that program used the undo-everything behavior

>￼ If possible, having some visual help about the nudging keys would be awesome. Ideally, I'd love to see Arrow Right / Arrow Left and SHIFT+Arrow Right / SHIFT+Arrow Left in the keyboard control panel when a subtitle edge goes into the nudging mode, but if it is too difficult to do, they should at least be listed in Keyboard Shortcuts modal.

Made #3372 for this one

**Comment by bendk** [comment]
￼ > How about highlighting the subtitle edge that is in the nudge mode in a higher contrast, more visible color, e.g. purple (such as the background under the TAB button on Keyboard Controls panel)? The current highlight color is teal, which is not much different from the regular edge color and does not help the feature to be easily discoverable.

I agree with this, but I think we should get occupop involved in this.  Made pculture/amara-design#296 for this one.

**Comment by bendk** [comment]
￼> If you enter the nudging mode and then start playing the video by pressing TAB key, the balloon edges still remain in the nudging mode and an Arrow Right / Left keystroke moves them. This goes against the spec in the description of this ticket.

Fixed this one

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
