### ISSUE TITLE
experimental editor: Rework the "current subtitle" concept

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#3273]
We have several related, but different concepts for the current subtitle:
  - The subtitle at the current playback time
  - The subtitle that's being edited (i.e. there's a text area inside it and you can type to change it)
  - The subtitle with the info tray
  - The subtitle whose timing is being changed
  - The subtitle with the up/down syncing helpers

There are various use cases where this gets confusing, so we should try to clean it up in the following way:
  - The subtitle at the current time:
     - Gets shown as the subtitle in the video player
     - Is no longer highlighted on the subtitle list
  - The selected subtitle in the subtitle list:
     - Is highlighted in the subtitle list
        - We should keep the same color regardless of if it's being edited or not.
     - Has the info tray shown for it
        - However, don’t show info tray while the video is playing -- there’s just not enough time for a user to read that while the video is playing
     - Can have a textarea displayed, but doesn't need to.  For example if you hit undo, we need to stop the text edit, but the subtitle should still be highlighted.
 - We remove the syncing helpers.  It's not clear they're well used and it's hard to focus on them when the video is changing and the timeline is playing.

We try to keep these in sync in various ways:
  - When you click on a synced subtitle in the subtitle list, and it’s not currently visible in the timeline, we seek to the start time (When you click on any unsynced subtitle, we do not seek)
  - What you play/seek the video, we stop the current edit (but keep that subtitle highlighted)
  - During play/seek if the playback time reaches a new subtitle, that one gets selected in the subtitle list
  - When you click/drag a subtitle in the timeline, that subtitle becomes selected in the subtitle list

We should change some keyboard handling:
  - Del should delete the selected subtitle (right now it's alt-delete, I think the main reason for that was to make it harder to do by accident when undo was not functional)

Some other minor changes:
  - Don't show a special background for empty subtitles.  We have the ! symbol for that and it interferes with the selection background. 
  - Highlight the selected subtitle in the timeline as well.

User interviews: https://docs.google.com/document/d/1ez5NIk-uf_bhGL6srTxX7LO_80SnwFSAKww3Wu_0uyQ/edit

**Comment by kslottow** [comment]
@bendk not sure if this should be included in this issue or put in another one in the epic:

- make sure Play works the same when triggered by:
  - keyboard shortcut
  - play button
  - play button icon in upper left of screen

**Comment by bendk** [comment]
@kslottow I made #3305 for the typing change.  I think the "play works the same" feature is captured in the description ("What you play/seek the video, we stop the current edit (but keep that subtitle highlighted)")

**Comment by bendk** [comment]
Removed the up/down key handling.  This conflicts with down as a syncing key, so let's not do it.

**Comment by PCF-Testing** [comment]
> When you click on a synced subtitle in the subtitle list, and it’s not currently visible in the timeline, we seek to the start time

This behaviour seems inconsistent to me. From the user's point of view, clicking some (not currently visible) subtitles seeks to the subtitle, and clicking other (visible) subtitles doesn't. It is not easy to figure out why this happens. Is there a solid reason not to seek to the subtitle every time a different subtitle is clicked?

**Comment by bendk** [comment]
> This behaviour seems inconsistent to me. From the user's point of view, clicking some (not currently visible) subtitles seeks to the subtitle, and clicking other (visible) subtitles doesn't. It is not easy to figure out why this happens. Is there a solid reason not to seek to the subtitle every time a different subtitle is clicked?

Yeah, that makes a lot of sense.  I think the main reason was to avoid constantly seeking and making the editor seem glitchy.  There's also a corner case where you're playing the video and we reach a new subtitle, so that one gets selected.  But then we seek to that subtitle, which might cause the player to rewind a few ms.

So I'm up for either solution:
  - Always seeking, and adding extra code to prevent glitchy behavior
  - Never seeking

What do you think @PCF-Testing  @kslottow?

**Comment by bendk** [comment]
Talked to day and decided on never seeking

**Comment by PCF-Testing** [comment]
I think it feels okay now.

**Comment by PCF-Testing** [comment]
Deployed.
