### ISSUE TITLE
Beta/experimental editor with initial improvement ideas to selection and syncing

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#3274]
This epic takes care of the following problems:

- remove legacy editor, while providing solutions to feedback from users about what they preferred in the Legacy Editor
- address user issues described in FD tickets and user interviews as follows:
  - user perception: subtitle "freezes" on playback in review mode
    - actually occurring, confusing behavior: if a subtitle is being edited, it continues to be displayed on the screen during playback
  - play button, tab key, and play icon in upper left do a combination of finishing or not finishing the subtitle being edited. They should all do the same thing.
  - preserves the ability of transcribers to continue editing the subtitle they were editing previously, after playback
  - confusion over expectations of the down arrow to set the endpoint of the "next subtitle," an expectation created in the initial syncing step
  - allows moving subtitle endpoints with increased precision

**Comment by PCF-Testing** [comment]
All the tickets in this epic have been completed, so I am going to close it.
