### ISSUE TITLE
Add GUI Tests for collab manager actions

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3287]
From the smoke tests: https://amara.testlodge.com/projects/23746/suites/124510

Add gui tests for these cases:

 - TC277 - Create a subtitle request - STUB
 - TC286 - As a work team admin, mark subtitles complete - STUB
 - TC284 - As an admin of evaluation team, send subtitle request back - STUB
 - TC285 - As an admin of an evaluation team, mark subtitle request complete - STUB

Once you're done add the testlodge tests to the automated smoke test suite: https://amara.testlodge.com/projects/23746/suites/128881

**Comment by danantonioreyes** [comment]
You may need to do `alter table videos_videoindex add FULLTEXT index `ft_text`(text);` on the guitest db container to add the index for videos

**Comment by danantonioreyes** [comment]
Added the above test cases to automated smoke test suite

**Comment by PCF-Testing** [comment]
This one has gone live a while ago.
