### ISSUE TITLE
Switch from celery to rq

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3304]
I've been trying to upgrade past celery 3.0.X and having a terrible time at it.  I'm seeing celery/celery#3620 a lot, regardless of what version I choose.

In that issue several people mention switching away from celery.  I think that's what we should do with Amara.  Originally I was thinking tasktiger, but it seems that rq is more popular and probably better supported.  Let's try that one.

It's also going to be great to drop the rabbitmq dependency and run redis instead.

**Comment by bendk** [comment]
This change affects all tasks that run in the worker process, rather than inside the webserver.   Some things to test:

 - import/fetching/syncing with externalsites like youtube/vimeo
 - management form submissions with lots of items (enough so the progress bar shows)
 - Sending emails
 
I doubt we can test this 100%.  But if you can catch anything, it's much better to do it now than after we deploy to production.

**Comment by PCF-Testing** [comment]
The stuff listed in the previous comment all seems to pass, except for some collab endorsements exploding with exceptions as described in 3247. Putting this ticket on hold, so that any remaining issues on the redis branch are tracked in 3247.

**Comment by bendk** [comment]
Merging this to dev

**Comment by PCF-Testing** [comment]
@bendk: while playing with dev, I keep having trouble with provider requests:
https://dev.amara.org/en/videos/EsQFhb5L3go5/en/1093471/?team=mac-test
https://dev.amara.org/en/videos/BdgSMHyjCWgU/info/mould-leaks-cracks-problems-in-brand-new-homes-devastate-owners/?team=m-collab-test-2
https://dev.amara.org/en/videos/qMUSTmMaZQBq/info/no-deal-brexit-advice-to-be-published-by-uk-government-bbc-news/?team=m-collab-test-2

The other stuff that is likely to be affected (messaging, HTTP callbacks, bulk actions on futureui teams, syncing to external systems) seems to work well.

**Comment by bendk** [comment]
@PCF-Testing Can you test with the dummy provider?  If that works, then I think we should try merging to staging and seeing if MAC works there.

**Comment by PCF-Testing** [comment]
No, provider requests to dummy still don't work - they get stuck in in-progress state:
https://dev.amara.org/en/videos/1Ln64kjABcz7/en/1093472/?team=m-collab-test-2

**Comment by bendk** [comment]
I forgot to start the scheduler process to schedule these.  I just started it and it looks like all the requests got processed.

**Comment by PCF-Testing** [comment]
Yes, things seem back to normal now.

**Comment by bendk** [comment]
This got deployed last week.
