### ISSUE TITLE
Dari (prs) script direction should be RTL instead of LTR

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#3307]
Captions in Dari (language code: prs) are displayed left to right. Dari is written in Persian script, which is right to left.

https://en.wikipedia.org/wiki/Persian_alphabet

**Comment by kslottow** [comment]
@franontanaya @deanjansen could you add some context for the urgency of deploying this? Thanks!

**Comment by deanjansen** [comment]
@kslottow have added a note to #engineering about this.

**Comment by asabine** [comment]
pushed the change directly to dev: https://github.com/pculture/unisubs/commit/530bd9ac84ef0a6e03ef60a0abd61860bb5548ca

**Comment by danantonioreyes** [comment]
Deployed
