### ISSUE TITLE
Create GTM account

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#3311]
From JayLo:

Create Google Tag Manager Account and put the snippet to every pages and embedders that currently tracked by GA standard tracking code

Don’t delete GA standard tracking code yet

[GTM Migration Explanation](https://docs.google.com/document/d/1V75jDRR2-CjKgtujDKx7l68aEAXtrTpzHH4jE74HKgE/edit)
[GTM Migration Timeline](https://docs.google.com/document/d/14eKMScjYPNAerbCdN3JvkfcRwqzEY2WSmlkr1u4Zz-4/edit)

**Comment by bendk** [comment]
Okay, I just set this up:

 - Added GTM account named "Participatory Culture Foundation"
 - Added GTM container named "amara.org"
 - Added google analytics property named "Amara GTM"
 - Added the GTM code to our templates

I just tested it from dev.amara.org and it seems to be working for me.

Writing an email to JayLo with more details.
