### ISSUE TITLE
Make sure Play works the same when triggered by play button, tab button in UI, and tab key

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#3314]
Copied this from #3273 where I think we miscommunicated about it in the comments:

Make sure Play works the same when triggered by:

- keyboard shortcut
- play button
- play button icon in upper left of screen

Subtitle in subtitle list should stay in edit mode when play is triggered by any of these.

**Comment by PCF-Testing** [comment]
Deployed.
