### ISSUE TITLE
Make separate docker image for dev/testing

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3316]
We should create a different docker image for dev/testing.  This would allow us to not include a bunch of requirements in our production images including at least these:

  - sqlite
  - fakeredis/lupa
  - django-debug-toolbar

I think the way to do this is with a build arg.  Something like this:

 - We create a build arg named `TESTING`
 - If `TESTING` is not empty, then we run a build script that calls `apt install` and `pip install` to install the dev dependencies.

**Comment by bendk** [comment]
Implemented in the gh-3316 branch.

I'm going to wait until we deploy the current code in dev, then do another deploy with only these changes.

**Comment by bendk** [comment]
I just merged this to dev.  @PCF-Testing can you do a quick pass on dev and check out if anything seems off?  I think if there was an issue it would be very obvious, so probably just a quick check is fine.

**Comment by bendk** [comment]
I just merged to staging.  Let's test there instead of dev.  That way we can commit to dev still.

**Comment by PCF-Testing** [comment]
I have been testing on dev.

Noticed issues with team activity log (https://dev.amara.org/en/teams/ted/activity/ does not include today's activity), HTTP callbacks (https://dev.amara.org/api/teams/ted/notifications/ does not include the recent entries), provider requests (https://dev.amara.org/en/videos/cUKFuviiLv2y/en/1093458/?team=m-collab-test-2 is stuck), syncing to external systems (https://dev.amara.org/en/videos/X2gNTJ6gTcBy/zh-cn/1093459/?tab=sync-history did not sync as expected).

**Comment by bendk** [comment]
The queue has been processed.  I took a look at the activity log and HTTP callbacks and it looks like they are fixed now.

**Comment by PCF-Testing** [comment]
Seems to be working fine now.

**Comment by bendk** [comment]
Just deployed this to production.
