### ISSUE TITLE
Map prs to fa-af on Vimeo integration

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#3317]
Vimeo only supports fa-af (Persian (Afghanistan)) from ISO-639-1, rather than prs (Dari) from ISO-639-3. prs and fa-af are equivalent, the difference is political.

Both fa-af and prs are valid codes on Amara, so a choice will have to be made regarding which one to sync if both were present for any reason. Since fa-af is the code supported on Vimeo it probably should take precedence.

**Comment by danantonioreyes** [comment]
Implemented in https://github.com/pculture/unisubs/tree/gh-unisubs-3317 (which I directly merged to dev)

**Comment by PCF-Testing** [comment]
Deployed.
