### ISSUE TITLE
Keyboard focus style

### ISSUE THREAD

**Issue by kslottow** [pculture/unisubs#3321]
Right now links/buttons that have keyboard focus look the same as when they're hovered.  Let's use the browser default focus ring style instead (eg. blue outline for chrome).  

From Kenzie: For buttons, I'm not sure this will work. Maybe we should change the colors of the text and background, depending on how well the focus ring stands out with our button colors.

Reasons from Ben:
   - It doesn't seem very intuitive to me when I tab through the links/buttons.  I'm not a screen reader user though, so I'm not sure how it would feel to users who do that more.
   - On the videos/create page when you click either the begin/learn more buttons, that button gets keyboard focus.  Currently this feels buggy to me as a mouse user, since I think of lime green as hover, but when I move my mouse away it stays lime green.  I think having a separate style for keyboard focus could improve that.  Alternatively, we could make the button lose keyboard focus when it's clicked, but I don't think that's the best behavior for keyboard users.

Reasons from Kenzie:
I like the idea of using the browser default, because it seems like it would match the expectation of a frequent keyboard user (rather than creating our own focus style). I tried tabbing through the marketing pages and I see that the text that can have keyboard focus currently changes color, but nothing happens for buttons, like "get started" or menu items with a different style, like the site map or language selector.

**Comment by bendk** [comment]
Commited this one directly to dev.

**Comment by bendk** [comment]
I don't think this needs to be in the changelog.

To test, just hit tab to focus various elements and make sure they look okay.

**Comment by PCF-Testing** [comment]
This is what it looks like on dev - "Begin" button has the focus:

![screenshot from 2018-09-12 04 22 27](https://user-images.githubusercontent.com/288455/45422210-6860b600-b644-11e8-81fe-e91ff5369a40.png)

The only visible difference compared to what is on production (screenshot below) is that the link inside the button is underlined. Not sure if it is an improvement in any way. Also, I don't see a way to simulate a mouse click on the selected button with the use of the keyboard - it does not respond to pressing Enter or Space.

![screenshot from 2018-09-12 04 30 52](https://user-images.githubusercontent.com/288455/45422589-7f53d800-b645-11e8-907d-12de44751f25.png)

**Comment by PCF-Testing** [comment]
Some elements on the marketing pages don't look great with this border. Examples:
* "Amara's Awards" section on the Home page if you click "award-winning" link (https://dev.amara.org/en/#awards)
![screenshot from 2018-09-13 03 49 10](https://user-images.githubusercontent.com/288455/45484271-6f50fc80-b708-11e8-9c94-cc3c6bf8e9a3.png)

* "Get Started" panel on Subtitling Platform page

**Comment by bendk** [comment]
Fixed the issue with the marketing pages

Made #3405 for issues that I think we should look over at some point, but we can ignore for the initial implementation.

**Comment by PCF-Testing** [comment]
Looks much better now.

Is it OK that tabbing does not take effect until you mouse click somewhere in the page or its header? This doesn't seem to fit well into the concept of navigating the site with the use of the keyboard only...

**Comment by bendk** [comment]
Yeah that's still a problem, but I think it's a different issue.  I made #3406 for that

**Comment by PCF-Testing** [comment]
Deployed.
