### ISSUE TITLE
Experimental editor: DELETE key removes the subtitle instead of deleting the text to the right from the cursor

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3327]
When you are editing the subtitle text and press the DELETE key, you expect it to remove the character to the right from the text cursor. However, instead it removes the whole subtitle. Another DELETE keystroke removes the next subtitle, etc. Of course, you can undo these actions, but every time this happens you need to notice what is happening, undo the changes, and click in the subtitle to resume editing, which could be time-consuming and annoying.

Expected: to remove a subtitle, use a combination of keys that normally is not used for text editing.

**Comment by PCF-Testing** [comment]
Verified. Marking as closed.

**Comment by kslottow** [comment]
What key is now used for deleting subtitles in the experimental editor?

**Comment by bendk** [comment]
`del` or `alt+del`
