### ISSUE TITLE
Create dependent checkboxes field

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3331]
See the Admin > Managers > Any team member field in on this page:

https://app.zeplin.io/project/5ac7a5796986566352af25f4/screen/5b50c9f53231fa207b07c943

**Comment by bendk** [comment]
Implemented in the gh-3331 branch.  You can test it out in the dependent checkboxes section of the styleguide.

One thing I find a bit weird is the following case: I have all 3 options selected, then I click "Manager" (the middle option).  Do I mean to uncheck manager (the normal case for checkboxes) or did I mean to keep manager checked, but uncheck admin?  I went with the former, but we could change the behavior.

**Comment by bendk** [comment]
I used the mockup more as a general guideline than as a specification.  I think we have to do that because the styles are slight different on different mockups.

Fixed the typo.

**Comment by PCF-Testing** [comment]
Deployed.
