### ISSUE TITLE
Update general form styles for the future UI settings page

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3332]
- fieldsets
  - headers
  - spacing/padding
- new things for settings forms
  - save changes button: this should only appear when there are unsaved changes, at the top and bottom right of the form.
  - back to top link
- [text areas](https://gyazo.com/5f865e002c1321ecedae2ec4763da3e5)
  - remove box shadow 
  - set font-color to charcoal instead of a light gray
  - set border radius to 0
  

All of these can be referenced in this [Zeplin comp](https://app.zeplin.io/project/5ac7a5796986566352af25f4/screen/5b50c9f53231fa207b07c943)

**Comment by danantonioreyes** [comment]
@bendk @kslottow 

> save changes button: this should only appear when there are unsaved changes, at the top and bottom right of the form.
Do we allocate space for where the save button is supposed to be? I.e. use `visibility:hidden` instead of `display:none` for the button? How about simply disabling it when no changes are made yet?

Where do we put back-to-top links? at the bottom most of the form? at every fieldset legend?

**Comment by bendk** [comment]
I think we decided to hide rather than disable, since it has better asthetics.  I think we should allocate the space so that other page elements don't jump around.  Either `visibility: hidden` or using absolute positioning should do it.

**Comment by danantonioreyes** [comment]
Personal note:
Fieldset updates to be global. Save changes and back to top button exclusive to settings pages

**Comment by danantonioreyes** [comment]
`textarea`s seem to be fine already without changing anything, maybe that's an outdated design?

**Comment by danantonioreyes** [comment]
Implemented in https://github.com/pculture/unisubs/tree/gh-unisubs-3332

The new fieldset styles and back-to-top and Save Changes button can be tested at the style guide:
http://unisubs.example.com:8000/en/styleguide/settings-fieldsets

**Comment by PCF-Testing** [comment]
The styleguide page looks pretty different from the zeplin mock-up:

![screenshot from 2018-08-20 01 58 08](https://user-images.githubusercontent.com/288455/44330759-b0f9ca80-a41c-11e8-8c48-631f02662f6e.png)

Not sure what the Password and Confirm Password fields are for; shouldn't password fields be masked for security?

The job application page (http://unisubs.example.com:8000/en/recruitment/apply/) is indeed messed up on the branch as the result of the change:

![screenshot from 2018-08-20 01 56 27](https://user-images.githubusercontent.com/288455/44330903-046c1880-a41d-11e8-8bc0-97514b686a24.png)

**Comment by danantonioreyes** [comment]
The style guide page is basically just to demonstrate how the new field sets look like and not meant to copy the exact zeplin mock-up for this particular issue.

Added a fix for the weird floating checkbox at the recruitment page

**Comment by PCF-Testing** [comment]
@danantonioreyes: shouldn't a change in the radio buttons or the checkbox make Save Changes buttons visible?

**Comment by PCF-Testing** [comment]
Deployed.
