### ISSUE TITLE
Implement image upload field

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3334]
It should support:
  - showing an empty image if nothing has been uploaded
  - removing images after they've been uploaded
  - resizing/scaling uploaded images
    - scale the image so it fits inside the preview box
    - make sure to maintain the aspect ratio
    - if it's too short or too narrow after resizing, then place it over the checkerboard pattern so you see what's off

See this one for various state changes
https://app.zeplin.io/project/5ac7a5796986566352af25f4/screen/5ad7ba41f962303c0ecdf156

See this one for it in the wild: 
https://app.zeplin.io/project/5ac7a5796986566352af25f4/screen/5b50c9f4cede834136cff8d6

We might need to do this in the general settings page, because I'm not sure how uploads are going to work with the styleguide.

**Comment by bendk** [comment]
- Implemented in the gh-3334 branch
- There's a migration
- You can test it out at `/styleguide/image-upload`

**Comment by PCF-Testing** [comment]
/styleguide/image-upload does not behave exactly as https://app.zeplin.io/project/5ac7a5796986566352af25f4/screen/5ad7ba41f962303c0ecdf156 specifies, but should it actually?

The image upload control on the branch does not have the Choose, Progress, or Complete state as specified in the mock-up, just Empty state and a hybrid state once an image file is selected. After a click on Submit, the image upload switches to the error state with "This field is required" message.

Also, the page explodes when viewed by an anonymous user:
app_1            | ERROR 2018-08-17 07:26:59,311 unhandled_error Cannot assign "<django.contrib.auth.models.AnonymousUser object at 0x7f74dc53b510>": "StyleguideData.user" must be a "CustomUser" instance.
app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
app_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1            |   File "/opt/apps/amara/apps/styleguide/views.py", line 57, in section
app_1            |     'form': get_form_for_section(request, section_id),
app_1            |   File "/opt/apps/amara/apps/styleguide/views.py", line 69, in get_form_for_section
app_1            |     return FormClass(request)
app_1            |   File "/opt/apps/amara/apps/styleguide/forms.py", line 30, in __init__
app_1            |     self.setup_form()
app_1            |   File "/opt/apps/amara/apps/styleguide/forms.py", line 57, in setup_form
app_1            |     styleguide_data = self.get_styleguide_data()
app_1            |   File "/opt/apps/amara/apps/styleguide/forms.py", line 43, in get_styleguide_data
app_1            |     return StyleguideData(user=self.user)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 440, in __init__
app_1            |     setattr(self, field.name, rel_obj)
app_1            |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 597, in __set__
app_1            |     self.field.rel.to._meta.object_name,
app_1            | ValueError: Cannot assign "<django.contrib.auth.models.AnonymousUser object at 0x7f74dc53b510>": "StyleguideData.user" must be a "CustomUser" instance.
app_1            | INFO 2018-08-17 07:26:59,726 access GET /styleguide/image-upload 500 (0.658s)

**Comment by bendk** [comment]
I decided to not include the upload button and related states for a few reasons:

  - It's harder to implement that way
  - We can display a preview image without actually uploading to the server
  - There's a UI question here.  If you upload to the server, does that change the image immediately, or do you need to wait until you click the save changes button?  If it's the latter, it adds even more complexity to the input
  - Users don't need to upload batches of images which is when the progress bar is most useful.

> After a click on Submit, the image upload switches to the error state with "This field is required" message.

Does this happen when the preview image is shown, or if you just click submit without selecting a file?

I'll fix the issue for the anonymous user.

**Comment by PCF-Testing** [comment]
The exception for the anonymous user is gone.

The screencast below shows how "This field is required" error happens: https://drive.google.com/file/d/1uHEGsuwTa88VImgjeb4YEwykDSqN9KzK/view. "Submit" is clicked when the preview image is displayed (but if I skip selecting an image file, the same thing occurs).

> If you upload to the server, does that change the image immediately, or do you need to wait until you click the save changes button?

I think it should be okay if the image changes immediately. This is the way uploading the user avatar works, and this seems to have never caused any problems.

**Comment by PCF-Testing** [comment]
The remove option works well for me.

One last small thing is that https://dev.amara.org/en/styleguide/image-upload has a double header.

**Comment by PCF-Testing** [comment]
Deployed.
