### ISSUE TITLE
Experimental editor: "start subtitle" and "end subtitle" button on the keyboard control panel do not do anything

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3350]
These are legacy buttons left from the previous implementation of the editor.. Clicking them does not modify any start or end times. Instead, they navigate down or up the subtitle set.

![screenshot from 2018-08-17 07 46 32](https://user-images.githubusercontent.com/288455/44272436-b6270180-a1f1-11e8-9326-8233bb4119fc.png)

**Comment by bendk** [comment]
Do you have the latest code?  I'm pretty sure they sync, at least in the syncing step.  I don't think they should be displayed on other steps.

**Comment by PCF-Testing** [comment]
The panel now has changed its appearance:

![screenshot from 2018-08-20 03 50 19](https://user-images.githubusercontent.com/288455/44336434-4c466c00-a42c-11e8-9479-54b2de72a51d.png)

but clicking the arrow down button still does not take any effect.

**Comment by bendk** [comment]
Clicking the arrow, does have an effect.  However, that command will only sync if there's as start/end time near the current time cursor.  I think it's within 1 second.

@PCF-Testing @kslottow is there a better language to use for this?  Is there some other way to clear up the potential confusion?

**Comment by PCF-Testing** [comment]
Okay, this ticket is actually more about the lack of option to sync subtitles past the syncing stage, which is discussed in a different ticket. Marking the current ticket as closed.
