### ISSUE TITLE
Move video index column to the videos table.

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3356]
Now that we are on a mysql version that supports FULLTEXT indexes on InnoDB tables, we can do this without issues.

**Comment by bendk** [comment]
This one is going to be in a couple stages.  Here's how to test:

- Before stage1:
  - Add a video
- stage1:
   - Run migrations
   - Check that searching for the video works
   - Update the title, and check searching for the new title
- stage2
   - Run migrations
   - Check that searching for the video works
   - Update the title, and check searching for the new title
- stage 3
   - Run migrations
   - Check that searching for the video works

**Comment by PCF-Testing** [comment]
@bendk: I could take this one now, would it be possible to merge in the latest changes from dev? Thanks!

**Comment by bendk** [comment]
@PCF-Testing Merged!

**Comment by PCF-Testing** [comment]
Migration error on stage1 branch:
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0009_video_search_text, 0009_auto_20180919_0026 in videos).
To fix them run 'python manage.py makemigrations --merge'

**Comment by bendk** [comment]
Should be fixed now.

**Comment by PCF-Testing** [comment]
@bendk: I have trouble restoring the database from a backup file with the use of bin/dev dbload [backup_filename]. The error is as follows:
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'mysqldump: [Warning] Using a password on the command line interface can be insec' at line 1
Traceback (most recent call last):
  File "/opt/apps/amara/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/dbshell.py", line 22, in handle
    connection.client.runshell()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/client.py", line 42, in runshell
    subprocess.check_call(args)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mysql', '--user=amara', '--password=amara', '--host=db', '--port=3306', 'amara']' returned non-zero exit status 1
read unix @->/var/run/docker.sock: read: connection reset by peer
Traceback (most recent call last):
  File "bin/dev", line 616, in <module>
    Dev().main()
  File "/home/maggie_s/unisubs/bin/command.py", line 191, in main
    self.execute(sys.argv[1:])
  File "/home/maggie_s/unisubs/bin/command.py", line 103, in execute
    self.run()
  File "/home/maggie_s/unisubs/bin/command.py", line 166, in run
    subcommand.execute(self.args.subcommand_args)
  File "/home/maggie_s/unisubs/bin/command.py", line 103, in execute
    self.run()
  File "bin/dev", line 208, in run
    run_manage(['dbshell'], stdin=f)
  File "bin/dev", line 554, in run_manage
    subprocess.check_call(cmdline + args, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker-compose', 'run', '--rm', 'app', 'manage', 'dbshell']' returned non-zero exit status 1
Is there anything I could try to restore the database after dbreset?

**Comment by PCF-Testing** [comment]
Migration error on branch gh-3356-stage2:

CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0010_merge_20181012_1358, 0010_auto_20180830_1237 in videos).
To fix them run 'python manage.py makemigrations --merge'

**Comment by bendk** [comment]
Should be fixed now.

**Comment by PCF-Testing** [comment]
Finished migrations through all three stages.

At stages 1-2, videos with the edited title could be found by the new title in the public area, but not in teams. For unchanged video titles, team search results were inconsistent - say, if some videos had "Kids of the Apocalypse" phrase in the title, "Apocalypse" or "Kids Apocalypse" returned the correct result set while the whole phrase, "Kids of the Apocalypse", did not do so. All of this matches the current behaviour on production.

On stage3 branch, editing a title of a public video made finding it by the new title impossible. After the edit, the video could be still found by the keywords from its old title, but not by the new one. I believe this behaviour is different from the expected one.

**Comment by bendk** [comment]
How are you updating the public videos?  I don't think the search index gets updated if you use the django admin.

It should get updated by running `dev manage index_videos`.  I fixed a couple bugs there though.

Another issue I noticed is dev databases are case-sensitive, which messes with searching.  I fixed the dbreset command to not do that, but existing databases will still be case-sensitive.  I checked dev/production and the settings are correct there, so I wouldn't worry about this issue so much.

**Comment by PCF-Testing** [comment]
> How are you updating the public videos?

By editing the primary language or through the API. I was searching with the case matching the phrase in the title, but that still did not work.

**Comment by bendk** [comment]
I think that should be fixed as well.

**Comment by bendk** [comment]
I followed those steps and both "BBC" and "BBC News" matched the video.  Can you give me the entire steps you tested so I can try to reproduce?

**Comment by PCF-Testing** [comment]
Here is what I am doing:
1. Select "Subtitle video" from the user drop-down menu.
2. Submit the video URL (this time it was https://www.youtube.com/watch?v=litJWtioNmc). Clicked Begin to submit.
3. Clicked the magnifying glass to open the list of recently added public videos.
4. In the search field, typed "Syrian refugee" and pressed Enter. This returned the new video.
5. Deleted the text from the search field and typed "BBC News", then pressed ENTER. The search returned some videos, but not the new one.
6. Deleted the text from the search field and typed just "BBC", then pressed ENTER. The search returned some videos, but not the new one.

**Comment by bendk** [comment]
I just took those steps and got the video both times.

I don't have the old videos in by database, maybe that makes a difference I don't know.  Fulltext search is complicated and can be conter-intuitive.  One possibility is that "BBC" is a very common word for videos in your database, which can affect the results.

In any case, it seems to me like the code is working, the only potential issue is how the fulltext search works.  I know there's already other issues there, so I would lean towards starting to merge this one.

**Comment by PCF-Testing** [comment]
My database is actually very small and only has a handful of videos that were added to an empty db (after dbreset) while testing this ticket.

OK, let's merge this branch and double-check how it behaves on large data sets.

**Comment by bendk** [comment]
This has been approved, the last thing to do is to merge this to production.

Since it's a multi-stage deploy, let's do the following:
 - Wait until we deploy dev
 - Then merge stage1 into dev, and deploy that to production
 - Do the same for stage2 and stage3

**Comment by bendk** [comment]
Finished the deploy today.

@PCF-Testing I'm going to move this back to the testing pipeline, since it seemed like there were maybe some issues to test out.

**Comment by PCF-Testing** [comment]
Generally works well for me, except that adding "the" to the search clause breaks it. Example: "internet's own boy" yields the desired search results, while "the internet's own boy" (the full title of the film) does not. Or did you want me to look into something more specific than this?

**Comment by bendk** [comment]
I think that's good.  I'm going to close this one.  The issue with "the" is a longstanding one as far as I know, I thought I already opened an issue for it.  In any case, I made #3496 for that one.
