### ISSUE TITLE
Experimental editor: cannot hide the tutorial 

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3358]
As a new user, I open the subtitle editor with the tutorial overlay displayed by default. If cannot be hidden by checking "Please go away" box or clicking anywhere outside of the tutorial area, so there is no way to actually start editing subtitles.

**Comment by bendk** [comment]
I was able to close the tutorial window, but the "Please go away" checkbox didn't do anything.

Fixed the please go away issue.  Tell me if you still have problems closing the tutorial altogether though.

**Comment by PCF-Testing** [comment]
Sorry, still a problem. "Please go away" still doesn't do its job, and in Firefox the tutorial just would not close at all.

**Comment by bendk** [comment]
Fixed the issue closing the tutorial.  I still can't see an issue with please go away.  Could that have been because you couldn't actually close the tutorial?

**Comment by PCF-Testing** [comment]
Verified the fix.

**Comment by PCF-Testing** [comment]
This one was a regression, so just closing it.
