### ISSUE TITLE
Experimental editor: unable to move back to previous stages and use the toolset for that stage

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3360]
In the experimental editor, the options available to the user depend on the stage (Typing, Syncing, or Review) the editor is in. Once the user moves to the next stage, there is no good way to return to one of the previous stages and redo things from scratch.

Example:
1. Submit a video.
2. Start a transcription.
3. Type some subtitles and sync them, move to the Review stage.
4. Clear all the timing and try to sync all the subtitles from scratch. There seems to be no good way to do that.

**Comment by bendk** [comment]
I think there's another issue for changing the editor stage.   I'm going to update the keyboard shortcuts so down syncs in any stage, I think that should fix the main issue here.
