### ISSUE TITLE
Add Franco-Provençal language

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3361]
Franco-Provençal (Arpitan) language
https://en.wikipedia.org/wiki/Franco-Proven%C3%A7al_language
ISO 639-3 code - frp
Directionality - LTR

Reason: requested in https://pculture.freshdesk.com/helpdesk/tickets/102944

**Comment by asabine** [comment]
pushed to unliangs master

**Comment by PCF-Testing** [comment]
Deployed.
