### ISSUE TITLE
Futureui settings pages: fix Save Changes button for Edge browser

### ISSUE THREAD

**Issue by danantonioreyes** [pculture/unisubs#3363]
### For change log:
No changelog entry
=====

Related to #3332 

Seems like Microsoft Edge has some problems regarding "input" and "change" events:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4660045/
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15181565/

This makes it so that the Save Changes button will not appear on Edge browser for the pages that use this button.

There's some options to make this work:

- workaround javascript to make the Save Changes button function as it should or
- always show the Save Changes button when the browser is MS Edge

**Comment by bendk** [comment]
One thing you can do is bind to both input and changed.  It's a bit redundant on good browsers, but it's not too much extra work to test twice.

**Comment by PCF-Testing** [comment]
Works in Edge now.

**Comment by PCF-Testing** [comment]
Deployed.
