### ISSUE TITLE
Add team context to Edit Subtitles button on the language page for simple teams

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3371]
@PCF-Testing commented on [Sat Jun 23 2018](https://github.com/pculture/amara-enterprise/issues/2018)

On the language page for simple teams, "Edit Subtitles" button redirects to the editor without the team context, e.g. http://unisubs.example.com:8000/en/subtitles/editor/024nsQCcxeXI/en/  As the result, when the subtitle editor is closed, the user lands on the old style page.

Expected: add the team context to the CTA link. (`?team=[slug]` if team is already present in the GET params)

**Comment by bendk** [comment]
We got a fix for this from @metanerd 

To test:
  - Make sure this doesn't break the subtitles page in any case
  - Make sure that for simple teams, when you have the team context in the URL, it is also in the edit subtitles button
  - Test again for collab teams.  If this breaks, then I can fix it since that's in the amara-enterprise repo

No notes needed for the release notes.

**Comment by PCF-Testing** [comment]
@bendk: is this one already on dev? There is no separate branch in the code that matches this ticket.

**Comment by bendk** [comment]
Yes it's on dev.  The branch was on metanerd's github account.

**Comment by PCF-Testing** [comment]
Doesn't work for me on dev. You can see this by clicking `section.videoSubtitles-progress div.videoSubtitles-cta a.button.cta.block`  on [video page](https://dev.amara.org/en/videos/v7rUuzcEpJHI/en/1038083/?team=simple-team-test) and then clicking Exit button in the subtitle editor.

**Comment by bendk** [comment]
@metanerd I just checked it out and here's what's happening:

 - You updated the code that handles non-team videos.  As far as I can tell, that should work fine.
 - However, the code that handles team videos is in a separate place, in fact it's in a few places because depending on the team type we have different code to controls when users can edit subtitles.
 - To make this work with team videos you'd need to:
    - Update the code for "simple teams" in `apps.teams.workflows.simple:SimpleSubtitlesPageCustomization`.  (Simple teams are teams that simply limit access to members-only)
    - Do one of the following:
         - Update the code that creates that class in `apps.teams.workflows.startup:subtitles_page_customize` and make it pass in the `team_slug` param
         - Don't pass in the `team_slug` param but instead have SimpleSubtitlesPageCustomization get it from the request object.  I kind of like this way better because there are other SubtitlesPageCustomization subclasses and this way we don't need to update their constructor yet.   It's not a big deal either way though.

Tell me if there are things that could help in this process.  I know that we could do way better on helping people from the community get onboard.  So if there are some improvements we could make I'm happy to do them.

**Comment by bendk** [comment]
I merged metanerd's code into gh-3371.  You should be able to test it there.

**Comment by PCF-Testing** [comment]
Deployed.
