### ISSUE TITLE
"New videos ready for subtitling" messages have stopped

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3374]
The last message of this type that has been delivered was dated by Aug 28.

Other messages, such "A user requested to join your team" and members joining/leaving, still keep coming in.

**Comment by bendk** [comment]
This one happened because the scheduled tasks stopped running.

I think this had to do with how I was starting/stopping the scheduler, but we should check a few more things:

 - [ ] Tomorrow, check the list of scheduled jobs.  It should be something like this:

```
<function unassign_expired_assignments at 0x7fc71fe4d398>
<function notify_about_assignment_deadline at 0x7fc71fe4d500>
<function retry_failed_sync at 0x7fc720145140>
<function check_for_missing_ted_ids at 0x7fc72bb56aa0>
<function trim_notification_log at 0x7fc71fe4d7d0>
<function add_videos_notification_hourly at 0x7fc7204f5de8>
<function retry_failed_requests at 0x7fc71ff59f50>
<function add_videos_notification_daily at 0x7fc7204f5c80>
<function expire_login_tokens at 0x7fc71fe4d8c0>
<function prune_notification_history at 0x7fc71fe4db90>
<function poll_results at 0x7fc71ff59de8>
<function expire_tasks at 0x7fc7204f5b18>
<function cleanup at 0x7fc7209768c0>
```

- [ ] After we deploy, check again

**Comment by bendk** [comment]
Looks good on staging after 2 deploys today.  I think we can close this one.

No changelog entry needed.
