### ISSUE TITLE
Experimental editor: ignore nudge keystrokes beyond the edge of adjacent subtitle

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3378]
Steps to reproduce:
1. Sync some subtitles by pressing Arrow Down key, so that the subtitles are adjoining each other with zero gap in between.
2. Click the start time for one subtitle to enable the nudge mode for it.
3. Press Arrow Right 3 times to shift the start time forward. This creates a gap between the subtitles.
4. Press Arrow Left 6 times to shift the start time back. As the start time reaches the end time for the adjoining subtitle, it stops changing.
5. Press Arrow Right 6 times. The first three keystrokes do nothing, as if the last 3 Arrow Left keystrokes somehow are being "undone". This feels weird and bug-like. I think the correct behavior is to ignore any keystroke that attempt to move the time past the boundary of another subtitle. When we start performing a different action, as in step 5, this action should take effect immediately.

**Comment by PCF-Testing** [comment]
Verified, closed.

**Comment by kslottow** [comment]
Without having tried this, it seems contrary to the fact that when moving subtitles with the mouse, adjacent subtitles are pushed. 

Instead, in the case of nudging, we're making the adjacent subtitles act more like a wall. What was the reasoning behind this?

**Comment by bendk** [comment]
We changed the behavior for both dragging with a mouse and nudging with the keyboard.

The reasoning is that once subtitles are touching, you can now drag from the middle of the 2 subtitles to move both the start/end times.

**Comment by kslottow** [comment]
got it, thanks!
