### ISSUE TITLE
Experimental editor: correcting a typo at syncing stage blocks further syncing

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3381]
Steps to reproduce:
1. Submit a new video.
2. Start transcribing.
3. In the editor, type several subtitles and start syncing.
4. In the middle of a subtitle, press TAB to pause, click inside a subtitle cell and type something (say, correct a typo).
5. Press TAB to resume.
6. Press Arrow Down to start a new subtitle. It doesn't work until you press ESC to exit the editing mode, but from the visual context it is nearly impossible to figure out why Arrow Down has suddenly stopped working. I think it is going to be very frustrating for new users. How about displaying "ESC  Stop editing subtitle text and resume syncing" in the Keyboard Controls?

**Comment by PCF-Testing** [comment]
Verified, closing.

**Comment by kslottow** [comment]
what was the solution implemented for this issue? Writing up the instructions for testing.

**Comment by kslottow** [comment]
got it, thanks!
