### ISSUE TITLE
List View Keyboard controls

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3398]
@bendk commented on [Mon Sep 10 2018](https://github.com/pculture/amara-enterprise/issues/2097)

We should implement keyboard controls for listview at some point.

I think it should be something like this:
 
 - Up/down should navigate through each item
 - When an item is selected:
   - enter should activate the right-most button (this will usually be the context menu)
   - space should toggle the checkbox, if present
 - Ctrl-A should toggle select all

This is pretty straightforward, but there are a couple tricky issues here:
 - Hover/selection interaction.  How should these work.  If I select an item with the keyboard, then hover my mouse over a different item, should both be highlighted?
     - I'm thinking it should be either or, once you navigate with the keyboard we remove the current hover state -- and vice-versa.
 - Context menus.  This is going to be a common way to interact with the keyboard, so we need to make this work well.  If the enter action is shows a context menu, then we should make it so once that menu closes (either because the user selects something, or they close the menu), then the focus goes back to the listview and the user can continue navigating it
- Selected styling: We need to style a selected item.
  - I think `light($lime)` looks pretty good.  If we go with that, then we need to make sure the secondary data turns white to provide good contrast.
  - We could either change the entire background, or maybe just a part of the item.  Gmail uses a line on the lift-hand side.

**Comment by bendk** [comment]
I went ahead and implemented this one in dev.  To style, I drew a lime bar on the left side of the item, like gmail does.  This simplifies a lot of styling issues compared to changing the entire background:
 - It can coexist with the expanded styles without any issue
 - We don't need to change the text color
 - It doesn't interfere with the hover styles at all

**Comment by PCF-Testing** [comment]
The details of implementation are discussed in enterprise-1951.

**Comment by PCF-Testing** [comment]
Deployed.
