### ISSUE TITLE
Remove event tracking code

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3401]
We're now using GTM for this, and the old code is causing JS errors.

**Comment by bendk** [comment]
To test, just make sure the marketing pages, and the videos/create page work okay.

**Comment by bendk** [comment]
Pushed this one directly to dev, since it's pretty simple.

**Comment by PCF-Testing** [comment]
Tested this one on dev and have not found any issues.

**Comment by PCF-Testing** [comment]
Deployed.
