### ISSUE TITLE
Fix migrating tasks with language code unset

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3413]
We should handle this case:
 - If the video language is set, use that for the language code
 - If not, then don't migrate the task

**Comment by bendk** [comment]
Fixed in dev.

**Comment by PCF-Testing** [comment]
The tasks without a language set don't get deleted during the migration. This could cause issue later, when users start to subtitle those videos.

Example:
https://dev.amara.org/en/admin/teams/task/1020543/
https://dev.amara.org/en/admin/teams/task/1020545/

**Comment by bendk** [comment]
Fixed this by adjusting the code to simply delete all tasks for the team after executing the migration.  Before, we would only delete them when we created a collab, and only for the language code of the collab.

I think the new way is safer, but tell me if you can see any issues with it.

**Comment by PCF-Testing** [comment]
Yes, the new ways definitely should be safer, we don't want any stray tasks left after migration.

Verified on dev.

**Comment by PCF-Testing** [comment]
Deployed.
