### ISSUE TITLE
KeyError: 'language1'

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3427]
To reproduce:
  - Navigate to the team application page
  - Don't fill in any of the language fields.  If they have initial values, change them to clear
  - Submit the form.

https://sentry.io/pculture/unisubs-staging/issues/697620984/

```
KeyError: 'language1'
(9 additional frame(s) were not displayed)
...
  File "teams/new_views.py", line 136, in wrapper
    return view_func(request, team, *args, **kwargs)
  File "teams/new_views.py", line 780, in join
    return application_form(request, team)
  File "teams/new_views.py", line 799, in application_form
    if form.is_valid():
  File "teams/forms.py", line 2129, in clean
    self._get_language_list()
  File "teams/forms.py", line 2116, in _get_language_list
    value = self.cleaned_data['language{}'.format(i)]

KeyError: 'language1'
```

**Comment by bendk** [comment]
Fixed on dev.

**Comment by PCF-Testing** [comment]
Verified. A graceful error message is displayed:

![screenshot from 2018-09-25 01 17 57](https://user-images.githubusercontent.com/288455/46001758-f5523900-c060-11e8-935f-e592496bc1de.png)

Marking as closed.
