### ISSUE TITLE
Incorrect search icon on videos/watch/page 

### ISSUE THREAD

**Issue by Rachel36** [pculture/unisubs#3435]
On videos/watch page, the correct search icon is replaced by the LinkedIn icon. This is not currently the case on production, although it has been observed in testing environment.

**Comment by bendk** [comment]
Pushed a fix directly to dev.

Make sure to do a shift-reload to clear your browser cache of the old font.

**Comment by Rachel36** [comment]
Hi @bendk! Change looks good to me.
