### ISSUE TITLE
APIError: get_video_info: Unexpected content: list index out of range

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3442]
The issue here is not so much making things work in this case, but simply catching the error and handling it nicely.  I think that maybe just means returning None from `get_video_info()`.

https://sentry.io/pculture/unisubs/issues/709878631/

```
APIError: get_video_info: Unexpected content: list index out of range
(3 additional frame(s) were not displayed)
...
  File "externalsites/tasks.py", line 147, in fetch_subs
    subfetch.fetch_subs(VideoUrl.objects.get(id=video_url_id), user, team)
  File "externalsites/subfetch.py", line 52, in fetch_subs
    fetch_subs_youtube(video_url, user, team)
  File "externalsites/subfetch.py", line 119, in fetch_subs_youtube
    account = find_youtube_account(video_id, lookup_youtube_accounts(video_url, user, team))
  File "externalsites/subfetch.py", line 145, in find_youtube_account
    video_info = google.get_video_info(video_id, possible_accounts)
  File "externalsites/google.py", line 446, in get_video_info
    raise e

APIError: get_video_info: Unexpected content: list index out of range
```

Possible replication:
Upload a private YouTube video while not having the owner channel linked to your Amara account

**Comment by danantonioreyes** [comment]
I think the way to replicate this is to upload a private YouTube video while not having the owner channel linked to your Amara account

**Comment by PCF-Testing** [comment]
Yes, this exception could be reproduced on dev exactly as described in the previous comment - thanks @danantonioreyes!

**Comment by PCF-Testing** [comment]
Verified the fix.

**Comment by danantonioreyes** [comment]
Accidentally merged this to dev while I was supposed to just update it for a PR

**Comment by PCF-Testing** [comment]
Deployed.
