### ISSUE TITLE
Split up redis into cache/storage databases

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3460]
We are currently using redis for two things:
  - simple replacement for memcached for things like caching pages
  - an actual key/value data store for things like storing scheduled jobs, team stats, job progress, etc.

When we deploy, we call the `clear_cache` command.  This is because pages cached from the previous deploy might not still be valid after the code changes.  However, this is also deleting things that should be permanent, for example the scheduled jobs.

One solution is to use 2 redis databases.  One for cache, that we can simply clear out every deploy.  One for permanent storage that we don't clear oup.

**Comment by PCF-Testing** [comment]
Deployed.
