### ISSUE TITLE
Team tags field required when updating team on Django Admin

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#3469]
Since the Django upgrade, the team tags field in the admin pages i.e. https://amara.org/en/admin/teams/team/x/ is required, though it seems this is optional metadata and wasn't in use so far.

**Comment by kslottow** [comment]
@bendk is it intended to be required? My understanding is they are optional

**Comment by bendk** [comment]
They are intended to be optional and I'm pretty sure this was already fixed.
