### ISSUE TITLE
Missing max assignments per user field in collaboration team workflow settings UI

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#3470]
This is probably already bundled in the pending UI update for the collab settings page.

The collaboration setting "Max assignments per user" is not available in the collaboration team workflow settings page. The setting is already functional, but can only be modified by finding the collaboration settings django admin page for that team.

**Comment by PCF-Testing** [comment]
This is addressed in https://github.com/pculture/amara-enterprise/issues/2050. Marking as closed.
