### ISSUE TITLE
Specify the frame mode in the ITT export

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#3475]
Our current ITT export doesn't specify the drop frame mode and assumes "dropNTSC" (the mode where timestamps match playback time) as default.

This is incorrect, as per the spec the "nonDrop" is the default.

https://www.w3.org/TR/2018/PR-ttml1-20181004/#parameter-attribute-dropMode

This causes issues with partners that see incorrect time delays due to having an incorrect header.

The tt tag in the ITT exports should include the parameter ttp:dropMode="dropNTSC" for the export to be correct.

**Comment by bendk** [comment]
Also add `ttp:timeBase="smpte"``

**Comment by franontanaya** [comment]
To correct myself, our export is correct as we omit timeBase, which defaults to media. In practice it doesn't seem to be working out, and it should be functionally the same to specify both smpte and dropNTSC to avoid issues.

**Comment by bendk** [comment]
Fixed in gh-3475

Note that this might not be correct for all partners.  Right now we only have 1 that's using ITT and this is what we want.

Down the line, if multiple teams want ITT output, then we allow them to customize what the exported file looks like.

**Comment by PCF-Testing** [comment]
@franontanaya: The new header looks as follows:
`<tt xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns="http://www.w3.org/ns/ttml" ttp:timeBase="smpte" ttp:dropMode="dropNTSC" ttp:frameRateMultiplier="999 1000" ttp:frameRate="30" xml:lang="en">`

Should the timing for exported ITT files change in any way compared to the ITTs we had exported before?

As a side note, I have noticed that in event of uploading and then downloading ITT files, the downloaded copy is slightly different (by 1 frame) from the uploaded original. Example:

- Fragment of the uploaded file:
`            <p begin="00:00:09:13" end="00:00:15:21">John Ronald Reuel Tolkien,<br/>was born on the 3rd January, 1892.</p>
            <p begin="00:00:15:21" end="00:00:19:00">He and his brother Hilary,<br/>experienced a difficult childhood.</p>
            <p begin="00:00:19:00" end="00:00:22:14">When Tolkien was just four,<br/>they lost their father, Arthur,</p>
            <p begin="00:00:22:14" end="00:00:24:00">to rheumatic fever.</p>
            <p begin="00:00:24:00" end="00:00:26:28">As a widow with low income,<br/>his mother Mabel,</p>
            <p begin="00:00:26:28" end="00:00:30:19">home schooled the brothers and played<br/>a vital role in their early education</p>
            <p begin="00:00:30:19" end="00:00:31:24">and development.</p>`

- After uploading and downloading, this fragment becomes:
`            <p begin="00:00:09:12" end="00:00:15:21">John Ronald Reuel Tolkien,<br/>was born on the 3rd January, 1892.</p>
            <p begin="00:00:15:21" end="00:00:19:00">He and his brother Hilary,<br/>experienced a difficult childhood.</p>
            <p begin="00:00:19:00" end="00:00:22:13">When Tolkien was just four,<br/>they lost their father, Arthur,</p>
            <p begin="00:00:22:13" end="00:00:24:00">to rheumatic fever.</p>
            <p begin="00:00:24:00" end="00:00:26:27">As a widow with low income,<br/>his mother Mabel,</p>
            <p begin="00:00:26:27" end="00:00:30:18">home schooled the brothers and played<br/>a vital role in their early education</p>
            <p begin="00:00:30:18" end="00:00:31:24">and development.</p>`

If this timing mismatch (up to 0.03 s) is significant enough to require a fix, I can make a separate ticket for it.

**Comment by PCF-Testing** [comment]
According to Fran, the rest of ITT file should not change.

**Comment by franontanaya** [comment]
The timing mismatch could affect files that required a gap of 1-2 frames between subtitles, but since the editor doesn't have an option to force them, them there's already no expectation of gaps being preserved.

Frame gaps prevent two adjacent captions being drawn on the same video frame, e. g. on burnt in captions. This is not an issue on web video.

I would check that the mismatch doesn't worsen with repeated downloading and uploading as opposed to a singular rounding error.

**Comment by bendk** [comment]
Should be fixed now.

**Comment by bendk** [comment]
I updated the code to convert frames to milliseconds.  @PCF-Testing  can you double check that import and export still works for you?

**Comment by PCF-Testing** [comment]
Import/export of ITT files now produces an ITT file that is identical by timing to the original file.

Found a small problem with timestamp conversion though.

If I upload an ITT file downloaded from production to a video on gh-3475 branch and then download a DFXP file, ITT timestamp 00:32:01:02 gets converted to DFXP 00:32:01.67, instead of 00:32:01.067. Similarly, 00:30:24:01 becomes 00:30:24.33 instead of 00:30:24.033. (You can use an ITT copy of https://amara.org/en/videos/TdXOHOy2TaQI/en/951993/ to observe this effect.)

**Comment by bendk** [comment]
Should be fixed now.

**Comment by PCF-Testing** [comment]
Looks good now.

**Comment by bendk** [comment]
Merged.

**Comment by PCF-Testing** [comment]
Deployed.
