### ISSUE TITLE
Team activity page: Show More link fails to load older entries

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#3483]
In old-style teams, a click on Show More link at the bottom of the page does not load older activity records. Instead, it invokes the text from the announcement and new messages banner and the user menu at the bottom of the page:

![screenshot from 2018-10-22 19 09 46](https://user-images.githubusercontent.com/288455/47330847-8f8ca900-d62e-11e8-962d-527bc57b12f9.png)

**Comment by danantonioreyes** [comment]
Implemented a fix in https://github.com/pculture/unisubs/tree/gh-unisubs-3483

**Comment by PCF-Testing** [comment]
Works well on my small local data set. Moving to Needs PR.

**Comment by PCF-Testing** [comment]
Deployed.
