### ISSUE TITLE
Experimental Editor Deploy

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#3495]
We have some new code in the experimental editor, we should:

 - Merge the HTML to dev
 - Update the JS/CSS on the next deploy.

There's nothing here to test really, I just wanted to make an issue to remind us to do these steps..

**Comment by bendk** [comment]
Just did the first part, this code is not going to work until we update the JS/CSS though.  Let's do that when we next deploy dev.

**Comment by PCF-Testing** [comment]
@bendk: the experimental editor on dev would not load at all:

![screenshot from 2018-11-15 02 49 58](https://user-images.githubusercontent.com/288455/48548322-85eb0f80-e881-11e8-88be-6e57d562747d.png)

**Comment by bendk** [comment]
Just uploaded the assets.  Things are looking good to me.

**Comment by PCF-Testing** [comment]
The fixes have been successfully deployed to dev and production.
