### ISSUE TITLE
Sentry: https://sentry.amara.org/amaraproduction/group/1021/

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#350]
Just keeping it here so no one waists time with it.

This error occurred a few times on jan 4th for one hour. Basically the ted sessions we get from their auth provider were expired, so people couldn't log in.

Usually, this happens if our clocks are out of sync, but now we have them on NTP updates, so that's probably it.

We think their box got a slow clock for a while, let's keep an eye on this, though.

**Comment by PCF-Testing** [comment]
Obsolete. Closing.
