### ISSUE TITLE
Guidelines page won't allow PM to add zh-cn language guidelines

### ISSUE THREAD

**Issue by Rieann** [pculture/unisubs#3531]
Priority: NOT URGENT - linguists can access via other methods until fixed
Issue: When AOD PM tries to update Guidelines for ZH-CN - Error page shows
Page Link: https://amara.org/en/guidelines/edit/3/

Steps reproduced by Viviane and Rieann:

You can add the zh-cn language and the Details Popup shows
![image](https://user-images.githubusercontent.com/28491502/61417317-a43f5a00-a8ab-11e9-9a4d-ccaac9734d2b.png)

When you try to add the link or any details and Save or SAVE AND EXIT
![image](https://user-images.githubusercontent.com/28491502/61417368-c507af80-a8ab-11e9-9ae5-011ffaa80ea6.png)
 - General Error is displayed
![image](https://user-images.githubusercontent.com/28491502/61417409-db157000-a8ab-11e9-919a-721f5fd39776.png)

 
https://drive.google.com/file/d/0B1gaWOIGz93uMVFaNjVYSlc4Qzg/view

**Comment by PCF-Testing** [comment]
Issue moved to [pculture/amara #4942](https://github.com/pculture/amara/issues/4942) via [**ZenHub**](https://www.zenhub.com/)
