### ISSUE TITLE
? displayed in place of language name

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#371]
A language code was not recognized as a source language and this: 

Subtitles translated from ? Showing Revision 1, created Today by janetPCF .

was displayed for the text on the video language page.

The source language in question is Chewa, language code nwa.

See it here: http://staging.amara.org/en/videos/hm0ido0XsFZx/de/410145/

I think this is a related sentry error: 
https://sentry.amara.org/amara/amarastaging/group/9809/

**Comment by PCF-Testing** [comment]
The link cited in the ticket no longer exists, and I don't think we have observed this issue ever since. Closing.
