### ISSUE TITLE
document  / simplify subtitle delete process for admin support

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#407]
This ticket is a spin off from i2180.

Currently if an admin via the django admin ui edits the visibiility_override setting for a language that is the source for other languages -  the result is that uses will not be able to upload a new set of subtitles for that language.  

They get a message that states: Sorry, we could not upload your subtitles since that would fork German translation made from it.

The django admin isn't setup to handle all the behind the scenes processing that goes along with changing that setting.   So the admin would have to set the dependent languages as forked, or delete the whole source language and successfully upload.

We should:
1. Document that process so an Admin / Superuser knows exactly what they need to do  when they need to delete a language.
2. If it's a common action by support staff - make a button on the UI visible only to admin / superusers that would perform all the actions that need to happen when deleting a lang (ex: forking dependant translations).

@dean assigning to you as it's something that you and @darren should figure how where to document superuser support stuff, and if it's something that happens often enough that a ui change is required.  And whether or not this should be considered a drm blocker or something that can get done at a lower priority.

**Comment by bendk** [comment]
Really old and I think it's been fixed along the line.
