### ISSUE TITLE
Default email addresses for FB/Twitter users do not work

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#410]
New Amara users who sign up with the use of FB or Twitter accounts get assigned dummy email addresses in accordance with the following template:
usersfirstname@facebookuser.unisubs.com
usersnickname@twitteruser.unisubs.com

Email notifications, including email confirmation request, do not get delivered when such dummy emails are in place.

Expected: if extracting valid email info for a user is not an option, show a pop-up requesting the user to enter their email address (we do a similar thing for OpenID account users).

**Comment by PCF-Testing** [comment]
We have revamped signup for FB/Twitter users. Closing.
