### ISSUE TITLE
Placeholder for title/description trans comes from original language instead of base

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#432]
Example:
- Translate subs and title/desc from English to French.
- Start a French to German translation.

When you get to the title/desc page, the labels will (correctly) be the French title/desc, but the contents of the text fields will be the English title/desc.

Do we need to fill these text fields at all?  The subtitle text fields aren't filled, and the only thing someone can do is backspace them out to make room for the translation.

**Comment by bendk** [comment]
I made #3173 which is an updated version of this one for the new editor.
