### ISSUE TITLE
Improve time calculation when inserting subs lines

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#449]
This came from a provider request

Creating new subtitle would re-time the subtitles on either side – when there's enough time, add it in w/ out changing other timing. 

Maybe reduce our minimum subtitle size or something, so that if you can add .75 second subtitle, you don't modify neighbors. 
Don't add more than 3-4 seconds (currently we fill entire gap between subtitles). 

Be as non-invasive as possible. (Dean's idea: Show a "shadow" for the "potential" incoming added subtitle?)

**Comment by bendk** [comment]
I'm having a hard time understanding this ticket.  Is the point of it to insert a subtitle inbetween two existing subtitles?  Can someone make the title clearer?

**Comment by franontanaya** [comment]
Here:

https://github.com/pculture/unisubs/blob/226009462fba4da79d4f58111e4c0a652ecaabbf/media/src/js/subtitle-editor/subtitles/models.js

In SubtitleList.prototype.insertSubtitleBefore:

```
// Inserting a subtitle between two others. Make it so each
// subtitle takes up 1/3 of the time available
var firstSubtitle = this.prevSubtitle(otherSubtitle);
var totalTime = otherSubtitle.endTime - firstSubtitle.startTime;
var durationSplit = Math.floor(totalTime / 3);
var startTime = firstSubtitle.startTime + durationSplit;
var endTime = startTime + durationSplit;
this._updateSubtitleTime(firstSubtitle, firstSubtitle.startTime,
startTime);
this._updateSubtitleTime(otherSubtitle, endTime, otherSubtitle.endTime);
```

When you insert a new subtitle, it takes the start time of the previous, the end time of the following one, then redistributes that time among the three. This completely ignores if the new subtitle is being placed within a big empty gap, after insertion the previous subtitle will end exactly at one third of the time, and the following one will start after two thirds of the total time.

Let's say the previous subtitle starts at 10:00 and ends at 10:02, the next subtitle starts at 15:58 and ends at 16:00. Inserting a new caption inbetween results on three captions that last from 10:00 to 12:00, from 12:00 to 14:00, and from 14:00 to 16:00. (Normally you don't have a 6 minutes gap, just an example)

A fix could be to find the middle time -- in this case, 13:30, make the new subtitle start a second and half before that and end a second and half 12:28.500 and 12:32.500, then find if these times overlap with the previous and next subtitles -- if they do so, divide the overlap by two and give one half to each; or if the preceding or following subtitles start/end less than one second and half from the middle point, take that as upper bound.

**Comment by bendk** [comment]
@franontanaya that's really clear, thanks.  I like the suggested algorithm and it should be pretty easy to implement.

**Comment by PCF-Testing** [comment]
> find if these times overlap with the previous and next subtitles -- if they do so, divide the overlap by two and give one half to each

Does this mean moving the start time for the next subtitle?

When we are inserting a new subtitle into a timed set, it is safer to assume that the set already has accurately synced start times, so we better avoid touching them. It the time gap between adjacent subtitles is absent or too short for a new line, always bite into the end time to make space for the new subtitle, but stay away from the start time. Caption makers get very annoyed when inserting a new line (e.g. for splitting long text into several parts) breaks already nicely synced start times.

**Comment by franontanaya** [comment]
That's a fair point. 

As long as the preceding subtitle won't be cut shorter than 1 second, we can borrow all the time from it. The new subtitle would last at least 1 second, (up to 3 if possible).

If the preceding subtitle would be cut shorter than 1 second, we can borrow the excess from the next one.

On a corner case of inserting a subtitle between two very short subtitles (e.g. 1 second each), we would have to divide the time like in the old formula.

**Comment by syl22-00** [comment]
Implemented the following algorithm, which hopefully is pretty much what was described earlier:
* If there is at least 3 sec between the subtitles, make the new subtitle 3 sec long, centered on the middle between the two if possible or just before the second subtitle.
* If there is at least 2 seconds between the beginning of the first and the beginning of the second, squeeze the new subtitle before the second one, adjusting the first subtitle end and making sure the first and new subtitles are at least 1 second long.
* Otherwise, keep the previous logic which is to make the 3 subtitles the same length to fit in the space available.

**Comment by syl22-00** [comment]
That should be pretty much working except a last glitch: the start time of the second subtitle is not update in the UI. It is updated intenrally and in the helper box though

**Comment by syl22-00** [comment]
So this should be all done, including updating the second subtitle start time in the list if it changed.

**Comment by PCF-Testing** [comment]
This algorithm breaks after a couple of insetions, producing overlapping subtitles.

Consider a set with gaps between subtitles - http://gh-449.amara.org/en/subtitles/editor/85CzEfk54w4q/es/

Insert a subtitle BELOW the first subtitle. Next, insert a subtitle ABOVE that newly added subtitle.

Result: subtitles 1 and 2 overlap
1
00:00.00 - 00:10.00

2
00:06.75 - 00:09.75

3
00:13.50 - 00:16.50

**Comment by PCF-Testing** [comment]
Time calculation has improved a lot.

Nitpick - when new subtitles are inserted before the first subtitle in the set, the start time for the existing subtitle does not get updated inside the cell, remaining set to 0.00.

**Comment by syl22-00** [comment]
Right @PCF-Testing , this part has not changed and was wrong. It should be fixed now.

**Comment by PCF-Testing** [comment]
Line insertion at the top of the set looks good now.

Noticed that if new cells are inserted in a chain, each new one below the previously inserted cell, the next cell can get pushed back in time even if each new cell lasts 1 - 2 secs - they dig into the next cell's time instead of getting compressed. 

Example: suppose we start inserting between cell 1 and cell 2 of http://gh-449.amara.org/en/subtitles/editor/85CzEfk54w4q/en/ (adjacent subtitles case). 3 insertions push the start time for cell 2 from 10.00 to 16.00:

![insert3newlines](https://cloud.githubusercontent.com/assets/288455/7429542/8eac71de-efb7-11e4-8f7c-9c25875cb144.png)

6 insertions already shift it  to 18.00, which is very far from the original value.

Is it an error in calculations? I believed the new subtitles should be compressed as much as possible, not meddling with pre-existing subtitles as long as possible.

**Comment by syl22-00** [comment]
@PCF-Testing I think right now it at least follows the criteria, in @franontanaya previous message:

"If the preceding subtitle would be cut shorter than 1 second, we can borrow the excess from the next one.

On a corner case of inserting a subtitle between two very short subtitles (e.g. 1 second each), we would have to divide the time like in the old formula."

If you insert below a very short subtitle, it will borrow time from the next one. I understand we should touch existing subs as little as possible, but once a subtitle has been inserted, then it is considered as "existing", meaning that if you insert as a "chain" we do not make difference between just added subtitles and "older" ones.

I think users will get use to add as the subtitles as they wish: usually towards where there is available time.

Does it make sense?

**Comment by jdragojevic** [comment]
I think what we have now is good enough for the basic use case.  I'm going to go ahead and make a pull request for this and if we want to do chaining to multiple inserts in the future we can make a new ticket.

**Comment by jdragojevic** [comment]
deployed.
