### ISSUE TITLE
Activities don't show up for me??

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#461]
This is a weird case where Gundega (dev at Udacity) is seeing something totally diff than I am:

In one screen shot the activities show up, but in the other they don't. Can't tell what's up (if anything)

http://www.amara.org/en/videos/sDXAUri1kNeq/info/non-photorealistic-rendering/#activity

**Comment by bendk** [comment]
I don't think this is still an issue.  If it is, can someone give an update and some more info on how we can start takling it?
