### ISSUE TITLE
Transcribing from scratch wipes out video title and description

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#464]
If the transcript in the original language is created in the new editor from scratch (i.e. no previous version had existed), the title and description in the resulting version go blank. The legacy editor populated the title and description for the first subtitle version from the video's metadata imported from the provider (if any).

Steps to reproduce:
1. Submit a video.
2. Click Subtitle Me and select the primary language to subtitle in.
3. In the legacy subtitle editor, do not enter anything. Just click Save and edit in new editor.
4. In the new editor, type in a few lines, save and exit.
5. Check the subtitle version in the subtitle view.

Apparently, this happens because the Title and Description fields in the editing panel are blank by default. To make them populated, a user should care to copy them from the reference panel where the video metadata are present (please see the attached screenshot).

**Comment by PCF-Testing** [comment]
No longer an issue. Closing.
