### ISSUE TITLE
Refactor Teams Signals/Notifications

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#466]
We should simplify how we handle notifications for teams.  Right now the system is:
- Whenever a component creates a new subtitle/language/team_video, it needs to emit the appropriate signal in in teams.signals
- teams.signals then handles the signal and sends a notification

This isn't really a good system for a few reasons:
- We need to remember to emit the signal whenever we create a new subtitle version.  This causes more coupling of components, when signals should cause less.
- There's lots of circular importing going on between teams.signals, teams.models, and teams.tasks.

Instead, we should replace it with a new system:
- Other components never have to emit signals from teams.signals.
- We create a module, maybe called teams.notifier, that's in charge of connecting to signals like post_save, and emitting the proper notification at that point.
- teams.signals becomes just a collection of signals, not handler functions.  A good example of this is the video_moved_from_team_to_team signal.

**Comment by PCF-Testing** [comment]
Working on this in different tickets. Closing.
