### ISSUE TITLE
TED Reports Disappearing Subtitles

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#467]
Dimitra @ TED reports: "Yesterday I approved Mr. Papandreou's subtitles in Greek and they are now published on TED.com However I cannot find the completed task on Amara in case changes are required."

I looked and saw that we had no record of greek anywhere, but that there were greek subtitles on TED.com. I've confirmed that the Greek subtitles are safe on the TED system, but we should still follow up on this.

Here's the video
    http://www.amara.org/en/videos/F90HkqY9RRRl/info/george-papandreou-imagine-a-european-democracy-without-borders/
    http://www.ted.com/talks/george_papandreou_imagine_a_european_democracy_without_borders.html

**Comment by PCF-Testing** [comment]
Marking as closed.
