### ISSUE TITLE
Empty lines in new editor produce a misleading 'Not all lines are synced' message

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#470]
When you are entering (or appending) subtitles through the new editor, pressing ENTER after the last meaningful line in your subtitles adds an empty line to the set.

After you are finished with all the syncing, you won't get "All lines are synced" because of that empty line, even if it (as well as all the other lines) has a proper start time and end time. All lines will count as synced only after this empty line gets some text (i.e. non-zero character count).

A similar thing happens when you insert an empty line in the middle of the set: you'll get the same misleading message "Not all lines are synced yet.", although the empty line automatically receives start and end time.

To help users understand what happens, we need to make separate checks for unsynced lines and for empty lines, and to display diagnostic messages for both cases. Possibly, if empty lines are present, we'll also want to return the user to 'Type what you hear' step.

**Comment by PCF-Testing** [comment]
We display "Subtitles cannot be blank" in this case. Closing.
