### ISSUE TITLE
Effects of automatic forking on dependent translations

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#490]
In i2369 - we've added some cases where we are going to fork translations.  When we do that - we want to keep as much relevant info as we can

re: https://docs.google.com/document/d/1FnxUwr8EiaTFa9O0B-mif4rzQgKJjOU-RY9PE3qcoss/edit

When we fork, we know what version child was based on. 

Copy extra subs/timing from the source version (before forking/upload) to the end of the dependent translation. 

Save new version, for the forked subtitles.

**Comment by jdragojevic** [comment]
closing as obsolete.
