### ISSUE TITLE
DMR: when submitting post-publish edits of dependent translations, check for completeness

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#491]
When a dependent translation which has already been published is being worked on, the number of lines in it may mismatch the number of lines in the source language. This can happen if the source language has been edited, too, with changing the number of lines.

Steps to reproduce:
1. Add a video to a moderating team, transcribe, review, publish.
2. Make a translation, review, publish.
3. Edit the transcript, inserting new lines. Submit.
4. Edit the translation, not filling the empty lines. Click Save and exit. The new version of the translation will get published with empty lines.

Expected: if it is a post-publish edit that goes public immediately, check the subtitle set for completeness. If there are untranslated lines left, do not submit. Instead, alert the user that there are untranslated lines remaining and prompt to finish the translation before saving. Or disable Save and Exit option, so that the users could only submit the final translation (which does check for completeness).

NB: this issue stems off the recent change which made all the post-publish edits go public immediately. Until then, Save and Exit would just save a draft for further editing.

**Comment by PCF-Testing** [comment]
DMR was completed long ago. Closing.
