### ISSUE TITLE
Billing: irregular billing records created on legacy subtitle sets

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#502]
Steps to reproduce:
1. Submit a video to the site (NOT to a team).
2. Subtitle.
3. Translate.
4. Add this video to a task-free team.
5. Make a minor edit to the transcript (e.g. change the time or a punctuation sign).

OBSERVED: TWO new billing records appear in the table on the admin side - for the transcript and the translation.

EXPECTED: TBD (either none, or one record for the set that got actually edited)

Example: http://prod-test.demo.amara.org/en/admin/teams/billingrecord/77/
http://prod-test.demo.amara.org/en/admin/teams/billingrecord/78/

**Comment by jdragojevic** [comment]
OBE ticket. closing.
