### ISSUE TITLE
Videos from hidden teams should not turn up in search results

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#506]
Video
http://www.amara.org/en/admin/videos/video/141958/
belongs to 
http://www.amara.org/en/admin/teams/team/137/
which is a hidden team; therefore, all its videos are not supposed to be visible to the general public who are not members of that team.

Yet, this video turns up in search results:
http://www.amara.org/en/search/#/?q=khartoum&video_lang=en&page=3
It shouldn't.

**Comment by PCF-Testing** [comment]
This has been fixed as part of video index work. Closing.
