### ISSUE TITLE
HTML and JS determine completeness display differently

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#509]
OBSERVED:

On Amara this video displays Japanese (a forked language) as 100%:
http://www.amara.org/en/videos/bTwjFBa50KES/info/3-colombianas-learn-english-at-ulearn/

When embedded, it displays Japanese with # of lines:
http://www.ulearn.ie/school-of-english-in-Ireland (second from bottom)

This seems to be because each context uses different logic:

The HTML page uses: https://github.com/pculture/unisubs/blob/production/apps/videos/templatetags/subtitles_tags.py#L46-L58

I think the widget uses: https://github.com/pculture/unisubs/blob/production/media/js/startdialog/videolanguage.js#L42-L60

**Comment by bendk** [comment]
Not relevant anymore
