### ISSUE TITLE
Popcorn support/functionality audit

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#512]
I'd like to develop a full picture of how much we're missing in Popcorn in order to have parity with the existing dialog/widget in terms of player/format support and functionality.

@margarita Can I ask you to please compile a list of all the players and formats we support in our existing dialog/widget? You can include ones that are partially supported too, just note them please.

@nicksergeant Maybe you can start by listing whatever detail you have about player interactions and whatnot, and what we have now vs what we have in Popcorn?

I'm sure @arthur will have thoughts to add at some point as well...

**Comment by syl22-00** [comment]
Proposing to close that.

**Comment by kslottow** [comment]
@syl22-00 @bendk should we close or repurpose this one?
