### ISSUE TITLE
Sort out the parameters returned by Subtitles API resource

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#513]
'title' and 'video_title' returned by Subtitles resource both return the title in the language of the subtitles. This is confusing; apparently, 'video_title" should be the title of the video in the last published subtitles in the original language.

Example:
GET /api2/partners/videos/x8LBe7dv7sv4/languages/es/subtitles/

{"description": "La descripcion Espanola", "language": {"code": "es", "name": "Spanish"}, "note": "", "resource_uri": "/api2/partners/videos/x8LBe7dv7sv4/languages/es/subtitles/", "site_url": "http://staging.amara.org/videos/x8LBe7dv7sv4/es/194784/", "sub_format": "json", "subtitles": [{"end": 2691, "meta": {"new_paragraph": true}, "position": 1, "start": 619, "text": "aaaa"}, {"end": 4835, "meta": {"new_paragraph": false}, "position": 2, "start": 2691, "text": "bbbb"}, {"end": 6907, "meta": {"new_paragraph": false}, "position": 3, "start": 4835, "text": "CCCC"}, {"end": 8958, "meta": {"new_paragraph": false}, "position": 4, "start": 6907, "text": "dddd"}], "title": "El titulo Espanol para Locarno Beach Park", "version_no": 2, "version_number": 2, "video": "New title for Locarno Beach", "video_description": "La descripcion Espanola", "video_title": "El titulo Espanol para Locarno Beach Park"}

**Comment by bendk** [comment]
video_title is no longer returned.

**Comment by PCF-Testing** [comment]
video_title is returned, but the value seems to be as expected.

Example:
https://amara.org/api/videos/tNE5imiv27uA/languages/uk/subtitles/
"title": "Як сходи непомітно впливають на ваше життя",
"video_title": "The hidden ways stairs shape your life"

So the issue appears to be resolved.
