### ISSUE TITLE
Private videos imported with YouTube Sync

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#515]
User on forum has reported that private videos from his channel were added to Amara. The videos are not visible, and clicking through the YouTube URL results in a page that states the video is private, however the titles and descriptions do get imported, and those might include sensitive information.

ex: http://www.amara.org/en/videos/r2FarycTFuBd/info/google-di-tu-jie-jing-fu-wu-zhi-chuan-yue-shi-kong-jian-dao-gui/

**Comment by PCF-Testing** [comment]
This is not known to happen at this time. Only public and unlisted videos get pulled in to Amara from linked YouTube channels. Closing.
