### ISSUE TITLE
Translation not showing up on video history

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#516]
Anna Cristiana Minoli is the translator into Italian of a TED talk, however, now she is assigned as the approver, but she doesn't show up in the video history for the video, instead, user Marco Latini is credited for 0% changes to the subtitles. 

There is no review history for this language translation, nor does Marco Latini show up in the task list, but according to his activity list, he has worked on it http://www.amara.org/en/profiles/profile/86777/

video: http://www.amara.org/en/videos/TR8HyBkKXWsT/en/488362/#revisions  

translation task completed by Anna  http://www.amara.org/en/admin/teams/task/248499/

I haven't seen this behavior before, any idea what may be causing this?

**Comment by bendk** [comment]
Lots of code changes since this one was filed.  I don't think it's useful anymore.
