### ISSUE TITLE
Video with two language instances on TED

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#518]
Two Polish versions created on video in TED Team

http://www.amara.org/en/videos/g2CMABeRPaNA/pl/520590/#revisions
http://www.amara.org/en/videos/g2CMABeRPaNA/pl/399814/#revisions

Polish for http://www.amara.org/en/videos/g2CMABeRPaNA/info/whats-invisible-more-than-you-think-john-lloyd/

Expected: only one of each language should be created for each video on the TED team

subtitles created by CapaGirl

**Comment by bendk** [comment]
This looks like pre-DRM.  I don't think it's relevant anymore.
