### ISSUE TITLE
Khan Language not showing on language list, marked as having no version

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#519]
Chinese Simplified is missing on Language List for video, although it exists on the Metadata tab, but is marked as not having a version. Searching on Admin shows there is a revision 0 and a subtitle page, and when selecting a new language to subtitle into, Chinese Simplified is marked as 100%. I edited subtitles and resubmitted, refreshing metadata afterwards but it was not successful in making subtitle reappear. 

http://www.amara.org/en/videos/sSFi1uQRXsiv/zh-cn/395493/#transcripts
http://www.amara.org/en/videos/sSFi1uQRXsiv/debug/
http://www.amara.org/en/videos/sSFi1uQRXsiv/info/napoleon-and-the-wars-of-the-first-and-second-coalitions/

**Comment by bendk** [comment]
This code has been changed several times.  I don't think this is an issue anymore.
