### ISSUE TITLE
Some of the languages imported from YT got marked as incomplete

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#525]
http://staging.amara.org/en/videos/XCfto33pcQIw/info/korean-sound-effects/

French and Korean got marked as incomplete, while the other languages are labeled as 100% done. Otherwise, there seems to be no difference between the languages.

Normally, CC imported from YT used to be labeled complete.

**Comment by PCF-Testing** [comment]
Subtitle import has changed significantly since this ticket was filed. Marking as closed.
