### ISSUE TITLE
Linking YT account to Amara user's account failed to push pre-existing subs

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#526]
Steps to reproduce:
1. Added a video to a YouTube account not linked to Amara.
2. As user B, submitted this video to Amara and subtitled into a few languages; at least one of the languages was completed.
3. Linked the YT account to the profile of user A on Amara.
4. Checked the YT video for captions - none was pushed.

http://staging.universalsubtitles.org/en/videos/OLu0KJCudjXj/info/la-cheminee/
http://www.youtube.com/watch?v=Jl1OwdRas9Q
User A - http://staging.universalsubtitles.org/en/profiles/profile/maggieManager/

**Comment by PCF-Testing** [comment]
Closing in favour of the newer ticket https://github.com/pculture/unisubs/issues/2456.
