### ISSUE TITLE
Subtitle bubble on timeline disappears when changing size

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#527]
When modifying the timing of a subtitle on staging or production by clicking and dragging the start and end points, there's a moment when it can disappear completely and not show up on the timeline at all, leading to confusion from users who no longer see the event. On the transcript it shows up as an event with start and end times at the same second. 
1. open any transcription task
2. get to syncing stage
3. move start timing towards the end of the video for an event, until it goes over the end timing arrow and then disappears. 

Video example at http://screenr.com/shd7

**Comment by kslottow** [comment]
this doesn't happen in the current editor, closing
