### ISSUE TITLE
Complete/Incomplete flag meaningless for translations

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#541]
As soon as we've stopped matching each line of the source with an equivalent line in translations, the value of IsComplete flag for translations has lost its former meaning and makes little sense in some use scenarios.

Consider the following common scenarios:

1) User makes a translation filling all the lines in the translation dialog and clicks Submit in the dialog; the translation is marked as complete -- that's OK, makes perfect sense.

2) User makes a translation filling all the lines in the translation dialog, exactly as in p.1, and clicks Save and Exit; the translation is marked as incomplete -- this may look weird to a third-party user who does not have an expert-level knowledge of the software, but might be still making sense to the author of the translation. Provisionally OK.

3) This is where the real fun begins. User makes a complete translation as described in p.1; then, the source language gets a few lines appended to it (which does not cause any forking by design). Guess what? The translation is still labeled as a translation from the modified language and is still marked as complete, which is, of course, not true.

4) A slightly different twist of p.3 -- user makes a complete translation as described in p.1; then she or someone else decides they are not quite happy with some lines in the translation and wipe them clean and save. The translation now has a number of empty lines--but is still wrongfully labeled as complete. 

Not sure whether we need to deal with this now, given that the old translation dialog is bound to go -- but if we do, it might be a good idea to check the number of lines in the source and translation when:
a) new lines are appended to the source (for most other edits, translations just get forked)
b) translation is changed and saved

**Comment by jdragojevic** [comment]
closing as obsolete.
