### ISSUE TITLE
DMR: translation dialog pre-loads the default description instead of approved one

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#543]
If the video description in the original language was changed during editing the transcript, so that the approved and published version has a description different from the default one, the translation dialog displays the published (new) version in boldface above the description editor and the default (old) one inside the description editor.

Steps to reproduce:
1. Add a YT/Vimeo video with a description to a moderating team.
2. Subtitle, editing the description, review, approve.
3. Start a translation. On screen 2 of the translation dialog, check the text inside and above the field for editing the description.

Expected: both text fragments should match the last published description in the original language.

**Comment by PCF-Testing** [comment]
Translation dialog is no longer in use. Closing.
