### ISSUE TITLE
Editor: hot keys should move the active edit box

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#550]
This is an often requested feature, by translators.

When you're editing text, up/down should act as hot-keys for moving up/down in the subtitles.

[subtitle 1]
[subtitle 2] *cursor is in here, editing*
[subtitle 3] 

In the above scenario, pressing the up arrow would move your editor cursor/focus from subtitle 2 to subtitle 1. Pressing down twice would cycle you down to subtitle 3. Pressing down again on subtitle 3 wouldn't do anything (if it's the final subtitle).

If there's a subtitle that has breaks in it or spans multiple lines, it'd be nice if the up arrow would navigate through the editable text, for example:

[subtitle 1 is short]
[subtitle 2
spans
many lines] *cursor is on bottom line*

Pressing the up arrow once would move the cursor up to the middle line of subtitle 2. Pressing up again would move to top line. Pressing up a 3rd time would move up to subtitle 1. This final request isn't critical, but is nice to have.

**Comment by PCF-Testing** [comment]
The editor now has navigation shortcut keys. Closing.
