### ISSUE TITLE
page not found clicking billing links

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#551]
I am getting this on prod-test 

Ran some billing reports for the coursera team: http://prod-test.demo.amara.org/en/admin/billing/

When I click the link in the ui - I get a page not found error.
ex:  http://prod-test.demo.amara.org/en/user-data/teams/billing/bill-coursera-prep-20130321-20130402-5.csv

**Comment by jdragojevic** [comment]
this is obsolete.  closing.
