### ISSUE TITLE
Editor: make new editor support NF videos

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#555]
Netflix uses forking heavily and so will need the new editor to accommodate the source and target languages on the same screen.

At this time, NF videos are not supported by the new editor (http://dev.amara.org/en/subtitles/editor/JXjngG0Vl6IX/en/; to get the permissions, impersonate user 'margarita'). I believe this should be put high on our priority list.

**Comment by PCF-Testing** [comment]
Marking as closed.
