### ISSUE TITLE
Editor: when a session expires, let the user try to resume or download their edits

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#557]
In the new editor, when a session times out and expires, the editor is closed completely and the video view is displayed. If any valuable edits have been made, they get irrevocably lost unless the user manages to resume the session in the short time period when the timeout warning is shown.

Expect: after the session expires and the lock on the language is released, keep the button "Try to resume your work" and the link for downloading the subtitles on the screen, similarly to how it is done in the conventional subtitling/translation dialogs.

**Comment by PCF-Testing** [comment]
Works as expected. Closing.
