### ISSUE TITLE
Editor display bug on Chrome/Linux

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#562]
When loading the new editor in Chrome 24.0.1312.56, the layout loads and then collapses into some weird scrollbar black hole:
http://www.youtube.com/watch?v=XzULJk2BC7M

In addition, the layout seems to exceed the viewport's width no matter what, so there's always a horizontal scrollbar.

**Comment by PCF-Testing** [comment]
This no longer seems to be an issue. Closing.
