### ISSUE TITLE
coding visible on upload confirmation screen

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#565]
User aliaksandr Autayeu reports that after uploading draft on moderated team,  instead of usual "... successfully"  he saw: 

(1062, "Duplicate entry '312220-2' for key 'videos_subtitleversion_language_id_75f11ee52cd2297e_uniq'")

the subtitle was uploaded, but two revisions were created, the second with 0% changes in either timing or text. 

http://www.amara.org/en/videos/2fZLiR6Idi0O/ru/312220/384408/#revisions

expected:  code should not be visible on user end dialog, and uploads should only generate one revision.

**Comment by bendk** [comment]
Not an issue anymore.
