### ISSUE TITLE
Hide Share panel with social network sharing tools for private videos

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#566]
For private teams, Share panel is not displayed. Example: http://staging.amara.org/en/teams/netflix/

However, videos from private teams (which are supposed to also be private) do have such a panel on the video page -- http://staging.amara.org/en/videos/c3weS91GKS9K/info/netflix-iphone-app-video/. It appears that they shouldn't -- but Get Embed Code link might still be needed if some partners with private teams plan to use offsite embedding.

**Comment by bendk** [comment]
We've updated this view code many times, as far as I know it's not a new issue.
