### ISSUE TITLE
Activity lists on the personal dashboard should be expandable

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#568]
Activity logs related to the user's videos/teams are limited to 8 entries each. Both logs should be expandable to the full length ("View all activity"), since 8 are not enough to cover even certain one-time actions, such as importing subtitles in multiple languages from YouTube or a team admin approving a huge number of applications,

**Comment by bendk** [comment]
This now have a pager.

**Comment by PCF-Testing** [comment]
They don't. The issue is about http://www.amara.org/en/profiles/dashboard/ (although this whole page is basically unfinished work, and I am not sure anyone actually uses it).

**Comment by bendk** [comment]
That makes sense.  So how should we allow users to view more activity?  Should link to the activity page?

**Comment by bendk** [comment]
We updated this page to make it paginated a while ago.
