### ISSUE TITLE
Subtitles unable to be resumed after converting timing and left idle, changes not saved

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#569]
today on Netflix N team: 

User converts subtitles, changes some of the syncing, gets interrupted and  if they are idle too long and it says do you want to resume work, they click yes - it doesn't work
that dialog box just hangs on the screen and then their changes don't seem to be saved.

expected: after remaining idle, file should save, and when they click on resume, it should take them back to the interface to continue their work. 

URL: http://www.universalsubtitles.org/en/videos/nrPIJJf3VOmu/nb/454694/#revisions

example of screen and file downloaded, but not saved on Amara.

**Comment by bendk** [comment]
This one is so old, it's probably fixed, and if not this report is not useful for fixing the issue today.
