### ISSUE TITLE
Play video here link on transcripts restarts video or skips to end.

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#570]
hovering over lines in a transcript, a note popus up saying "play video here". Clicking on timing does not affect where the video is playing for some videos, and in others it takes user to the end of the video.

Expected:
Clicking on the play video here areas of the transcript should move video to that point in the timeline and play it. 

examples: 
http://www.universalsubtitles.org/en/videos/fHT7SnWWjSVB/fr/251632/  video restarts after clicking on any transcript line. 

http://www.universalsubtitles.org/en/videos/AYbHRuftABux/fr/459021/  video skips to the end of the video after clicking on any other line. 

reported through forum  http://pculture.freshdesk.com/categories/6573/forums/28027/topics/9768?page=1#posts-19212

**Comment by bendk** [comment]
I think this got fixed when Sylvain overhauled the transcript viewer.
