### ISSUE TITLE
Production peformance impact (TED)

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#579]
On Oct. 29 at around 4p EDT, I noticed a degradation in performance.  Load times were almost 40 seconds at the worst.  I activated the NewRelic agent on one of the application servers to see what was happening.  About 54% of the utilization was from history views and calls to the API, with 20% hitting the TED resource.  After discussing with Arthur, this is a known issue as there is little to no caching on the API and TED is known do do a massive data fetch periodically.  Attached are the NewRelic screenshots.

If needed, I can activate the NewRelic agent again.

**Comment by bendk** [comment]
Really old and not actionable anymore.
