### ISSUE TITLE
Translation task for a forked language cannot be resumed after saving

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#580]
Steps to repro:
1. Start performing a translation task.
2. Translate and click Convert to Timed Subtitles link (you need to have the permissions to subtitle to do that).
3. Make a few timing edits, add extra lines, etc.; then click Save and Exit.
4. When resuming the task, there will be no option to translate Directly from video. Instead, you will be prompted to translate from one of the available languages starting from scratch.

Example: http://staging.universalsubtitles.org/en/teams/t-win/tasks/?lang=fi&assignee=me

**Comment by PCF-Testing** [comment]
Obsolete issue - marking as Closed.
