### ISSUE TITLE
Diffing tool marking identical lines as different

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#585]
Situation:
Comparing two revisions, the system marks in red those lines which are different, but it is also marking identical lines in red. 

Expected result:  The only lines in red should be those that were changed in content or timing from one revision to the next.  

Actual result: both different and identical lines are being marked in red. 

Example:
http://www.universalsubtitles.org/en/videos/diffing/246100/240407/

actually different lines are:
0:54-0:57
0:57-1:01
1:01-1:06
10:41-10:44
13:46-13:50
but several other lines are also shown in red:
1:24-1:30
6:54-6:57
6:57-7:00
7:29-7:33
7:33-7:35
7:35-7:38

Downloading the .srt files and comparing them showed that the lines in the second group are all identical: no timing changes or text changes at all. Revision 9 was changed in Amara, revision 10 was uploaded. 

Via IRC Maggie said it  could be due to the diffing tool not being able to deal with uploads. 

Reported by Yasushi Aoki 

http://pculture.freshdesk.com/helpdesk/tickets/3100

**Comment by PCF-Testing** [comment]
We have revamped the diffing page since. Closing.
