### ISSUE TITLE
Uploading a translation from a language not labeled as Original fails

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#586]
Steps to reproduce:
1. Submit a video.
2. On the video view, click Upload Subtitles link.
3. Select two different languages as the primary spoken language of the video (Language 1) and the language of the uploaded file (Language 2). Commit the upload, wait for it to finish, reload the page.
4. Again, click Upload Subtitles link. Select to upload subtitles in Language 3, translated from Language 2. Proceed with uploading. Reload the page and make sure via Debug page that 0 lines have been uploaded and that Language 3 is labeled as translated from None.

Example: http://staging.universalsubtitles.org/en/videos/GEup6YXafuBW/debug/

**Comment by bendk** [comment]
Pretty sure this one is old and not happening anymore.
