### ISSUE TITLE
Add a custom "offsite" or "origin" field to TeamVideo

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#596]
Basically, the idea here is to allow clients/partners to link back for example to the video record in their CMS or wherever. Because we want to start pushing client-specific functionality back onto clients to implement, we need to have ways to make it easy for management to happen across platforms.

E.g. TED might have a way to override crediting on their side. So it should be easy on our side when you're looking at a video to say "Oh we should change this" and be able to easily jump to the video in their CMS.

**Comment by PCF-Testing** [comment]
Marking as closed.
