### ISSUE TITLE
Translation tasks not blocked when the transcript is unpublished

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#599]
https://staging.universalsubtitles.org/en/teams/t-win/tasks/?team_video=17218

Added video to a moderating team > transcribed and published the transcript > translated a few languages > unpublished the transcript.

Expected: tasks that cannot be executed should be locked until the transcript is approved and published.

**Comment by PCF-Testing** [comment]
We do not have Unpublish button anymore. Closing.
