### ISSUE TITLE
Replace Arrow Left link in subtitle view with a text link (Back to main video page)

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#602]
The &lt;--  link is not displayed when the video title is in an RTL language (example: https://staging.universalsubtitles.org/en/videos/LpxV7Q8LjoQz/he/325024/).

Please replace it with a text link "Back to main video page", so that we don't have to bother with LTR/RTL language positioning here, and the link becomes friendlier to end users.

**Comment by bendk** [comment]
Pretty sure this has been fixed.

**Comment by bendk** [comment]
Actually, this is still an issue, but we're switching to the futureui version of this page soon, so let's not put in work to fix it.
