### ISSUE TITLE
Subs getting published instantly through API.

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#608]
link to video: https://dev.universalsubtitles.org/en/videos/JlKqWhNR7wqV/info/wicked-tuna-biggest-fish-of-the-year/

During creating subtitle through API, get few cases (team has the same settings as T-rial):
1. Owner, created Engl. subtitles. 
Result: Subtitles get published. No any task created
note: Sign on the video image in video menu ‘1 language (no completed languages)’
2. Owner updated Engl. subtitles. 
Result: Subtitles get published. No any task created
3. Contributor, tried to change Engl. subtitles. 
Result: couldn’t change engl. subtitles (It's OK)
4. Contributor, created French subtitles. 
Result: Subtitles get published. No any task created
note: Sign on the video in video menu changed to ‘No subtitles yet’, but this video has Engl. and Fr subtitles.
5. Contributor updated Fr. subtitles. 
Result: Subtitles get published. No any task created
note: Sign on the video in video menu changed to ‘2 languages (no completed languages)’.

**Comment by bendk** [comment]
This is a really old issue that I don't think is happening anymore.  In any case, it doesn't seem useful, so let's close it.
