### ISSUE TITLE
"vt not defined" error with two URL's for the same video

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#609]
Steps to reproduce below.

On staging:
1) Add a video to a team with the url: https://c264153.ssl.cf1.rackcdn.com/talk/transcript/2012/None/JohnHockenberry_2012-transcript.mp4

2) Go to that video on the team, click the "URL" tab, and click "add new URL"

3) Add the following URL: http://video.ted.com/talk/podcast/2012/None/JohnHockenberry_2012-480p.mp4

4) Click the video tab and get the message "vt not defined"

5) This is fixed if you click "edit video" on the admin menu at the bottom of the page, and delete the original URL.

**Comment by bendk** [comment]
This is really old and the code has been updated a lot.  I don't think it's useful at this point.
