### ISSUE TITLE
Search on Team Videos page incorrectly processes non-ascii queries

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#610]
Compare
https://staging.universalsubtitles.org/en/teams/t-win/?assignee=&lang=&q=qwerty
vs.
https://staging.universalsubtitles.org/en/teams/t-win/?assignee=&lang=&q=%D0%B9%D1%86%D1%83%D0%BA%D0%B5%D0%BD
(both queries ought to yield "Sorry, no videos found...").

A meaningful non-ascii query should return the list of results.

**Comment by PCF-Testing** [comment]
Seems to work now. Closing.
