### ISSUE TITLE
"Your work cannot be saved" error message, yet work is actually saved

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#613]
==FD Ticket==
- http://pculture.freshdesk.com/helpdesk/tickets/1765

==Amara URL==
- Revisions Page: http://www.universalsubtitles.org/en/videos/ca17f1c85ecdeaebd6b7619588adafa7ba15fe7f/nl/329123/
- Admin page for tasks for the talk, sorted by language: http://www.universalsubtitles.org/en/admin/teams/task/?q=Hans+Rosling%3A+Religion+and+babies&ot=asc&o=5

==What's happening==
- Translators are going through the translation UI entirely, getting an error message that work was not saved, when in fact the work does become saved.
- The translators that have submitted this ticket are experienced (one is an LC) so I trust them when they say the 100% complete the translation. 

==Steps to reproduce (according to the translator that sent the ticket in)==
1) Click "perform task" on translation task.
2) Complete the perform task, and complete both step 1 and step 2 of the translation interface.
3) Click "Done?: Submit final translation"
4) Receive "Your work cannot be saved" error message.
5) Check revisions history, and find that your work was actually saved.

**Comment by PCF-Testing** [comment]
This does not seem to be happening anymore. Closing.
