### ISSUE TITLE
Robustness when DB is unavailable

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#619]
Similar to i167, serve simple static content and/or maintenance page when this condition occurs:

[Sat May 12 15:49:44 2012] [error]   File "/var/www/universalsubtitles/env/lib/python2.6/site-packages/MySQLdb/**init**.py", line 81, in Connect
[Sat May 12 15:49:44 2012] [error]     return Connection(_args, *_kwargs)
[Sat May 12 15:49:44 2012] [error]   File "/var/www/universalsubtitles/env/lib/python2.6/site-packages/MySQLdb/connections.py", line 187, in **init**
[Sat May 12 15:49:44 2012] [error]     super(Connection, self).**init**(_args, *_kwargs2)
[Sat May 12 15:49:44 2012] [error] OperationalError: (1040, 'Too many connections')

**Comment by bendk** [comment]
Too many connections is not happening anymore, no need to fix this.
