### ISSUE TITLE
Improved grouping of errors on sentry

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#625]
Sentry groups errors by the exception type and message. 

This means that a lot of the same actual problems get split up on separate groups. For example:
http://d.pr/i/5GlR

You can see that the 2nd, 4th and 5th errors are actually the same problem.
While it's impossible to really fix this, we could do something smart. We could group by a combination of function / and exception type.

This would make grouping much more reliable and easy to grok.

**Comment by PCF-Testing** [comment]
Closing.
