### ISSUE TITLE
64kb, 256kb MP4 (archive.org) video playback problem

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#629]
Expecting result:
Player has to playback MP4 (64kb, 256kb, 512kb) video files from archive.org.

Actual result:
1. Player playbacks MP4 (512kb) video file with no problems from archive.org.
2. Player has a problem to playback MP4 (64kb and 256kb) video files from archive.org. It has only sound stream, and no video stream.

links:
https://dev.universalsubtitles.org/en/videos/5gREEeifHM4d/info/#video - 512kb, works fine
https://dev.universalsubtitles.org/en/videos/TE0EYjfnno1k/info/ - 64kb, no video
https://dev.universalsubtitles.org/en/videos/Ln5tJfWjm4Kd/url/31584/#video - 256kb, no video

links to original files:
http://archive.org/details/WILDJUNG2001

http://archive.org/download/WILDJUNG2001/WILDJUNG2001_512kb.mp4
http://archive.org/download/WILDJUNG2001/WILDJUNG2001_256kb.mp4
http://archive.org/download/WILDJUNG2001/WILDJUNG2001_64kb.mp4

**Comment by kslottow** [comment]
this looks old @PCF-Testing @bendk can we close?

**Comment by PCF-Testing** [comment]
I think yes. The lower res videos do not even play in the editor, so this hardly is a problem with Amara.
