### ISSUE TITLE
Weird "started" entries in activity logs on overwriting the transcript for a video

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#634]
When the transcript (original language) for a video is overwritten by an uploaded file, "started language" entries are created in activity log for 0 line long translations.

Examples:
http://www.universalsubtitles.org/en/videos/YALRx6cu6ihu/info/Dominance%20/#activity
https://staging.universalsubtitles.org/en/videos/SqawJLxidLfy/info/#activity

Steps to repro:
1. Add a video to a team (a mock-up of Stanford in my case).
2. Subtitle and translate to create a few tracks.
3. Start a couple of more translations without saving; this will create zero-line translations that won't be shown on the video view. On Debug page, check that these translations are listed.
4. Overwrite the original language with the attached empty file. This will fork the proper translations (with appropriate records in the activity log) and create "started" entries for zero-line translations.

Solution: do not create "started" entries for zero-line translations - this may confuse and even frighten users.

**Comment by bendk** [comment]
I don't think this is still an issue.  If it is, can someone give an update and some more info on how we can start tackling it?
