### ISSUE TITLE
API ignores custom metadata for submitted videos from YouTube, Dailymotion

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#642]
For some videos from external providers, API ignores the custom values of title and description provided with HTTP POST request and fetches the values from the provider.

This was the case for YouTube video:

http://staging.universalsubtitles.org/en/videos/PNvpQFBbLzvt/info/Carving%20Ski%20Lesson/
{"video_url":"http://youtu.be/IcGaXRQ7l4Q", "title":"Carving", "description":"ski lesson"}
{"all_urls": ["http://www.youtube.com/watch?v=IcGaXRQ7l4Q"], "created": "2011-12-27T05:41:22.148621", "description": "ski lesson", "duration": 132, "id": 

"PNvpQFBbLzvt", "languages": [], "original_language": null, "resource_uri": "/api2/partners/videos/PNvpQFBbLzvt/", "site_url": 

"http://staging.universalsubtitles.org/videos/PNvpQFBbLzvt/info/", "thumbnail": "http://i.ytimg.com/vi/IcGaXRQ7l4Q/3.jpg", "title": "Carving", "video_url": 

"http://www.youtube.com/watch?v=IcGaXRQ7l4Q"}

And for Dailymotion video:

http://staging.universalsubtitles.org/en/videos/oACkf9IhYxHp/info/The%20Hobbit%20Trailer/
{"video_url":"http://www.dailymotion.com/video/xn5884_the-hobbit-trailer_shortfilms#rel-page-under-2", "title":"Hobbit", "description":"Film trailer"}
{"all_urls": ["http://dailymotion.com/video/xn5884"], "created": "2011-12-27T05:58:41.183836", "description": "Film trailer", "duration": null, "id": "oACkf9IhYxHp", 

"languages": [], "original_language": null, "resource_uri": "/api2/partners/videos/oACkf9IhYxHp/", "site_url": 

"http://staging.universalsubtitles.org/videos/oACkf9IhYxHp/info/", "thumbnail": "http://static2.dmcdn.net/static/video/801/578/38875108:jpeg_preview_large.jpg?

20111221072257", "title": "Hobbit", "video_url": "http://dailymotion.com/video/xn5884"}

For Vimeo or OGG Wikimedia videos, this didn't seem to be a problem.

**Comment by kslottow** [comment]
please check is this is still an issue. Thanks!

**Comment by PCF-Testing** [comment]
Works well now. Marking as closed.
