### ISSUE TITLE
Subtitles not displayed by YouTube HTML5 video player

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#645]
Steps to reproduce:
1. In FF or Chrome, disable Flash.
2. Navigate to www.youtube.com/html5 and click "Join the trial" link at the bottom of the page (unless you have already joined the trial).
3. Open a page with an embedded YouTube video with subtitles.
Examples:
http://www.universalsubtitles.org/en/pagedemo/blog_youtube_embed
http://maggie.mirocommunity.org/webm/
4. Play the video. Subtitles will not be displayed on the screen.

**Comment by bendk** [comment]
I'm pretty sure this is working now.
