### ISSUE TITLE
troubleshoot playback test failures on dev server

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#647]
For ages now - the pagedemo playback tests fail when run on the dev server, but are successful when run locally.

Did some checking, and reason the tests fail is that playback never actually starts as it should.  Confirmed w/ a screenshot via webdriver.

So either there's something that makes the javascript command that starts playback not work - or there's is something wrong with the flashplayer not starting play back, I noticed that it never starts running, as it does on my local machine.

These are pretty important tests - and are generally useless if we don't have reliable results on the nightly test runs.

**Comment by bendk** [comment]
Not sure what this one is about, but it's very outdated.
