### ISSUE TITLE
Beginner speed mode not functioning with Vimeo videos

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#653]
Steps to reproduce:
1. Open a Vimeo video onsite or offsite (e.g. http://staging.universalsubtitles.org/en/videos/p2oXRzMHqhrG/).
2. Click Edit Subtitles button.
3. In the subtitling dialog, make sure Beginner speed mode is selected.
4. Start playback in the subtitling dialog. It won't stop after 8 seconds, as expected.

**Comment by bendk** [comment]
@pcf-testing is this still an issue?  If so, let's schedule it.  If not, let's close.

**Comment by PCF-Testing** [comment]
Works in the current editor. Marking as closed.
