### ISSUE TITLE
Team view changes when zoomed in or out

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#667]
When I zoom out of Amara team views (anything less than 100%), the content stacks up, when I zoom back in it goes back to normal.  

This also used to happen with my old netbook on a much smaller screen, I thought it had to do with my small screen size, but on a 15 inch monitor the issue remains. Dean also tried this out with the same results. 

I'm on Chrome, Windows 7.

**Comment by bendk** [comment]
This is for the old-style team UI.  Let's close it and focus and making futureui ready.
