### ISSUE TITLE
Issues from clicking "restart this step"

### ISSUE THREAD

**Issue by ehazlett** [pculture/unisubs#673]
On Staging
1. Performing a review task with subtitle overlaid on video
2. Make changes to timing through small arrows for start times
3. Click on "Restart this step"
   Result: Subtitles are no longer overlaid on video, but subtitles scroll through.

Can click on X and exit discarding changes, then reopen task and subtitles are once again overlaid.
1. Performing a translation task that was previously "save and exited" at the final stage
2. Make changes to timing through arrows for start times on syncing step
3. Click on "Restart this step"
   Result: Subtitles are no longer synced despite previous save and exit that included this step. 
   Expected result: changes made since last save should disappear, but not the original syncing.

**Comment by PCF-Testing** [comment]
This one is for the legacy editor. Closing.
