### ISSUE TITLE
Video tab titles should match video page titles

### ISSUE THREAD

**Issue by deanjansen** [pculture/unisubs#691]
I renamed these videos in the admin console and the new names aren't reflected on the videos tab of the team (although they are reflected on the video page).

A) video tab should say same thing as the video page
B) admins/owners should be able to change video title

![screen shot 2013-07-12 at 7 06 04 pm](https://f.cloud.github.com/assets/216145/791520/72e928c2-eb48-11e2-8b59-a28600e07f4e.png)
![screen shot 2013-07-12 at 7 11 43 pm](https://f.cloud.github.com/assets/216145/791521/762f0718-eb48-11e2-9dd0-7df107b27fbd.png)

**Comment by bendk** [comment]
As far as I know this stuff is working okay.  I'm going to close this one, but please re-open if there still is an issue.
