### ISSUE TITLE
ssa output subs don't include linebreaks

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#692]
Download multi-line subtitles in ssa format.

Resulting output subtitles do not include linebreaks and the lines are squashed together.

Ex:

upload srt: 

<code>99:59:59,999 --> 99:59:59,999
this is line 1
this is line 2</code>

output ssa:
<code>Dialogue: 0,9:59:59.99,9:59:59.99,Default,,0000,0000,0000,,this is line 1this is line 2</code>

Recognized linebreak tag for ssa is \n.  See http://aegisub.cellosoft.com/docs/ASS_Tags

**Comment by franontanaya** [comment]
Bumping this due to the inquiry about Advanced Sub Station Alpha support. The line break needed is literal \N with capital N. \n won't work or it'll be mistaken with the line break control character.

**Comment by bendk** [comment]
This was a really simple fix, I tested with VLC and the newlines work.  I'm just going to push it directly to dev.  It'll get to staging/production with our next deploy.

**Comment by PCF-Testing** [comment]
I don't see this work either on dev or on staging. Tested by downloading and checking SSA subtitles from:
https://dev.amara.org/en/videos/WHxkeEcrDUeS/en/8/
https://staging.amara.org/en/videos/39Bt6wdBpRXD/en/813206/

The downloaded subtitles don't have line break symbols in them.

**Comment by bendk** [comment]
I only deployed to dev, and the build failed there because of the DB issue.  I think it should be working now, I just tested with that link on staging and it looked good to me.

**Comment by PCF-Testing** [comment]
Confirming SSA files are downloadable with \N separator for like breaks.

Uploading subtitles from SSA files, however, does not honor the separator. Subtitles are uploaded as shown on the screenshot below:

![screenshot from 2018-04-20 03 24 25](https://user-images.githubusercontent.com/288455/39046260-6bded774-444a-11e8-8362-9c31590729c1.png)

Will we fix that as well?

**Comment by PCF-Testing** [comment]
Verified.

**Comment by PCF-Testing** [comment]
Deployed.
