### ISSUE TITLE
Keyboard shortcuts should use CMD on osx.

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#782]
This works for many shortcuts, but a couple could be broken:

- `CMD + SHIFT + .`
- `CMD + SHIFT + ,`
- `CMD + Enter`

We should make a general system in the code for Ctrl/Cmd shortcuts so that this is unlikely to happen with other ones.

**Comment by bendk** [comment]
I'm not sure what Command + Enter is supposed to do, but the other 2 should seek the video and they indeed only work with Ctrl, not Cmd.

**Comment by PCF-Testing** [comment]
@bendk: I cannot think of a way to test this without MAC computer and keyboard. How about I just pass it and we ask someone among the test group of users to give it a try?

**Comment by bendk** [comment]
Sounds good to me.

**Comment by PCF-Testing** [comment]
Deployed.
