### ISSUE TITLE
Ted is not getting reviewers in their API responses

### ISSUE THREAD

**Issue by bendk** [pculture/unisubs#792]
Alex made this gist with the our response data and no reviewers are listed for several videos.

https://gist.github.com/alexdean/08ba06e3d8040afdf67d

Janet says that we have reviewer info in the tasks associated with these languages.  However, I checked the subtitle metadata and there was no reviewer set there.

Janet's theory, is that these were submitted when we were having post-dmr issues and saving tasks was messed up.  That certainly sounds correct to me.

I think the solution is to manually go into the DB and set the reviewer/approver info.  Probably the easiest way is for me to do it with the django shell.

**Comment by PCF-Testing** [comment]
@bendk: This one looks obsolete, since we are switching to a different method of evaluating credits. Is it OK to close this one?

**Comment by bendk** [comment]
Agreed.  Closing.
