### ISSUE TITLE
Some languages messed up, not selectable from widget menu

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#802]
Consider http://www.amara.org/en/videos/1JeMDQ7uLtr4/info/fatmagulun-sucu-ne-27bolum-part-1/, which has a couple of dicey things about it:
- What is labeled as Turkish and Esperanto in reality is not either of these languages, but English. These languages are rather old, so it is hardly an oversight.
- It is impossible to select English, British from the widget menu in the video view -- the menu returns back to the primary audio language, which is Turkish.

Could anything get messed here in the course of DMR? 

Updating the video's metadata does not help here.

Other instances of  a similar problem have been reported; I have fixed one by deleting the troublesome language via UI and re-uploading it from a backup.

**Comment by bendk** [comment]
At this point, I don't think there's anything we can do here.
