### ISSUE TITLE
Always pushing to youtoube has failed.

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#806]
There isn't much of an error message here:

https://sentry.amara.org/amara/amaraproduction/group/8307/

But this error was shown in sentry when I attempted to manually sync this video:

http://www.amara.org/en/videos/n8PjGA8yNH8E/debug/

from the debug page.

```
filename    models.py

funcName    youtube_sync

lineno  72

message     Always pushing to youtoube has failed.

module  models

pathname    /opt/apps/production/unisubs/deploy/../../unisubs/apps/accountlinker/models.py

process     5686

processName     MainProcess

thread  140470939555584

threadName  MainThread

video   n8PjGA8yNH8E

vurl    616368L
```

**Comment by PCF-Testing** [comment]
Syncing has undergone multiple changes since this ticket was filed, so this report is outdated. Marking as closed.
