### ISSUE TITLE
Overlapping timings shouldn't be allowed

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#813]
There's some circumstance under which it is possible to make the end time of a subtitle to overlap the start time of the next one.

The only circumstance when this would be allowable is when both subtitles are displayed at different parts of the screen. But, until that is being determined, no timings should overlap at all. Otherwise subtitles will overlay each other during a fraction of the time.

**Comment by bendk** [comment]
I think #2588 covers this one better, let's use that.
