### ISSUE TITLE
A number of TED users cannot sign in to Amara

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#823]
If the first and/or last name in the user profile on TED.com exceed a certain length (which seems to be around 18 characters), an attempt to sign in to Amara.org with the use of TED button results in an error. 

Example (with a fictitious username):
First name: Abuhasan Abracadabra
Last name: Abcdef
Such a user cannot log in. However, Abuhasan Abracadab Abcdef does not have such a problem.

Expected: in real world, some names can exceed this limit. Could it please be raised higher to whatever is possible? My understanding is that Amara usernames must be 30 characters long or less, so this may be a factor here, but otherwise being able to 20-25 char long names would be great. Thank you!

**Comment by syl22-00** [comment]
One issue I saw is when users had long names on TED, it would fail creating an amara account because `full_name` gets over the `max_length` (63 characters). So I changed it to strip the characters above the limit to generate the full name.

**Comment by syl22-00** [comment]
On branch gh-unisubs-823

**Comment by PCF-Testing** [comment]
Got the following exception after clicking TED button on Sign Up page:

TypeError at /unisubservicesauth/ted_login_done_confirm/
unsupported operand type(s) for +: 'NoneType' and 'NoneType'
Request Method:	GET
Request URL:	http://unisubs.example.com/en/unisubservicesauth/ted_login_done_confirm/?next=%2Fteams%2Fted%2F&email=&sso=3sE8rqQrqbCT8aMxX4xDejiy0jPn1h9S9Rt4HX_4EGAjcOP9x_tMtAh0OolpEiP7FwjlpzS9E45CZ2lnAP9bs-7jxrT4c7n7ngUhGGlC4-Uvw6gZrSztXnGhDamSShvVnTfnw4lJXk21gzoK8UWvDsL4FcPQPQJUDlwt7SIhc7-h4AzY3DXl1c7cuCoqxH_49QUn5FBamD_2ocLy9Sk31g%253D
Django Version:	1.4.21
Exception Type:	TypeError
Exception Value:	
unsupported operand type(s) for +: 'NoneType' and 'NoneType'
Exception Location:	/opt/apps/amara/utils/multipass.py in __init__, line 18

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/amara-enterprise/servicesauth/views.py" in ted_login_done
  37.         (existing, email) = TEDAuthBackend.pre_authenticate(sso_token)
File "/opt/apps/amara/amara-enterprise/ted/auth_backends.py" in pre_authenticate
  87.         mp = multipass.MultiPass(TED_SITE_KEY, TED_API_KEY)
File "/opt/apps/amara/utils/multipass.py" in __init__
  18.         self.secret = hashlib.sha1(api_key + site_key).digest()[:16]

Exception Type: TypeError at /unisubservicesauth/ted_login_done_confirm/
Exception Value: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

**Comment by PCF-Testing** [comment]
OK, the previous exception was caused by the lack of TED API key in the dev_local_settings. After fixing that, the following exception is raised:

EVPError at /unisubservicesauth/ted_login_done_confirm/
wrong final block length
Request Method:	GET
Request URL:	http://unisubs.example.com/en/unisubservicesauth/ted_login_done_confirm/?next=%2Fteams%2Fted%2F&email=&sso=3sE8rqQrqbCT8aMxX4xDejiy0jPn1h9S9Rt4HX_4EGAjcOP9x_tMtAh0OolpEiP7FwjlpzS9E45CZ2lnAP9bs-7jxrT4c7n7ngUhGGlC4-Uvw6gZrSztXnGhDamSShvVnTfnw4lJXk21gzoK8UWvDsL4FcPQPQJUDlwt7SIhc79UprGqkhJCiJa-6fchx6EyrVA-rBFPbaY6PVK9Bku9NQ%253D
Django Version:	1.4.21
Exception Type:	EVPError
Exception Value:	
wrong final block length
Exception Location:	/usr/lib/python2.7/dist-packages/M2Crypto/EVP.py in final, line 128

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  109.                         response = callback(request, *callback_args, **callback_kwargs)
File "/opt/apps/amara/amara-enterprise/servicesauth/views.py" in ted_login_done
  37.         (existing, email) = TEDAuthBackend.pre_authenticate(sso_token)
File "/opt/apps/amara/amara-enterprise/ted/auth_backends.py" in pre_authenticate
  88.         obj = mp.decode(sso_token)
File "/opt/apps/amara/utils/multipass.py" in decode
  60.         v += aes.final()
File "/usr/lib/python2.7/dist-packages/M2Crypto/EVP.py" in final
  128.         return m2.cipher_final(self.ctx)

Exception Type: EVPError at /unisubservicesauth/ted_login_done_confirm/
Exception Value: wrong final block length

**Comment by syl22-00** [comment]
This should be fixed in gh-823 and gh-unisubs-823

**Comment by PCF-Testing** [comment]
Looks good, except for a minor issue - pre-populated field on Set New Password page.

**Comment by PCF-Testing** [comment]
Deployed.

**Comment by PCF-Testing** [comment]
Still breaking after the fix has gone live.
User: https://www.ted.com/profiles/5621768
Details are available in FD ticket 83474.

**Comment by syl22-00** [comment]
@PCF-Testing do you know if we still have an issue here?

**Comment by PCF-Testing** [comment]
No new incidents have been reported for quite a while. Marking as closed.
