### ISSUE TITLE
Forbidding users to submit when there's blank lines causes confusion

### ISSUE THREAD

**Issue by franontanaya** [pculture/unisubs#857]
Typical scenario we are facing a lot:

Translator creates a translation from English SDH. They have to remove some tags as per guidelines, leaving some lines blank. They try to submit, the app refuses to save the subtitles because there's "untranslated" subtitles (which is false) and they run to support to get help.

_Suggested behaviour_

Save succeeds, subtitle is marked as incomplete (the blank lines should be deleted), a warning message about **blank lines** is displayed.

**Comment by bendk** [comment]
I think our current behavior is pretty good:
  - We don't allow a endorsing, but we do allow save draft
  - We display a warning explaining why.
