### ISSUE TITLE
Expose Project Description in team UI

### ISSUE THREAD

**Issue by darren-bridenbeck** [pculture/unisubs#865]
Right now, if you create a description for a project in a team, that text doesn't appear anywhere on the team UI.

I'm not certain what the best UI choice would be, for exposing this information. . . what if:

1) Click a project in the left-panel of a team
2) Between the team description and the Bold heading "Projects" the following would appear:
- Bold text saying "You're viewing videos in [name of project]"
- The description of the project

Take a look at the screenshot below:

![untitled drawing](https://f.cloud.github.com/assets/5092242/1003179/54dcd1c0-0a89-11e3-9234-09134376b1fd.jpg)

**Comment by bendk** [comment]
Looks like there's nothing to do here.
