### ISSUE TITLE
Expired and declined tasks stop getting auto-assigned properly

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#872]
Normally, for a moderated video sent back and re-submitted tasks should go to the translator, reviewer, or approving manager who performed a similar task on this language before. However, this breaks in the case of tasks expired or declined in the course of this work and taken by another user.

Steps to reproduce (I could reproduce this on staging):
1. Pick a review task for TED team. Review and submit.
2. As an approving manager, send back.
3. As the reviewer, edit and decline.
4. As yet another user, pick the review task, edit and submit. The task will not go to the approving manager who worked on it previously in p.2.

A real-life example from production:
http://www.amara.org/en/videos/1lIDsnsLfT0O/info/camille-seaman-photos-from-a-storm-chaser/
(Portuguese language had multiple reviewers, and did not get automatically assigned to the correct LC for approval.)

**Comment by bendk** [comment]
I don't think we want to contintue to fix tasks bugs.  Let's close this one.
