### ISSUE TITLE
'Discard changes and exit' in Review/Approve dialog does not discard changes

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#880]
Changes made during a review session get stored in the browser cache and do not get discarded when a user clicks [X] button and then chooses to click 'Discard changes and exit'. During the next session in the same browser these changes will be loaded into the dialog.

Steps to reproduce:
1. Start an Approve Translation task.
2. Make a couple of changes to the text.
3. Let the session continue long enough for browser cache to get saved (a couple of minutes should do).
4. Click [X] -> Discard changes and exit.
5. Go to the list of your tasks and click Resume for the previously chosen task.
The dialog will load the subtitles from the cache with the changes made during the last session. Instead, it should load the last saved version for this task from the server.

**Comment by bendk** [comment]
I'm pretty sure this is fixed now.
