### ISSUE TITLE
Videos added via feed to private team display in search results.

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#882]
If a user adds a feed of videos to a private team, the videos are still displaying in the watch page results.

Clicking the link results in a 404 error for the page if the user is not a member of the team. 

But as with videos individually added to a private team, feed videos added to a private team should not display in the watch page / search results.

**Comment by PCF-Testing** [comment]
Affects BC and YT feeds.

**Comment by PCF-Testing** [comment]
Issue moved to [pculture/amara-enterprise #1539](https://github.com/pculture/amara-enterprise/issues/1539) via [**ZenHub**](https://www.zenhub.com/)
