### ISSUE TITLE
collaboration team language configurations

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#897]
**Implement a different languages configuration page for when the workflow_style is set to collaboration**

LANGUAGES - allows admins to select which languages they want translated.  

-  [x] 1. Use a double list-box interface. 
 - All potential languages are listed on the left, languages that the team wants are on the right.  
 - Users can click to move a language back and forth).
 - Users can select multiple langauges to move across

-  [ ] 2. Add Project-level language configurations.   
 - There are existing cases where there is 1 team that want 1 set of videos in 1 language set, and different set of videos with different languages.  
 - If a team is using projects, new projects get the default set, or they can make a project specific setting 

***

added #1167 to cover this issue.

-  [x] 3. English-first job workflow.  (Where I really mean primary_audio language)
 -  If a team wants primary_audio to be completed first it can that be specified here
 - If it’s set then the other language jobs won’t be displayed until primary_audio is completed. 
 - This should also be able to be over-ridden at the project level

*Note: 2 and 3 can be broken out to separate tickets if necessary*

**Comment by bendk** [comment]
Made #2495 for the per-project issue.  I think the rest of this is implemented.
