### ISSUE TITLE
New permission settings for collaboration style teams

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#899]
**Implement new permissions for team with workflow_style = collaboration.**

NEW PERMISSIONS SYSTEM --  When we check to see if a user can view/edit subtitles.

Peers are not necessarily reviewers.  Managers and above can be approvers, but also a regular user should be able to be given an approver role.  Also, depending on the team settings we may limit the number of collaborators for each role.

Instead of the current model of increasing levels of permissions - we should use more of a role-based model where a person can translate and / or review and/or approve

So for a particular team member there should be checkboxes for 
[ ] can subtitle
[ ] can review
[ ] can approve

If a user is added as a manager, then they have those 3 boxes checked by default.
A team admin / manager can give a user approve authority.

We may want need to implement this at the project level as there are some cases where we just don't want some team members working on a particular teams videos or projects.

**Comment by bendk** [comment]
I don't think we are planning on implementing this anymore.  It seems like the basic system of role-based permissions + a system for project/language managers is good enough.
