### ISSUE TITLE
Views for collaboration teams to display jobs and progress

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#900]
For teams that use the collaboration-style workflow, we create a new dashboard page (and there is no tasks tab).  

This page displays work that the user could be doing and for Admins and Managers work that is complete and/or in-progress

- [ ] CURRENTLY WORKING ON:  (list of videos that you are a collaborator for, but have not endorsed)

- [ ] AVAILABLE JOBS: List of video languages that need work in the languages that you speak.  If we are implmenting role based permissions as in #899 we should allow users to see a list based on role.
 - Subtitle view:  we list videos that don't have a subtitler yet
 - Reviewer: we list videos with a subtitler's endorsement, but no reviewer
 - Approver view: we list videos with a reviewer's endorsement, but no approver
 - Admins and managers need to be able to see completed vs incomplete jobs
 - Videos are ordered so that the first ones created are at the top 

- [ ]  Jobs list is a table view with the following columns: 
 - video, 
 - language name, 
 - video language, 
 - existing completed subtitle languages, 
 - video creation date.
 - deadline

- [ ]These lists will also include jobs for teams that have requested work from your team.  For those jobs, we will consider them complete based on the settings of the team performing the action.  

- [ ] Once jobs are complete, we'll use the setting of the team that owns the video to decide what to do.

- [ ] Once we have a collaborator from one team, only members of that team can join the collaboration.

**Comment by bendk** [comment]
I think the current collab dashboard handle this.
