### ISSUE TITLE
For inactive (retired) accounts, do not show the list of video submissions

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#938]
At present, the list of video submissions by a user is shown even after the account  is deactivated. Some users are very sensitive about this claiming such information is too private and should not be displayed for retired users.

Could Videos tab be hidden in profiles of retired users? Anonymizing numerous videos from unwanted accounts is a lot of slow manual work.

**Comment by kslottow** [comment]
handled by pculture/amara-enterprise/issues/1986
