### ISSUE TITLE
Compare Revisions feature broken on paginated revision lists

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#944]
If a language has a long, paginated revision history and you need  to compare revisions from different pages, the system would not permit you to check revisions on different pages and compare them -- when you click Compare Revisions, you are asked to select 2 revisions [on the current page].

Maybe it is time to start using two drop-downs with revision numbers instead of checkboxes, or make the list of revisions single-paged showing the 10 most recent versions and a link Show All Revisions to expose the rest?

Example:
http://www.amara.org/en/videos/UDjlR9ua4fuk/pt-br/563491/?page=1&tab=revisions

**Comment by PCF-Testing** [comment]
Revision list has become paginated instead of expandable again:
http://www.amara.org/en/videos/NmkV5cbiCqUU/en/16497/?tab=revisions

This results in remote versions not selectable for comparison.

**Comment by bendk** [comment]
The gh-944-fix branch should fix the regression.

**Comment by jdragojevic** [comment]
@bendk - functionality is back but the button is oddly placed and styled, pushed off to the left and underlined.

![image](https://cloud.githubusercontent.com/assets/299270/5844638/d530c79a-a1b5-11e4-95d2-26bc2df650d3.png)

**Comment by bendk** [comment]
99b8209 should fix the styling issues.

**Comment by jdragojevic** [comment]
this was fixed and deployed weeks ago.
