### ISSUE TITLE
Going 4 seconds back does not work for Wistia videos

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#978]
Reported in http://ted-support.amara.org/helpdesk/tickets/69997; could reproduce instantly.

Video: http://amara.org/en/videos/MOhLL4gKx6P9/info/social-city-hootsuite-the-city-of-new-york/

Steps to reproduce:
1. Start editing subtitles.
2. Start playing the video in the editor.
3. Press SHIFT+TAB. Instead of going back 4 seconds, it goes back a shorter time period and stops. Pressing the keys again does not move the video any further.

Given that Wistia videos are not supported in the new editor, caption makers have a very hard time transcribing and syncing videos.

**Comment by bendk** [comment]
We've kind of given up support for wistia at this point.
