### ISSUE TITLE
Uploading a new draft wipes out speaker name

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#986]
Suppose the latest subtitle version for a TED video has a title, description, and speaker name.

If a user uploads a new draft from a file, the resulting version will copy the title and description from the previous one, but the speaker name will not be copied. It should.

**Comment by PCF-Testing** [comment]
Happens again after the latest deploy with #2540 - video title, description, and metadata go blank after upload.

Req's:
- If no versions had existed for a translation prior to upload or the previous version had no metadata, the uploaded version should have blank metadata, too
- If a previous version existed and had some metadata, it should be copied into the new version

**Comment by syl22-00** [comment]
This was indeed broken by 2540 changes. It is now fixed in a new branch gh-986-refix.

Meanwhile, I included a fix to avoid collapsing messages when there are more than one error messages.

**Comment by PCF-Testing** [comment]
Looks good on the branch.

**Comment by PCF-Testing** [comment]
Deployed.
