### ISSUE TITLE
Video cache stores stale subtitle versions, is hard to update

### ISSUE THREAD

**Issue by PCF-Testing** [pculture/unisubs#990]
Sometimes new subtitle languages or versions fail to timely register with the widget. If this happens, the drop-down widget menu does not include the recently added language or the video displays obsolete subtitle version during playback. In such cases, Cache section on Video Debug page usually displays that the affected language is missing or has an old version as the public top.

A recent example from FD:
http://ted-support.amara.org/helpdesk/tickets/70070

Usually when I reset the video metadata or make an edit, the cache gets updated over 24 hours. Is there a way to make it faster? Before DMR, it used to update reasonably fast (in a few seconds/minutes, max ~30 min) after clicking Reset Video Metadata.

**Comment by bendk** [comment]
Doesn't seem to happen anymore.
