### ISSUE TITLE
old editor pre-populated title text for ted videos

### ISSUE THREAD

**Issue by jdragojevic** [pculture/unisubs#992]
For TED videos, the pre-populated text in the title field displays as speaker: title.

It should just display the title same as it displays for the source text.
![blank](https://f.cloud.github.com/assets/299270/1379496/cbd8ce6e-3aef-11e3-82f3-6b0857a9fcd6.png)

ref: http://pculture.freshdesk.com/helpdesk/tickets/69793

**Comment by bendk** [comment]
This one is fixed now.
